### ISSUE TITLE
error when attempting `from poliastro.twobody import Orbit`

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [poliastro/poliastro#1007]
When I issue the command `from poliastro.twobody import Orbit`, poliastro in turn attempts to import from astropy, and that import fails.  For reasons that are unclear, poliastro or astropy is reaching out to some network path to which I don't have access.  (I did have access to that path at one time, but no longer).  There must be some configuration file that has this path in it, but i haven't been able to find it.

```
(py38) >python
Python 3.8.5 (default, Aug  5 2020, 09:44:06) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from poliastro.twobody import Orbit
C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astropy\config\configuration.py:557:
ConfigurationMissingWarning: Configuration defaults will be used due to FileNotFoundError:2 on None
  warn(ConfigurationMissingWarning(msg))
WARNING: CacheMissingWarning: Remote data cache could not be accessed due to FileNotFoundError:
[WinError 53] The network path was not found: '\\\\networkpath\\UserID\\.astropy' [astropy.utils.data]
WARNING: CacheMissingWarning: Not clearing data cache - cache inaccessible due to FileNotFoundError:
[WinError 53] The network path was not found: '\\\\networkpath\\UserID\\.astropy' [astropy.utils.data]
Downloading https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat
|===========================================| 1.3k/1.3k (100.00%)         0s
WARNING: CacheMissingWarning: ('Cache directory cannot be read or created, providing data in temporary file instead.',
'C:\\Users\\UserID\\AppData\\Local\\Temp\\astropy-download-3896-9e2u29pm') [astropy.utils.data]
WARNING: ConfigurationMissingWarning: Configuration defaults will be used due to FileNotFoundError:2 on None [astropy.config.configuration]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\poliastro\twobody\__init__.py", line 1, in <module>
    from .orbit import Orbit
  File "C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\poliastro\twobody\orbit.py", line 15, in <module>
    from astroquery.jplhorizons import Horizons
  File "C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astroquery\jplhorizons\__init__.py", line 216, in <module>
    from .core import Horizons, HorizonsClass
  File "C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astroquery\jplhorizons\core.py", line 1302, in <module>
    Horizons = HorizonsClass()
  File "C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astroquery\jplhorizons\core.py", line 86, in __init__
    super(HorizonsClass, self).__init__()
  File "C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astroquery\query.py", line 162, in __init__
    paths.get_cache_dir(), 'astroquery',
  File "C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astropy\config\paths.py", line 173, in get_cache_dir
    return os.path.abspath(_find_or_create_root_dir('cache', linkto, rootname))
  File "C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\astropy\config\paths.py", line 298, in _find_or_create_root_dir
    os.mkdir(innerdir)
FileNotFoundError: [WinError 53] The network path was not found: '\\\\networkpath\\c30_as$\\homes2\\home28\\UserID\\.astropy'
```

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>
  
```bash
# Paste your output here:

```
</details>

* `python -c "import poliastro.testing; poliastro.testing.test()"`

<details>

```bash
# Paste your output here:

```
</details>

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Phillip-M-Feldman** [comment]
Output from `conda list` follows:

# packages in environment at C:\ProgramData\Anaconda3\envs\py38:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0
alabaster                 0.7.12                     py_0
anaconda                  custom                   py38_1
anaconda-client           1.7.2                    py38_0
anaconda-project          0.8.4                      py_0
argh                      0.26.2                   py38_0
argon2-cffi               20.1.0           py38he774522_1
asn1crypto                1.4.0                      py_0
astroid                   2.4.2                    py38_0
astropy                   4.0.1.post1      py38he774522_1
astroquery                0.4.1              pyh9f0ad1d_0    conda-forge
atomicwrites              1.4.0                      py_0
attrs                     19.3.0                     py_0
autopep8                  1.5.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
backports                 1.0                        py_2
backports.shutil_get_terminal_size 1.0.0                    py38_2
bcrypt                    3.1.7            py38he774522_1
beautifulsoup4            4.9.1                    py38_0
bitarray                  1.4.2            py38he774522_0
bkcharts                  0.2                      py38_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
blosc                     1.19.0               h7bd577a_0
bokeh                     2.1.1                    py38_0
boto                      2.49.0                   py38_0
bottleneck                1.3.2            py38h2a96729_1
brotlipy                  0.7.0           py38he774522_1000
bzip2                     1.0.8                he774522_0
ca-certificates           2020.6.24                     0
cached-property           1.5.1                      py_1
cartopy                   0.18.0           py38hd77ba2b_0
certifi                   2020.6.20                py38_0
cffi                      1.14.0           py38h7a1dbc1_0
cfitsio                   3.470                he774522_5
chardet                   3.0.4                 py38_1003
click                     7.1.2                      py_0
cloudpickle               1.5.0                      py_0
clyent                    1.2.2                    py38_1
colorama                  0.4.3                      py_0
comtypes                  1.1.7                 py38_1001
conda                     4.8.4                    py38_0
conda-build               3.18.11                  py38_1
conda-pack                0.4.0                      py_0
conda-package-handling    1.6.1            py38h62dcd97_0
console_shortcut          0.1.1                         4
contextlib2               0.6.0.post1                py_0
cryptography              2.9.2            py38h7a1dbc1_0
curl                      7.69.1               h2a8f88b_0
customimporter            2.0.2                      py_0    <unknown>
cycler                    0.10.0                   py38_0
cython                    0.29.21          py38ha925a31_0
cytoolz                   0.10.1           py38he774522_0
dask                      2.22.0                     py_0
dask-core                 2.22.0                     py_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20200713                   py_0
distributed               2.23.0           py38h32f6830_0    conda-forge
docutils                  0.16                     py38_1
entrypoints               0.3                      py38_0
et_xmlfile                1.0.1                   py_1001
expat                     2.2.9                h33f27b4_2
fastcache                 1.1.0            py38he774522_0
filelock                  3.0.12                     py_0
flake8                    3.8.3                      py_0
flask                     1.1.2                      py_0
freetype                  2.10.2               hd328e21_0
freexl                    1.0.5                hfa6e2cd_0
fsspec                    0.7.4                      py_0
future                    0.18.2                   py38_1
gdal                      3.0.2            py38h2fee047_7    conda-forge
geos                      3.8.0                h33f27b4_0
geotiff                   1.5.1                h5770a2b_1
get_terminal_size         1.0.0                h38e98db_0
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
gevent                    20.6.2           py38he774522_0
glib                      2.65.0               he4de6d7_0    conda-forge
glob2                     0.7                        py_0
gmpy2                     2.0.8            py38h7edee0f_3
greenlet                  0.4.16           py38he774522_0
h5py                      2.10.0          nompi_py38h422b98e_102    conda-forge
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.5          nompi_ha405e13_1104    conda-forge
heapdict                  1.0.1                      py_0
html5lib                  1.1                        py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.10                       py_0
imageio                   2.9.0                      py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py38_0
importlib_metadata        1.7.0                         0
iniconfig                 1.0.1                      py_0
intel-openmp              2020.1                      216
intervaltree              3.0.2                      py_1
ipdb                      0.13.3             pyh9f0ad1d_0    conda-forge
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.16.1           py38h5ca1d4c_0
ipython_genutils          0.2.0                    py38_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py38_0
itsdangerous              1.1.0                      py_0
jdcal                     1.4.1                      py_0
jedi                      0.17.1                   py38_0
jinja2                    2.11.2                     py_0
joblib                    0.16.0                     py_0
jpeg                      9d                   he774522_0    conda-forge
jplephem                  2.14               pyhe916df7_1    conda-forge
json5                     0.9.5                      py_0
jsonschema                3.2.0                    py38_0
jupyter                   1.0.0                    py38_7
jupyter_client            6.1.6                      py_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.3                    py38_0
jupyterlab                2.1.5                      py_0
jupyterlab_server         1.2.0                      py_0
kealib                    1.4.13               hd6dc3df_0    conda-forge
keyring                   21.2.1                   py38_0
kiwisolver                1.2.0            py38h74a9793_0
krb5                      1.17.1               hc04afaa_0
lazy-object-proxy         1.4.3            py38he774522_0
libarchive                3.4.2                h5e25573_0
libblas                   3.8.0                    16_mkl    conda-forge
libboost                  1.67.0               hd9e427e_4
libcblas                  3.8.0                    16_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0
libcurl                   7.69.1               h2a8f88b_0
libffi                    3.2.1             ha925a31_1007    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libgdal                   3.0.2                ha9114c6_7    conda-forge
libiconv                  1.15                 h1df5818_7
libkml                    1.3.0                he5f2a48_4
liblief                   0.10.1               ha925a31_0
libllvm9                  9.0.1                h21ff451_0
libnetcdf                 4.7.3           nompi_hc957ea6_101    conda-forge
libopenblas               0.3.10          pthreads_h1662909_4    conda-forge
libpng                    1.6.37               h2a8f88b_0
libpq                     12.2                 h3235a2c_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
libspatialite             4.3.0a               h7ffb84d_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.1.0                h56a325e_1
libwebp                   1.0.2                hfa6e2cd_5    conda-forge
libxml2                   2.9.10               h464c3ec_1
libxslt                   1.1.34               he774522_0
llvm-meta                 5.0.0                         0    conda-forge
llvmlite                  0.31.0           py38ha925a31_0
locket                    0.2.0                    py38_1
lxml                      4.5.2            py38h1350720_0
lz4-c                     1.9.2                h62dcd97_1
lzo                       2.10                 he774522_2
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py38he774522_0
matplotlib                3.2.2                         0
matplotlib-base           3.2.2            py38h64f37c6_0
mccabe                    0.6.1                    py38_1
menuinst                  1.4.16           py38he774522_1
mistune                   0.8.4           py38he774522_1000
mkl                       2020.1                      216
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.1.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
mock                      4.0.2                      py_0
more-itertools            8.4.0                      py_0
mpc                       1.1.0                h7edee0f_1
mpfr                      4.0.2                h62dcd97_1
mpir                      3.0.0                hec2e145_1
mpmath                    1.1.0                    py38_0
msgpack-python            1.0.0            py38h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py38_0
nbconvert                 5.6.1                    py38_0
nbformat                  5.0.7                      py_0
networkx                  2.4                        py_1
nltk                      3.5                        py_0
nose                      1.3.7                    py38_2
notebook                  6.1.1                    py38_0
numba                     0.48.0           py38h47e9c7a_0
numexpr                   2.7.1            py38h25d0782_0
numpy                     1.19.1           py38h5510c5b_0
numpy-base                1.19.1           py38ha3acd2a_0
numpydoc                  1.1.0                      py_0
olefile                   0.46                       py_0
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openpyxl                  3.0.4                      py_0
openssl                   1.1.1g               he774522_1
owslib                    0.20.0                     py_0
packaging                 20.4                       py_0
pandas                    1.1.0            py38ha925a31_0
pandoc                    2.10.1                        0
pandocfilters             1.4.2                    py38_1
paramiko                  2.7.1                      py_0
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0
path                      14.0.1                   py38_0
path.py                   12.5.0                        0
pathlib2                  2.3.5                    py38_0
pathtools                 0.1.2                      py_1
patsy                     0.5.1                    py38_0
pcre                      8.44                 ha925a31_0
pep8                      1.7.1                    py38_0
pexpect                   4.8.0                    py38_0
pickleshare               0.7.5                 py38_1000
pillow                    7.2.0            py38hcc1f983_0
pip                       20.2.2                   py38_0
pkginfo                   1.5.0.1                  py38_0
plotly                    4.8.2                      py_0
pluggy                    0.13.1                   py38_0
ply                       3.11                     py38_0
poliastro                 0.14.0                     py_1    conda-forge
poppler                   0.67.0               h1707e21_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 h3235a2c_0
powershell_shortcut       0.0.1                         3
progressbar2              3.37.1                   py38_0
proj                      6.2.1                h9f7ef89_0
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
prompt_toolkit            3.0.5                         0
psutil                    5.7.0            py38he774522_0
py                        1.9.0                      py_0
py-lief                   0.10.1           py38ha925a31_0
pycodestyle               2.6.0                      py_0
pycosat                   0.6.3            py38he774522_0
pycparser                 2.20                       py_2
pycurl                    7.43.0.5         py38h7a1dbc1_0
pydocstyle                5.0.2                      py_0
pyepsg                    0.4.0                      py_0
pyflakes                  2.2.0                      py_0
pygments                  2.6.1                      py_0
pykdtree                  1.3.1           py38h8c2d366_1002
pylint                    2.5.3                    py38_0
pynacl                    1.4.0            py38h62dcd97_1
pyodbc                    4.0.30           py38ha925a31_0
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyperclip                 1.8.0              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38hcfa1391_1
pyqt                      5.12.3           py38h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyreadline                2.1                      py38_1
pyrsistent                0.16.0           py38he774522_0
pyshp                     2.1.0                      py_0
pyside2                   5.13.2           py38hfa7ce6d_2    conda-forge
pysocks                   1.7.1                    py38_0
pytables                  3.6.1            py38h26f9782_1    conda-forge
pytest                    6.0.1                    py38_0
pytest-runner             5.2                        py_0
python                    3.8.5                he1778fa_0
python-dateutil           2.8.1                      py_0
python-docx               0.8.10                     py_0    conda-forge
python-jsonrpc-server     0.3.4                      py_1
python-language-server    0.34.1                   py38_0
python-libarchive-c       2.9                        py_0
python-utils              2.3.0                    py38_0
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1                     py_0
pywavelets                1.1.1            py38he774522_0
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7                    py38_0
pyyaml                    5.3.1            py38he774522_1
pyzmq                     19.0.1           py38ha925a31_1
qdarkstyle                2.8.1                      py_0
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtawesome                 0.7.2                      py_0
qtconsole                 4.7.5                      py_0
qtpy                      1.9.0                      py_0
regex                     2020.7.14        py38he774522_0
requests                  2.24.0                     py_0
retrying                  1.3.3                      py_2
ripgrep                   11.0.2                        0
rope                      0.17.0                     py_0
rtree                     0.9.4            py38h21ff451_1
ruamel_yaml               0.15.87          py38he774522_1
scikit-image              0.16.2           py38h47e9c7a_0
scikit-learn              0.23.1           py38h25d0782_0
scipy                     1.5.0            py38h9439919_0
seaborn                   0.10.1                     py_0
send2trash                1.5.0                    py38_0
setuptools                49.6.0                   py38_0
shapely                   1.7.0            py38h210f175_0
simplegeneric             0.8.1                    py38_2
singledispatch            3.4.0.3                  py38_0
sip                       4.19.24          py38ha925a31_0
six                       1.15.0                     py_0
snappy                    1.1.8                h33f27b4_0
snowballstemmer           2.0.0                      py_0
sortedcollections         1.2.1                      py_0
sortedcontainers          2.2.2                      py_0
soupsieve                 2.0.1                      py_0
sphinx                    3.2.1                      py_0
sphinxcontrib             1.0                      py38_1
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
sphinxcontrib-websupport  1.2.4                      py_0
spyder                    4.1.4                    py38_0
spyder-kernels            1.9.2                    py38_0
sqlalchemy                1.3.18           py38he774522_0
sqlite                    3.32.3               h2a8f88b_0
statsmodels               0.11.1           py38he774522_0
sympy                     1.6.1                    py38_0
tbb                       2020.0               h74a9793_0
tblib                     1.6.0                      py_0
terminado                 0.8.3                    py38_0
testpath                  0.4.4                      py_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tiledb                    1.7.0                h0b90766_4    conda-forge
tk                        8.6.10               he774522_0
toml                      0.10.1                     py_0
toolz                     0.10.0                     py_0
tornado                   6.0.4            py38he774522_1
tqdm                      4.48.2                     py_0
traitlets                 4.3.3                    py38_0
typing_extensions         3.7.4.2                    py_0
ujson                     1.35             py38he774522_0
unicodecsv                0.14.1                   py38_0
urllib3                   1.25.10                    py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
watchdog                  0.10.3                   py38_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
werkzeug                  1.0.1                      py_0
wheel                     0.34.2                   py38_0
widgetsnbextension        3.5.1                    py38_0
win_inet_pton             1.1.0                    py38_0
win_unicode_console       0.5                      py38_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py38he774522_0
xerces-c                  3.2.2                ha925a31_0
xlrd                      1.2.0                      py_0
xlsxwriter                1.2.9                      py_0
xlwings                   0.19.5                   py38_0
xlwt                      1.3.0                    py38_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
zeromq                    4.3.2                ha925a31_2
zict                      2.0.0                      py_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zope                      1.0                      py38_1
zope.event                4.4                      py38_0
zope.interface            4.7.1            py38he774522_0
zstd                      1.4.5                h04227a9_0

**Comment by Phillip-M-Feldman** [comment]
(py38) >conda info -a

     active environment : base
    active env location : C:\ProgramData\Anaconda3\envs\py38
            shell level : 1
       user config file : C:\Users\UserID\.condarc
 populated config files : C:\Users\UserID\.condarc
          conda version : 4.8.4
    conda-build version : 3.18.11
         python version : 3.8.5.final.0
       virtual packages : __cuda=8.0
       base environment : C:\ProgramData\Anaconda3\envs\py38  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\ProgramData\Anaconda3\envs\py38\pkgs
                          C:\Users\UserID\.conda\pkgs
                          C:\Users\UserID\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs\py38\envs
                          C:\Users\UserID\.conda\envs
                          C:\Users\UserID\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.8.5 Windows/10 Windows/10.0.17763
          administrator : True
             netrc file : None
           offline mode : False

# conda environments:
#
                         C:\ProgramData\Anaconda3
                         C:\ProgramData\Anaconda3\envs\py27
base                  *  C:\ProgramData\Anaconda3\envs\py38
                         C:\ProgramData\Anaconda3\envs\py38b

sys.version: 3.8.5 (default, Aug  5 2020, 09:44:06) [...
sys.prefix: C:\ProgramData\Anaconda3\envs\py38
sys.executable: C:\ProgramData\Anaconda3\envs\py38\python.exe
conda location: C:\ProgramData\Anaconda3\envs\py38\lib\site-packages\conda
conda-build: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-build.exe
conda-convert: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-convert.exe
conda-debug: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-debug.exe
conda-develop: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-develop.exe
conda-env: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-env.exe
conda-index: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-index.exe
conda-inspect: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-inspect.exe
conda-metapackage: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-metapackage.exe
conda-pack: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-pack.exe
conda-render: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-render.exe
conda-server: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-server.exe
conda-skeleton: C:\ProgramData\Anaconda3\envs\py38\Scripts\conda-skeleton.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: py38
CONDA_EXE: C:\ProgramData\Anaconda3\envs\py38\condabin\..\Scripts\conda.exe
CONDA_EXES: "C:\ProgramData\Anaconda3\envs\py38\condabin\..\Scripts\conda.exe"
CONDA_PREFIX: C:\ProgramData\Anaconda3\envs\py38
CONDA_PROMPT_MODIFIER: (py38)
CONDA_PYTHON_EXE: C:\ProgramData\Anaconda3\python.exe
CONDA_ROOT: C:\ProgramData\Anaconda3\envs\py38
CONDA_SHLVL: 1
CURL_CA_BUNDLE: <not set>
HOMEPATH: \
PATH: C:\ProgramData\Anaconda3\envs\py38;C:\ProgramData\Anaconda3\envs\py38\Library\mingw-w64\bin;
 C:\ProgramData\Anaconda3\envs\py38\Library\usr\bin;C:\ProgramData\Anaconda3\envs\py38\Library\bin;
 C:\ProgramData\Anaconda3\envs\py38\Scripts;C:\ProgramData\Anaconda3\envs\py38\bin;
 C:\ProgramData\Anaconda3\envs\py38;C:\ProgramData\Anaconda3\envs\py38\Library\mingw-w64\bin;
 C:\ProgramData\Anaconda3\envs\py38\Library\usr\bin;C:\ProgramData\Anaconda3\envs\py38\Library\bin;
 C:\ProgramData\Anaconda3\envs\py38\Scripts;C:\ProgramData\Anaconda3\envs\py38\bin;
 C:\PROGRA~1\Anaconda3;C:\PROGRA~1\Anaconda3\Library\mingw-w64\bin;C:\PROGRA~1\Anaconda3\Library\usr\bin;
 C:\PROGRA~1\Anaconda3\Library\bin;C:\PROGRA~1\Anaconda3\Scripts;C:\LSF_9.1\9.1\bin;C:\LSF_9.1\9.1\lib;
 C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\bin;C:\WINDOWS\System32\Wbem;
 C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\ProgramData\Oracle\Java\javapath;
 C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;
 C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;
 C:\Program Files\Microsoft SQL Server\130\Tools\Binn;
 C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;
 C:\Program Files\MATLAB\R2017b\runtime\win64;C:\Program Files\MATLAB\R2017b\bin;
 C:\Program Files\TortoiseGit\bin;C:\Apps\Git\cmd;C:\WINDOWS\System32\OpenSSH;
 C:\Program Files\MiKTeX 2.9\miktex\bin\x64;C:\Program Files\PuTTY;
 C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;
 C:\Program Files\Anaconda3;C:\Program Files\Anaconda3\Scripts;C:\Program Files\Anaconda3\Library\bin;
 C:\Program Files\Anaconda3\Library\usr\bin;
 C:\Program Files\Anaconda3\bin;C:\Program Files\Anaconda3\condabin;
 C:\Users\UserID\AppData\Local\Microsoft\WindowsApps;
 C:\Program Files (x86)\GnuWin32\bin;.
PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PYTHON: C:\ProgramData\Anaconda3\envs\py38\python.exe
PYTHONBREAKPOINT: ipdb.set_trace
PYTHONSTARTUP: C:\Users\UserID\PYTHONSTARTUP.py
PYTHON_VERSION: 3.8
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>

**Comment by astrojuanlu** [comment]
Hi @Phillip-M-Feldman! I edited your comments to have better formatting.

It seems that your error has to do with some weird configuration from Astropy, which is unable to find this directory:

```
\\\\networkpath\\c30_as$\\homes2\\home28\\UserID\\.astropy
```

I'm 99 % sure this is not related to poliastro (I can lend a hand anyway). Could you try this?

```
(py38) >python
Python 3.8.5 (default, Aug  5 2020, 09:44:06) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from astropy.config import paths
>>> print(paths.get_cache_dir())
?
```

**Comment by astrojuanlu** [comment]
I think this issue you reported upstream is the culprit https://github.com/astropy/astropy/issues/10661 let's follow up there :)
