### ISSUE TITLE
Remove mention to `poliastro.testing` from issue template

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1012]
We no longer ship tests as part of poliastro.

(Noticed in #1011)

**Comment by priyanshurohilla** [comment]
Hey @astrojuanlu what i have understood from this issue, if i am rigth is that you want `poliastro.testing`l abel to be removed from issue templates. But this is only possible who has the write access to this repository

**Comment by astrojuanlu** [comment]
Sorry for the delay, the template is on `.github/` directory, see #1024

**Comment by astrojuanlu** [comment]
Closed in #1024!
