### ISSUE TITLE
Ditch transparent logo for good

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1022]
https://twitter.com/icymi_py/status/1308843120382140419

![Screenshot_2020-09-23 Python posts you might have missed on Twitter](https://user-images.githubusercontent.com/316517/94057723-52179400-fde0-11ea-836d-eec7cb78fa6d.png)

Let's face it, we need a white background.

**Comment by jorgepiloto** [comment]
I labeled this with good first issue and the hacktoberfest so people get encouraged to solve this.

**Comment by jorgepiloto** [comment]
If generated from scratch with vectorial drawing software, PNG files usually ship with no background. However, if those same images are converted to JPEG a white background is included, then:

* Should we add the same image converted to JPEG file or just add white background to actual PNG file located in `docs/source/_static/logo_text.png`?

**Comment by zupeiza** [comment]
I propose modifying current logo_text.png, adding a white background. The former one would be kept and renamed as logo_text_transp.png, in case it is needed for the future.

**Comment by astrojuanlu** [comment]
Closed!
