### ISSUE TITLE
Void poliastro/integrators.py module

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#1031]
🐞 **Problem**

I just noticed that [integrators.py](https://github.com/poliastro/poliastro/blob/master/src/poliastro/integrators.py) is completely empty! This file used to hold DOP853 differential equation solver till it was implemented in Scipy. After that, the solver was no longer required to be hard-coded in poliastro.

💡 **Possible solutions**

We might discuss about keeping this module for future custom solvers or just get rid of if for the moment.

📋  **Steps to solve the problem**

* Apply `git rm src/poliastro/integrators.py`
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by astrojuanlu** [comment]
Wow, how could we forget about this 😅

**Comment by astrojuanlu** [comment]
Closed in #1033
