### ISSUE TITLE
Discuss about refactoring porkchops as a class

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#1041]
**Introduction to the issue** :memo:

I was asked to solve for a porkchop map map at university and decided to use the plotting utility provided by poliastro. At the moment, this utility is located under the `poliastro.plotting.porkchop` module, which holds a public function
under the name `porkchop`:

https://github.com/poliastro/poliastro/blob/61c6caadb00a34aec6dfb5027a8a0a5307c5c6bb/src/poliastro/plotting/porkchop.py#L104-L114

**The issue** :beetle:

Although the function works as expected, I think that by having a class we could achieve a better structured code. In addition, user could easily access other attributes such us internal axes, which can increase customization of the figures. Notice that the actual function expects an `ax` parameter but does not return it, making it no longer accessible outside the routine. Other enhancements might have been already proposed in #1020

From my point of view, we could better divide the workflow of the `porkchop()` algorithm if converted into a class under the name `PorkchopPlotter` (just to follow same namespace as other plotting routines).

Let me know what you think about this proposal :rocket:

**Comment by astrojuanlu** [comment]
Closed in gh-1059
