### ISSUE TITLE
Leverage importlib to avoid hardcoding version in Sphinx

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1045]
See for example:

https://github.com/astropy/astropy/pull/11091/files#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3

**Comment by astrojuanlu** [comment]
More info: https://docs.python.org/3/library/importlib.metadata.html

**Comment by DhruvSondhi** [comment]
Hello, 
After reading the source link thus mentioned, I think we need to have to update the version automatically through the required library by calling the relevant function `version`. Can you please shed some more light on the same?

**Comment by astrojuanlu** [comment]
Fixed in gh-1070
