### ISSUE TITLE
Documentation builds take too long and sometimes die

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1066]
https://readthedocs.org/projects/poliastro/builds/12697560/

```
Command killed due to excessive memory consumption
```

**Comment by DhruvSondhi** [comment]
This also fails whenever we try to build the docs locally. Could be something related to any particular file generation or `sphinx` in general.:thinking:

**Comment by astrojuanlu** [comment]
I could not reproduce the failure locally.

According to my observations, RAM stayed mostly constant. The only notebook that required more RAM was the NEOS one. However, note that I already have DASTCOM5 downloaded to my computer, so perhaps that played a role.

**Comment by astrojuanlu** [comment]
In this other case: https://readthedocs.org/projects/poliastro/builds/12714055/

```
Build exited due to time out
```

**Comment by astrojuanlu** [comment]
And I launched another build: https://readthedocs.org/projects/poliastro/builds/12722086/

```
Notebook error:
DeadKernelError in examples/Using NEOS package.md:
Kernel died
```

However, interestingly, @DhruvSondhi PR https://github.com/poliastro/poliastro/pull/1067 succeeded by changing something totally unrelated.

**Comment by astrojuanlu** [comment]
PR succeeded: https://github.com/poliastro/poliastro/pull/1069, https://readthedocs.org/projects/poliastro/builds/12722362/
But `master` after merging the PR, failed https://readthedocs.org/projects/poliastro/builds/12722868/

https://github.com/readthedocs/readthedocs.org/issues/7815

**Comment by DhruvSondhi** [comment]
> And I launched another build: https://readthedocs.org/projects/poliastro/builds/12722086/
> 
> ```
> Notebook error:
> DeadKernelError in examples/Using NEOS package.md:
> Kernel died
> ```
> 
> However, interestingly, @DhruvSondhi PR #1067 succeeded by changing something totally unrelated.

Found out that it was a Local Machine configuration error rather than CI `ReadTheDocs` issue. Sorry for this confusion :disappointed_relieved: 
Closed the #1067 :)

**Comment by astrojuanlu** [comment]
Grr `master` builds keep failing but pull request builds keep passing. We'll have to wait for RTD folks to lend us a hand.

**Comment by astrojuanlu** [comment]
Looks like lots of RAM is needed to build our docs from scratch (~3 GB are not enough). RTD increased the capacity of our builders. The issue is closed!
