### ISSUE TITLE
Add keplerian element in IOD

### ISSUE THREAD

**Issue by AngelMamba** [poliastro/poliastro#1071]
Is it possible to add keplerian element result for Initial Orbit Determination (IOD) module?
Now, there is only the velocity solution of Lambert problem.
I think since it is orbit determination, keplerian element seems better.

**Comment by astrojuanlu** [comment]
Hi @AngelMamba , thanks for your interest in poliastro!

Perhaps you can try https://docs.poliastro.space/en/latest/autoapi/poliastro/maneuver/index.html#poliastro.maneuver.Maneuver.lambert, which returns a `Maneuver` object and therefore can be applied to a existing `Orbit` using https://docs.poliastro.space/en/latest/autoapi/poliastro/twobody/orbit/index.html#poliastro.twobody.orbit.Orbit.apply_maneuver.

Please let us know if this fulfills your needs.

**Comment by AngelMamba** [comment]
> Hi @AngelMamba , thanks for your interest in poliastro!
> 
> Perhaps you can try https://docs.poliastro.space/en/latest/autoapi/poliastro/maneuver/index.html#poliastro.maneuver.Maneuver.lambert, which returns a `Maneuver` object and therefore can be applied to a existing `Orbit` using https://docs.poliastro.space/en/latest/autoapi/poliastro/twobody/orbit/index.html#poliastro.twobody.orbit.Orbit.apply_maneuver.
> 
> Please let us know if this fulfills your needs.

Hi @astrojuanlu Thank you for the reply. It helps a lot.
But I just need to calculate keplerian elements from postion and velocity vector, not a orbit maneuver case. So I think Orbit object from twobody module works.
Anyway, I kind of figure this out. thank you.

**Comment by astrojuanlu** [comment]
Excellent! Don't hesitate to ask if you have any further questions by opening a new issue or joining http://chat.poliastro.space
