### ISSUE TITLE
Docs search is broken

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1079]
We are getting this error and empty search results:

https://github.com/sphinx-doc/sphinx/issues/5460

It looks like this solution works: https://github.com/agentos-project/agentos/pull/17/files

**Comment by Yash-10** [comment]
Hello,

The above solution obviously works as I tested it locally. Previously the search results hanged and didn't render any results after searching but adding that line made it work.

Could you please tell me as to what are we looking for here exactly @astrojuanlu ?

Thanks!!

**Comment by astrojuanlu** [comment]
Hello @Yash-10 ! What I'm looking for is for a first-time contributor to send a PR implementing that solution :) Please leave this one for newcomers, because it's a perfect good first issue. Thanks!

**Comment by Yash-10** [comment]
Ok, no problem. I'll leave this :)

Thanks!!

**Comment by zkl2** [comment]
@astrojuanlu I can help with this one! I'll submit a PR per the poliastro contributing guidelines.

**Comment by astrojuanlu** [comment]
Fixed in gh-1090!
