### ISSUE TITLE
Notebooks don't open in Binder

### ISSUE THREAD

**Issue by DhruvSondhi** [poliastro/poliastro#1081]
Binder integration of the new modified notebooks(format `.mystnb`) in `index` file returns a `404` page not found error whenever accessing the notebooks. Need to investigate in more detail where the problem is arising from. Can be confirmed from #1080 🤔

**Comment by astrojuanlu** [comment]
Not only the links: the notebooks do not open _as notebooks_. I suspect jupytext is not being properly installed.
