### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by fanxinxing** [poliastro/poliastro#1086]
code:
from poliastro.examples import molniya

molniya.plot()

Error:
ValueError: subformat not allowed for format jyear_str

another question:
Can this sample code run in PyCharm? Why not display graphics?

Thanks!

**Comment by astrojuanlu** [comment]
Hi @fanxinxing! This is a known issue with poliastro 0.14 and latest Astropy. Please downgrade your Astropy version to 4.1 or 4.0 to make it work, and let us know if it fixed the issue.

**Comment by fanxinxing** [comment]
Thanks,  Astropy version 4.0 does work.

**Comment by astrojuanlu** [comment]
Thanks! Closing then
