### ISSUE TITLE
Wrong Equations in API Documentation 

### ISSUE THREAD

**Issue by DhruvSondhi** [poliastro/poliastro#1093]
Hello, 
While I was traversing the documentation, I found that equations stated here [1](https://docs.poliastro.space/en/latest/autoapi/poliastro/core/angles/index.html#poliastro.core.angles.E_to_nu) & [2](https://docs.poliastro.space/en/latest/autoapi/poliastro/core/angles/index.html#poliastro.core.angles.F_to_nu) are wrong (discussed with @astrojuanlu)

🐞 **Problem**

The equation here is not correct & hence can be fixed with the correct representation {Latex}. 

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>
  
```bash
# Paste your output here:
Not Required 🤔 

```
</details>

<details>

```bash
# Paste your output here:
Not Required 🤔 
```
</details>

💡 **Possible solutions**
 

Representation of the equation can be altered as to demonstrate the correct equation 😄 
📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by astrojuanlu** [comment]
Good catch @DhruvSondhi !
