### ISSUE TITLE
Remove internal uses of deprecated Orbit.from_body_ephem

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1095]
Doing a quick search, the only place where we are using `Orbit.from_body_ephem` is this one:

https://github.com/poliastro/poliastro/blob/6ee8e9386a27d4d241cd0e9cb22f6fb6fbf2cf45/src/poliastro/plotting/_base.py#L372-L374

Instead, we should instead be doing this:

```python
    ephem = Ephem.from_body(body, J2000_TDB)
    orbit = Orbit.from_ephem(Sun, ephem, J2000_TDB)
```

And, after that, tests covering `Orbit.from_body_ephem` can be removed.

**Comment by Yash-10** [comment]
And I think, [this](https://github.com/poliastro/poliastro/blob/6ee8e9386a27d4d241cd0e9cb22f6fb6fbf2cf45/src/poliastro/twobody/orbit.py#L76) line comments that it was only needed for `from_body_ephem`. So an equivalent fix for that might be needed?

**Comment by astrojuanlu** [comment]
Good catch @Yash-10 !

**Comment by astrojuanlu** [comment]
In any case, let's leave this one for a newcomer as well :)

**Comment by Yash-10** [comment]
Yes, sure!

**Comment by ishanSrt** [comment]
Hey! I am a newcomer to this org and I would like to be assigned to this issue.

**Comment by astrojuanlu** [comment]
Hi @ishanSrt , all yours!

**Comment by ishanSrt** [comment]
Only the internal use cases of `Orbit.from_body_ephem` and tests need to be removed for this issue? Or does the function definition and the docs need to be changed too?

**Comment by astrojuanlu** [comment]
@ishanSrt The function has already been deprecated, there are no more changes needed to its function definition and docs.
