### ISSUE TITLE
OrbitPlotter3D not rendering in Jupyter notebook

### ISSUE THREAD

**Issue by manweichan** [poliastro/poliastro#1097]
🐞 **Problem**
OrbitPlotter3D is not rendering in my notebook. I've been using the [Plotting in 3D](https://docs.poliastro.space/en/stable/examples/Plotting%20in%203D.html) example:

    import numpy as np

    from poliastro.constants import J2000
    from poliastro.examples import *
    from poliastro.plotting import *

    import plotly.io as pio
    pio.renderers.default = "notebook_connected"

    frame = OrbitPlotter3D()

    frame.plot(churi)
    frame.plot_body_orbit(Earth, J2000)

With an output 
<img width="1243" alt="Screen Shot 2021-01-31 at 11 29 15 PM" src="https://user-images.githubusercontent.com/17070627/106415083-38d0c500-641c-11eb-8e2f-64d2cc359953.png">

Some interesting notes:

- As you can see, running the commands plots the legend, but not the actual orbit plots. Instead, I get a white square with a frown.
- There is no error message within the Jupyter notebook, and when I click on the white square with the frown, I get brought to a [WebGL page](https://get.webgl.org/), where I do see the spinning cube, indicating WebGL is enabled in my browser.
- Using `frame = OrbitPlotter2D()`, generates a static 2D plot with no issues
- Changing to `pio.renderers.default = "browser"`, renders a 3D plot in a new browser tab without issues
- I'm using the current dev version of Poliastro taken from GitHub.

I realize this might not be a poliastro issue and more of an issue with the plotly integration with the Jupyter notebook; however, I figure this might be a good place to start given that some of the other functionality (OrbitPlotter2D, the legend appearing in OrbitPlotter3D) works fine.

Thanks in advance for any advice on how to fix this problem. I find the entire PoliAstro library very useful.

🖥 **Please paste the output of following commands**

<details>
  
```bash
# Paste your output here:
appnope==0.1.2
argon2-cffi==20.1.0
astropy==4.2
astroquery==0.4.1
async-generator==1.10
attrs==20.3.0
autopep8==1.5.4
backcall==0.2.0
beautifulsoup4==4.9.3
bleach==3.2.1
cached-property==1.5.2
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.3
entrypoints==0.3
html5lib==1.1
idna==2.10
importlib-metadata==3.1.1
ipdb==0.13.4
ipykernel==5.3.4
ipympl==0.6.3
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.17.2
Jinja2==2.11.2
jplephem==2.15
jsonschema==3.2.0
jupyter-client==6.1.7
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.7.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
jupyterthemes==0.20.0
keyring==21.5.0
kiwisolver==1.3.1
lesscpy==0.14.0
llvmlite==0.35.0
lxml==4.6.2
MarkupSafe==1.1.1
matplotlib==3.3.3
mistune==0.8.4
mpmath==1.1.0
nbclient==0.5.1
nbconvert==5.6.1
nbformat==5.0.8
nest-asyncio==1.4.3
notebook==6.1.5
numba==0.52.0
numpy==1.19.4
packaging==20.8
pandas==1.1.5
pandocfilters==1.4.3
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.0.1
plotly==4.14.0
ply==3.11
poliastro @ https://github.com/poliastro/poliastro/archive/master.zip
prometheus-client==0.9.0
prompt-toolkit==3.0.8
ptyprocess==0.6.0
pycodestyle==2.6.0
pycparser==2.20
pyerfa==1.7.1.1
Pygments==2.7.3
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2020.4
PyYAML==5.3.1
pyzmq==20.0.0
requests==2.25.0
retrying==1.3.3
scipy==1.5.4
seaborn==0.11.0
Send2Trash==1.5.0
six==1.15.0
soupsieve==2.0.1
terminado==0.9.1
testpath==0.4.4
toml==0.10.2
tornado==6.1
traitlets==5.0.5
urllib3==1.26.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
yapf==0.30.0
zipp==3.4.0

```
</details>

<details>

```bash
# Paste your output here:

```
</details>

**Comment by DhruvSondhi** [comment]
Hello @manweichan, Thanks for using Poliastro :) 
Can you please specify the browser you are using? It does seem so that the browser is the fault as I am able to run it without any problems (having same versions of Jupyter Notebook & Plotly installed) 🤔 ... There could be 2 things that could be done: 
1. You can search online for **WebGL** activation as in some browsers this is an experimental feature & may need to be turned on so as to allow it to be used [ The webpage [here](https://get.webgl.org/) as mentioned just only shows that your browser supports it but it doesn't show whether it is enabled or disabled ... I do think this may be the case ... check for *flag* in browsers (experimental features)]
2. You can try reinstalling **Jupyter Notebook and/or Plotly** as it may the version that may be deprecated [Though I highly doubt this as I have compared the Changelogs of your version & mine too ... Doesn't seem so that this a problem though can be given a try 🤔]

**Comment by manweichan** [comment]
Hi @DhruvSondhi, thanks for the advice! It was the browser. I am using Chrome and updated the version to: 88.0.4324.96 (Official Build) (x86_64).

The newest Chrome version now allows the 3D plots to render within the Jupyter Notebook.

Thanks!
