### ISSUE TITLE
Add GSOC 2021 ideas

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1099]
https://gitlab.com/librespacefoundation/soc-org/-/wikis/Google-Summer-of-Code-2021#ideas-template

**Comment by jorgepiloto** [comment]
I was thinking about adding the following topic: `Expand event detectors`, in addition to previous year ones. It has the advantage of working with "raw algorithms implementations", avoiding the needs of working with the high-level API.

**Comment by astrojuanlu** [comment]
Draft: https://github.com/poliastro/czml3/issues/81

**Comment by astrojuanlu** [comment]
- https://gitlab.com/librespacefoundation/soc-org/-/issues/19
- https://gitlab.com/librespacefoundation/soc-org/-/issues/20
- https://gitlab.com/librespacefoundation/soc-org/-/issues/21
- https://gitlab.com/librespacefoundation/soc-org/-/issues/22

**Comment by astrojuanlu** [comment]
Done!
