### ISSUE TITLE
Outdated Makefile examples rule 

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#1108]
🐞 **Problem**

After switching to MyST format, the Makefile rule `make examples` became outdated, as it tries to find for `*.md` format notebooks, instead of `*.mystnb` ones.

💡 **Possible solutions**

A simple solution is to change previous file extension.

📋  **Steps to solve the problem**

Change the `*.md` from the following line:

https://github.com/poliastro/poliastro/blob/b1ea3ede8672da782cb3a989b52a17c78fad8ca1/docs/Makefile#L57

into a `*.mystnb`.

**Comment by OBITORASU** [comment]
Can I pick this one up? Seems like a quick fix.

**Comment by jorgepiloto** [comment]
Sure @OBITORASU!

**Comment by jorgepiloto** [comment]
Closing this!
