### ISSUE TITLE
Default branch was renamed to main

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1115]
For more info: https://github.com/github/renaming

I know this is controversial, and nobody asked for it (yet). Still, I went ahead and unilaterally made the change, to avoid more pain in the future.

This issue is just to notify everyone, please adjust your local environments accordingly:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

Regardless of whether I like this or not, (1) it's a debate that is not going away, and it will hit every project sooner or later, and (2) I will keep doing things I consider are important and impactful to make the tech industry and the open source universe more welcoming to others, as I've been doing for almost a decade now, and encourage others to do the same.

The open source universe has a diversity, inclusion and representation problem, and we have the moral obligation to fix it. This is only a baby step in that direction. The battle doesn't end here.

**Comment by DhruvSondhi** [comment]
This was also made official by GitHub ... all newer repositories will be by default be named as Main rather than Master as it used to be the case 😄 [Shared just in case anyone wants some info]

**Comment by DhruvSondhi** [comment]
A small correction @astrojuanlu ... the command should be `git branch -u origin/master main` than `git branch -u origin/main main` ... Checked it right now as it throws some unexpected errors ... Please check & confirm :)
