### ISSUE TITLE
molniya plot not being shown in README.md

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#1117]
🐞 **Problem**

After renaming main repository branch, the link to the `molniya` figure got broken. In addition, remember that #610 is still open, so we could take advantage from this situation and solve both issues at the same time. Let us discuss that option in the comments below :thinking:

:bulb: **Solution**

Change old line:

```markdown
 <image src="https://github.com/poliastro/poliastro/raw/master/docs/source/examples/molniya.png">
 ```
 
 to
 
 ```
 <image src="https://github.com/poliastro/poliastro/raw/main/docs/source/examples/molniya.png">
 ```

**Comment by 96RadhikaJadhav** [comment]
@jorgepiloto Can I work on it?

**Comment by jorgepiloto** [comment]
Sure @96RadhikaJadhav! :rocket:

**Comment by jorgepiloto** [comment]
Closing!
