### ISSUE TITLE
Discussion on Broken Links & References related to renaming of Master to Main Branch 

### ISSUE THREAD

**Issue by DhruvSondhi** [poliastro/poliastro#1119]
🐞 **Problem**
The current renaming of the `master` branch to the `main` branch lead to different integrated services not working as intended. These have broken some links & services which needs fixing. An example may include Issue #1117.
Current the following things according to me have been affected:
- [x] Binder Repository 
- [x] License on README 
- [x] `index.ipynb` file givings unknown type errors
- [x] `COPYING` file
- [x] Azure pipeline (is redirected accordingly but we need to change it)
- [x] `Poliastro/Validiation` workflow needs to be redirected to the correct branch
- [x] Alternative method of installation via Zip file
- [x] Other 🤔  

💡 **Possible solutions**
Each & Every change needs to be made accordingly. These need to be classified according to the permissions on the repo & can be included to make **Good First Issues**. Others that are not either **GFI** or permission locked, I will be making a PR with the required _FIX_ where ever possible.  

📋  **Steps to solve the problem**
 Each problem needs to be accounted for here & hence be checked accordingly to migrate all `master` branch references to `main` branch for successful renaming.

**Comment by DhruvSondhi** [comment]
@astrojuanlu Please check this out & add/remove if anything is out of the blue 😄

**Comment by DhruvSondhi** [comment]
Thanks, @xlxs4 for fixing `COPYING` file link 😄

**Comment by astrojuanlu** [comment]
What's missing here after #1122 and #1123 were merged?

**Comment by DhruvSondhi** [comment]
Now, according to me, only `License` tag in `README` & changing the build triggers to `main` branch for Azure Pipelines is left ... Everything else has been fixed ... Though I will tinker around a bit to find any unnoticed bug(s) & will update the list ... will wait for a couple of days & then close accordingly :)

**Comment by abdulmoiz37** [comment]
Hi @jorgepiloto @DhruvSondhi I am looking to contribute to this issue in License in Readme to Understand more about the ecosystem and improve my chances for Selection.Can i Work on this issue or someone else is working on this issue currently?

**Comment by astrojuanlu** [comment]
@abdulmoiz37 Nobody else is working on it, feel free to fix the remaining `master` references :)

**Comment by abdulmoiz37** [comment]
#1141

**Comment by abdulmoiz37** [comment]
Hey @astrojuanlu Can u merge this #1141 to the main branch?...Now,I think Changing Building Triggers to main Branch for Azure Pipeline is Left

**Comment by astrojuanlu** [comment]
Done! :) Last one missing: Azure pipelines badges

**Comment by DhruvSondhi** [comment]
@astrojuanlu if no one wants to complete it should I go ahead?

**Comment by astrojuanlu** [comment]
@DhruvSondhi our general policy is that regular contributors should leave "good first issues" to newcomers

**Comment by abdulmoiz37** [comment]
I am Little Confused. Do i need to Change the the Link to Redirect of the Pipeline or Should I change the Badge to main Branch @astrojuanlu?

**Comment by AlphaVictorDelta** [comment]
Hey, I am new to open source. But I want to get the hang of it to participate in GSoC ( under libre Space Foundation). Where can I start?

**Comment by xlxs4** [comment]
Hey @AlphaVictorDelta!
[This](https://summerofcode.withgoogle.com/organizations/4651833357762560/) is a good start. Consider dropping a [hi](https://libre.space/community/) ✨

**Comment by astrojuanlu** [comment]
Closing this finally, thanks everyone!

**Comment by abdulmoiz37** [comment]
Your Welcome @astrojuanlu :)
