### ISSUE TITLE
bug in the alternative installation method of poliastro .

### ISSUE THREAD

**Issue by amanem1** [poliastro/poliastro#1128]
While trying the pip method to load poliastro on your desktop which is an alternative to the conda setup to do the installation process , the command provided there is to be reconsidered as it shows an error while running on the desktop .

the pip command  on this page https://docs.poliastro.space/en/latest/getting_started.html#alternative-installation-methods
here you find an  command written as -$ pip install https://github.com/poliastro/poliastro/archive/master.zip
if you follow the procedure you land up with error showing
<!---   ERROR: HTTP error 404 while getting https://github.com/poliastro/poliastro/archive/master.zippip

for me, when I was installing this setup using PIP command which is alternative to conda , the above error occured .

possible solutions -
instead of using this  command   -  $ pip install https://github.com/poliastro/poliastro/archive/master.zip
which is mentioned their in https://docs.poliastro.space/en/latest/getting_started.html#alternative-installation-methods documentation
use this command - $ pip install https://github.com/poliastro/poliastro/archive/main.zip
just replace this command and try , your command will definitely work
and the outcome would be something like-
successfully installed poliastro -0.15.dev0  this was what i got as output when i used the command 
$ pip install https://github.com/poliastro/poliastro/archive/main.zip
instead of 
$ pip install https://github.com/poliastro/poliastro/archive/master.zip

**Comment by astrojuanlu** [comment]
Closed in #1129
