### ISSUE TITLE
(Continuous) Localization

### ISSUE THREAD

**Issue by xlxs4** [poliastro/poliastro#1135]
According to the [index](https://docs.poliastro.space/en/latest/index.html):
> poliastro is developed by an open, international community.

Provided that all integration is seamless, it would be great if there was a way to include translated versions of the documentation. It can be strictly a community-based effort, requiring no effort from the development team.

💡 **Feature request**

A good idea would be something like [Weblate](https://weblate.org/en/), which provides [gratis hosting](https://hosted.weblate.org/hosting/) for libre projects (I don't know if they strictly provide these services to copyleft/GPL licensed projects). Of course alternatives exist and they should be explored.

🎯 **Goal**

Not only would this feature potentially enable non-fluent users to familiarize with poliastro, but it would also draw in community members that want to start being more involved (see https://github.com/orbit-love/orbit-model#orbit-3---participants for an example).

**Comment by jorgepiloto** [comment]
Hi @xlxs4! As far as I now, you can configure Read The Docs to point to project's translated documentation, so there is no need to use additional hosting providers or similar.

However, I am not sure if we have ever discussed about translated documentation. It is a very interesting topic, although it would require us to double our efforts on docs maintenance. Let us for other users and developers to comment on this issue 😉

**Comment by xlxs4** [comment]
Hi @jorgepiloto! Well, I didn't suggest it that much for the actual hosting, but rather for the other integration features services such as Weblate provide, which facilitate writing/adding/reviewing translations significantly. I don't know whether additional maintenance effort would be required, maybe we can depend on the community to enhance/cross-check; same thing happens with the official EN documentation

**Comment by astrojuanlu** [comment]
It would be very cool to have translated documentation! 🚀 As @jorgepiloto says, I think all of this should be possible inside Read the Docs: @xlxs4 can you have a look at https://docs.readthedocs.io/en/stable/localization.html and let us know what you find?

**Comment by xlxs4** [comment]
Sure, will do!

**Comment by astrojuanlu** [comment]
Unlikely that we will set this up. The project is quite small, and I think there's more value in folks producing tutorials or videos in their own language rather than translating the documentation. We can of course aggregate resources about poliastro in other languages if we ever find them :)

Closing.
