### ISSUE TITLE
add .DS_Store to .gitignore

### ISSUE THREAD

**Issue by ishanSrt** [poliastro/poliastro#1138]

**Comment by Yash-10** [comment]
Hello @ishanSrt, That seems to be a good option since macOS users have this annoying file generated. Would you like to make  PR?

**Comment by ishanSrt** [comment]
Sure

**Comment by xlxs4** [comment]
Might be useful:
* https://github.com/snielsen/DeathToDSStore
* from https://www.aorensoftware.com/blog/2011/12/24/death-to-ds_store/

**Comment by astrojuanlu** [comment]
Thanks @ishanSrt for opening this issue! It is indeed very annoying. I labeled this as a good first issue, therefore it should only be tackled by new contributors.

**Comment by astrojuanlu** [comment]
Fixed in #1151

**Comment by DhruvSondhi** [comment]
@astrojuanlu This issue can be closed as it has been fixed !!
