### ISSUE TITLE
Lambert transfers should be Maneuvers

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#114]
After writing http://nbviewer.jupyter.org/github/poliastro/poliastro/blob/6d5b231/examples/Exploring%20the%20New%20Horizons%20launch.ipynb#From-Earth-to-Jupiter I realized that the API for the Lambert problem is not consistent with the rest of maneuvers. I already considered this in https://github.com/poliastro/poliastro/wiki/API-Refactor:-Maneuver-objects.

**Comment by Juanlu001** [comment]
With the arrival of multi revolution solutions this is a bit unclear. I'm postponing the changes to next version.

**Comment by Juanlu001** [comment]
See https://github.com/poliastro/poliastro/wiki/API-Refactor:-Multi-revolution-Lambert-problem for details.

**Comment by Juanlu001** [comment]
It seems that @nikita-astronaut and I are doing some work on Maneuvers in the coming months, so I'm moving this to the next milestone.

**Comment by Juanlu001** [comment]
Out of time to make this work for this release, but we will be in a good position for the next one, also because we will be able to combine it with the flybys that we just introduced.

**Comment by Juanlu001** [comment]
Tons of work on reference frames and documentation for the next sprint. Postponing.

**Comment by Juanlu001** [comment]
Addressed in #680! It would be great to update [the User Guide](https://docs.poliastro.space/en/latest/user_guide.html#traveling-through-space-solving-the-lambert-problem) accordingly

**Comment by jorgepiloto** [comment]
Should we also update the notebooks [Going to Mars with Python using poliastro](https://docs.poliastro.space/en/latest/examples/Going%20to%20Mars%20with%20Python%20using%20poliastro.html) and [Going to Jupiter with Python using Jupyter and poliastro](https://docs.poliastro.space/en/latest/examples/Going%20to%20Jupiter%20with%20Python%20using%20Jupyter%20and%20poliastro.html)?

**Comment by Juanlu001** [comment]
Definitely!

**Comment by Juanlu001** [comment]
More than three years later, this is in :)
