### ISSUE TITLE
Remove numba as being optional in README?

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1146]
Just a quick glance at the [requirements](https://github.com/poliastro/poliastro#requirements) section of README.md made me realize that `numba` is still written to be optional where infact it was made mandatory in #1061 some time ago.

We should remove optional from there, isn't it?

Thanks!

**Comment by AlphaVictorDelta** [comment]
Done! 
I have made a pull request! waiting for it to get accepted

**Comment by astrojuanlu** [comment]
Closed in #1149.
