### ISSUE TITLE
Improve front documentation page to highlight documentation classification

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1150]
In #975 we reviewed our documentation classification according to The Documentation System, and now I think we should highlight it in our documentation more prominently, like the pandas people do:

![Screenshot_2021-04-03 pandas documentation — pandas 1 2 3 documentation](https://user-images.githubusercontent.com/316517/113488363-d9e00880-94bd-11eb-83ef-29f3c4462c5c.png)

One idea is to use something like https://github.com/executablebooks/sphinx-panels

By the way, "The Documentation System" is now called Diátaxis https://diataxis.fr/ 😉🇬🇷

**Comment by DhruvSondhi** [comment]
I would also suggest that we also have a custom CSS or Custom Theming scheme for the documentation as it will be more tailored towards _poliastro_.

**Comment by AlphaVictorDelta** [comment]
I am learning Advanced CSS (FlexBox and CSS_Grid) and BootStrap. I guess I can take this as an assignment. I'll get to apply my knowledge in realtime.

**Comment by astrojuanlu** [comment]
Hi @AlphaVictorDelta! I don't think we need much CSS knowledge here, have a look at the extension I linked

**Comment by astrojuanlu** [comment]
I'm blocking this issue on #1158.

**Comment by astrojuanlu** [comment]
Redirected everything to https://www.poliastro.space, working on having the apex domain (`https://poliastro.space`) working as well. Closing!

**Comment by astrojuanlu** [comment]
Sorry, I closed the wrong issue 🤦🏽

**Comment by astrojuanlu** [comment]
Not blocked anymore.

**Comment by astrojuanlu** [comment]
There was an attempt of doing this at #1175 that doesn't look too bad:

![Screenshot 2021-11-12 at 19-39-31 poliastro - Astrodynamics in Python — poliastro 0 16 dev0 documentation](https://user-images.githubusercontent.com/316517/141518506-459e19b3-fe51-40da-b929-0729d19469ac.png)

However, it's a minor cosmetic change that doesn't change the overall reader experience on our documentation. I think we should postpone these changes until we bite the bullet and hire a designer that revamps our docs.

This is, therefore, a non-task, so I'm going to close it.
