### ISSUE TITLE
Add `codemeta.json`

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1156]
Background: https://codemeta.github.io/

> I think `codemeta.json` is basically ready to supersede the badly documented `zenodo.json`.

(https://github.com/codemeta/codemeta/issues/213)

To validate it: https://github.com/caltechlibrary/convert_codemeta

Zenodo has support for it in its roadmap: https://github.com/zenodo/zenodo/issues/1504 but we can add it to our repository already.

Good starting point: https://zenodo.org/record/3816771/export/schemaorg_jsonld

Example: https://github.com/adrn/gala/blob/main/codemeta.json

**Comment by satyamroy001** [comment]
Hello, @astrojuanlu I randomly selected this issue for working before GSOC, I will send the updates soon !!

**Comment by satyamroy001** [comment]
@astrojuanlu  I will work on all these Issues left, but in this mean time I will work on this issue please assign this to me!!
I have started working please share the details of poliastro foe developing code meta

my work till now________________

"@context": "https://doi.org/10.5063/schema/codemeta-2.0",
    "@type": "SoftwareSourceCode",
    "datePublished": "2015-05-09",
    "name": "poliastro",
    "description": "poliastro is an open source collection of Python subroutines for solving problems in Astrodynamics and Orbital Mechanics.\n\npoliastro combines cutting edge technologies like Python JIT compiling (using numba) with young, well developed astronomy packages (like astropy and jplephem) to provide a user friendly API for solving Astrodynamics problems."
}

**Comment by abdulmoiz37** [comment]
Can I Contribute to this Isssue?

**Comment by satyamroy001** [comment]
@abdulmoiz37 but I am working on it !!!

**Comment by satyamroy001** [comment]
> Can I Contribute to this Isssue?

And I have solved 50% in the comment sections @abdulmoiz37

**Comment by astrojuanlu** [comment]
1. @satyamroy001 calling this 50 % is a bit optimistic in my opinion 😉 
2. The way you solve this issue is by doing a pull request, not by leaving comments here.
3. @abdulmoiz37 asked about contributing, so you could have proposed doing it together.
4. @satyamroy001 You asked twice about the details of poliastro, but in my initial commit I wrote everything you need, so I think you didn't pay enough attention to it.

Please reflect about this feedback and do better.

**Comment by abdulmoiz37** [comment]
Its okay @astrojuanlu.It will be great if @satyamroy001 Completes It.

**Comment by astrojuanlu** [comment]
Closed in #1172
