### ISSUE TITLE
Update software citations in documentation

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1157]
The SciPy and Astropy citations in https://github.com/poliastro/poliastro/blob/main/docs/source/bibliography.md are outdated, we should use the most recent ones:

- https://www.nature.com/articles/s41592-019-0686-2
- https://iopscience.iop.org/article/10.3847/1538-3881/aabc4f

**Comment by itsabhianant** [comment]
Hi @astrojuanlu ,

I got what your issue is and I think that I can resolve the issue.
Please assign me this issue so that I can start working on it as soon as possible.

Best,
Abhishek

**Comment by astrojuanlu** [comment]
Hi @itsabhianant ! Sure, all yours :)
