### ISSUE TITLE
Fix Link Redirection to NEO's Notebook in Binder

### ISSUE THREAD

**Issue by DhruvSondhi** [poliastro/poliastro#1160]
🐞 **Problem**
The Binder repository is giving a `404` error when trying to redirect to the `Using NEO Package` notebook.

💡 **Possible solutions**
Change the redirection link to the point to the correct notebook path in the `index.ipynb` notebook 😄

**Comment by abdulmoiz37** [comment]
I will Try to Work on this issue :)

**Comment by abdulmoiz37** [comment]
@DhruvSondhi @astrojuanlu I Found that Using NEO Package Notebook was Replaced Hence Binder Repo is Showing 404 Error🤒.
So I will Update The Redirection Link with Correct Notebook and I will Surely Resolve this Issue
