### ISSUE TITLE
Fix mention of 'easy' issues in CONTRIBUTING.md

### ISSUE THREAD

**Issue by nrishabh** [poliastro/poliastro#1164]
🐞 **Problem**
The `easy` tag for issues (mentioned in the [code writing](https://github.com/poliastro/poliastro/blob/main) section) does not exist anymore and the link for it in the doc appears broken. 

💡 **Possible solutions**
Change the phrase and the link such that it redirects to the "good first issue" tag.

**Comment by astrojuanlu** [comment]
Closed in #1165
