### ISSUE TITLE
Export to CZML

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#117]
See https://github.com/poliastro/poliastro/issues/22 for previous ideas.

**Comment by Juanlu001** [comment]
Relevant libraries:

* CesiumWidget http://mybinder.org/repo/petrushy/CesiumWidget
* cesiumpy http://mybinder.org/repo/sinhrks/cesiumpy

**Comment by Juanlu001** [comment]
Postponing this to 0.7, when the exporting capabilities are more mature.

**Comment by Juanlu001** [comment]
This might need a bit of refactoring after #22 is finally there. Postponing.

**Comment by Juanlu001** [comment]
Retargetting this as 0.8 as part of #22.

**Comment by Juanlu001** [comment]
Blocked on #237.

**Comment by Juanlu001** [comment]
Now that #263 has been implemented, this is no longer blocked.

**Comment by Juanlu001** [comment]
I have been doing a bit of research and I am not sure that exporting to CZML is worth it at all, since Cesium is mainly Earth-based (which is the main thing poliastro tries to avoid). Here is the email I have sent to an AGI representative:

> After some months, I am finally in a position where I can use poliastro with Cesium and CZML. However, I have been digging in the documentation and reading old google groups discussions and I could not find one feature that is essential for me: the ability to specify a central body that is *not* the Earth. That is mentioned in this outdated roadmap from 2015:
> 
> https://github.com/AnalyticalGraphicsInc/cesium/wiki/Architecture
> 
> > The CentralBody primitive represents the globe (in a future Cesium version, any central body such as the Moon and Mars will be supported).
> 
> 
> However, there are no further references since then.
> 
> I actually don't need high accuracy planetary imagery for each of the bodies of the Solar System, but a much simpler feature: specify a plain body with any color. Most of our work is based on interplanetary trajectories in the Solar System, so the sizes of the planets would be extremely small in comparison.
> 
> On the other hand, by reading the simple.czml example I see that nowhere it is specified which central body do the satellites orbit:
> 
> https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Specs/Data/CZML/simple.czml
> 
> This means that I can focus on exporting an orbit as a correct CZML and leave the rest to the user. But I fear that this will lead to incorrect results because there are many Earth-based assumptions in Cesium.

**Comment by Juanlu001** [comment]
This reassures our idea that Cesium was not a good option for us regarding 3D visualization. I'm removing the milestone from this issue until we have more information from AGI or someone comes up with an idea.

**Comment by Juanlu001** [comment]
I asked about this in the Cesium forum and got some interesting input, see thread:

https://groups.google.com/d/msg/cesium-dev/_zKyk0fRd-g/oTpRyuo8BgAJ

Although it's not Cesium primary goal, visualizing interplanetary trajectories is more or less feasible. This would require some work though, and a proper understanding of what's written above.

**Comment by himanshuc3** [comment]
Hi Juanlu. I want like to make a proposal for this issue. I am an aspirant in GSOC and would also further like to remain a long term contributor after GSOC finishes and help with improving the project.

**Comment by Juanlu001** [comment]
Hi @himanshuc3, thanks for your interest in poliastro! Apart from a proposal, OpenAstronomy requires that students make one meaningful pull request to the project. Please take a look at the list of "good first issues" :)

What I would expect from a proposal for this particular issue is:

* Clear understanding of the cesium-dev thread and its implications
* An incremental plan that can quickly produce a prototype, for example for orbits around the Earth, and that contemplates delivering value every 1-2 weeks

**Comment by Juanlu001** [comment]
This has been accomplished in #601 by @Sedictious. We will expand the functionality in the future!
