### ISSUE TITLE
Functional Description For `from_orbit` Method Not Rendered Correctly 

### ISSUE THREAD

**Issue by DhruvSondhi** [poliastro/poliastro#1170]
🐞 **Problem**

The class method `from_orbit` description inside `Ephem` class is not being rendered correct & can be seen [here](https://docs.poliastro.space/en/latest/autoapi/poliastro/ephem/index.html#poliastro.ephem.Ephem.from_orbit) in the latest documentation build.

💡 **Possible solutions**

Formatting the `docstring` for the `from_orbit` class method may fix the rendering issue. Care must be taken so as to adhere to the `.rst` format for Sphinx documentation generation for API Docs

**Comment by astrojuanlu** [comment]
https://github.com/poliastro/poliastro/blob/48bf2c6b64f3d35b005d0a60abe8bcd483adbced/src/poliastro/ephem.py#L313-L331

Unclear what's failing 🤔 But we should investigate and fix it.

**Comment by Yash-10** [comment]
Yes, locally testing does render that part correctly but maybe something happened that causes the latest docs to not render it as expected...

**Comment by DhruvSondhi** [comment]
Hello @astrojuanlu... This seems to be something weird going on ... I recently rebased the #1107 PR & then tried checking for the documentation of the `from_orbit` function ... and it fixes the documentation as seen [here](https://poliastro--1107.org.readthedocs.build/en/1107/autoapi/poliastro/ephem/index.html#poliastro.ephem.Ephem.from_orbit)

**Comment by astrojuanlu** [comment]
Perhaps a transient version problem. I'll try to rebuild `main` and see what happens.

**Comment by abdulmoiz37** [comment]
The Description in the from_orbit seems to render Correctly as per [https://docs.poliastro.space/en/latest/autoapi/poliastro/ephem/index.html#poliastro.ephem.Ephem.from_orbit](url).So it Doesn't Look Unclear @DhruvSondhi :)

**Comment by astrojuanlu** [comment]
It got fixed after rebuilding the docs. Closing!
