### ISSUE TITLE
`py:mod` roles do not link to corresponding summary page

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1198]
And they have never worked, apparently. See for example https://docs.poliastro.space/en/v0.13.1/changelog.html#backwards-incompatible-changes

I wonder if this is a limitation of autodoc or if we're misusing it.

**Comment by DhruvSondhi** [comment]
Hello @astrojuanlu, I did some digging around ... Though I haven't found any example where I can see the actual working of this `py:mod` tag, I have made some changes as shown 
![image](https://user-images.githubusercontent.com/66117751/116881437-e1bbd580-ac40-11eb-9c30-93e8c37ec8c3.png)
I don't understand this but this looks better :) ... It doesn't link to the summary page though 😥

**Comment by astrojuanlu** [comment]
> It doesn't link to the summary page though 😥 

Then it's not what we want... If `py:class` and `py:meth` work, I would be very interested in knowing why `py:mod` doesn't.

**Comment by DhruvSondhi** [comment]
> It would be very interested in knowing why `py:mod` doesn't
I may have understood why it is not working ... It is not working because the current file is not present in the updated codebase ... what I mean by this is that when we are referencing the module with the `py:mod` directive, due to the newer codebase not having the file, it is not linking it ... similar case would be when we link to a function or a class which doesn't exist in the codebase 🤔

**Comment by astrojuanlu** [comment]
You're right that the example I linked is a bad one. But I tried with other modules that do exist, with identical result.

**Comment by DhruvSondhi** [comment]
@astrojuanlu I found the answer, we were looking for ... it is on their docs page 🤦🏼 
![image](https://user-images.githubusercontent.com/66117751/116894413-a4127900-ac4f-11eb-935f-a44abfcee871.png)
We can do nothing in this context ... I think this closes this issue as well 😞 {[Link](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-py-module) here as well, check the last line of the paragraph}

**Comment by astrojuanlu** [comment]
Hahaha oh dear, I didn't know this! Thanks for actually _reading the docs_... I think it's safe to close this issue then.
