### ISSUE TITLE
Review examples

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#120]
- [ ] ~~Add custom matplotlibrc style, compatible with matplotlib 2.0~~
- [x] Rerun all with matplotlib 2.0
- [ ] ~~Add instructions on index to download SPK files~~
- [ ] Add explanations where missing
- [ ] Rewrite Cowell notebook using new methods, review error checking (more time to see significant changes?) and validation (perhaps take example from https://github.com/Juanlu001/pfc-uc3m/)
- [x] Rerun all notebooks and fix corresponding bugs
- [x] Add interactive widget to Mars notebook as done with the lightning talks
- [x] Add links in index to old notebooks (those checking performance of Python vs Fortran) and remove them from master
- [ ] ~~Move to a separate repository, hopefully preserving history (see https://git-scm.com/docs/git-filter-branch and http://blog.jupyter.org/2015/04/15/the-big-split/ for inspiration)~~

**Comment by AunSiro** [comment]
Tried to run this notebook with library just installed from conda forge:

https://github.com/poliastro/poliastro/blob/master/examples/Solving%20Lambert's%20problem%20in%20Python.ipynb

The comment cell states that it is necessary to activate a different branch, but:
- The link is dead
- There is no branch with the exact name stated
- There is no info or link on how to change the active branch with poliastro installed through conda

**Comment by AunSiro** [comment]
Tried to run the "Going to Mars with Poliastro", had critical failure dowloading ephemeris (404):

https://github.com/poliastro/poliastro/blob/master/examples/Going%20to%20Mars%20with%20Python%20using%20poliastro.ipynb

In code cell 2º had the following warnings:

> No SPICE kernels found under ~/.poliastro.
> Please download them manually or using
> 
>   poliastro download-spk [-d NAME]
> 
> to provide a default kernel, else pass a custom one as
> an argument to `planet_ephem`.
> 
> Downloading de421.bsp from http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/, please wait...
> Not Found
> Downloading de421.bsp from http://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/a_old_versions/, please wait...
> 

The links appear to be dead as of now. Following this, calling the function:
`ephem.planet_ephem(ephem.EARTH, times_vector)`
will return:

 

> TypeError                                 Traceback (most recent call last)
> <ipython-input-13-7202734be5bc> in <module>()
> ----> 1 ephem.planet_ephem(ephem.EARTH, times_vector)
> 
> C:\Anaconda3\lib\site-packages\poliastro\ephem.py in planet_ephem(body, epoch, kernel)
>     130 
>     131     """
> --> 132     r, v = kernel[0, body].compute_and_differentiate(epoch.jd1, epoch.jd2)
>     133     r = r * u.km
>     134     v = v * u.km / u.day
> 
> TypeError: 'NoneType' object is not subscriptable

**Comment by Juanlu001** [comment]
Won't rerun the examples until we have settled on the legends issue #230.

**Comment by Juanlu001** [comment]
This is not blocked anymore.
