### ISSUE TITLE
Displaying plots from poliastro

### ISSUE THREAD

**Issue by OrbitalMechanic** [poliastro/poliastro#122]
I've successfully installed poliastro ver. 0.4.3 on my MacBook Pro running Mac OS X ver. 10.11.3 in the Anaconda environment for Python 2.7. in the example attached to this note, I've not been able to get poliastro to display a plot.

Any thoughts?

[OrbPlt.py.txt](https://github.com/poliastro/poliastro/files/183492/OrbPlt.py.txt)

**Comment by Juanlu001** [comment]
Hello @OrbitalMechanic, you are right: in non interactive mode, this code won't plot anything (and this behaviour is not explained in poliastro docs). You have to import matplotlib and add a `plt.plot()` call at the end, in this way:

```python
import numpy as np
from astropy import units as u
import matplotlib.pyplot as plt  # See below
from poliastro.bodies import Earth, Sun
from poliastro.twobody import State
from poliastro.plotting import plot
# Data from Curtis, example 4.3
r = [-6045, -3490, 2500] * u.km
v = [-3.457, 6.618, 2.533] * u.km / u.s
ss = State.from_vectors(Earth, r, v)
plot(ss)

plt.show()  # Blocks the interpreter and displays the plot
```

If you use the Jupyter Notebook you can activate the inline mode typing `%matplotlib inline`. Feel free to close the issue if these worked for you.

Finally, I encourage you to register in the mailing list I have just created :) https://groups.io/g/poliastro-dev

**Comment by OrbitalMechanic** [comment]
@Juanlu001 tried your suggestion. It worked. Thanks.
