### ISSUE TITLE
Smarter initial estimates of eccentric and hyperbolic anomaly?

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1240]
💡 **Feature request**
It deals with the calculation of eccentric and hyperbolic anomaly from the mean anomaly using the newton-raphson iteration method. Specifically, the [`M_to_E`](https://github.com/poliastro/poliastro/blob/main/src/poliastro/core/angles.py#L262) and [`M_to_F`](https://github.com/poliastro/poliastro/blob/main/src/poliastro/core/angles.py#L294) in `core/angles.py`.

The "feature request" comes from a section in "Fundamentals of Astrodynamics and Applications" by Vallado under the section "Hybrid solutions" in chapter 2.

![hybrid](https://user-images.githubusercontent.com/68844397/120311911-b38bed00-c2f5-11eb-984f-647f68706236.png)

Barring the case of parabolic motion (since the values can be determined deterministically using the cubic equation already), the section states that by using a slightly smarter initial guess for the eccentric and hyperbolic anomaly for elliptic and hyperbolic motion, the computation time can be decreased by ~15%. Algorithm 2 and 4 in the book provides the algorithm for it.

**Further points**
- The functions are jitted and using the `timeit` module gives the following rough analysis:

Note: the below "no. of iterations" are the no. of times both the implementations are run using `timeit` and not the no. of iterations for the newton-raphson method.

    - For 1000 iterations, there is ~0.26 s time improvement.
    - For 10000 iterations, there is ~2.62 s time improvement.
    - For 100000 iterations, there is ~26.08 s improvement.

Summarizing it in a graph:

![image](https://user-images.githubusercontent.com/68844397/120313601-d9b28c80-c2f7-11eb-958a-23918ccbd4b5.png)

A starter implementation can be seen [here](https://github.com/Yash-10/poliastro/commit/7ca4d7e298cdf59e6e07c094b5d7ab2e7c6d7001). Important to note, the linked implementation yields a slight mismatch for the hyperbolic case but works perfectly fine for the elliptical case. Maybe it has to do with the no. of iterations in the newton method.

**Benefits**
This results in a micro-improvement (even if the functions were already jitted) in terms of execution time.

I would love to get any thoughts on this.

Thanks!

**Comment by jorgepiloto** [comment]
Hi @Yash-10. I reviewed your code, and it matches Vallado's one. Could you please develop more about those differences within the Hyperbolic case? I checked that your implementation passes all current tests related with angle computations.

**Comment by Yash-10** [comment]
Hi @jorgepiloto thank you so much for reviewing the code and for your confirmation!

I shall take a closer look for the slight inaccuracies in the hyperbolic case. I noticed a line in Vallado, which mentions:

![hyperbolic](https://user-images.githubusercontent.com/68844397/120641130-ddc5e200-c490-11eb-8108-f3527546d8f0.png)

Where Algorithm 4 was for the hyperbolic case. So probably some investigation needs to be taken on that line.

**Comment by jorgepiloto** [comment]
Closing this. Thank you @Yash-10 👍🏽
