### ISSUE TITLE
LaTeX PDF documentation fails

### ISSUE THREAD

**Issue by OrbitalMechanic** [poliastro/poliastro#1242]
Is there a way to generate documentation of poliastro ver. 0.15.0 as a pdf file? When I attempted to so I get:

(base) user@Mac-Pro docs % make latexpdf
sphinx-build -b latex -d build/doctrees   source build/latex
Running Sphinx v4.0.1

Extension error:
Could not import extension autoapi.extension (exception: No module named 'autoapi')
make: *** [latexpdf] Error 2
(base) user@Mac-Pro docs %

Any suggestions?

Sam Dupree.

**Comment by astrojuanlu** [comment]
Hello @OrbitalMechanic , sorry for the delay!

After reading your request I went to Read the Docs because I though they were generating the PDF for us, but apparently not. So I opened an issue about it https://github.com/readthedocs/readthedocs.org/issues/8253

On the other hand, to generate the PDF, these are the steps:

```
(base) $ pip install .[dev]  # From the `pyproject.toml` directory
(base) $ cd docs
(base) $ make latexpdf
```

In other words, you were missing the `[dev]` extra dependencies, that install the documentation dependencies.

I am generating the PDF myself now, I'll attach it here.

**Comment by astrojuanlu** [comment]
(Edit: added one extra set of dependencies)

**Comment by astrojuanlu** [comment]
Well, it turns out that our PDF documentation with LaTeX is a bit broken :)

```
! Package inputenc Error: Unicode character ♁ (U+2641)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.544 ...ound Earth (♁) at epoch J2000.000 (TT)}
                                                  
? 
```

I typed `S` to skip the errors.

**Comment by astrojuanlu** [comment]
And finally, I got it! I am not 100 % sure that this is complete, but it's a start. [poliastro.pdf](https://github.com/poliastro/poliastro/files/6637407/poliastro.pdf)

Noting this as a bug, thanks as always @OrbitalMechanic 🙏🏽

**Comment by astrojuanlu** [comment]
I also tried generating the PDF with rinohtype, but it failed: https://github.com/brechtm/rinohtype/issues/267

**Comment by OrbitalMechanic** [comment]
Juan,

Thank you responding to my posting. I tried to generate the PDF using 
your procedure below. The result I get is the error message:

(base) user@Mac-Pro poliastro % pip install .[dev]
zsh: no matches found: .[dev]

 From the posting on GitHub I tried |pip install .[dev,cesium] and got 
the following error message|

(base) user@Mac-Pro poliastro % pip install .[dev,cesium]
zsh: no matches found: .[dev,cesium]

Now I checked the poliastro GitHub download file and got

(base) user@Mac-Pro poliastro % ls -l
total 224
-rw-r--r--   1 user  staff  3132 Jun  6 22:31 CODE_OF_CONDUCT.md
-rw-r--r--   1 user  staff  5124 Jun  6 22:31 CONTRIBUTING.md
-rw-r--r--   1 user  staff  1132 Jun  6 22:31 COPYING
-rw-r--r--   1 user  staff   166 Jun  6 22:31 MANIFEST.in
-rw-r--r--@  1 user  staff   373 Jun  6 22:31 Makefile
-rw-r--r--   1 user  staff  8720 Jun  6 22:31 README.md
-rw-r--r--   1 user  staff  2212 Jun  6 22:31 azure-pipelines.yml
drwxr-xr-x   3 user  staff   102 Jun  6 22:31 binder
-rw-r--r--   1 user  staff  5824 Jun  6 22:31 codemeta.json
drwxr-xr-x   5 user  staff   170 Jun  6 22:31 contrib
drwxr-xr-x   5 user  staff   170 Jun  6 22:32 docs
-rw-r--r--   1 user  staff  4288 Jun  6 22:31 index.ipynb
-rw-r--r--   1 user  staff    87 Jun  6 22:31 mypy.ini
-rw-r--r--   1 user  staff  2961 Jun  6 22:31 pyproject.toml
-rw-r--r--   1 user  staff   378 Jun  6 22:31 setup.cfg
drwxr-xr-x   3 user  staff   102 Jun  6 22:31 src
drwxr-xr-x  20 user  staff   680 Jun  6 22:31 tests
-rw-r--r--   1 user  staff  2165 Jun  6 22:31 tox.ini

There is no pyproject.toml, but as you'll see I have pyproject.toml 
directory.

Please advise.

Sam Dupree.

**Comment by astrojuanlu** [comment]
I see! The command I gave you needs to be tweaked according to https://stackoverflow.com/a/30539963

Please try `pip install '.[dev,cesium]'`

**Comment by astrojuanlu** [comment]
I came back to this. Yes, PDF documentation build is failing with obscure LaTeX syntax errors. I have no idea how to fix them, but if anyone wants to dig deep enough, you're welcome to do so.

Good starting point:

```diff
diff --git a/.readthedocs.yaml b/.readthedocs.yaml
index 9f6a399e..ded872c2 100644
--- a/.readthedocs.yaml
+++ b/.readthedocs.yaml
@@ -15,3 +15,7 @@ python:
 
 sphinx:
   fail_on_warning: true
+
+formats:
+  - html
+  - pdf
diff --git a/docs/source/conf.py b/docs/source/conf.py
index adbe8f54..56322d41 100644
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -177,3 +177,6 @@ exclude_patterns.extend(["autoapi/index.rst", "autoapi/poliastro/index.rst"])
 # Ignore sphinx-autoapi warnings on reimported objects
 # See https://github.com/readthedocs/sphinx-autoapi/issues/285
 suppress_warnings.append("autoapi.python_import_resolution")
+
+# LaTeX settings for PDF generation
+latex_engine = "xelatex"
```

**Comment by OrbitalMechanic** [comment]
Attempted to build the latexpdf document for poliastro ver. 0.17.0 under Mac OS X version 12.4 (Monterey), and it fails with the message:

```
Latexmk: Missing input file 'tgtermes.sty' (or dependence on it) from following:
  '! LaTeX Error: File `tgtermes.sty' not found.'
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'poliastro.log' for details
Latexmk: If appropriate, the -f option can be used to get latexmk
  to try to force complete processing.
make[1]: *** [poliastro.pdf] Error 12
make: *** [latexpdf] Error 2
(base) user@Mac-Pro docs %
```

See the attached file for details.
[poliastro_latexpdf_build_log.txt](https://github.com/poliastro/poliastro/files/9088481/poliastro_latexpdf_build_log.txt)

**Comment by astrojuanlu** [comment]
Hi @OrbitalMechanic, thanks for trying it out!

I did a quick search and the root cause seems to be a missing TeX package, possibly `tex-gyre` or similar. I'm not sure how did you install LaTeX/TeXLive on macOS, could you try finding this package and updating us?

I'd love to bring PDF/static documentation back but LaTeX is a mess. Thinking about exporting the HTML as a static document or similar, would that work for you?

**Comment by OrbitalMechanic** [comment]
See my responses below.

Sam Dupree.


On July/11/2022 21:51:22, Juan Luis Cano Rodríguez wrote:
>
> Hi @OrbitalMechanic <https://github.com/OrbitalMechanic>, thanks for 
> trying it out!
>
> I did a quick search and the root cause seems to be a missing TeX 
> package, possibly |tex-gyre| or similar. I'm not sure how did you 
> install LaTeX/TeXLive on macOS, could you try finding this package and 
> updating us?
>
*/Used the TeXLive utility to install the TeX packages I needed on a 
package by package basis. However, I still get errors using latexpdf. / **
*
> **
>
> I'd love to bring PDF/static documentation back but LaTeX is a mess. 
> Thinking about exporting the HTML as a static document or similar, 
> would that work for you?
>
/*I was able to build the HTML-based documentation successfully. In 
addition, I was able to build the epub based documentation as well. 
Either of these solutions will work for me.*//
/
