### ISSUE TITLE
Feature discussion - Eclipse

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1244]
**Background**

The `core/perturbations.py` module has an existing [`shadow_function`](https://github.com/poliastro/poliastro/blob/main/src/poliastro/core/perturbations.py#L180) which uses geometrical manipulation to calculate whether a satellite is in earth's shadow or not. This binary switching function assisted in turning solar radiation pressure "on" and "off" based on the shadow function.

For determining if a satellite is in eclipse or not and their entry and exit times, having a model that accounts for umbral and penumbral regions might be good to have. First, we could find out if the satellite is in sunlight or is in the umbra or the penumbra region. Further, we could also determine the entry and exit times of the eclipse for a satellite. 

For the latter idea, the book by Vallado assumes a cylindrical earth shadow (effectively not considering the shadow as umbra or penumbra but a single type of earth shadow of zero solar pressure). This assumption might have been made to ease the complexity of the analysis since determining times of eclipse requires integration operations, which seems to be trickier by itself.

The paper [On Satellite Umbra/Penumbra Entry and Exit Positions](https://apps.dtic.mil/sti/pdfs/ADA320904.pdf) dealt with eclipse times for both cylindrical and conical earth shadow.

**Question**

If we intend to focus on umbral and penumbral regions (and not just a cylindrical earth shadow), we could detect and find times of entry and exit times within these regions. In such a case, there most likely will be a need to modify the [`radiation_pressure`](https://github.com/poliastro/poliastro/blob/main/src/poliastro/core/perturbations.py#L233) to account for umbral (zero solar pressure) and penumbral (minute non-zero solar pressure) regions.

This feature of dealing with umbral and penumbral regions is good to have. Still, I wondered if it adds some complexity, given the above points, for example.

**Summary**

Do we go with umbra and penumbra analysis (and consider everything that is needed to accompany it, for example, the solar pressure variations) or stick with a cylindrical earth shadow assumption as is currently done in `poliastro`?

Thanks!

**Comment by apogeecmb** [comment]
I have some relatively simple logic coded up from algorithms in the book Mission Geometry written by James Wertz that calculates whether a satellite is currently in eclipse and what type of eclipse (umbra, penumbra, annular).  It's just trig functions, no integration required.  But it requires position vectors for the Sun, Earth, and the satellite.  Would that be of interest?  You can't predict entry or exit times using it.  It just tells you the instantaneous eclipse status.

**Comment by Yash-10** [comment]
Thank you for reaching out @apogeecmb ! Based on what you said, it seems that the algorithm you propose is similar to the one in Vallado since it too works on simple trigonometric calculations and returns a boolean value, whether the satellite is in eclipse or not. Since poliastro uses scipy's `solve_ivp`, it turned out that we do not need to manually integrate the system of equations (although there are pure mathematical treatments in the literature to do that).

Since scipy's `solve_ivp` expects a continuous output which it can use to detect events, the task has effectively boiled down to return a value that continuously varies with time and use that as a basis for detecting eclipse conditions for a propagating orbit.

If you would have any thoughts/suggestions on the on-going discussion in #1246, it would be great!

Thanks again.

**Comment by astrojuanlu** [comment]
Some inspiration from Orekit: https://gitlab.orekit.org/orekit/orekit/-/blob/develop/src/37d6c3d1/java/org/orekit/propagation/events/EclipseDetector.java#L173-191 looks like a continuous function?

**Comment by Yash-10** [comment]
Orekit's implementation seems to be relatively shorter and cleaner. Although, there's the method `pointOnLimb` being used in `EclipseDetector` here: https://gitlab.orekit.org/orekit/orekit/-/blob/develop/src/main/java/org/orekit/propagation/events/EclipseDetector.java#L182 whose code is here: https://gitlab.orekit.org/orekit/orekit/blob/develop/src/main/java/org/orekit/bodies/Ellipsoid.java#L246. There seems to be a bit of geometry involved. I think poliastro doesn't deal with an attractor's limb yet.

As a result, there might be a need of adding a `pointOnLimb` like method in perhaps, `spheroid_location.py`? In such a case, the logic again gets complicated. So the question is whether to:

- Add "limb" capabilities in `poliastro`  and make the eclipse implementation totally inspired from `orekit`, or
- Stick with vallado's treatment of eclipse.

---
I also saw that using the `shadow_function` in current main [(here)](https://github.com/poliastro/poliastro/blob/main/src/poliastro/core/perturbations.py#L180) inside eclipse events seems to be in close agreement with orekit's validation case (poliastro/validation#29) even though orekit's implementation uses the star's radius but `shadow_function` doesn't. 

So there might be a need to check if the current main's `shadow_function` might suffice to use in eclipse events and we could get away with `pointOnLimb`...

**Comment by astrojuanlu** [comment]
Closed in #1246 🎉  @Yash-10 will add some extra documentation soon 💪🏽
