### ISSUE TITLE
Problem with testing on Windows 7 64bit

### ISSUE THREAD

**Issue by Fedor-Lyanguzov** [poliastro/poliastro#126]
Hi,

I've tried to install poliastro and when i've gotten to test it, i had this problem:
```
============================= test session starts =============================
platform win32 -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: c:\, inifile: 

======================== no tests ran in 0.00 seconds =========================
ERROR: file not found: C:\Program
```
I'm using Windows 7 Pro 64bit, with Python 3.5.1 installed in `C:\Program Files\Python35`, command: `python -c "import poliastro.testing; poliastro.testing.test()"`

There are many issues with installation due to lack of wheel packages of requirements for 64bit arch, which are not related to poliastro, but may provide valuable info, so this is what i've done during install:

1. Tried to install with pip, failed because of inability to build c-extensions (error: `unable to find vcvarsall.bat`)
2. Installed Visual C++ Build Tools 2015 (https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/, also inspired, but not strongly following https://github.com/nodejs/node-gyp/wiki/Visual-Studio-2010-Setup)
3. Couldn't find `Windows SDK 7.1 Command Prompt` or anything similar, tried to install with pip again, failed (error: `file kernel32.lib not found`)
4. Started installing requirements with pip one by one, installed `NumPy`, failed on `Astropy`
5. Downloaded and installed unofficial wheels for `Astropy`, `numba`, `SciPy`, `llvmlite` (numba's requirement) from http://www.lfd.uci.edu/~gohlke/pythonlibs/
6. Installed `matplotlib` and `jplephem` with pip
7. Tried to test, failed without `pytest`
8. Installed `pytest` with pip
9. At last, tried to test, failed with aformentioned error

My guess, this bug is located somewhere in `poliastro.testing` line 10, but what could it be - i have no ideas.

**Comment by Fedor-Lyanguzov** [comment]
By the way, i've tried "Going to Mars with Python using poliastro" locally, it works, but not on first run. On first run code downloads kernel "de421", but do not make it the default kernel (`ephem.default_kernel`), because selecting default kernel is done on `ephem` import.

**Comment by franktoffel** [comment]
I have been bitten several times by the 'vcvarsall.bat' error when trying to install packages via pip in windows. I strongly encourage to use [Anaconda](https://www.continuum.io/downloads) or its lightweight version, called [miniconda](http://conda.pydata.org/miniconda.html), instead.

Poliastro should be ready to install in windows machines as well:
https://anaconda.org/search?q=poliastro

Let us know if you need help getting used to Anaconda/miniconda

**Comment by Juanlu001** [comment]
I already confirmed the first problem, it's a coding bug in poliastro too (see https://github.com/pytest-dev/pytest/issues/1703 for my mental process). Will fix soon.

**Comment by Fedor-Lyanguzov** [comment]
Hi @Juanlu001,

> Regarding the installation: to be honest, no Python developer expects sane users to have working compilers on Windows 

Yeah. I totally agree with you. BUT: i wanted to install Linux on my laptop on vacation trip, but found my BIOS passworded, and me not remembering anything about it. So for now, i'm stuck with win7pro, and a huge creativity. 

> Could you please paste the output of these commands?

```
> pip --version
pip 8.1.2 from c:\program files\python35\lib\site-packages (python 3.5)
> python -c "import setuptools; print(setuptools.__version__)"
24.0.2
> python -c "import wheel; print(wheel.__version__)"
0.29.0
```

https://pypi.python.org/pypi/astropy/1.2.1 - whl for win x64 nowhere to be found.
https://pypi.python.org/pypi/numba - same.

> Also, in case you don't know it consider using Anaconda or miniconda, since they are specially tailored for scientific Python packages.

Thank you, i might give it a try. I'm not the TRUE science person, i just want my little games be realistic. I'll try anaconda with `panda3d`, it's just spectacular to observe real-timeish simulation of star systems.

On a side note, maybe you could add a testing requirement for `pytest` in the docs? Thanks in advance.

**Comment by Juanlu001** [comment]
> Yeah. I totally agree with you. BUT: i wanted to install Linux on my laptop on vacation trip, but found my BIOS passworded, and me not remembering anything about it. So for now, i'm stuck with win7pro, and a huge creativity. 

Why bad things happen to good people? :sweat_smile: 

> https://pypi.python.org/pypi/astropy/1.2.1 - whl for win x64 nowhere to be found.
https://pypi.python.org/pypi/numba - same.

Damn, I didn't know there where no wheels for Windows... they probably assume a conda installation or the use of Christoph Gohlke packages :persevere: 

> Thank you, i might give it a try. I'm not the TRUE science person, i just want my little games be realistic. I'll try anaconda with panda3d, it's just spectacular to observe real-timeish simulation of star systems.

So you're thinking about using poliastro to make a game? Wow, keep us posted about that :smile:

> On a side note, maybe you could add a testing requirement for pytest in the docs? Thanks in advance.

Sure, thanks for the suggestion!

**Comment by Juanlu001** [comment]
Hi @Fedor-Lyanguzov, I fixed the original issue of the testing in the master branch.

* If you want to install from source, you can download the repository and run `pip install path\to\poliastro-master.zip`
* As it is a very small change, you can edit `C:\Program Files\Python35\Lib\site-packages\poliastro\testing.py` in this way:

https://github.com/poliastro/poliastro/commit/ae618ffa

For the selection of the ephemerides I will open a new issue as it will take me some more time.

**Comment by Fedor-Lyanguzov** [comment]
Hi @franktoffel, thanks for suggestion. Your proposition is very nice, but i should try to sort this out by myself first.

Hi @Juanlu001, thank you for your time and work. I'm going to make a truly open-source realease (with requirements.txt and setup.py and all of that sort) of my game sometime near fall, so i'll send you a message then.
