### ISSUE TITLE
possible to get a conda-compatible .bz2 file?

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [poliastro/poliastro#1278]
I'm hoping to get a conda-compatible .bz2 file so that I can avoid using pip.  (pip tends to produce corrupted environments, while I haven't experienced that with conda).

**Comment by astrojuanlu** [comment]
Hi @Phillip-M-Feldman ! We produce conda packages through conda-forge https://github.com/conda-forge/poliastro-feedstock is that enough for you? `conda install poliastro --channel conda-forge` should work

**Comment by Phillip-M-Feldman** [comment]
I was looking for the .bz2 file, which I found here:
https://anaconda.org/conda-forge/poliastro/files

Thanks!

Phillip
