### ISSUE TITLE
Mismatch in planet state

### ISSUE THREAD

**Issue by SimplyLucKey** [poliastro/poliastro#1287]
🐞 **Problem**
Initial planet state is not matching to JPL's ephemeris.

I was verifying my own lambert algorithm and found a mismatch in planet state when using JPL ephermis.

```
raw_date_launch = '2032-12-26 00:00'
raw_date_arrival = '2035-09-30 00:00'

date_launch = time.Time('2032-12-26 00:00', scale='tdb')
date_arrival = time.Time('2035-09-30 00:00', scale='tdb')

ss0 = Orbit.from_ephem(Sun, Ephem.from_body(Earth, date_launch), date_launch)
ssf = Orbit.from_ephem(Sun, Ephem.from_body(Mars, date_arrival), date_arrival)

man_lambert = Maneuver.lambert(ss0, ssf)
dv_a, dv_b = man_lambert.impulses
```

<details>
  
```
output:
launch date in jd: 2463592.5
arrival date in jd: 2464600.5
ss0.r.si = [-1.16978071e+10  1.34580240e+11  5.83580584e+10] m
ss0.v.si = [-30200.28463037  -2150.28625857   -932.83918015] m / s

ssf.r.si = [ 2.07740347e+11  5.14298750e+09 -3.21333056e+09] m
ssf.v.si = [  423.12926315 23903.5174167  10952.92214908] m / s
```
</details>

```
JPL's raw data (in km and km/s):
Earth:
2463592.500000000 = A.D. 2032-Dec-26 00:00:00.0000 TDB 
 X =-1.169790465171204E+07 Y = 1.466884109345771E+08 Z = 9.536910870127380E+03
 VX=-3.020028448569751E+01 VY=-2.343910554849657E+00 VZ=-5.292465694742843E-04

Mars:
2464600.500000000 = A.D. 2035-Sep-30 00:00:00.0000 TDB 
 X = 2.077432333850707E+08 Y = 3.432835468984354E+06 Z =-4.994442094667937E+06
 VX= 4.217528540925862E-01 VY= 2.628730343052505E+01 VZ= 5.408912715256982E-01
```

**Comment by jorgepiloto** [comment]
Hi @SimplyLucKey! By default, poliastro will use astropy's builtin ephemeris, which are different from JPL ones, see [astropy's docs](https://docs.astropy.org/en/stable/api/astropy.coordinates.solar_system_ephemeris.html):

```
- 'builtin': polynomial approximations to the orbital elements.
- 'de430' or 'de432s': short-cuts for recent JPL dynamical models.
- 'jpl': Alias for the default JPL ephemeris (currently, 'de430').
- URL: (str) The url to a SPK ephemeris in SPICE binary (.bsp) format.
- PATH: (str) File path to a SPK ephemeris in SPICE binary (.bsp) format.
- `None`: Ensure an Exception is raised without an explicit ephemeris.
```

If you want to use JPL, then you must include the following line before executing any other code:

```python
from astropy.coordinates import solar_system_ephemeris
solar_system_epehemeris("jpl")
```

Previous code will ensure the usage of JPL for your computations when using poliastro 👍🏽

**Comment by jorgepiloto** [comment]
Also, notice that astropy makes use of DE430, although JPL also provides other type of epehemeris, see [JPL ephemeris webpage](https://ssd.jpl.nasa.gov/?planet_eph_export).

**Comment by SimplyLucKey** [comment]
> ```python
> solar_system_epehemeris("jpl")
> ```

I included the code but I was getting a TypeError. 
`TypeError: __init__() takes 1 positional argument but 2 were given`

**Comment by astrojuanlu** [comment]
@SimplyLucKey please try this instead:

```python
solar_system_ephemeris.set("jpl")
```

**Comment by SimplyLucKey** [comment]
> @SimplyLucKey please try this instead:
> 
> ```python
> solar_system_ephemeris.set("jpl")
> ```
That took care of the bug but the initial states are still the same as before.

**Comment by astrojuanlu** [comment]
Sorry @SimplyLucKey , I'm not following - if I understand your issue correctly, you expected `ss0` and `ssf` to match what JPL HORIZONS gave you. When you say "that took care of the bug", what do you mean exactly?

We can investigate a bit further if the assumptions in poliastro and HORIZONS are the same or not, but we would need your HORIZONS inputs as well. For example, heliocentric vs barycentric is a common source of displacements, and equatorial vs ecliptic is a common source of rotations. From a quick visual inspection at the numbers, you seem to have both.

**Comment by SimplyLucKey** [comment]
@astrojuanlu Sorry, what I meant was that the initial state didn't change but the code was able to compile.
I uploaded my data below for both earth and mars

https://ssd.jpl.nasa.gov/horizons.cgi
[earth_data.txt](https://github.com/poliastro/poliastro/files/6897624/earth_data.txt)
[mars_data.txt](https://github.com/poliastro/poliastro/files/6897625/mars_data.txt)

**Comment by astrojuanlu** [comment]
I had the chance to have a look at this issue more closely. Let's narrow down its scope a bit.

With this code:

```python
from astropy import units as u
from astropy.coordinates import solar_system_ephemeris

from poliastro.bodies import Earth
from astropy import time
from poliastro.ephem import Ephem

solar_system_ephemeris.set("jpl")

date_launch = time.Time('2032-12-26 00:00', scale='tdb')
e = Ephem.from_body(Earth, date_launch)
r, v = e.rv()

print(e.epochs[0])
print(r.to(u.km))
print(v.to(u.km / u.s))
```

I get this result:

```
2032-12-26 00:00:00.000
[[-1.16978000e+07  1.34580239e+08  5.83580605e+07]] km
[[-30.20028449  -2.15028542  -0.93283965]] km / s
```

which doesn't match what you have in `earth_data.txt`:

```
2463592.500000000 = A.D. 2032-Dec-26 00:00:00.0000 TDB 
 X =-1.169790465171204E+07 Y = 1.466884109345771E+08 Z = 9.536910870127380E+03
 VX=-3.020028448569751E+01 VY=-2.343910554849657E+00 VZ=-5.292465694742843E-04
```

However, it looks like the source of the JPL data is `DE441`, whereas Astropy is using `DE430/DE431`:

```
In [13]: print("\n".join(solar_system_ephemeris.kernel.comments().splitlines()[:7]))


September 03, 2013
C. Acton

JPL's Solar System Dynamics Group has released two new planetary/lunar ephemerides,
named DE430 and DE431.
```

Therefore, there is a chance that the mismatch comes from there. Investigating.

**Comment by astrojuanlu** [comment]
Immediately after writing my previous comment I realized that the differences in Y, Z and VY, VZ were just too big. I then tried changing the plane:

```diff
--- ephem.py	2021-08-06 19:00:35.493972801 +0200
+++ ephem.new.py	2021-08-06 19:05:49.603120912 +0200
@@ -3,12 +3,13 @@
 
 from poliastro.bodies import Earth
 from astropy import time
+from poliastro.frames import Planes
 from poliastro.ephem import Ephem
 
 solar_system_ephemeris.set("jpl")
 
 date_launch = time.Time('2032-12-26 00:00', scale='tdb')
-e = Ephem.from_body(Earth, date_launch)
+e = Ephem.from_body(Earth, date_launch, plane=Planes.EARTH_ECLIPTIC)
 r, v = e.rv()
 
 print(e.epochs[0])
```

with this result:

```
2032-12-26 00:00:00.000
[[-1.16978048e+07  1.46688458e+08  9.55533159e+03]] km
[[-3.02002844e+01 -2.34391160e+00 -5.26545112e-04]] km / s
```

@SimplyLucKey ☝🏽 this looks mostly correct now, although not pixel-perfect.

**Comment by astrojuanlu** [comment]
By specifying the relevant DE441 URL directly:

```diff
--- ephem.new.py	2021-08-06 19:05:49.603120912 +0200
+++ ephem.new2.py	2021-08-06 19:09:54.736540388 +0200
@@ -6,7 +6,7 @@
 from poliastro.frames import Planes
 from poliastro.ephem import Ephem
 
-solar_system_ephemeris.set("jpl")
+solar_system_ephemeris.set("https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de441_part-2.bsp")
 
 date_launch = time.Time('2032-12-26 00:00', scale='tdb')
 e = Ephem.from_body(Earth, date_launch, plane=Planes.EARTH_ECLIPTIC)
```

I got this result:

```
$ python ephem.new2.py 
Downloading https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de441_part-2.bsp
|========================================================================================================================================================================================================| 1.6G/1.6G (100.00%)      9m12s
2032-12-26 00:00:00.000
[[-1.16979095e+07  1.46688411e+08  9.56312440e+03]] km
[[-3.02002844e+01 -2.34391155e+00 -5.26563796e-04]] km / s
```

which is still not exactly the same data that can be obtained in HORIZONS, but is close.

**Comment by astrojuanlu** [comment]
I have a loooooooong story fighting against HORIZONS (see #222, https://github.com/astropy/astropy/pull/6508, https://github.com/astropy/astropy/pull/8394). It's a painful task because the naming conventions are different everywhere, and some choices of equinox, ecliptic, and obliquity are hidden or implicit. Unfortunately I don't have the bandwidth to devote one full weekend or a whole week to debugging this anymore 😓 Therefore, in case I don't follow up with the root cause of the difference, some ideas so folks can keep debugging it:

- Be very careful with the HORIZONS input. Understand what every parameter means before trying to compare its output with other systems.
- poliastro uses https://docs.astropy.org/en/stable/api/astropy.coordinates.get_body_barycentric_posvel.html as can be seen in the source of `Ephem.from_body`. The ICRS coordinates should match exactly.
- There is a transformation from ICRS to ecliptic coordinates involved. However, there is a chance that our choice of `BarycentricMeanEcliptic` does not match your HORIZONS query:

https://github.com/poliastro/poliastro/blob/0c2d441bdd79cee40ed421506edc41492c8f16d3/src/poliastro/ephem.py#L143-L144

There are two possibilities here: (a) this is just wrong for your query, or (b) this is wrong for all ecliptic queries. In the first case, you would have to find the appropriate query to compare the data. In the second case, this is a bug in poliastro.

I will leave this issue open, in case you want to dig a bit more.

**Comment by astrojuanlu** [comment]
The bot decided to close this issue, and that's fine for me. My last comment still stands though, if folks are certain that there is a bug in poliastro ecliptic transformation, feel free to report it.
