### ISSUE TITLE
Handling multiple propagation's for some events

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1289]
There were some ideas about the `LOSEvent` or detecting whether two satellites collide or not. Such events consider two propagating orbits instead of the single orbit case, for example, in the eclipse event.

The events are eventually passed as an argument to the `cowell` method which propagates a single orbit. As a result, this discussion aims to think about ways in which multiple orbits can be handled inside:

- the `__call__` method, and/or
- the `cowell` method.

or if there would be a way to get away with dealing with multiple orbits and still get the desired output somehow.

An initial idea might be to allow `cowell `to take multiple positions and velocity vectors and return the propagated vectors corresponding to each passed state. However:

- The `cowell` method is sometimes found to have slowed down execution. For eg: in the radiation pressure tests.
- The `cowell` method is not yet `jitted` due to the involvement of `solve_ivp`.

So I wonder if adding this functionality might harm some performance.

**Comment by astrojuanlu** [comment]
Rather than propagating two objects, we should receive a trajectory of the secondary object. Then we can compute the miss distance.

**Comment by astrojuanlu** [comment]
I don't think we'll support multiple propagation, probably too complex. Closing in favor of #1485.
