### ISSUE TITLE
Change plotting units

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1291]
💡 **Feature request**

By default, plots are shown with the axis in kilometers, like this one:

![plot](https://user-images.githubusercontent.com/316517/126806072-a3370201-8cd5-4586-a675-023644618908.png)

And the reason is that units are hardcoded here:

https://github.com/poliastro/poliastro/blob/19880062af49dbf92147528f1b98de378a3d4e89/src/poliastro/plotting/core.py#L186-L190

It would be nice to be able to change those units easily. This can be manually done manipulating the Plotly figure, but it's far from ideal.

A possible solution would be to add a `unit` parameter to the initializer of `_PlotlyOrbitPlotter`, here:

https://github.com/poliastro/poliastro/blob/19880062af49dbf92147528f1b98de378a3d4e89/src/poliastro/plotting/core.py#L17-L18

so that in `_plot_coordinates` we end up with this code:

```python
    def _plot_coordinates(self, coordinates, label, colors, dashed):
        trace = Scatter3d(
            x=coordinates.x.to_value(self.unit),
            y=coordinates.y.to_value(self.unit),
            z=coordinates.z.to_value(self.unit),
```

Notice that this would require modifying also the initializers of `OrbitPlotter3D` and `OrbitPlotter2D`, as well as the corresponding `super` calls.

**Comment by Patil2099** [comment]
I would love to pick this up
