### ISSUE TITLE
Fix attractor size when plotting different orbits

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#130]

**Comment by Juanlu001** [comment]
Related to #111. Postponing.

**Comment by anhiga** [comment]
I was about to open an issue when I saw this one.

As title says, attractor size when plotting distant orbits seems too big.
![figure_1](https://user-images.githubusercontent.com/18404378/29026890-52945f0e-7b7e-11e7-8af6-29ca6c7eaa15.png)

It can be fixed changing [line 126 in plotting.py](https://github.com/poliastro/poliastro/blob/master/src/poliastro/plotting.py#L126) from:
```Python
radius = max(orbit.attractor.R.to(u.km).value, orbit.r_p.to(u.km).value / 6) 
```
to
```Python
radius = orbit.attractor.R.to(u.km).value
```
but I suppose that without that `max` statement, attractor would appear really small in most cases, so I don't know if there is any solution.

**Comment by Juanlu001** [comment]
> but I suppose that without that `max` statement, attractor would appear really small in most cases, so I don't know if there is any solution.

Yep, that's the problem. There is also another thing:

https://github.com/poliastro/poliastro/blob/286e524/src/poliastro/plotting.py#L125

The attractor is being plotted one time for each planet. We could always plot the "real" radius, and although it would be too small in most cases, it is the easiest way to fix a sensible value without ruining the plot. Perhaps we should plot the attractor only once in the first place?
