### ISSUE TITLE
Links in README

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1300]
- The alternative installation link here: https://github.com/poliastro/poliastro/#installation seems to not work. Instead this could work: https://docs.poliastro.space/en/latest/installation.html#alternative-installation-methods ?
- Maybe the contributing link can be explicitly redirected to `main` instead of `master`?
- Would it be a good option to provide a link for `COPYING` file here: https://github.com/poliastro/poliastro/#license ?

Thanks!

**Comment by astrojuanlu** [comment]
- This link https://github.com/poliastro/poliastro#installation works for me 🤔 How is it not working for you? And where did you find it?
  - In any case, https://docs.poliastro.space/en/stable/installation.html is a good alternative (be careful with `stable` vs `latest`, the right choice depends on context)
- Yes, I see a couple of references to `master` in README, we should replace them:

https://github.com/poliastro/poliastro/blob/a153edbd909613f09c7967f7ccb23b0d127ad44e/README.md#L12

https://github.com/poliastro/poliastro/blob/a153edbd909613f09c7967f7ccb23b0d127ad44e/README.md#L108

- By the way, we can remove `master_doc` from `conf.py`, we are using the default value
- You mean, apart from the badge? Yes, let's do it

**Comment by Yash-10** [comment]
Sorry for the confusion,

> The alternative installation link here: https://github.com/poliastro/poliastro/#installation seems to not work. Instead this could work: https://docs.poliastro.space/en/latest/installation.html#alternative-installation-methods ?

I meant the link under the "installation" section which reads "Please check out the documentation for alternative installation methods." seems to not work. Instead, the link https://docs.poliastro.space/en/latest/installation.html#alternative-installation-methods could be used?


> Would it be a good option to provide a link for COPYING file here: https://github.com/poliastro/poliastro/#license ?

> You mean, apart from the badge? Yes, let's do it

I am not sure if I got it right: The README says "Please refer to the COPYING file." but doesn't give a link to the COPYING file. So I was thinking if we could have a link for COPYING there instead if just the text COPYING.

Thanks!

**Comment by astrojuanlu** [comment]
Agreed with both 👍🏽
