### ISSUE TITLE
inconsistent number of inputs to density functions in different atmospheric models causes error

### ISSUE THREAD

**Issue by orbitfab-ethan** [poliastro/poliastro#1302]
In poliastro\core\perturbations there is a function atmospheric_drag_model.  This calculates rho (density) using the model.density function, when model.density is called in poliastro\core\perturbatoins.atmospheric_drag_model there is only 1 input.  However, the Jachia atmospheric model has 2 inputs to its density function.  Therefore, attempting to propagate an orbit with the Jachia 77 atmospheric drag model results in an error 

<TypeError: density() missing 2 required positional arguments: 'alt' and 'Texo'>

🐞 **Problem**

I am using conda, results of 'conda info -a' and 'conda list' are attached.

**Comment by astrojuanlu** [comment]
Hi @orbitfab-ethan , thanks for your interest in poliastro!

You're totally right: COESA76 has 1 parameter

https://github.com/poliastro/poliastro/blob/6b9e5a2ef5233e10ce557257f7d369159a82338f/src/poliastro/earth/atmosphere/coesa76.py#L231-L232

but Jacchia77 has 2:

https://github.com/poliastro/poliastro/blob/6b9e5a2ef5233e10ce557257f7d369159a82338f/src/poliastro/earth/atmosphere/jacchia.py#L135-L136

This is a bug. Happy to receive pull requests to fix it.

**Comment by orbitfab-ethan** [comment]
@astrojuanlu, thanks for getting back to me.  I can make that fix and create a pull request. However, I don't see anywhere in poliastro's modules that Texo (exospheric temperature) is defined.  Should that be a user input variable or calculated within poliastro?  If you can point me to where I can get an algorithm for that I'm happy to make it a function in poliastro/earth/atmosphere/jachia.py and include that in my pull request.

**Comment by astrojuanlu** [comment]
You can draw some inspiration from `test_jacchia77.py`, however to be completely honest I missed this detail when I reviewed #1113 and I'm not sure where `Texo` should come from. Summonning @jorgepiloto as my local expert in atmospheres :)

**Comment by orbitfab-ethan** [comment]
@astrojuanlu Can we get some input from @jorgepiloto on this?

**Comment by jorgepiloto** [comment]
Hi @orbitfab-ethan, sorry for the delay answering this. Thank you for spotting this. I am only experienced with COESA models and only have an small idea of the mathematical model behind Jacchia-77 atmosphere.

Sadly, I am quite busy at this moment. Nevertheless, I will take a closer look by the end of the month together with https://github.com/poliastro/poliastro/issues/1256.

**Comment by jorgepiloto** [comment]
Hi @orbitfab-ethan, after a quick review of the original article, I see that the exospheric temperature (`Texo` variable) is in fact a required parameter for computing the density. 

Jacchia models consider Sun's effects on upper atmosphere and this `Texo` temperature is the one carrying this information.

**Comment by jorgepiloto** [comment]
This is the line producing this bug:

https://github.com/poliastro/poliastro/blob/48c854a4ad5500116f7c09ca171f77a60e2de04b/src/poliastro/core/perturbations.py#L176

**Comment by jorgepiloto** [comment]
An approach to solve this could be to pass the density as a parameter. The function should be renamed from `atmospheric_drag_model` to `atmospheric_drag` instead, as it no longer accepts an atmospheric model.

In addition to this, I think the `atmospheric_drag_exponential` model should be moved to another module, as duplicates the logic of this future `atmospheric_drag` function.

**Comment by astrojuanlu** [comment]
Discussed in our community meeting today, totally agree with @jorgepiloto suggestion above ☝🏽

**Comment by astrojuanlu** [comment]
Fixed by #1334! Will see the light in the next release, Coming Soon ™
