### ISSUE TITLE
`norm` of position vectors less than attractor radius sometimes?

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1307]
Initially observed in #1258, I was thinking about the below behaviour since some time and has been partly blocking some progress in #1258. For example, using the below:
```py
from astropy import units as u
from numpy.linalg import norm

from poliastro.bodies import Earth
from poliastro.twobody import Orbit
from poliastro.twobody.propagation import cowell

orb = Orbit.from_classical(Earth, 9000 * u.km, 0.56*u.one, 7*u.deg, 0*u.deg, 0*u.deg, 0*u.deg)

tofs = [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.5] << u.s

r, v = cowell(
    Earth.k,
    orb.r,
    orb.v,
    tofs,
)
```

and checking `r`:

```
[[3960, 0.12437535, 0.015271372], [3960, 0.24875069, 0.030542745], [3960, 0.37312604, 0.045814117], [3960, 0.49750139, 0.061085489], [3960, 0.62187673, 0.076356861], [3960, 0.74625208, 0.091628234], [3959.9999, 0.87062742, 0.10689961], [3959.9968, 6.2187657, 0.76356841]]km
```

Checking their `norm`:

```py
[norm(r_) for r_ in r]
```
gives
```
[<Quantity 3960.00000071 km>,
 <Quantity 3960.00000285 km>,
 <Quantity 3960.00000641 km>,
 <Quantity 3960.00001139 km>,
 <Quantity 3960.00001779 km>,
 <Quantity 3960.00002562 km>,
 <Quantity 3960.00003487 km>,
 <Quantity 3960.00177928 km>]
```

It seems their norm is less than the attractor's radius. I am not so sure but does this look like a valid result? Since these are wrt to the center of the attractor, the *norm must have been always greater than the radius of the attractor*, isn't it? Or did I miss something?

What I think is that orbits with:

- semi-major axis (`a`) not very bigger than the radius of their attractor (for eg: orbit with 9000 km semi-major axis about the Earth), and combined with
- not low eccentricities

maybe cause such orbits to cut the attractor?

![Screenshot from 2021-08-18 11-06-53](https://user-images.githubusercontent.com/68844397/129843185-129cb4e9-1016-483a-b636-6b733c2604b1.png)

Any insights/thoughts on this?

Thanks!

**Comment by Yash-10** [comment]
It was decided that:

- For general use of orbits that cut the attractor (as seen above from the plots), we should do nothing.
- However, for the particular case of using such orbits for LOS events (under development), we should raise an error if the orbit starts cutting the attractor.

**Failure of an edge case**
An immediate edge case for this is when the Lithobrake event is used with LOS. If the orbit is going to cut the attractor and the `events` parameter has both LOS and Lithobrake, then ideally Lithobrake must have terminated the propagation. But that case doesn't seem to perform as expected locally since even using both, LOS raises an error even though lithobrake was terminated earlier than LOS. This error is raised during the call to `solve_ivp`.

This means that the error is because of the arrangement of logic blocks inside `cowell`. The newly added block:

```py
if events is not None:
...
...
...
    tofs = [tof for tof in tofs if tof < last_t] + [last_t]
```
is done after `solve_ivp`. Hence the `tofs` that `solve_ivp` gets, are not the cropped ones.

**Implication**
This could mean that any errors raised inside the event class (either inside `__call__` or inside `core/events`) which would potentially be raised after the cropped time, would be raised forcefully even if we cropped the position vectors using the newly added block above.

**Possible solutions**
- Raise a warning instead of an error inside the LOS event. This would resolve any unexpected behaviors, but this option was not decided a good one. Also because the LOS calculations could work unexpectedly if satellite is below the surface.

**Comment by astrojuanlu** [comment]
Discussed at length in #1258 and here. We decided for the warning solution, which appears to be the "lesser evil". Thanks @Yash-10 and @jorgepiloto for the throrough discussion!
