### ISSUE TITLE
Examples missing from the gallery

### ISSUE THREAD

**Issue by MLopez-Ibanez** [poliastro/poliastro#1341]
Is there a reason why some examples such as:

https://github.com/poliastro/poliastro/blob/main/docs/source/examples/Multirevolutions%20solution%20in%20Lamberts%20problem.mystnb

are not shown in the gallery?

https://github.com/poliastro/poliastro/blob/main/docs/source/gallery.md

It would be great if they were. Happy to submit a pull request if desired.

**Comment by astrojuanlu** [comment]
We moved this one to https://docs.poliastro.space/en/stable/examples/Multirevolutions%20solution%20in%20Lamberts%20problem.html in #1158, to differentiate between How-to Guides and Background.

But perhaps this is useful enough that should be moved to the Examples?
