### ISSUE TITLE
Bug in plot_maneuver

### ISSUE THREAD

**Issue by MLopez-Ibanez** [poliastro/poliastro#1377]
This cannot be correct:

https://github.com/poliastro/poliastro/blob/80c7de132c42c751d47fbb495dc54fb3e3460f12/src/poliastro/plotting/_base.py#L171-L173

If the len() is zero, then one cannot index it.

**Comment by astrojuanlu** [comment]
Lazy reviewer's fault ✋🏽 Good catch @MLopez-Ibanez
