### ISSUE TITLE
Is there any reason why func_twobody is not @jit ?

### ISSUE THREAD

**Issue by MLopez-Ibanez** [poliastro/poliastro#1380]
https://github.com/poliastro/poliastro/blob/81b1738c723a2a821f387ef017fff9426e979c5f/src/poliastro/core/propagation/__init__.py#L38-L40

This prevents using it in jitted functions.

**Comment by astrojuanlu** [comment]
Historical reason! It used to have a more complex signature, but I didn't realize in https://github.com/poliastro/poliastro/pull/1053 that we could JIT it.

This is a trivial contribution, so I'm going to label it as such. Please leave this one for first timers.

**Comment by junietoc** [comment]
We can `@jit` this function by simply
`@jit()
def func_twobody(t0, u_, k):
    """Differential equation for the initial value two body problem.
`
This will used the Numba JIT (Just In Time) Compiler in `nopython` mode (since `njit` is imported as `jit`)

**Comment by astrojuanlu** [comment]
That's right @junietoc ! Awaiting your pull request 🙌🏼
