### ISSUE TITLE
Return values of change_ecc_inc are inconsistent with other thrust functions

### ISSUE THREAD

**Issue by MLopez-Ibanez** [poliastro/poliastro#1381]
https://github.com/poliastro/poliastro/blob/d0a13af27e5971e3435c9a762942041201ee13a6/src/poliastro/twobody/thrust/change_ecc_inc.py#L74

returns beta ?

But all others return:
```python
return a_d, delta_V, t_f * u.s
```

Also the return values are not documented.

**Comment by astrojuanlu** [comment]
> But all others return:

I see how this is inconsistent, but I think it makes sense to return extra parameters when appropriate. We could change this to

```python
    return a_d, (delta_V, beta_), t_f
```

instead.

In the meanwhile, [PEP 3132 Extended Iterable Unpacking](https://www.python.org/dev/peps/pep-3132/) works:

```
In [30]: l1 = "a", 1, 2, "z"

In [31]: l2 = "a", 3, "z"

In [32]: a, *_, z = l1

In [33]: a, z
Out[33]: ('a', 'z')

In [34]: a, *_, z = l2

In [35]: a, z
Out[35]: ('a', 'z')
```

> Also the return values are not documented.

Right, we should change this.

**Comment by MLopez-Ibanez** [comment]
> > But all others return:
> 
> I see how this is inconsistent, but I think it makes sense to return extra parameters when appropriate.

Sure, but why here and not in the others? Sorry, I may be missing something obvious.
