### ISSUE TITLE
the beta function in change_ecc_inc.py does not reproduce the figures in the original paper

### ISSUE THREAD

**Issue by MLopez-Ibanez** [poliastro/poliastro#1382]
Hi,

I'm trying to reproduce Figure 5 in https://apps.dtic.mil/sti/pdfs/ADA384536.pdf where Eq 9 seems to correspond to this code:
 
https://github.com/poliastro/poliastro/blob/d0a13af27e5971e3435c9a762942041201ee13a6/src/poliastro/core/thrust/change_ecc_inc.py#L8-L29

but the plot is completely different:

```python
import numpy as np
from poliastro.core.thrust.change_ecc_inc import beta
from matplotlib import pyplot as plt
inc_f = np.linspace(0,30,100)
for ecc_0 in [0.1, 0.2, 0.4, 0.6, 0.8]:
    betas = beta(ecc_0 = np.deg2rad(ecc_0), ecc_f = 0, inc_0 = 0, inc_f = np.deg2rad(inc_f),
                 argp=np.deg2rad(180))
    betas = np.rad2deg(betas)
    plt.plot(inc_f, betas)
    plt.text(inc_f[-1], betas[-1], f'ecc={ecc_0}')
plt.show()
```

**Comment by astrojuanlu** [comment]
Weird, [originally](https://github.com/astrojuanlu/pfc-uc3m/blob/master/code/plot_combined_ei_analytic.py) the plots looked correct:

![Screenshot 2021-11-05 at 16-26-09 study-analytical-solutions pdf](https://user-images.githubusercontent.com/316517/140535664-936814fc-0725-46df-b2a3-fa540e4653af.png)

Fortunately I provided an `environment.yml` file, although [it doesn't work directly](https://github.com/astrojuanlu/pfc-uc3m/issues/2). With [some effort](https://github.com/astrojuanlu/pfc-uc3m/issues/3), I managed to reproduce the original plot, as it appears in Pollard, 2000.

Perhaps we made a mistake when translating the code from my project to poliastro? This requires closer inspection.

**Comment by astrojuanlu** [comment]
> ```python
> import numpy as np
> from numpy.testing import assert_allclose
> from astropy import units as u
> from poliastro.twobody.thrust import change_ecc_inc
> from poliastro.twobody import Orbit
> from poliastro.bodies import Sun
> from poliastro.core.propagation import func_twobody
> from poliastro.twobody.propagation import propagate, cowell
> 
> orbit = Orbit.from_vectors(Sun, r=np.array([-3.87956134e+08,  1.05155086e+08,  1.30885524e+07]) << u.km,
>                            v=np.array([ -4.96831485, -18.42591704,  -0.09133032]) << (u.km / u.s))
> 
> a_d, deltav, t_f = change_ecc_inc(orbit, ecc_f = 0, inc_f = 0, f = 1e-4 << (u.m / u.s ** 2))
> 
> def apply_thrust(orbit, t_f, a_d):
>     def f(t0, state, k):
>         du_kep = func_twobody(t0, state, k)
>         ax, ay, az = a_d(
>             t0,
>             state,
>             k,
>         )
>         du_ad = np.array([0., 0., 0., ax, ay, az])
>         # print(t0, end=':')
>         # print(du_kep, end=':')
>         # print(du_ad)
>         return du_kep + du_ad
>     return orbit.propagate(t_f, method=cowell, rtol=1e-9, f=f)
> 
> orbit = apply_thrust(orbit, t_f, a_d)
> assert_allclose(orbit.inc, 0.)
> assert_allclose(orbit.ecc, 0.)
> ```
> 
> ```
> In [2]: orbit.inc
> Out[2]: <Quantity 0.17070543 rad>
> 
> In [3]: orbit.ecc
> Out[3]: <Quantity 0.0282447>
> ```
> 
> They look very far from what was expected.

(From #1383)

**Comment by MLopez-Ibanez** [comment]
> Fortunately I provided an `environment.yml` file, although [it doesn't work directly](https://github.com/astrojuanlu/pfc-uc3m/issues/2). With [some effort](https://github.com/astrojuanlu/pfc-uc3m/issues/3), I managed to reproduce the original plot, as it appears in Pollard, 2000.

The correct values used to generate those plots would make a nice test to check for.

**Comment by MLopez-Ibanez** [comment]
Apologies, there is a mistake in my code. Eccentricity does not have units. I created a notebook that replicates the plots using the latest version of poliastro. So this is not the root of #1383
