### ISSUE TITLE
Typos in atmospheric model documentation

### ISSUE THREAD

**Issue by tjnd89** [poliastro/poliastro#1406]
The documentation for the atmospheric models has some minor errors in spelling and graph labels. 

🐞 **Problem**

On this page https://docs.poliastro.space/en/latest/examples/Atmospheric%20models.html#Temperature,-pressure-and-density-distrubutions the following errors exist:

1. The word "distrubutions" is misspelled. It should be "distributions". This exists in two places.
2. The temperature plot at the bottom has the X-axis mislabeled as "Altitude [K]" when it should be "Temperature [K]". 

💡 **Possible solutions**

Update the doc and code example to correct the two errors.

**Comment by astrojuanlu** [comment]
Thanks for reporting @tjnd89 ! Do you want to send a pull request for those?

**Comment by tjnd89** [comment]
Yep, I'll pull one together. I'm new to the whole github thing and am fighting through a bunch of missing dependencies in order to build the docs via "make html". I'll open a separate issue on the missing requirements.

**Comment by astrojuanlu** [comment]
If you want, you can make the edits directly on the GitHub interface, and a Continuous Documentation service will render the docs when you open the pull request: 

https://github.com/poliastro/poliastro/blob/1b3da82d82328c5d748959455d93b18b1e740364/docs/source/examples/Atmospheric%20models.mystnb#L115

**Comment by astrojuanlu** [comment]
Closed in #1408.
