### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1427]
There is one broken link in https://github.com/poliastro/poliastro#can-i-do-insert-awesome-thing-with-poliastro (spotted by @jorgepiloto)

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this. Is there anyone on it already?

**Comment by astrojuanlu** [comment]
Hi @Carlosbogo , all yours! 😃

**Comment by Carlosbogo** [comment]
Hi, sorry for the late reply, I had my final exams and couldn't work on it before.
Could you tell me which link is the broken one? I have been looking around a bit but I couldn't find it.

**Comment by astrojuanlu** [comment]
No worries! The "commonly used Astrodynamics software" leads to a "page not found".
