### ISSUE TITLE
Do not include `contrib/` in coverage measurements

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1452]
As per title. Comes from https://github.com/poliastro/poliastro/pull/1451#issuecomment-1018510181 by @jorgepiloto.

**Comment by SidharajYadav** [comment]
Respect Sir,
I'm Siddharaj Yadav a computer engineering undergraduate, Pursuing TE at D Y Patil College under (Pune University).
I am new to open source contribution but I am well aware of Python,Django,HTML and Git& GitHub. I would to contribute to your organization but could you please tell me how to get started? Gsoc
Hoping to hear from you soon

mail- sidharajyadav157@gmail.com
