### ISSUE TITLE
Documentation typo in Hohmann (Maneuver) functions (altitude/orbital radius)

### ISSUE THREAD

**Issue by manweichan** [poliastro/poliastro#1454]
The documentation for Hohmann transfers incorrectly describes the r_f input parameter as the 'altitude' of the orbit. The following equations support that r_f is actually the orbital radius, not altitude (distance above the surface of the gravitational body). I'm thinking this may trip someone up in the future.

[poliastro/core/maneuver](https://github.com/poliastro/poliastro/blob/726c95d17da3fb6b43bf38ace5b2b17170e1255f/src/poliastro/core/maneuver.py#L39)
[poliastr/maneuvero](https://github.com/poliastro/poliastro/blob/726c95d17da3fb6b43bf38ace5b2b17170e1255f/src/poliastro/maneuver.py#L86)

Note: this should be a quick fix, and I figure this would be the best channel to expose this error, but please let me know if there's another preferred way.

📋  **Steps to solve the problem**

 * Change lines above from `final altitude of the orbit` to `final orbital radius`

**Comment by astrojuanlu** [comment]
Good catch @manweichan ! Do you want to send a pull request?

**Comment by manweichan** [comment]
Looks like I was slow to the pull! 

Thanks @Sync271 for fixing this!

I've never contributed to a project before and was working through the documentation. I'll definitely try to contribute to another issue in the future!

Looks like this one can be closed.

**Comment by Sync271** [comment]
> Looks like I was slow to the pull! 
> 
> Thanks @Sync271 for fixing this!
> 
> I've never contributed to a project before and was working through the documentation. I'll definitely try to contribute to another issue in the future!
> 
> Looks like this one can be closed. 

I just started contributing, thanks to you too in a way for reporting the issue :)

**Comment by manweichan** [comment]
Awesome @Sync271 ! If I may ask, what do you find easiest for contributing? Working from the GitHub browser, cloud, or local?

**Comment by Sync271** [comment]
@manweichan check for issues that have "good first issue", which usually are editable through a browser
