### ISSUE TITLE
Update CI badge in README file

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#1463]
🐞 **Problem**

After migrating from Azure Pipelines to CircleCI (as per #1458), the CI badge in README became outdated.

💡 **Solution**

Badge generation is described in [this CircleCI guide](https://circleci.com/docs/2.0/status-badges/#generating-a-status-badge). We should add the required link within `README.md` file.

**Comment by astrojuanlu** [comment]
Closed in #1466
