### ISSUE TITLE
`numpy.ndarray` instead of `np.array` in docstrings?

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1482]
I observed that sometimes the numpy array docstrings looks like this:

https://github.com/poliastro/poliastro/blob/9797eb079d7ce86b39aaef379b750d88c3135ce2/src/poliastro/core/util.py#L56

whereas sometimes like this:

https://github.com/poliastro/poliastro/blob/ada3fce2d26bdb020db38d54795d0b2a63d05760/src/poliastro/core/propagation/gooding.py#L52

The latter seems to be a better choice since it renders a link when viewing the documentation which is not observed when using the former. I am not sure if the former style was used due to the documentation style followed, but maybe the inconsistency is something that could be worked upon?

**Comment by astrojuanlu** [comment]
> The latter seems to be a better choice since it renders a link when viewing the documentation which is not observed when using the former.

Correct! I fixed some of those in #1438 after applying https://github.com/Carreau/velin but it didn't pick them all apparently. Happy to get pull requests for this one (preferably from new contributors).
