### ISSUE TITLE
Unify coding style dependencies

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#1487]
💡 **Feature request**

At the moment, there are three separate files holding coding style requirements:

1. The `pyproject.toml`. In this file, it is possible to find the style requirements in the `dev` group.
2. The `.pre-commit-config.yaml`. This file is not able to parse previous one, so dependencies need to be declared again.
3. The `tox.ini` file. Becasue the `[check]` environment does not install the project, we are forced to pass the required commands.

It is likely that, eventually, we miss the same version for a particular tool or that these three files end up being different from the point of view of the coding style. 

🎯 **Goal**

The goal is to unify all of them following these steps:

* All style requirements must be only defined in the `.pre-commit-config.yaml`.
* In the `tox.ini` file, the `[check]` style should read as follows:

   ```bash
    description = Checks for coding style
    skip_install = True
    deps = pre-commit
    commands = 
        pre-commit install
        pre-commit run --all-files
    ```
* Finally, we could get rid of the code style dependencies in the `pyproject.toml`. Unless those are being parsed by any third tool, I think previous approach unifies and simplifies the problem depicted before.

By the way, if users would like to use `pre-commit`, they can install it by doing `python -m pip install pre-commit`.

**Comment by astrojuanlu** [comment]
We were hit again by this: https://github.com/poliastro/poliastro/pull/1495
