### ISSUE TITLE
How to unittest?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [poliastro/poliastro#1488]
I tried to unittest your code. But `unittest` do not discover any tests.

```
python3 -m unittest discover

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

```

How do you test your code?

**Comment by astrojuanlu** [comment]
I can reproduce, even with an activated environment:

```
(.venv)  juanlu at valinor in ~/Projects/LSF/poliastro/library on main
$ python -m unittest discover

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

However, we don't use `unittest` for our tests, we use `pytest` instead. You can either run `pytest`, or better yet, `tox`. Closing, but feel free to continue the discussion if you still face problems.
