### ISSUE TITLE
Add patched conics computations

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#150]

**Comment by AunSiro** [comment]
Fly-by maneuvers are extremely sensitive to initial conditions. In KSP, I frequently observe that changes of ~0.5 m/s a quarter of an orbit before the encounter can result in dramatic differences, often changing the post-flyby trajectory more than 40º.

Maybe, an interesting approach can be the following:
First, use the desired objective of the maneuver, like the vectorial dV obtained or flyby trayectory, to obtain a hyperbolic flyby orbit, and propagate it backwards in time with precision to the limit of the SOI.

Using the required speed vector, a collision heliocentric orbit is calculated. 

Then calculate the correction maneuvers required to get to the entering SOI point with the required speed vector.

Maybe, the first two steps can be executed in the inverse order, getting a cone of the possible post flyby trajectories given a collision trajectory, and then finding the optimum one from this possibility space.

**Comment by AunSiro** [comment]
I propose having a minimun flyby altitude for every planet equal to 2% of the planet radius (p.ej, for Earth is ~120 km).
Imagine a generic orbit plane. Assuming a hyperbolic orbit, depending on the speed at the periapsis, a speed can be calculated either at both intersections of the orbit with the SOI or at the infinite before and after flyby. Then, a vectorial difference between the entering and leaving velocities can be calculated. Therefore, we can correlate a maximum speed change with every entering speed, that is to say, the maximum delta v obtainable with a flyby without additional propulsion can be calculated depending only on the scalar value of the relative speed between the spacecraft and the planet. 

I think that getting the function that calculate it could be a good starting point!

**Comment by Juanlu001** [comment]
Thanks a lot for these ideas Siro! I am starting a new page in the wiki to draft a proposal of an API:

https://github.com/poliastro/poliastro/wiki/Patched-conics-computations

Let us first try to imagine how one would **use** these functions and then proceed to implement them. We can take other pages of the wiki as inspiration, for example https://github.com/poliastro/poliastro/wiki/Maneuver:-New-ideas or https://github.com/poliastro/poliastro/wiki/API-Refactor:-Maneuver-example.

Working on this again after four years is going to be extremely refreshing! :smile:

**Comment by AunSiro** [comment]
I suggested some ideas in the wiki page, check them and tell me what do you think!

**Comment by Juanlu001** [comment]
This looks promising! Some comments here:

* Instead of adding more methods to `Body` (I would like to keep these objects small, see our discussions in #153) why not having a new module and pass a body as an argument, closer to what it's done with the Lambert problem?

```
>>> (v0, v), = iod.lambert(Sun.k, r0, r, tof)
>>> max_norm_dv, max_tan_dv, max_angle_change = flyby.max_flyby(Earth.k, relative_speed)
```

(keeping your notation in this example)

Actually, these flybyes should probably be some kind of `Maneuver` (see also #114), but we can ignore that for the time being because there's a big refactor pending there.

* Being able to return a vector would be interesting... but in which reference frame? See the email I sent you four years ago 😅 and this Physics.SE answer http://physics.stackexchange.com/q/69792/7641
* The 2 % margin over the planet radius seems sensible, but it's of course arbitrary. Why not leave it as an optional parameter?

```
>>> _ = flyby.max_flyby(Earth.k, relative_speed)  # 2 %
>>> _ = flyby.max_flyby(Earth.k, relative_speed, margin=0.05)  # 5 %
>>> _ = flyby.max_flyby(Earth.k, relative_speed, margin=5)  # 5 %, maybe this is better?
>>> _ = flyby.max_flyby(Earth.k, relative_speed, margin=-1)  # Should negative values raise a ValueError?
```

(the parameter name is not important, but should be explicit enough)

I don't comment on the rest because I think there's enough work here :) We can do this step by step, start with unpowered flybys and refine from there. What do you think?

**Comment by Juanlu001** [comment]
By the way: I'm not passing `Earth.r_soi` there because I'm hesitant whether it's necessary. Perhaps we can just assume for these computations that the SOI is at infinity?

**Comment by Juanlu001** [comment]
Since #153 was closed, I suggest to start afresh with the SOI computations:

* Add a new function in `bodies.py` to compute the _approximate radius of the Laplace sphere of influence_, as defined by Bate, Mueller and White "Fundamentals of Astrodynamics".
* Add a new method to the `Body` class to compute this radius based on the parent body, if present, and using the previously defined function.
* Validate this data using table A.2. from Curtis "Orbital Mechanics for Engineering Students" (approximate values anyway).

After that we can of course add the methods that @AunSiro proposed.

**Comment by Juanlu001** [comment]
I have been talking to @PabloRdrRbl about this issue in private and he has made some very important remarks... which match exactly with was @AunSiro warned when he opened his original pull request months ago. Siro, my sincere apologies :pray:

To sum up: the formula for the _approximate radius of the Laplace sphere of influence_ is

r_SOI = a (m / M) ^ (2/5)

which means that we need the semimajor axis of the small body. [As I said the on March 20](https://github.com/poliastro/poliastro/pull/153#pullrequestreview-27859092):

> While I am not comfortable with the Body class growing this much, I don't still have a clear alternative. It's obvious that, for the sphere of influence, me must
> 
> a) Read it from somewhere, or
> b) Compute it from the semimajor axis
> 
> For a), we must find authoritative resources. There is a table of r_SOI for the planets in Battin, but I'm sure it will be hard to find such resources for other bodies, even asteroids.
> 
> For b), you suggest using mean elements and storing them inside the bodies. If we don't do that, we must bring poliastro.ephem here, compute them outside of this module, or do something else.

So we are back to square one :sweat: And I must add that a) is a problem for bodies which are not listed in any table. [As @AunSiro said](https://github.com/poliastro/poliastro/pull/153#discussion_r106941141):

> I  don't like hardcoding the values or r_SOI for two reasons:
> 
>* It is not a physical measurable property, but an artificial radius that in the context of patched conics we decide that works well enough. It is a consequence of other values that we already have, not something you could measure in real life.
> * If we calculate it trough a function, we can obtain it for any body with mass and semi-major axis, wether or not its value has been documented before. This means that we can use patched conics for mission planning for anything, from Trappist System to Jovian satellites exploration, or even fictional systems.

I still maintain that we should not add orbital parameters to bodies. Also, as @PabloRdrRbl noticed, if this value is approximate it makes no sense to make it dependant on time (i.e. computing the semimajor axis using Astropy). This would introduce a circular dependency anyway.

**Solution**: Let us keep all this stuff off `bodies.py`, and create a new module in `src/poliastro/patched_conics.py` with a function that takes a `Body` and a semimajor axis and outputs the _approximate radius of the Laplace sphere of influence_ (or raises appropriate errors if `Body.parent` is missing, etc). @PabloRdrRbl what do you think?

**Comment by Juanlu001** [comment]
If we do like this, it's the responsability of the user how do they choose the semimajor axis. In case we want to make it even easier, we can leave it as optional and compute it using the ephemerides of J2000 if not present.

**Comment by PabloRdrRbl** [comment]
I agree with @Juanlu001, we should keep 'src/poliastro/bodies.py' as simple as possible and implement a new module for the patched conics. 

Concerning how the semimajor axis is obtained, having both options (user introducing it or a reference value such as the J2000 ephemerides) seems to be the most convenient approach.

**Comment by Juanlu001** [comment]
Forgot to say that we already have sphere of influence computations (see #231), so I'm renaming this issue to communicate that it is about having functions to compute flybys.

**Comment by Juanlu001** [comment]
Removing the milestone here, and waiting for someone to volunteer.

**Comment by Juanlu001** [comment]
Today we were analyzing some flybys @PabloRdrRbl, Veronica and myself and we thought that it would be great to automate part of the process. I was thinking of having some plotting utility that can produce sketches like this:

![screenshot from 2018-08-11 18-58-14](https://user-images.githubusercontent.com/316517/43995288-7a42d2c4-9dab-11e8-9eef-9bf1428fcd6d.png)

Given, for example, velocity of the body around the attractor, velocity of the spacecraft around the attractor, and periapsis distance of the flyby hyperbola.

**Comment by Juanlu001** [comment]
I'm closing this issue which is a bit long and open-ended, and opening new ones.
