### ISSUE TITLE
Sometimes OMM notebook fails

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1535]
https://github.com/astropy/astropy/issues/13447

**Comment by astrojuanlu** [comment]
- Failed: https://readthedocs.org/projects/poliastro/builds/17408507/
- Passed: https://readthedocs.org/projects/poliastro/builds/17430049/

At least the `stable` version of the docs is built now. Will add some debugging statements so that the next time it fails we hopefully have more information.

**Comment by astrojuanlu** [comment]
This hasn't happened in a while. Closing until it does again.

**Comment by jorgepiloto** [comment]
This just hitted me suddenly. Docs were rendering without problem until now.
