### ISSUE TITLE
No inclination reduction possible with change_ecc_inc.py

### ISSUE THREAD

**Issue by othmar-humboldt** [poliastro/poliastro#1577]
🐞 **Problem** 
Hello dear Poliastros,
I think there is a bug in change_ecc_inc.py.
I cannot reduce the inclination for a low thrust trajectory.

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>
  
```bash
# Paste your output here:

```
</details>

<details>

```bash
# Paste your output here:

```
</details>

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by astrojuanlu** [comment]
Hi @othmar-humboldt, thanks for opening this issue - I guess you mean this line:

https://github.com/poliastro/poliastro/blob/88c16fe70825e74517885e303aeb02ff6fe41daa/src/poliastro/core/thrust/change_ecc_inc.py#L88v

Could it be that this is the root cause of the problems observed in https://github.com/poliastro/poliastro/issues/1383 ?

**Comment by othmar-humboldt** [comment]
Yes, this is the line. 
I think it is the same problem indeed. I observed that inclination reduction doesn't work. For inclination changes, you need to do out-of-plane thrusting which is governed by the w_ vector. So it seems that you need to just add the sign-decision similar to for in-plane thrusting from line 75, so that you can toggle the vector depending on increase or reduction.

I didn't read Pollard's paper but the proposed change seems to solve the issue.

**Comment by astrojuanlu** [comment]
Would you like to make the change yourself? You can do it from the GitHub web interface - navigate to the file, click the ✏️  button, make the change, and open a pull request.

**Comment by othmar-humboldt** [comment]
Done :-)

**Comment by astrojuanlu** [comment]
see #1579

**Comment by astrojuanlu** [comment]
Thanks for the ping!
