### ISSUE TITLE
Orbit.to_ephem yielding inaccurate trajectory

### ISSUE THREAD

**Issue by earthshrink** [poliastro/poliastro#1581]
I'm attempting to reconstruct NEAR's 1998 Earth flyby trajectory, and to reproduce its 13+ mm/s velocity anomaly.
The orbital elements are given in Antreasian & Guinn's 1998 AIAA paper ([analysis](https://github.com/earthshrink/flyby-analysis/blob/master/About.md) Ref 1).

Following code
```
from astropy import units as u
from astropy.time import Time, TimeDelta

from poliastro.util import norm, time_range
from poliastro.frames import Planes
from poliastro.ephem import Ephem
from poliastro.bodies import Sun, Earth

from poliastro.twobody.orbit import Orbit
from poliastro.twobody.sampling import EpochsArray

import numpy as np

start_epoch = Time("1998-01-23 06:00:00", scale="tdb")
flyby_epochs = start_epoch + (np.arange(0, 60*2, 1) << u.minute)

near_start_ephem = Ephem.from_horizons("NEAR", start_epoch, plane=Planes.EARTH_EQUATOR)
earth_ephem = Ephem.from_body(Earth, flyby_epochs, plane=Planes.EARTH_EQUATOR)

near_start_rv = [near_start_ephem.rv(start_epoch)[i] - earth_ephem.rv(start_epoch)[i]
    for i in [0,1]]

print(norm(near_start_rv[0]) << u.km)
print(norm(near_start_rv[1]) << u.km /u.s)

near_orbit = Orbit.from_vectors(Earth, near_start_rv[0], near_start_rv[1], start_epoch)
print("Eccentricity:", near_orbit.ecc)
print("Periapse radius:", near_orbit.a)

near_ephem = near_orbit.to_ephem(EpochsArray(flyby_epochs))
ranges = [norm(near_ephem.rv(e)[0]) - Earth.R for e in flyby_epochs]
min_range = min(ranges)

print("Range start and end:", ranges[0], ranges[-1])

periapse_indices = [i for i, v in enumerate(ranges) if v == min_range]
periapse_epoch = flyby_epochs[periapse_indices[0]]
periapse_speed = norm(near_ephem.rv(periapse_epoch)[1])

print("Periapse:", min_range, "speed", periapse_speed, " at ", periapse_epoch)
...
```
produces the following output:
```
44506.3267454762 km
8.052078157439505 km / s
Eccentricity: 1.812851690223661
Periapse radius: -8494.617643714524 km
Range start and end: 38128.19014547623 km 14623.424015768689 km
Periapse: 526.7508837628302 km speed 12.742780802286209 km / s  at  1998-01-23 07:24:00.000
Deflection: 61.75086762328967 deg
```
The eccentricity fits JPL's value of 1.81, and deflection is consistent with the overall 66.92 deg deflection.
However, the perigee radius should be -8493.326, the altitude should be closer to 538.8 km.
The worst discrepancy is the perigee time- it is off JPL's value of 07:22:55.6 UTC by over a minute.
Changing the plane to EARTH_ECLIPTIC makes the answers worse.

I also tried using other time scales listed in _astropy.time_, but `Ephem.from_body` seems to want only `tdb`.

Is this inaccuracy due to the propagation algorithm used in `to_ephem`? Or simply some parameters need to be different?

**Comment by astrojuanlu** [comment]
> Is this inaccuracy due to the propagation algorithm used in `to_ephem`?

Most likely yes. This is by design: poliastro by default propagates with two-body motion methods, and therefore does not take into account various perturbations by default. The "true" observed position of a body and the position predicted by poliastro will always differ.

You could potentially make them closer by introducing more force models, like Sun pressure (implemented, but you'd need the surface area of the spacecraft and the model is quite simplistic) and third body effects (implemented). If there are other relevant perturbations (relativistic effects?), you'd need to implement them yourself.

**Comment by earthshrink** [comment]
It seems more sensitive to initial conditions than I'd naively assumed. Changing `from_body` to `from_horizons` for the earth ephemeris forced also moving `start_epoch` to say 06:30 to limit the Horizons query size, and brings the perigee a lot closer, to 532 km. But starting at 06:40 rolls it back to 530 km!

Since you mentioned perturbations. Antreasian & Guinn Table 4 lists them as at least 2 orders smaller than the anomaly. The inaccuracy looks larger. To hazard a guess, solar pressure would be cumulative, but my time interval of interest is too short. The range interval is within geosynchronous orbit, so third body effects should be small. A&G also discussed tides. Frame dragging effects were treated in [my analysis](https://github.com/earthshrink/flyby-analysis/blob/master/About.md) Ref 2, and combined with gravito-magnetism in Ref 6. However, the anomaly is fully explained by an unexpected travel time mismatch between tracking and radar signals on similar paths also exposed in A&G (Refs 3, 5, and my comment to Ref 6).

For my object of more thoroughly testing this signal issue impact, this sensitivity should be fine if I keep the initial conditions consistent. Thank you for making trajectory computation accessible to non-astrodynamicists like myself!

**Comment by astrojuanlu** [comment]
Thanks for the thorough explanations @earthshrink! Just a few more comments:

> Since you mentioned perturbations. Antreasian & Guinn Table 4 lists them as at least 2 orders smaller than the anomaly.

Interesting!

> It seems more sensitive to initial conditions than I'd naively assumed. Changing from_body to from_horizons for the earth ephemeris forced also moving start_epoch to say 06:30 to limit the Horizons query size, and brings the perigee a lot closer, to 532 km. But starting at 06:40 rolls it back to 530 km!

This depends on a global setting that is a bit invisible: `Ephem.from_body` uses the Astropy ephemerides, which can either be (a) the builtin ones or (b) the JPL ones. For the latter, one has to do

```python
from astropy.coordinates import solar_system_ephemeris
solar_system_ephemeris.set("jpl")
```

(see https://docs.poliastro.space/en/stable/quickstart.html#where-are-the-planets-computing-celestial-ephemerides)

This will automatically download `de430.bsp` from JPL. However, according to https://ssd.jpl.nasa.gov/horizons/manual.html, HORIZONS is currently using DE440/441, so you can also specify any SPICE kernel you want, manually. That way you can at least make sure that there are no hidden inaccuracies.

In any case, `from_horizons` will be as accurate as it gets (at the cost of requiring network access, and being non-reproducible in the future).

**Comment by earthshrink** [comment]
The JPL ephemerides do reduce the start epoch sensitivity, which helps. DE441 and start epoch advanced to before 03:00 gets us to 535.72 km for perigee, within spheroidal error of A&G value though I used only Earth.R. Believe Horizons reverts to older ephemerides for backward consistency of mission plans and data, so it is interesting that DE441 gets closer!  Thanks again, @astrojuanlu
