### ISSUE TITLE
J2 perturbation

### ISSUE THREAD

**Issue by ashalogu23** [poliastro/poliastro#1582]
🐞 **Problem**

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>
  
```bash
# Paste your output here:

```
</details>

<details>

```bash
# Paste your output here:

```
</details>

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by astrojuanlu** [comment]
Issue is empty, closing.

**Comment by ashalogu23** [comment]
exercising QUICKSTART programs. Interested in the moon and MARS mission design.
