### ISSUE TITLE
3D plotting not working

### ISSUE THREAD

**Issue by VincentPujau** [poliastro/poliastro#1584]
Dear all, 

I have been trying to plot some orbit in 3D using the examples in [this page](https://docs.poliastro.space/en/stable/examples/Plotting%20in%203D.html). The code is very simple

```
import numpy as np
from poliastro.bodies import Earth, Sun
from poliastro.constants import J2000
from poliastro.examples import churi, iss, molniya
from poliastro.plotting import OrbitPlotter3D
from poliastro.twobody import Orbit
import plotly.io as pio

pio.renderers.default = "plotly_mimetype+notebook_connected"

frame = OrbitPlotter3D()
frame.plot(churi)
```

But nothing happens once I run the code, even `churi.plot(interactive=True, use_3d=True)` does not work.
If I try `churi.plot()` I do get a plot but in 2D. 

Is there a way to solve this? 
I am using Spyder by the way. 

Thanks in advance

**Comment by astrojuanlu** [comment]
Hi @VincentPujau, I think the default Plotly rendering needs Jupyter Notebook to work. However, if you install the static renderer https://github.com/plotly/Kaleido, you should be able to make it work.

I made a quick search and found some old posts, like https://community.plotly.com/t/plotly-for-spyder/10527 however, many things have changed in Plotly and Spyder in the past 4 years, so my recommendation would be for you to register there and open a new question.

If you get any results (positive or negative), please let us know.

**Comment by VincentPujau** [comment]
The issue was indeed with Plotly. After a lot of research I realized I need to run the code in Jupyter in order to see the plots. 

Thanks for your advice!

**Comment by astrojuanlu** [comment]
You're welcome! Feel free to reach out if we can help in any other way.
