### ISSUE TITLE
Avoid spaces in notebooks file names

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#1592]
🐞 **Problem**
Some of the files under the `examples/` directory contain spaces in their filenames. This is considered a bad practice when it comes to naming files. In addition, it is a bit annoying to work with files whose name contains spaces in the shell.

💡 **Solution**
Let us get rid of those spaces. Furthermore, it would be awesome too if we could remove the capital case at the very beginning of the file name.

**Comment by jerobado** [comment]
Hi @jorgepiloto 

Just a few questions:

> Let us get rid of those spaces.
1. What will be the separator for each word? I can see some files are either using an underscore like `gravity_assist.png` or dash like `hohmann-bielliptic-transfers.png`.

>  it would be awesome too if we could remove the capital case at the very beginning of the file name.
2. Does that mean a filename will now be in lowercase? For example: from `Loading OMM and TLE satellite data.myst.md` to `loading_omm_and_tle_satellite_data.myst.md`.

**Comment by jorgepiloto** [comment]
Hi @jerobado,

thanks for your quick reply to this issue. Let me answer your questions:

1. I think we should use `-` as separator. The reason is that the file name of the notebook is the final part of the URL. Using `-` in a URL allows browsers to filter content by words, making our docs more discoverable.

2. That is correct. All letters in the file name must be in lowercase except those that represent acronyms.
