### ISSUE TITLE
Can't set orbit plot axis units

### ISSUE THREAD

**Issue by joebro1907** [poliastro/poliastro#1603]
When using StaticOrbitPlotter() you can customize certain things such as trajectory colors, markers, title, grid, etc. However, I can't find any documentation on the poliastro site on how, if even possible, to change the units used for the x and y axis, which are always shown in km.  

Having the ability to change from km to astronomical units is essential when working, for example, with asteroid orbits, due to them so much more expansive compared to satellites or crafts.

I tried using ax.yaxis.set_units(u.AU) from matplotlib and astropy, just to see if that could work but it didn't do anything. 

If there is indeed a way to change the units from km to au, please let me know.

**Comment by jorgepiloto** [comment]
Hi @joebro1907,
thanks for opening this issue. This features will be introduced one #1545 gets merged and `poliastro 0.18` gets released.

I would like to merge the pull-request before the end of the month.

**Comment by joebro1907** [comment]
Hi @jorgepiloto, thanks for letting me know, I'll be looking forward to it!
