### ISSUE TITLE
Allow docs environment in tox to use python3

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#1605]
🐞 **Problem**
The `docs` environment in the `tox.ini` file is forced to use Python 3.8. For developers using any other Python distribution, it is not possible to execute this environment.

💡 **Solution**
Include the `docs` environment inside the `python3` collection of environments.

**Comment by sairevanth0007** [comment]
Hello @jorgepiloto,
I am new to this project, Since it is mentioned as a good first issue I would like to know what needs to be done and a basic idea of how to do it. I would like to contribute to this project.

**Comment by jorgepiloto** [comment]
Hi @sairevanth0007,
let me give more details on how to solve this issue.

The `tox.ini` file collects all the configuration for `tox`, the tool we use for automation. In this file, there are various tasks specified. Each one of the tasks is linked to a particular Python version:

https://github.com/poliastro/poliastro/blob/main/tox.ini#L15-L21

Note that the `docs` environment is linked to Python 3.8. We now want the `docs` environment to use a any Python 3 version. Therefore, line 20 of the `tox.ini` file needs to be deleted and 
line 21 modified as follows:

```diff
-docs: python3.8
+{style,docs,reformat,build}: python3
```

**Comment by sairevanth0007** [comment]
Thanks for helping @jorgepiloto . I will try to make the changes mentioned and make a PR.
