### ISSUE TITLE
Problem with different epochs

### ISSUE THREAD

**Issue by anhiga** [poliastro/poliastro#205]
If you plot orbits with different epochs, only the last epoch is showed in the title:
```Python
In [1]: from poliastro.neos import dastcom5
In [2]: from poliastro.plotting import OrbitPlotter
In [3]: eros = dastcom5.orbit_from_name('eros')[0]
In [4]: apophis = dastcom5.orbit_from_name('apophis')[0]
In [5]: eros.epoch
Out[5]: <Time object: scale='utc' format='jd' value=2451960.5>
In [6]: apophis.epoch
Out[6]: <Time object: scale='utc' format='jd' value=2454441.5>
In [7]: frame = OrbitPlotter()
In [8]: frame.plot(eros, label='eros')
In [9]: frame.plot(apophis, label='apophis')
```
![epochs](https://user-images.githubusercontent.com/18404378/29220971-3c574f2a-7ebd-11e7-86c2-667abc6faaee.png)

I think you should be able to choose the epoch. Maybe we should use `Orbit.propagate` function.

**Comment by Juanlu001** [comment]
After discussion in the wiki (see https://github.com/poliastro/poliastro/wiki/Plotting-multiple-orbits:-use-cases) I'm labeling this as a bug.

**Comment by Juanlu001** [comment]
I will give you the honor of submitting a plot showcasing the solution and closing this issue @anhiga :)

**Comment by anhiga** [comment]
This is how plots look now.
![figure_1](https://user-images.githubusercontent.com/18404378/30056499-3bd87644-9233-11e7-9b18-ee0cff84825a.png)

**Comment by Juanlu001** [comment]
Using `%matplotlib notebook` and some patience one can arrive to something like this:

![png image 482 x 684 pixels](https://user-images.githubusercontent.com/316517/30056991-4e4d70e8-9235-11e7-983f-2c6dd185168e.png)

While I admit it is not optimal (notice the white space above the plot, apart from the manual tweaking) this fixes the original issue. Interested readers might want to check out #214, #226, #230 and https://github.com/matplotlib/matplotlib/issues/9155.
