### ISSUE TITLE
Try numba wheels

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#219]
numba 0.35 RC has been released, and multi platform wheels with them!

https://groups.google.com/a/continuum.io/d/msg/numba-users/OuBmvN7zpVA/GCMdTRoDCwAJ

For testing purposes, one can use `dependency_links` in `setup.py` to add the external URL, as explained here:

https://stackoverflow.com/a/30064248/554319

Or we can wait for the stable release. This has profound implications in the installation process, since the only dependency without wheels would be SciPy, and that won't last long:

https://github.com/scipy/scipy/pull/7616

**Comment by Juanlu001** [comment]
This worked flawlessly on Linux:

```
$ pip install -e .[fast] --extra-index-url https://pypi.anaconda.org/numba/simple --pre
```

Testing on Windows and OS X needed. @anhiga @newlawrence ?

**Comment by anhiga** [comment]
Worked on Windows 10 (after manually installing scipy).

**Comment by Juanlu001** [comment]
Works! #221 Closing
