### ISSUE TITLE
Add from_relative to Body?

### ISSUE THREAD

**Issue by jzmiller1** [poliastro/poliastro#224]
There was some discussion about adding a from_relative method to the Body class on a recently closed PR thread: https://github.com/poliastro/poliastro/pull/153

Is that something that there's some interest in seeing in a new PR?

**Comment by Juanlu001** [comment]
You're right @jzmiller1, I oversaw that. Please go ahead :) I think this comment summarizes more or less what you wanted, right?

https://github.com/poliastro/poliastro/pull/153#issuecomment-284218548

**Comment by jzmiller1** [comment]
Yes, something like that should work well.  I'll put a PR for it together in the next week unless you already had the code for it somewhere?

**Comment by Juanlu001** [comment]
I don't have it, so please do. Also, I encourage you to join our chat, so we can guide you more quickly:

https://riot.im/app/#/room/#poliastro:matrix.org

**Comment by Juanlu001** [comment]
This was closed in #235.
