### ISSUE TITLE
Always plot osculating orbit?

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#227]
After looking at this plot by @anhiga:

![29966416-17dd66ce-8f12-11e7-9348-9c85fd11ac29](https://user-images.githubusercontent.com/316517/29970422-ca520c6c-8f24-11e7-8ece-d7bc2e46a6cb.png)

I suddenly wondered if it makes sense to plot a point _without the osculating orbit_. That point could have an elliptic, or circular, or hyperbolic orbit... And there is no way to know without at least plotting a fraction of the orbit. No usage of `osculating=False` in the user guide nor the examples either. I think we should consider removing that feature.

**Comment by anhiga** [comment]
I think we could keep that feature as long as there is no problems with it.
It can be useful when plotting many bodies, `Atira NEOs` for example:
![atiras2](https://user-images.githubusercontent.com/18404378/29979889-928169b8-8f47-11e7-83b7-d1c0572735b2.png)

![atiras_without_osculating](https://user-images.githubusercontent.com/18404378/29979977-e94c56a4-8f47-11e7-970e-319c0d8a839f.PNG)

Even if the first is much more beautiful, maybe someone could prefer the second one 😆

**Comment by Juanlu001** [comment]
This is a tie then :) I'll leave this open in case more people want to weigh in.

**Comment by Juanlu001** [comment]
This feature was removed in #230, so closing.
