### ISSUE TITLE
NeoWs API key

### ISSUE THREAD

**Issue by anhiga** [poliastro/poliastro#229]
`NeoWs` module should provide a good way of using [NASA API key](https://api.nasa.gov/index.html#apply-for-an-api-key) for requests.

**Comment by Juanlu001** [comment]
@anhiga you fixed this in https://github.com/poliastro/poliastro/pull/239/, right?

**Comment by anhiga** [comment]
Yes, but I haven't tested properly.

**Comment by anhiga** [comment]
#239 got merged yesterday. Closing.
