### ISSUE TITLE
Constants in SI basic units

### ISSUE THREAD

**Issue by PabloRdrRbl** [poliastro/poliastro#232]
I have observed that the units implemented in [poliastro/constants.py](https://github.com/poliastro/poliastro/blame/master/src/poliastro/constants.py) are not always in the basic units of the SI system, but sometimes use some multiple. e.g. the GM of the Sun and Earth are in m3/s2, meanwhile the other Solar System's bodies have a GM in km3/m2.

Although this is not necessarily a problem when using Astropy's `Quantity` objects, since the method `.decompose()` simplifies the units derived from mixing different units for the same dimensions, I think is cleaner to use always the basic units. However, it may be the case of an existing convection in Astronomy.

@anhiga pointed me in the chat that the reason to implement the GM in these units is that they are used in the original source, which is a good remark. But we can discuss it here.

**Comment by anhiga** [comment]
I agree that it would be cleaner.
Let's see what @Juanlu001 thinks.

**Comment by Juanlu001** [comment]
Thanks for raising this issue @PabloRdrRbl! It's okay that @anhiga respected the original units, but I also prefer to be consistent in this case. Pull requests welcome :)

**Comment by anhiga** [comment]
Fixed by #233.
