### ISSUE TITLE
Add warning if input time for ephemeris is not TDB

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#234]
Those users that want utter precision might want to check against HORIZONS or SPICE. These systems use TDB as their input, so in the absence of time scale an implicit conversion is made, which makes use of the "wrong" time:

https://space.stackexchange.com/q/22901

Example code:

```
In [17]: EPOCH = Time("2017-09-01 12:05:50")

In [18]: Orbit.from_body_ephem(Venus, EPOCH)
Out[18]: 1 x 1 AU x 24.4 deg orbit around Sun (☉)

In [19]: _.epoch
Out[19]: <Time object: scale='utc' format='iso' value=2017-09-01 12:05:50.000>

In [20]: _.tdb
Out[20]: <Time object: scale='tdb' format='iso' value=2017-09-01 12:06:59.183>

In [21]: _19 == _20
Out[21]: True
```

I would raise a warning if the input scale is not TDB to avoid this confusion, and also set the epoch to TDB to signal this fact. Thoughts? @poliastro/development

**Comment by anhiga** [comment]
I agree with @Juanlu001. Either a warning at runtime or a detailed explanation in docs, but user should be aware of this.
