### ISSUE TITLE
Try out flit for publishing

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#252]
Our `setup.py` is relatively simple, so now that [PEP 517 has been provisionally accepted](https://www.python.org/dev/peps/pep-0517/) let us try flit for publishing:

https://github.com/takluyver/flit

**Comment by Juanlu001** [comment]
If that works, we would be able to remove `setup.py` and replace it with a `[build-system]` key in `pyproject.toml` as explained here:

https://www.python.org/dev/peps/pep-0517/#source-trees

**Comment by Juanlu001** [comment]
To be precise: this pull request has to be implemented first https://github.com/takluyver/flit/pull/137

**Comment by Juanlu001** [comment]
The APIs are still evolving. Postponing.

**Comment by Juanlu001** [comment]
Also: https://github.com/takluyver/flit/issues/115

**Comment by Juanlu001** [comment]
Closing until takluyver/flit#115 is fixed.

**Comment by Juanlu001** [comment]
https://github.com/takluyver/flit/pull/260 has been merged. Reopening!

**Comment by takluyver** [comment]
I'm [looking for people to test a release candidate](https://discuss.python.org/t/flit-2-release-candidate-user-testing-requested/2677) including support for `src/` directories, if you're interested.

**Comment by Juanlu001** [comment]
On it! Figuring out how to move all the metadata elements from `setup.cfg` to `pyproject.toml` :)

**Comment by Juanlu001** [comment]
Tracking in #802.
