### ISSUE TITLE
Use pip for readthedocs

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#255]
The documentation is failing because we forgot to update `environment.yml`:

http://readthedocs.org/projects/poliastro/builds/6076389/

But poliastro is now pip-installable, so perhaps we don't need to use conda anymore. I'm concerned about having the dependencies spread out in several places where we have to update them. What do you think of this @anhiga?

**Comment by anhiga** [comment]
I agree that having the dependencies in a single place would be much more desirable. Although, aren't RTD build options inside RTD account settings, and not in the code?

**Comment by anhiga** [comment]
I was wrong, build options can be changed in `readthedocs.yml`: #258. Let's see if that works.

**Comment by anhiga** [comment]
Closing: #258
