### ISSUE TITLE
Try creating a ClassicalElementsRepresentation

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#257]
By creating a `ClassicalElementsRepresentation` we could integrate better with the `astropy.coordinates` machinery, including transformation from/to other representations.

Here is the guide on how to do it:

http://docs.astropy.org/en/v2.0.2/coordinates/representations.html#creating-your-own-representations

Some problems that might arise:

* Different units for each element
* Singularities
* ?

**Comment by anhiga** [comment]
It's a really good idea, but how could we deal with the gravitational parameter? It would be impossible to have a straight `from_cartesian()` transformation without knowing `k`.

**Comment by Juanlu001** [comment]
One could create a `ClassicalElementsRepresentation` based on a specific `k`:

```
ThisRep = ClassicalElementsRepresentation.from_k(...)
```

Then `ThisRep` would store `k` internally and allow conversions. What do you think?

**Comment by Juanlu001** [comment]
I'm postponing this until we have better validation of reference frames, see #109.

**Comment by shreyasbapat** [comment]
What I understand is: 
We have to use ``CartesianRepresentation`` class to return the positions, but we are already doing that as ``_sample()``  already returns a ``CartesianRepresentation`` object. So, what are we talking about here? :confused:

**Comment by shreyasbapat** [comment]
Or, probably, we are planning to create a new class which could represent  positions and name it ``ClassicalElementRepresentation`` ?

**Comment by Juanlu001** [comment]
The thing is that now you can only sample position and velocity, it would be nice to sample any other thing (the true anomaly for example) and be able to convert that to a trajectory. So the idea would be to create a class that holds classical elements in an array, in the same way that `CartesianRepresentation` holds position and velocity in arrays.

**Comment by Juanlu001** [comment]
Let's move this to the next milestone. @eteq said on chat that it would be very nice to see this integrated on Astropy, although the question on how to treat velocities is still open.

**Comment by Juanlu001** [comment]
Postponing this to the next milestone. There's some discussion that should happen though, so it's not clear we'll go this way.

**Comment by Juanlu001** [comment]
We don't really need validation of reference frames to do this: the _representation_ is contained in a _frame_, but can live independently.

**Comment by Juanlu001** [comment]
The problem is that `coe2r` works, but `r2coe` doesn't: we need the complete information of the orbit to retrieve the orbital parameters.

<details>
A one-way representation would be:

```python
class ClassicalElementsRepresentation(BaseRepresentation):
    attr_classes = OrderedDict([
        ('p', u.Quantity),
        ('ecc', u.Quantity),
        ('inc', u.Quantity),
        ('raan', u.Quantity),
        ('argp', u.Quantity),
        ('nu', u.Quantity),
    ])

    @property
    def a(self):
        """Semimajor axis. """
        return self.p / (1 - self.ecc ** 2)

    @property
    def p(self):
        """Semilatus rectum. """
        return self._p

    @property
    def ecc(self):
        """Eccentricity. """
        return self._ecc

    @property
    def inc(self):
        """Inclination. """
        return self._inc

    @property
    def raan(self):
        """Right ascension of the ascending node. """
        return self._raan

    @property
    def argp(self):
        """Argument of the perigee. """
        return self._argp

    @property
    def nu(self):
        """True anomaly. """
        return self._nu

    def to_cartesian(self):
        r = coe2r(
            self.p.to(u.km).value,
            self.ecc.value,
            self.inc.to(u.rad).value,
            self.raan.to(u.rad).value,
            self.argp.to(u.rad).value,
            self.nu.to(u.rad).value,
        ) * u.km

        return CartesianRepresentation(r, xyz_axis=-1, copy=False)
```

Given the `coe2r` function, of course.
</details>

**Comment by Juanlu001** [comment]
Reviewing old messages, it seems that with the current state of things we are out of luck:

> The other issue I guess is that to turn a representation from orbital elements you also need the **mass** of whatever the thing that is being orbited is. Stateful information like that isn’t really supported by representations because they are meant to be “stateless” aside from the actual locations themselves

([Source](https://chat.openastronomy.org/#/room/#astropy_coordinates:openastronomy.org/$15278712594485VQdBN:openastronomy.org))

Which is also the problem @anhiga anticipated:

```python
class ClassicalElementsRepresentation(BaseRepresentation):
    attr_classes = OrderedDict([
        ('k', u.Quantity),  # Do I need this one?
        ('p', u.Quantity),
        ('ecc', u.Quantity),
        ('inc', u.Quantity),
        ('raan', u.Quantity),
        ('argp', u.Quantity),
        ('nu', u.Quantity),
    ])

    @classmethod
    def from_cartesian(cls, cart):
        k = ...  # Where do I get this from?

        p, ecc, inc, raan, argp, nu = rv2coe(
            k.to(u.km ** 3 / u.s ** 2).value,
            cart.xyz.to(u.km).value,
            cart.differentials["s"].d_xyz.to(u.km / u.s).value
        )

        return cls(
            k,  # If needed
            p * u.km,
            ecc * u.one,
            inc * u.rad,
            raan * u.rad,
            argp * u.rad,
            nu * u.rad,
        )
```

I'm closing this issue and abandoning this effort in the short term.

**Comment by astrojuanlu** [comment]
I keep silently coming to this issue over and over again, so I want to leave a comment for my future self:

There is no way we can have a `ClassicalElementsRepresentation` at the same level of abstraction as `{Cartesian,Cylindrical,*}Representation`, and the reason is that classical elements already constrain the motion: they describe a very specific conic section, as well as the period (if applicable). Therefore, they are much more than a purely kinematic description: they contain the dynamics as well.

Stop thinking this is possible at all: it's not. We need other solutions, other abstractions.
