### ISSUE TITLE
Have a nice logo!

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#26]
Inspired by https://github.com/obspy/obspy

**Comment by AunSiro** [comment]
I tried! A first try, more like a concept trial or something like that. I had the idea but somewhat lack the proper knowledge of how to make a proper logo.
![version2 copia](https://cloud.githubusercontent.com/assets/9275233/6795099/87300136-d1db-11e4-9de2-1637202103ea.png)

**Comment by Juanlu001** [comment]
Hey, thanks very much for trying @AunSiro! I actually like the idea, though it's a bit Earth-centered, don't you think? :stuck_out_tongue_winking_eye: 

> *"Man will not always stay on Earth; the pursuit of light and space will lead him to penetrate the bounds of the atmosphere, timidly at first, but in the end to conquer the whole of solar space."*

**Comment by Juanlu001** [comment]
You know what would be cool? Having something based on this:

![Grand Tour](http://upload.wikimedia.org/wikipedia/commons/5/53/Voyager_Path.svg)

I also considered Cassini (for being European) and Rosetta (for being also very recent), but:

* The Grand Tour is a special planetary conjunction which won't happen again until 22nd century,
* The Voyager trajectories have no multiple revolutions, which simplifies drawings, and
* They carry the Golden Records, which for me are a precious symbol of the ambition of mankind and specifically of Carl Sagan :heart:

If I find the time I might try to draw something with a snake in it :smile:

**Comment by Juanlu001** [comment]
Though I have to admit this one is very cool too

![XKCD](http://imgs.xkcd.com/comics/six_words.png)

**Comment by Juanlu001** [comment]
![Poliastro](https://cloud.githubusercontent.com/assets/316517/7400397/fd22df96-eebc-11e4-993d-68d109e5ff50.png)

What do you think?

**Comment by Juanlu001** [comment]
I just couldn't resist :grin: transferred the repo to a new organization and put this logo. I will have to fix a couple of broken links in the following days but this got serious now. Closing!
