### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#262]
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

Some basic steps, `conda info -a`, `python -c "import poliastro.testing; poliastro.testing.test()"` would be enough I think.

**Comment by Roshanjossey** [comment]
This is the issue template I use in my project
https://github.com/Roshanjossey/first-contributions/blob/master/ISSUE_TEMPLATE.md

We could tweak this to suit poliastro with requirement to include output of commands you mentioned above

Here's a sample issue
Roshanjossey/first-contributions#802

🐞 Problem

🎯 Goal

💡 Possible solutions

📋 Steps to solve the problem

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - Addresses #<put issue number here>
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

This is working extremely well for me. I've written a blog post about it
https://medium.com/@roshanjossey/how-better-issues-improve-collaboration-5a4e6ff95e90

Do reply if you like it. I'll submit a pull request to include this

**Comment by Juanlu001** [comment]
This is very nice @Roshanjossey, and your first-contributions project looks awesome! If you add instructions to paste the output of those commands when reporting a problem, I will be glad to add your contribution. Thanks!

**Comment by Roshanjossey** [comment]
@Juanlu001, thank you. I'll start working on this.

We also have a slack team to help/mentor people trying to contribute to open source projects. It'd be awesome to have somebody as experienced as you there.
You can join the team by going to https://firstcontributions.herokuapp.com

**Comment by Juanlu001** [comment]
Thanks for the offer @Roshanjossey. Unfortunately I won't be able to dedicate the time it deserves, but please feel free to add a brief reference to that channel in the issue template :)
