### ISSUE TITLE
Allow plotting segments of orbits in 2D

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#274]
🐞 **Problem**

Right now, the `plot` function and the `OrbitPlotter.plot` method decide which points to plot, making it impossible to customize.

🎯 **Goal**

Plotting a complete orbit is easy but plotting a fraction of an orbit is extremely hard. This can lead to too much clutter when complex maneuvers are being plotted.

💡 **Possible solutions**

This refactoring #269 paves the way for this feature: we can pass custom parameters to the `sample` method calls, so instead of a fixed number of points we can specify a range of times or true anomaly values.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
The new 3D plotting functions already allow this thanks to the `plot_trajectory` method. It would be nice to have it in 2D plots as well.

**Comment by Juanlu001** [comment]
However, this will need a little refactoring in `OrbitPlotter` that won't arrive in time for 0.8.0.

**Comment by Juanlu001** [comment]
This functionality can be a workaround for hyperbolic cases while we figure out what to do: https://github.com/poliastro/poliastro/issues/111

**Comment by shreyasbapat** [comment]
Working on it !

**Comment by shreyasbapat** [comment]
Addressed in PR #332
