### ISSUE TITLE
[question] Zoom in to a planet

### ISSUE THREAD

**Issue by www2000** [poliastro/poliastro#280]
I have an orbit that the sol is the attractor and cross earth. I wand to plot this orbit in the point of view of earth and not sol.

**Comment by Juanlu001** [comment]
Thanks for your interest @www2000. This is what we do in the notebook about the Florence asteroid:

http://docs.poliastro.space/en/latest/examples/Catch%20that%20asteroid!.html

You have to convert the Heliocentric orbit to GCRS and use the Earth as an attractor.

In case you need more interactive help, I encourage you to join our chat:

https://riot.im/app/#/room/#poliastro:matrix.org

Feel free to ask questions in this issue or in the chat. If you succeed, please close it at your earliest convenience :) And please share your code if you can!

**Comment by Juanlu001** [comment]
Closing after a week, feel free to reopen!
