### ISSUE TITLE
Plotly graphs do not show in docs

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#281]
See https://github.com/spatialaudio/nbsphinx/issues/128

I wonder if there's some sort of dirty workaround we can have in place prior the release...

**Comment by Juanlu001** [comment]
I'd love to have this in 0.8.0, but I doubt it will arrive in time.

**Comment by Juanlu001** [comment]
In fact, this is a problem of the default RTD theme: https://github.com/rtfd/sphinx_rtd_theme/issues/328 I'm not switching the theme to accomodate the notebooks, so we will either include `require.js` in the quick 'n' dirty way or wait for an upstream fix.

**Comment by Juanlu001** [comment]
This pull request fixes the issue https://github.com/rtfd/sphinx_rtd_theme/pull/467

**Comment by Juanlu001** [comment]
Reopening, as it's the case again.

**Comment by Juanlu001** [comment]
Being tracked at https://github.com/rtfd/sphinx_rtd_theme/pull/545, but it will probably take a while to ship.

**Comment by shreyasbapat** [comment]
The PR is still open. Do you think it is a local issue and we can solve it in poliastro?

**Comment by Juanlu001** [comment]
It's indeed an upstream issue that will take a while, but in the meanwhile we have a workaround, which is adding some extra cells at the top (and running them!)

```python
# Temporary hack, see https://github.com/poliastro/poliastro/issues/281
from IPython.display import HTML
HTML('<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js"></script>')
```

**Comment by shreyasbapat** [comment]
Oh! Okay. I will add these lines and run the notebooks again

**Comment by shreyasbapat** [comment]
I thought it was not really an issue. Even I experienced this multiple times. That the plots were showing fine locally, while building in RTD stopped them. However, even Firefox does not load the plots all the time 😅

**Comment by Juanlu001** [comment]
This is still an issue :( Conversations restarted on the sphinx_rtd_theme, which is where jQuery should go. An alternative would be to change Plotly to load jQuery asynchronously. In any case, I want to fix this upstream.

**Comment by Juanlu001** [comment]
I spent some time setting up a test case to display the behavior, see my comment at

https://github.com/rtfd/readthedocs.org/issues/4367#issuecomment-423814712

> My current workarounds are:
> 
> * Use widgets, because they seem to work better.
> * Use an unreleased version of rtd_sphinx_theme that *should* work.
> * Use a totally different theme.

I don't want workarounds 2 and 3, and widgets have still some rough edges (see https://github.com/jupyter-widgets/ipywidgets/issues/1632, https://github.com/jupyterlab/jupyterlab/issues/5200 and https://github.com/jupyter/nbconvert/issues/751, not to mention the slightly related https://github.com/jupyter/nbconvert/issues/878).

There is no perfect solution but having empty boxes where there should be plots is not acceptable either, so I will wait for some weeks to progress to happen on any of these fronts and I will make a decision before the next poliastro release.

**Comment by Juanlu001** [comment]
After #728, here we are again!

**Comment by Juanlu001** [comment]
https://github.com/readthedocs/sphinx_rtd_theme/issues/788

**Comment by Juanlu001** [comment]
Even though @shreyasbapat has suggested several times to change the theme... I'd still would love to work upstream to fix this. Even though it's been two years already...

**Comment by Juanlu001** [comment]
This time it was easy: https://github.com/readthedocs/sphinx_rtd_theme/issues/788

With https://github.com/poliastro/poliastro/pull/741, now we are **really** closing this issue, and after almost two years I can say the Plotly + nbsphinx + RTD drama is over!
