### ISSUE TITLE
Add missing notebooks to gallery

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#292]
🐞 **Problem**

The Florence asteroid, NEOS and 3D plotting notebooks are not in `index.ipynb`, and therefore don't show in the binder gallery (although they are already in the Sphinx documentation).

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by alkesh47** [comment]
@Juanlu001 For the three missing notebooks, I'm unable to locate the png files for displaying in the binder gallery. All the other images are located in the docs/source/example folders. Any help where I might find the missing images for The Florence Asteroid, NEOS and 3D plotting notebooks?

**Comment by shreyasbapat** [comment]
Please have a look at Pull Request #309

**Comment by Juanlu001** [comment]
Closed in #310
