### ISSUE TITLE
Default steps 2D plots are too visible

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#294]
🐞 **Problem**

With the default number of points, the steps in the pericenter are too visible:

| Before                                                                                                       | After                                                                                                         |
|--------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|
| ![index](https://user-images.githubusercontent.com/316517/34196128-ff6eb412-e560-11e7-892b-0d452ccfdda4.png) | ![index2](https://user-images.githubusercontent.com/316517/34196136-0571c99e-e561-11e7-8a8b-6d7b204b1200.png) |

This came after the propagation changes in plotting and the different way to compute the data points.

🎯 **Goal**

Make the plots smooth again.

💡 **Possible solutions**

* Increase the default `num_points`
* Other?

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Another side effect:

![index4](https://user-images.githubusercontent.com/316517/34196364-15a25076-e562-11e7-8d9a-9abb34aacdb2.png)

This is a slightly different issue, namely that the pericenter is not always included in the propagation.

**Comment by Juanlu001** [comment]
Notice that, while fixing the previous one, one might step into #265.

**Comment by nikita-astronaut** [comment]
Started working on this issue

**Comment by Juanlu001** [comment]
Thanks @nikita-astronaut, keep us posted! Notice that the propagation might fail and distract you, see the last comment in this issue.

**Comment by nikita-astronaut** [comment]
I'll be prepared. Could you please provide code to reproduce this issue?

**Comment by Juanlu001** [comment]
This is a good moment to say that just increasing the number of points is not going to be the preferred solution. In the report ["The generalized Sundman transformation for propagation of high-eccentricity elliptical orbits"](http://www.dtic.mil/dtic/tr/fulltext/u2/a605040.pdf) we can read:

> Because of the large number of satellites, attention must be paid to the total time of computation.
For very eccentric orbits, satisfactory accuracy can be maintained with a larger step size near apogee
than is used at perigee

Take a look at this plot:

![screenshot-2018-2-21 a605040 pdf](https://user-images.githubusercontent.com/316517/36465149-1fd8fe98-16d4-11e8-9f67-0111f7ea1458.png)

We are now in the situation of Figure 2.d), since we're uniformly sampling the true anomaly:

https://github.com/poliastro/poliastro/blob/24a9299f/src/poliastro/twobody/orbit.py#L295-L302

And before we introduced the `sample` method, we were doing *almost* the same thing:

https://github.com/anhiga/poliastro/blob/cd0a31ca3e7ffc99a3/src/poliastro/plotting.py#L169-L182

The most immediate fix for this issue, in my view, would be to use a uniform sample of the eccentric anomaly instead of the true anomaly. However, from the same report:

> Merson (Ref. 13) introduced the idea of using the value n = 3 / 2 in the generalized Sundman transformation, with an intent not of regularization per se, but of maximizing computational efficiency; see also Ref. 14. He gave an analysis showing that this value of n equally distributes the integration error around a full orbit, even if the eccentricity is high.

I will therefore accept a pull request (with plots of the before/after situation) that use the eccentric anomaly as a first step, but implementing an s-integrator as described in the report would be a great next step (see #253).

**Comment by Juanlu001** [comment]
I found another book that might be useful: "Regularization in Orbital Mechanics: Theory and Practice" (https://doi.org/10.1515/9783110559125)

**Comment by nikita-astronaut** [comment]
I will now read the report and try to implement the s-integration.

**Comment by Juanlu001** [comment]
Great! Nevertheless this issue has been fixed in #320, so I'm closing. Let's continue the discussion in #253, or in the upcoming pull requests.

**Comment by Juanlu001** [comment]
Or in #265, for that matter. Notice that, when we have a working propagator, we can include the pericenter in all the samplings if we consider it appropriate, see https://github.com/poliastro/poliastro/issues/294#issuecomment-352989434.

**Comment by Juanlu001** [comment]
Another nice before/after table:

| Before                                                                                                        | After                                                                                                        |
|---------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------|
| ![before](https://user-images.githubusercontent.com/316517/36843136-40da40cc-1d4e-11e8-9838-21c30e522f80.png) | ![after](https://user-images.githubusercontent.com/316517/36843190-6efbff40-1d4e-11e8-96c7-d0eb96aa09ce.png) |

This is with the same number of points. Veeeeeeeeery nice :)
