### ISSUE TITLE
Fix position in hyperbolic plots

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#295]
🐞 **Problem**

The position is not plotted correctly for hyperbolic orbits, see https://github.com/poliastro/poliastro/issues/111#issuecomment-355731620.

💡 **Possible solutions**

One option: add an offset of `+nu_limit` to `nu_values`:

https://github.com/poliastro/poliastro/blob/44dbc6e26f2d0a6b395a910c39c9e8131c8946b2/src/poliastro/twobody/orbit.py#L296-L300

Other option: remove the assumption that the first value from `sample` is the current position:

https://github.com/poliastro/poliastro/blob/44dbc6e26f2d0a6b395a910c39c9e8131c8946b2/src/poliastro/plotting.py#L158-L159

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
Working on it!
