### ISSUE TITLE
install test failed

### ISSUE THREAD

**Issue by kristentetreault** [poliastro/poliastro#296]
After following the directions at http://docs.poliastro.space/en/latest/getting_started.html
The test of the installation, 

`python -c "import poliastro.testing; poliastro.testing.test()"`

output the following (final lines only, there were many more scrolling included)

             
`File "C:\Users\Kristen\Anaconda2\lib\contextlib.py", line 35, in _
exit__
               self.gen.throw(type, value, traceback)
             File "C:\Users\Kristen\Anaconda2\lib\site-packages\numba\errors.py
, line 249, in new_error_context
               six.reraise(type(newerr), newerr, sys.exc_info()[2])
             File "C:\Users\Kristen\Anaconda2\lib\site-packages\numba\errors.py
, line 243, in new_error_context
               yield
             File "C:\Users\Kristen\Anaconda2\lib\site-packages\numba\typeinfer
py", line 430, in __call__
               self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
             File "C:\Users\Kristen\Anaconda2\lib\site-packages\numba\typeinfer
py", line 385, in resolve
               sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
             File "C:\Users\Kristen\Anaconda2\lib\site-packages\numba\typeinfer
py", line 972, in resolve_call
               return self.context.resolve_function_type(fnty, pos_args, kw_arg
)
             File "C:\Users\Kristen\Anaconda2\lib\site-packages\numba\typing\co
text.py", line 111, in resolve_function_type
               res = defn.apply(args, kws)
             File "C:\Users\Kristen\Anaconda2\lib\site-packages\numba\typing\te
plates.py", line 185, in apply
               sig = generic(args, kws)
             File "C:\Users\Kristen\Anaconda2\lib\site-packages\numba\typing\np
decl.py", line 203, in generic
               sig = super(NumpyRulesArrayOperator, self).generic(args, kws)
             File "C:\Users\Kristen\Anaconda2\lib\site-packages\numba\typing\np
decl.py", line 107, in generic
               if not supported_ufunc_loop(ufunc, ufunc_loop):
             File "C:\Users\Kristen\Anaconda2\lib\site-packages\numba\numpy_sup
ort.py", line 226, in supported_ufunc_loop
               from .targets import ufunc_db
           InternalError: Parent module 'numba' not loaded, cannot perform rela
ive import
           [1] During: typing of intrinsic-call at C:\Users\Kristen\Anaconda2\l
b\site-packages\poliastro\stumpff.py (22)
           --%<----------------------------------------------------------------

           File "Anaconda2\lib\site-packages\poliastro\stumpff.py", line 22

naconda2\lib\site-packages\numba\dispatcher.py:308: TypingError
============== 5 failed, 18 passed, 17 error in 16.41 seconds ================`

The output of the command

`conda info -a`

output the following

`(C:\Users\Kristen\Anaconda2) C:\Users\Kristen>conda info -a
Current conda install:

               platform : win-64
          conda version : 4.3.32
       conda is private : False
      conda-env version : 4.3.32
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.14.2
       root environment : C:\Users\Kristen\Anaconda2  (writable)
    default environment : C:\Users\Kristen\Anaconda2
       envs directories : C:\Users\Kristen\Anaconda2\envs
                          C:\Users\Kristen\AppData\Local\conda\conda\envs
                          C:\Users\Kristen\.conda\envs
          package cache : C:\Users\Kristen\Anaconda2\pkgs
                          C:\Users\Kristen\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.32 requests/2.14.2 CPython/2.7.12 Windows/8.
1 Windows/6.3.9600
          administrator : False
# conda environments:
#
bunnies                  C:\Users\Kristen\Anaconda2\envs\bunnies
snakes                   C:\Users\Kristen\Anaconda2\envs\snakes
snowflakes               C:\Users\Kristen\Anaconda2\envs\snowflakes
root                  *  C:\Users\Kristen\Anaconda2

sys.version: 2.7.12 |Anaconda custom (64-bit)| (defau...
sys.prefix: C:\Users\Kristen\Anaconda2
sys.executable: C:\Users\Kristen\Anaconda2\python.exe
conda location: C:\Users\Kristen\Anaconda2\lib\site-packages\conda
conda-build: C:\Users\Kristen\Anaconda2\Scripts\conda-build.exe
conda-convert: C:\Users\Kristen\Anaconda2\Scripts\conda-convert.exe
conda-develop: C:\Users\Kristen\Anaconda2\Scripts\conda-develop.exe
conda-env: C:\Users\Kristen\Anaconda2\Scripts\conda-env.exe
conda-index: C:\Users\Kristen\Anaconda2\Scripts\conda-index.exe
conda-inspect: C:\Users\Kristen\Anaconda2\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\Kristen\Anaconda2\Scripts\conda-metapackage.exe
conda-render: C:\Users\Kristen\Anaconda2\Scripts\conda-render.exe
conda-server: C:\Users\Kristen\Anaconda2\Scripts\conda-server.exe
conda-sign: C:\Users\Kristen\Anaconda2\Scripts\conda-sign.exe
conda-skeleton: C:\Users\Kristen\Anaconda2\Scripts\conda-skeleton.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: C:\Users\Kristen\Anaconda2
CONDA_ENVS_PATH: <not set>
CONDA_PREFIX: C:\Users\Kristen\Anaconda2
CONDA_PS1_BACKUP: $P$G
CONDA_ROOT: C:\Users\Kristen\Anaconda2
DYLD_LIBRARY_PATH: <not set>
FTP_PROXY: <not set>
HTTPS_PROXY: <not set>
HTTP_PROXY: <not set>
LD_LIBRARY_PATH: <not set>
PATH: C:\Users\Kristen\Anaconda2\Library\bin;C:\Users\Kristen\Anaconda2;C:\Users
\Kristen\Anaconda2\Library\mingw-w64\bin;C:\Users\Kristen\Anaconda2\Library\usr\
bin;C:\Users\Kristen\Anaconda2\Library\bin;C:\Users\Kristen\Anaconda2\Scripts;C:
\gurobi650\win64\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\P
rogram Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\win
dows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPow
erShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C
:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
 Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\In
tel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C
:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Condusiv Tec
hnologies\ExpressCache\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\b
in;C:\ProgramData\Lenovo\ReadyApps;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C
:\Program Files\MATLAB\R2017a\bin;C:\Program Files\MATLAB\R2016a\bin;C:\Program
Files\MATLAB\R2015a\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git
\cmd;C:\Users\Kristen\Anaconda2;C:\Users\Kristen\Anaconda2\Scripts;C:\Users\Kris
ten\Anaconda2\Library\bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>

License directories:
    C:\Users\Kristen\.continuum
    C:\Users\Kristen\Anaconda2\licenses
    C:\Users\Kristen\AppData\Roaming\Continuum
License files (license*.txt):
Package/feature end dates:

(C:\Users\Kristen\Anaconda2) C:\Users\Kristen>`

Is there some way to explore what is causing the testing? I have already tried re-installing the poliastro package.

**Comment by Juanlu001** [comment]
Hi @kristentetreault, thanks for your interest! I fear that poliastro is not compatible with Python 2. Can you please detail how you installed it and which version do you have?

Try creating a Python 3 environment and repeat the testing step:

```
conda create -n py3 python=3
activate py3
```

(And then install with pip or conda)

**Comment by kristentetreault** [comment]
Thank you @Juanlu001 , that did seem to help some. However after re-installing and testing in the new environment, I get `135 passed, 2 xfailed in 34.62 seconds`. The output from testing is

`============================= test session starts =============================
platform win32 -- Python 3.6.4, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: C:\Users\Kristen, inifile:
collected 137 items

Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_bodies.py .... [  2%]
..                                                                       [  4%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_coordinates.py . [  5
]
..                                                                       [  6%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_hyper.py ..... [ 10%]
......                                                                   [ 14%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_iod.py ....... [ 19%]
..                                                                       [ 21%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_jit.py ...     [ 23%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_maneuver.py .. [ 24%]
....                                                                     [ 27%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_patched_conics.py . [
28%]
.                                                                        [ 29%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_plotting.py .. [ 30%]
....                                                                     [ 33%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_plotting3d.py . [ 34%

.....                                                                    [ 37%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_stumpff.py ... [ 40%]
                                                                         [ 40%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_twobody.py ..  [ 41%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\test_util.py ...... [ 45%]
.                                                                        [ 46%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\tests_neos\test_dastcom5.p
 . [ 47%]
........                                                                 [ 53%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\tests_neos\test_neos_neows
py . [ 54%]
.....                                                                    [ 57%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\tests_twobody\test_angles.
y . [ 58%]
......                                                                   [ 62%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\tests_twobody\test_decorat
rs.py . [ 63%]
.                                                                        [ 64%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\tests_twobody\test_orbit.p
 . [ 64%]
.................                                                        [ 77%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\tests_twobody\test_propaga
ion.py . [ 78%]
........                                                                 [ 83%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\tests_twobody\test_sample.
y . [ 84%]
xx.........                                                              [ 92%]
Anaconda2\envs\py3\lib\site-packages\poliastro\tests\tests_twobody\test_states.
y . [ 93%]
.........                                                                [100%]

=================== 135 passed, 2 xfailed in 34.62 seconds ====================`

**Comment by Juanlu001** [comment]
"xfailed" means expected failures, so you're done :) I'm closing this!
