### ISSUE TITLE
Notebook timeouts

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#306]
🐞 **Problem**

Some of the notebooks take very long to execute and often produce timeouts, adding noise while testing and introducing false negatives.

🎯 **Goal**

Fix them, once and for all.

💡 **Possible solutions**

?

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Apart from timeouts, there might be HTTP 429 errors ("too many requests") as well https://httpstatuses.com/429

**Comment by Juanlu001** [comment]
* Timeout: https://travis-ci.org/poliastro/poliastro/jobs/340664636#L872
* HTTP 429: https://travis-ci.org/poliastro/poliastro/jobs/340664637#L869

**Comment by shreyasbapat** [comment]
Any probable solution we can try out?

**Comment by Juanlu001** [comment]
The only solution I can think of is to ignore the errors in this specific notebook, which is what we already do with another one:

https://github.com/poliastro/poliastro/commit/331b8933dad18c129183880a1c250566f89d967a

Let's try that in #305 and we will think of an alternative in the future.
