### ISSUE TITLE
Improve categorization of the issues and labels

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#314]
Different dimensions:

- Component: `coordinates`, `plotting`, `maneuvers`, `propagation`, `infra`, `documentation`
- Triaging: `bug`, `invalid`, `support`, `enhancement`
- Status: `help wanted`, `ready`, `blocked`, `needs discussion`
- Skills needed: `python`, `astrodynamics`
- Other: `hacktoberfest`

**Comment by Juanlu001** [comment]
It would also be nice to try to come up with some high level goals of poliastro, as per our [Core principles](https://github.com/poliastro/poliastro/wiki/Core-principles), such as `UX`, `Performance`, `Code Quality`, `Community`. (What about `New Feature`? And `Bug`?)

**Comment by xlxs4** [comment]
Status? 😄

**Comment by astrojuanlu** [comment]
Stalled :) But I must take care of this.

**Comment by astrojuanlu** [comment]
I _think_ I'm mostly happy with the categories I proposed in the first comment here (edited). Will try to do that before release, otherwise I'll do it right after.

**Comment by astrojuanlu** [comment]
I finally did this!
