### ISSUE TITLE
OrbitPlotter.set_frame redraws colors

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#316]
🐞 **Problem**

When calling `set_frame`, all the orbits get redrawn without retaining the original colors.

![screenshot-2018-2-18 untitled](https://user-images.githubusercontent.com/316517/36350953-d9946bb8-14a1-11e8-8884-6af4e871c054.png)

🎯 **Goal**

This is important in conjunction to #315 to allow reusability of plotting frames.

💡 **Possible solutions**

Store the colors and the orbits somewhere inside the object.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
I am unable to reproduce the error:
![image](https://user-images.githubusercontent.com/24257914/46262584-d0f2d280-c520-11e8-847d-05848ef239b6.png)
I am getting long tracebacks like this:
https://gist.github.com/shreyasbapat/2a8679755bba6916c39f0522c0b958ac

**Comment by Juanlu001** [comment]
Please open a separate issue with code to reproduce :) It might be a problem in matplotlib 3.0 or some other thing.

**Comment by shreyasbapat** [comment]
Okay! On it!
