### ISSUE TITLE
Split documentation build

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#318]
🐞 **Problem**

Several notebooks are causing timeouts in the builds and had to be disabled (see for instance the conversation in https://github.com/poliastro/poliastro/pull/305 and https://github.com/poliastro/poliastro/pull/263). We should split the docs into its own build that is allowed to fail, so we can inspect failures without adding noise to the pull requests. There is some risk that we commit failing notebooks, but many of them make access to external resources that we cannot mock.

🎯 **Goal**

Reduce noise in pull requests.

💡 **Possible solutions**

Simplify the Travis and AppVeyor builds and split the docs building separately, either with a new step in Travis or in Read the Docs.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
How can I test the .yml files locally? Any idea about that?

**Comment by Juanlu001** [comment]
Not sure, what I do in this cases is configuring everything in my fork and do the tests there.

**Comment by shreyasbapat** [comment]
But I don't have CI's enabled in my fork :/
We have to buy TravisCI Right?

**Comment by Juanlu001** [comment]
Travis CI is free for open source ;)

![screenshot_20180222-083329 2](https://user-images.githubusercontent.com/316517/36525660-44381008-17ab-11e8-8aec-561d040c897e.png)

**Comment by shreyasbapat** [comment]
![screenshot from 2018-02-22 16-34-17](https://user-images.githubusercontent.com/24257914/36535027-4d1aa62a-17ee-11e8-912d-757b0d151543.png)
This should not be happening right? Is it a local problem because it is not able to find the path. This is Appveyor

**Comment by shreyasbapat** [comment]
![screenshot from 2018-02-22 17-20-15](https://user-images.githubusercontent.com/24257914/36536954-b796c9f6-17f4-11e8-8736-2fa6fdbb18e2.png)
Same thing I did in Travis it worked :/

**Comment by shreyasbapat** [comment]
Pull Request #323

**Comment by shreyasbapat** [comment]
This needs to be closed!
