### ISSUE TITLE
Propagating 0 seconds with cowell fails

### ISSUE THREAD

**Issue by shreyasbapat** [poliastro/poliastro#328]
Currently we can only use the basic ```mean_method``` function to propagate orbits. As the Orbit.Sample() can now accept other propagators as well, we must be able to use ```cowell``` method  as well.
🐞 **Problem**
We can't use the cowell's method and other propagators to propagate the orbit because of differences in the parameters passed in the normal propagator while using Orbit.Sample().

🖥 **Please paste the output of following commands**

`conda info -a`

`python -c "import poliastro.testing; poliastro.testing.test()"`
python3 -c "import poliastro.testing; poliastro.testing.test()"
============================= test session starts ==============================
platform linux -- Python 3.6.3, pytest-3.4.1, py-1.5.2, pluggy-0.6.0
rootdir: /home/shreyas/poliastro, inifile: setup.cfg
plugins: cov-2.5.1
collected 141 items                                                            

poliastro/src/poliastro/tests/test_bodies.py ......                      [  4%]
poliastro/src/poliastro/tests/test_coordinates.py ...                    [  6%]
poliastro/src/poliastro/tests/test_hyper.py ...........                  [ 14%]
poliastro/src/poliastro/tests/test_iod.py .........                      [ 20%]
poliastro/src/poliastro/tests/test_jit.py ...                            [ 22%]
poliastro/src/poliastro/tests/test_maneuver.py ......                    [ 26%]
poliastro/src/poliastro/tests/test_patched_conics.py ..                  [ 28%]
poliastro/src/poliastro/tests/test_plotting.py .........                 [ 34%]
poliastro/src/poliastro/tests/test_plotting3d.py ......                  [ 39%]
poliastro/src/poliastro/tests/test_stumpff.py ...                        [ 41%]
poliastro/src/poliastro/tests/test_twobody.py ..                         [ 42%]
poliastro/src/poliastro/tests/test_util.py .......                       [ 47%]
poliastro/src/poliastro/tests/tests_neos/test_dastcom5.py .........      [ 53%]
poliastro/src/poliastro/tests/tests_neos/test_neos_neows.py ......       [ 58%]
poliastro/src/poliastro/tests/tests_twobody/test_angles.py .......       [ 63%]
poliastro/src/poliastro/tests/tests_twobody/test_decorators.py ..        [ 64%]
poliastro/src/poliastro/tests/tests_twobody/test_orbit.py .............. [ 74%]
.....                                                                    [ 78%]
poliastro/src/poliastro/tests/tests_twobody/test_propagation.py ........ [ 83%]
.                                                                        [ 84%]
poliastro/src/poliastro/tests/tests_twobody/test_sample.py ............  [ 92%]
poliastro/src/poliastro/tests/tests_twobody/test_states.py ..........    [100%]

========================= 141 passed in 21.47 seconds ==========================

🎯 **Goal**
To be able to Propagate the orbit using different propagators.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Can you check if this is still the case after merging https://github.com/poliastro/poliastro/pull/322? Also, is it a specific problem of `cowell` or affects other propagators as well? Can you ellaborate?

**Comment by shreyasbapat** [comment]
I realized that I could forget this hence I put it here.

**Comment by Juanlu001** [comment]
This looks like a convergence problem with the `cowell` method, rather than an API problem:

```
In [25]: iss.propagate(0 * u.s, method=cowell)
/home/juanlu/.miniconda36/envs/poliastro36/lib/python3.6/site-packages/scipy/integrate/_ode.py:1095: UserWarning: dop853: step size becomes too small
  self.messages.get(istate, unexpected_istate_msg)))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-25-5ec3bbe8e578> in <module>()
----> 1 iss.propagate(0 * u.s, method=cowell)

~/Development/poliastro/poliastro-library/src/poliastro/twobody/orbit.py in propagate(self, epoch_or_duration, method, rtol)
    254             time_of_flight = time.TimeDelta(epoch_or_duration)
    255 
--> 256         return propagate(self, time_of_flight, method=method, rtol=rtol)
    257 
    258     def sample(self, values=None, method=mean_motion):

~/Development/poliastro/poliastro-library/src/poliastro/twobody/propagation.py in propagate(orbit, time_of_flight, method, rtol, **kwargs)
    213                   time_of_flight.to(u.s).value,
    214                   rtol=rtol,
--> 215                   **kwargs)
    216     return orbit.from_vectors(orbit.attractor, r * u.km, v * u.km / u.s, orbit.epoch + time_of_flight)
    217 

~/Development/poliastro/poliastro-library/src/poliastro/twobody/propagation.py in cowell(k, r0, v0, tof, rtol, ad, callback, nsteps)
    102         r, v = rr.y[:3], rr.y[3:]
    103     else:
--> 104         raise RuntimeError("Integration failed")
    105 
    106     return r, v

RuntimeError: Integration failed
```

of course, sending a value of 0 seconds should return just the same position :) An easy issue to fix!

**Comment by shreyasbapat** [comment]
Yep! True!

**Comment by Juanlu001** [comment]
I think that `iss.sample(method=cowell)` won't raise the error after this was merged:

https://github.com/poliastro/poliastro/pull/330

However, `iss.propagate(0 * u.s, method=cowell)` or `iss.sample([0] * u.s, method=cowell)` should do.

**Comment by shreyasbapat** [comment]
Working on it!

**Comment by Juanlu001** [comment]
@shreyasbapat C'mon, leave some easy issues for the newcomers :stuck_out_tongue_winking_eye:

**Comment by shreyasbapat** [comment]
@Juanlu001  Not Working Now :wink:

**Comment by Juanlu001** [comment]
I still want some newcomer to fix this issue, so I'm removing the milestone.

**Comment by Juanlu001** [comment]
Is this still the case with the new integrator @nikita-astronaut?

**Comment by nikita-astronaut** [comment]
This still fails, but the error is different: the new integrator does not do anything and returns nothing :) I will fix this in the next PR

**Comment by nikita-astronaut** [comment]
Hey, @Juanlu001 

After the last PR, 'iss.propagate(0 * u.s, method=cowell)' forks nice. But 

`>>> iss.sample(np.array([0]) * u.s, method=cowell)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/astronaut/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py", line 334, in sample
    return values, self._sample(values, method)
  File "/home/astronaut/anaconda3/lib/python3.6/site-packages/poliastro/twobody/orbit.py", line 339, in _sample
    values, _ = cowell(self, (time_values - self.epoch).to(u.s).value)
  File "/home/astronaut/anaconda3/lib/python3.6/site-packages/astropy/time/core.py", line 1411, in __rsub__
    return -out
TypeError: bad operand type for unary -: 'Time'`

**Comment by nikita-astronaut** [comment]
Seems like providing of time list from outside of `orbit.sample` works incorrect, but we don't use it so tests do not fall.

The reason is that now one needs to explicitly cast u.s to `Time` instance. Am I right?

**Comment by Juanlu001** [comment]
> Seems like providing of time list from outside of orbit.sample works incorrect, but we don't use it so tests do not fall.

Then we need more tests!

> The reason is that now one needs to explicitly cast u.s to Time instance. Am I right?

poliastro, not the user :)

**Comment by Juanlu001** [comment]
Let's try to fix this one before the next release.

**Comment by Juanlu001** [comment]
Well... Or maybe the next after that!

**Comment by Juanlu001** [comment]
I will fix this myself.

**Comment by shreyasbapat** [comment]
You said this was a beginner issue :/
