### ISSUE TITLE
Propagate to a certain value of the true anomaly

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#329]
🐞 **Problem**

Although the `Orbit.sample` method is very flexible and allows many different kinds of inputs, the `Orbit.propagate` method does not allow a value of the true anomaly. Therefore, propagating to the pericenter or the apocenter is very involved.

🎯 **Goal**

This would be useful for testing, and perhaps also for some maneuvers.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by nikita-astronaut** [comment]
Started working on this!
I propose first calculating orbit elements, and then generating the orbit with certain true anomaly and the same orbit elements using `from_classical`.

**Comment by Juanlu001** [comment]
That would work! The other way would be manually using the `t = (M - M_0) / n` equation after converting from the true anomaly, and then use the normal `propagate` function with an elapsed time.

**Comment by Juanlu001** [comment]
Closed in #334.
