### ISSUE TITLE
Add Geocentric Solar Ecliptic (GSE) frame

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#335]
🎯 **Goal**

Produce plots like this:

![screenshot-2018-3-6 esa ssa-neo coordination centre monthly newsletter - march 2018 - juanlu001 gmail com - gmail](https://user-images.githubusercontent.com/316517/37024534-6b096394-2129-11e8-8db0-aaac19aefa90.png)

And this:

https://twitter.com/planet4589/status/910720207701897221

💡 **Possible solutions**

Perhaps it's similar to this one, or even exactly this one! http://docs.astropy.org/en/stable/api/astropy.coordinates.GeocentricTrueEcliptic.html

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
Do you think we would have to change things in our plotting module too?

**Comment by Juanlu001** [comment]
If http://docs.astropy.org/en/stable/api/astropy.coordinates.GeocentricTrueEcliptic.html is really the frame that we need, this is a non issue. But it would be nice to have a `OrbitPlotter2D.set_frame` that accepts a frame and knows what to do with it, instead of the horrible `Orbit.pqw()` that we use now. Don't remember if there's an issue for that.

**Comment by shreyasbapat** [comment]
> 2.1 Geocentric solar ecliptic (GSE)
This system has its X axis towards the Sun and its Z axis perpendicular to the plane of the Earth's orbit around the Sun (positive North). This system is fixed with respect to the Earth-Sun line. It is convenient for specifying magnetospheric boundaries. It has also been widely adopted as the system for representing vector quantities in space physics databases.

While, `GeocentricTrueEcliptic` says:

> Geocentric ecliptic coordinates. These origin of the coordinates are the geocenter (Earth), with the x axis pointing to the true (not mean) equinox at the time specified by the equinox attribute, and the xy-plane in the plane of the ecliptic for that date.

I don't think that's the same :/

**Comment by shreyasbapat** [comment]
Also, if I look at it more closely, I don't see a difference between the code of `class BarycentricTrueEcliptic(BaseEclipticFrame)` and `class GeocentricTrueEcliptic(BaseEclipticFrame)`

https://github.com/astropy/astropy/blob/master/astropy/coordinates/builtin_frames/ecliptic.py

**Comment by shreyasbapat** [comment]
Also,  I think as of now, system of frames is very non intuitive in poliastro.  Also, there has to be some cooperation from the point of view of plotting module. We always plot the attractor at the center https://github.com/poliastro/poliastro/blob/master/src/poliastro/plotting/_base.py#L147-L149. But keeping in mind some frames have to have earth in center.

**Comment by Juanlu001** [comment]
> Also, if I look at it more closely, I don't see a difference between the code of...

That's because the difference is in the transformation graph:

https://github.com/astropy/astropy/blob/master/astropy/coordinates/builtin_frames/ecliptic_transforms.py

**Comment by Juanlu001** [comment]
> Also, I think as of now, system of frames is very non intuitive in poliastro.

It's starting to form :) In fact, for the moment there are only two "planes", not even arbitrary frames.

> Also, there has to be some cooperation from the point of view of plotting module.

Following up in #557, but I just remembered where the ideas were: https://github.com/poliastro/poliastro/wiki/Orbits-and-reference-frames#proposed-steps

> We always plot the attractor at the center

True, and it's a mistake. The most paradigmatic example is orbits in ICRS, because the center is _not_ the Sun.

**Comment by shreyasbapat** [comment]
So, where do I contribute the frame?

**Comment by shreyasbapat** [comment]
I have to contribute methods to convert one frame to this one, as done here: 
https://github.com/astropy/astropy/blob/master/astropy/coordinates/builtin_frames/ecliptic_transforms.py

**Comment by Juanlu001** [comment]
Check out https://github.com/poliastro/poliastro/blob/master/src/poliastro/frames.py

**Comment by Juanlu001** [comment]
Closed in #562
