### ISSUE TITLE
Improve documentation on Jupyter and JupyterLab

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#337]
🐞 **Problem**

JupyterLab is a new environment, and some extra steps are needed to get things working: in particular, the user needs NodeJS and two extensions, `@jupyter-widgets/jupyterlab-manager` and `@jupyterlab/plotly-extension` for 3D.

Also, it's not clear in which versions of IPython/Jupyter is `%matplotlib inline` needed, and that deserves some documentation as well.

🎯 **Goal**

Make it easier for newcomers to have a poliastro environment up and running.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
What about "Getting started"?

**Comment by Juanlu001** [comment]
By the way: next version of nbconvert will finally have support for ipywidgets >= 7, which means: dynamic widgets in static HTML!

https://github.com/jupyter/nbconvert/issues/636#issuecomment-411002734

So, after it's released, we can start testing using widgets more.

On the other hand, there's an ongoing discussion on whether Jupyter should save the widget status by default or not:

https://github.com/jupyter-widgets/ipywidgets/issues/1632#issuecomment-406540741

Which, IMHO, is the final tweak that's needed for them to be as usable as the old HTML static output (see also https://github.com/python-visualization/folium/issues/874#issuecomment-393545499)

**Comment by shreyasbapat** [comment]
https://github.com/plotly/plotly.py/blob/master/README.md#jupyterlab-support-python-35
This should also go somewhere!

**Comment by Juanlu001** [comment]
Isn't it already there?

https://docs.poliastro.space/en/stable/getting_started.html#using-poliastro-on-jupyterlab

**Comment by Juanlu001** [comment]
I mean... You added those! https://github.com/poliastro/poliastro/pull/459

**Comment by shreyasbapat** [comment]
Not all of them :/
One that's not added: (Most Crucial)

# FigureWidget support
jupyter labextension install plotlywidget@0.7.0

**Comment by shreyasbapat** [comment]
Moreover, there is nothing like plotly extension mentioned over there :/

**Comment by Juanlu001** [comment]
Oh, you're right! Perhaps the extension is outdated? In any case, reopening. All yours :)

**Comment by shreyasbapat** [comment]
On it!

**Comment by Juanlu001** [comment]
Thanks @shreyasbapat! Re-closing :)
