### ISSUE TITLE
Refactor plotting to use backends and a consistent notebook experience

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#338]
🐞 **Problem**

The experience with 2D and 3D plots in the notebook is inconsistent, due to the inconsistencies in the rendering between matplotlib and plotly. The transition from Jupyter notebook to JupyterLab is making things more difficult, as the documentation is scattered and now the users need to install JavaScript extensions as well.

Also, `OrbitPlotter` and `OrbitPlotter3D` do not share a common parent class and API, which is also a problem since most of the functionality is shared.

Related: #315 and #316.

🎯 **Goal**

1. [ ] Refactor the `plotting` module so it allows the user to configure a "backend", via an environment variable or an IPython magic
2. [ ] Unify the `OrbitPlotter` and `OrbitPlotter3D` classes, putting common functionality in a parent superclass
3. [ ] Use Plotly for the notebook, both in 2D and 3D, and leave a matplotlib backend for those that want static, publication-quality 2D

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
Started Working on this!

**Comment by Juanlu001** [comment]
I think there is a fair share of code duplication now in `plotting.py`, but still I think #345 should be fixed first.

**Comment by shreyasbapat** [comment]
Yeah! True.

**Comment by shreyasbapat** [comment]
Do you mean to say that we have ``OrbitPlotter2D`` , ``OrbitPlotter3D`` and ``BaseOrbitPlotter`` all three at a same time?

**Comment by Juanlu001** [comment]
for the moment yes, although `BaseOrbitPlotter` should perhaps be private (so `_BaseOrbitPlotter`) and we might think of just having one class and switching the behavior using a flag, or something like that

**Comment by shreyasbapat** [comment]
Oh! Yes that's quite possible! Atleast it would reduce the clutter

**Comment by shreyasbapat** [comment]
@Juanlu001  Did we complete the objective here?

**Comment by Juanlu001** [comment]
We did part of step 2. :) `OrbitPlotter` still does not share a parent class with the plotly methods (maybe it doesn't have to?), but the plotting experience is still inconsistent between matplotlib and plotly. I still think we should stick to plotly in the notebook, and allow the user to choose matplotlib for static, 2D plots.

**Comment by shreyasbapat** [comment]
Okay! So do you have any idea?Like we can set some variable to do this?

**Comment by shreyasbapat** [comment]
I investigated IPython Magic. Could not figure out any way to do it. What kind of backend selection are we talking about here?

**Comment by Juanlu001** [comment]
Another problem: even if the user does not want to use matplotlib, it gets imported when doing `import poliastro.plotting`, as noted in #478.

**Comment by Juanlu001** [comment]
After careful consideration, I think we should throw away the idea of unifying an unified interface for both backends, and focus instead of **using Plotly to offer a 2D & 3D, interactive, notebook-first plotting experience**, while leaving matplotlib for static, 2D plots. Some reasons:

* matplotlib is special-cased everywhere in Jupyter/IPython, and the logic that shows the figure is very difficult to replicate elsewhere
* Alternative matplotlib backends, such as ipympl, still have some issues to retain PNG output, because of how the ecosystem works (see https://github.com/matplotlib/jupyter-matplotlib/issues/16)
* matplotlib is literally everywhere and there will always be users that prefer its simplicity and publication-quality output, despite its inability to do 3D right
* Focusing on Plotly for "the notebook experience" will allow us to leverage its awesome interactive features

There is one thing though: interactive widgets "break" some workflows, in the sense that, until you "close" the plot or create a new figure, everything gets plotted in the current figure, and some people just want to plot one figure after another.

Therefore, we should strive to make our APIs more lightweight, and don't get in the way regardless of the user preference. An example of this with the current Plotly API is https://github.com/poliastro/poliastro/issues/460.

We have to offer simple APIs that "just work" (`plot(orbit)`) while allowing power users to reuse these structures as they please (see for example https://docs.poliastro.space/en/latest/examples/Customising%20orbit%20plots.html).

**Comment by Juanlu001** [comment]
By the way, this is no longer blocked.

**Comment by Juanlu001** [comment]
Current ideas: https://github.com/poliastro/poliastro/wiki/Plotting I'm happy enough to start implementing in the coming days.
