### ISSUE TITLE
AttributeError: 'CartesianRepresentation' object has no attribute 'to' (get_body_ephem issue)

### ISSUE THREAD

**Issue by jmerskine1** [poliastro/poliastro#354]
🐞 **Problem**
Removal of get_body_ephem leads to issues re: data types (from "Going to Mars" which i was attempting to run as a test)

Because astropy.coordinates.get_body_barycentric_posvel outputs type "CartesianRepresentation" whereas poliastro.ephem.get_body_ephem outputs type "Quantity" (I think...)

Any advice on how to swap the data types? or is there a known fix for this already?

Thank you!

SYSTEM INFO
############################################################################
`conda info -a`
     active environment : None
       user config file : /Users/Jonny/.condarc
 populated config files : /Users/Jonny/.condarc
          conda version : 4.4.10
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : /anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /anaconda3/pkgs
                          /Users/Jonny/.conda/pkgs
       envs directories : /anaconda3/envs
                          /Users/Jonny/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.3 Darwin/17.5.0 OSX/10.13.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False

# conda environments:
#
base                  *  /anaconda3

sys.version: 3.6.3 |Anaconda custom (64-bit)| (defaul...
sys.prefix: /anaconda3
sys.executable: /anaconda3/bin/python
conda location: /anaconda3/lib/python3.6/site-packages/conda
conda-build: /anaconda3/bin/conda-build
conda-convert: /anaconda3/bin/conda-convert
conda-develop: /anaconda3/bin/conda-develop
conda-env: /anaconda3/bin/conda-env
conda-index: /anaconda3/bin/conda-index
conda-inspect: /anaconda3/bin/conda-inspect
conda-metapackage: /anaconda3/bin/conda-metapackage
conda-render: /anaconda3/bin/conda-render
conda-server: /anaconda3/bin/conda-server
conda-skeleton: /anaconda3/bin/conda-skeleton
conda-verify: /anaconda3/bin/conda-verify
user site dirs: 

CIO_TEST: <not set>
CONDA_ROOT: /anaconda3
PATH: /anaconda3/bin:/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin://anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>

License directories:
    /Users/Jonny/.continuum
    /Users/Jonny/Library/Application Support/Anaconda
    /anaconda3/licenses
License files (license*.txt):
Package/feature end dates:
############################################################################

TESTS - Didnt pass them all.. ah well
############################################################################

`python -c "import poliastro.testing; poliastro.testing.test()"`
============================= test session starts ==============================
platform darwin -- Python 3.6.3, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /anaconda3/lib/python3.6/site-packages/poliastro, inifile:
collected 173 items                                                             

../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_bodies.py ......
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_coordinates.py ...
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_hyper.py ...........
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_iod.py .........
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_jit.py ...
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_maneuver.py ......
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_patched_conics.py ..
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_plotting.py .........
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_plotting2d.py ........
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_plotting3d.py .........
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_stumpff.py ...
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_twobody.py ..
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/test_util.py .......
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/tests_neos/test_dastcom5.py .........
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/tests_neos/test_neos_neows.py ......
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_angles.py .......
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_decorators.py ..
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_orbit.py ....................
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_perturbations.py ..
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_propagation.py ..............xx
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_sample.py ......................X
../../anaconda3/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_states.py ..........

============== 170 passed, 2 xfailed, 1 xpassed in 73.89 seconds ===============
############################################################################

💡 **Possible solutions**
Reconfigure either poliastro or astropy w.r.t. this issue

Thanks for your help!

**Comment by Juanlu001** [comment]
Hi @jmerskine1, thanks for your interest in the project! The best thing you can do to extract a `Quantity` from a `CartesianRepresentation` is to use the `.xyz` attribute:

http://docs.astropy.org/en/stable/api/astropy.coordinates.CartesianRepresentation.html#astropy.coordinates.CartesianRepresentation.xyz

This is done in the Mars notebook (look for `.xyz` before the plotting code)

http://docs.astropy.org/en/stable/api/astropy.coordinates.CartesianRepresentation.html#astropy.coordinates.CartesianRepresentation.xyz

Did this fix your issue? Also, which poliastro and astropy versions are you using?

**Comment by jmerskine1** [comment]
Fixed! Thanks very much for your quick reply and easy solution. an example of what was required below (for some reason I got errors when trying to leave it as rr_mars, vv_mars = ...."

Astropy Version 3.0.1; Poliastro Version 0.8.0

Keep up the incredible work and thanks again!
    
    rr_mars_cartesian = get_body_barycentric_posvel("mars", times_vector)[0]
    vv_mars_cartesian = get_body_barycentric_posvel("mars", times_vector)[1]
    #rr_mars, vv_mars = get_body_ephem("mars", times_vector)
    rr_mars, vv_mars = rr_mars_cartesian.xyz, vv_mars_cartesian.xyz

**Comment by Juanlu001** [comment]
Thanks for your kind words! May I ask what are you using poliastro for? :)

Just as a side comment, your issue reminded me that we have to improve the issue template #355 so I don't have to ask the poliastro & astropy version.

**Comment by jmerskine1** [comment]
Our team have a university (TU Delft) assignment to develop the navigation methods for the LUMIO microsat mission.

https://www.tudelft.nl/en/2018/lr/lumio-the-cubesat-that-will-watch-meteoroid-impacts-on-the-far-side-of-the-moon/

I want to plot the mission using poliastro and show how and where the navigation strategy will operate over the injection, transfer and operational orbit phases (based on the FOV of the onboard camera). Probably a very basic use for poliastro but I'm sure i will find it challenging enough.

**Comment by Juanlu001** [comment]
Awesome! Greetings to Prof. Topputo :) Please ping me if I can ever help you in any way, and also feel free to join our chat: https://riot.im/app/#/room/#poliastro:matrix.org
