### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by shreyasbapat** [poliastro/poliastro#357]
The readme file seems to be outdated. Specifically the what's the future of the project section. 
🐞 **Problem**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
True, I think I wrote that when the future of the project was unclear :) I assign this to myself!
