### ISSUE TITLE
Upgrade pytest and NumPy in all CI machines

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#358]
🐞 **Problem**

The OS X and Linux builds on Travis CI do not have the same pytest and NumPy versions. The reason is that, on Linux, pytest and NumPy are already there and pip does not upgrade by default:

* OS X https://travis-ci.org/poliastro/poliastro/jobs/370183695#L105, https://travis-ci.org/poliastro/poliastro/jobs/370183695#L252
* Linux https://travis-ci.org/poliastro/poliastro/jobs/370183697#L602, https://travis-ci.org/poliastro/poliastro/jobs/370183697#L750

🎯 **Goal**

We should run the tests with always the latest version of pytest so we have as much information as possible, for example these improvements for parametrized tests:

https://docs.pytest.org/en/3.4.0/changelog.html#trivial-internal-changes

And we should be able to control the NumPy version at will.

💡 **Possible solutions**

We would have to change how we install the dependencies here:

https://github.com/poliastro/poliastro/blob/master/.travis.yml#L57-L68

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by newlawrence** [comment]
I'm taking care of this if you don't mind.

**Comment by Juanlu001** [comment]
:tada:

**Comment by Juanlu001** [comment]
The CI infrastructure has changed a bit, but Travis CI is still used for OS X. @newlawrence do you still want to test whether you can fix the dependencies there?

**Comment by Juanlu001** [comment]
Tests are not xpassing anymore on OS X and I think this is a bit outdated, so I will close.
