### ISSUE TITLE
Some plotting tests fail when Jupyter is not installed

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#361]
🐞 **Problem**

As noted in #355, the plotting tests that make use of Plotly fail from the command line with errors like this:

```
$ pytest -k plotting -vvv
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0 -- /home/juanlu/.miniconda36/envs/_test36/bin/python
cachedir: .pytest_cache
rootdir: /home/juanlu/Development/poliastro/poliastro-library, inifile: setup.cfg
collected 373 items / 347 deselected                                           

src/poliastro/tests/test_plotting.py::test_orbitplotter_has_axes PASSED  [  3%]
src/poliastro/tests/test_plotting.py::test_set_frame PASSED              [  7%]
src/poliastro/tests/test_plotting.py::test_axes_labels_and_title PASSED                                                                                                                                                                [ 11%]
src/poliastro/tests/test_plotting.py::test_number_of_lines_for_osculating_orbit PASSED                                                                                                                                                 [ 15%]
src/poliastro/tests/test_plotting.py::test_legend PASSED                                                                                                                                                                               [ 19%]
src/poliastro/tests/test_plotting.py::test_color PASSED                                                                                                                                                                                [ 23%]
src/poliastro/tests/test_plotting.py::test_plot_solar_system[True-8] PASSED                                                                                                                                                            [ 26%]
src/poliastro/tests/test_plotting.py::test_plot_solar_system[False-4] PASSED                                                                                                                                                           [ 30%]
src/poliastro/tests/test_plotting.py::test_plot_trajectory_sets_label PASSED                                                                                                                                                           [ 34%]
src/poliastro/tests/test_plotting2d.py::test_get_figure_has_expected_properties PASSED                                                                                                                                                 [ 38%]
src/poliastro/tests/test_plotting2d.py::test_set_different_attractor_raises_error PASSED                                                                                                                                               [ 42%]
src/poliastro/tests/test_plotting2d.py::test_plot_sets_attractor PASSED                                                                                                                                                                [ 46%]
src/poliastro/tests/test_plotting2d.py::test_plot_appends_data PASSED                                                                                                                                                                  [ 50%]
src/poliastro/tests/test_plotting2d.py::test_plot_trajectory_without_attractor_raises_error PASSED                                                                                                                                     [ 53%]
src/poliastro/tests/test_plotting2d.py::test_plot_trajectory_plots_a_trajectory PASSED                                                                                                                                                 [ 57%]
src/poliastro/tests/test_plotting2d.py::test_show_calls_prepare_plot FAILED                                                                                                                                                            [ 61%]
src/poliastro/tests/test_plotting2d.py::test_savefig_calls_prepare_plot PASSED                                                                                                                                                         [ 65%]
src/poliastro/tests/test_plotting3d.py::test_get_figure_has_expected_properties PASSED                                                                                                                                                 [ 69%]
src/poliastro/tests/test_plotting3d.py::test_set_different_attractor_raises_error PASSED                                                                                                                                               [ 73%]
src/poliastro/tests/test_plotting3d.py::test_plot_sets_attractor PASSED                                                                                                                                                                [ 76%]
src/poliastro/tests/test_plotting3d.py::test_plot_appends_data PASSED                                                                                                                                                                  [ 80%]
src/poliastro/tests/test_plotting3d.py::test_plot_trajectory_without_attractor_raises_error PASSED                                                                                                                                     [ 84%]
src/poliastro/tests/test_plotting3d.py::test_set_view PASSED                                                                                                                                                                           [ 88%]
src/poliastro/tests/test_plotting3d.py::test_plot_trajectory_plots_a_trajectory PASSED                                                                                                                                                 [ 92%]
src/poliastro/tests/test_plotting3d.py::test_show_calls_prepare_plot FAILED                                                                                                                                                            [ 96%]
src/poliastro/tests/test_plotting3d.py::test_savefig_calls_prepare_plot PASSED                                                                                                                                                         [100%]

================================================================================================================== FAILURES ==================================================================================================================
________________________________________________________________________________________________________ test_show_calls_prepare_plot ________________________________________________________________________________________________________

    def test_show_calls_prepare_plot():
        patcher = mock.patch.object(OrbitPlotter2D, '_prepare_plot')
        patched = patcher.start()
    
        m = OrbitPlotter2D()
        earth = Orbit.from_body_ephem(Earth)
        m.plot(orbit=earth, label="Obj")
>       m.show()

src/poliastro/tests/test_plotting2d.py:83: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.miniconda36/envs/_test36/lib/python3.6/site-packages/poliastro/plotting.py:578: in show
    iplot(self.figure)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

figure_or_data = {'data': [{'type': 'scatter', 'x': array([ 3.62760316e+07,  2.71113062e+07,  1.78350308e+07,  8.48455766e+06,
       -...9, 'y1': -67716885.44669741, 'opacity': 1, 'fillcolor': 'rgb(31, 119, 180)', 'line': {'color': 'rgb(31, 119, 180)'}}]}}
show_link = True, link_text = 'Export to plot.ly', validate = True, image = None, filename = 'plot_image', image_width = 800, image_height = 600, config = None

    def iplot(figure_or_data, show_link=True, link_text='Export to plot.ly',
              validate=True, image=None, filename='plot_image', image_width=800,
              image_height=600, config=None):
        """
        Draw plotly graphs inside an IPython or Jupyter notebook without
        connecting to an external server.
        To save the chart to Plotly Cloud or Plotly Enterprise, use
        `plotly.plotly.iplot`.
        To embed an image of the chart, use `plotly.image.ishow`.
    
        figure_or_data -- a plotly.graph_objs.Figure or plotly.graph_objs.Data or
                          dict or list that describes a Plotly graph.
                          See https://plot.ly/python/ for examples of
                          graph descriptions.
    
        Keyword arguments:
        show_link (default=True) -- display a link in the bottom-right corner of
                                    of the chart that will export the chart to
                                    Plotly Cloud or Plotly Enterprise
        link_text (default='Export to plot.ly') -- the text of export link
        validate (default=True) -- validate that all of the keys in the figure
                                   are valid? omit if your version of plotly.js
                                   has become outdated with your version of
                                   graph_reference.json or if you need to include
                                   extra, unnecessary keys in your figure.
        image (default=None |'png' |'jpeg' |'svg' |'webp') -- This parameter sets
            the format of the image to be downloaded, if we choose to download an
            image. This parameter has a default value of None indicating that no
            image should be downloaded. Please note: for higher resolution images
            and more export options, consider making requests to our image servers.
            Type: `help(py.image)` for more details.
        filename (default='plot') -- Sets the name of the file your image
            will be saved to. The extension should not be included.
        image_height (default=600) -- Specifies the height of the image in `px`.
        image_width (default=800) -- Specifies the width of the image in `px`.
        config (default=None) -- Plot view options dictionary. Keyword arguments
            `show_link` and `link_text` set the associated options in this
            dictionary if it doesn't contain them already.
    
        Example:
        ```
        from plotly.offline import init_notebook_mode, iplot
        init_notebook_mode()
        iplot([{'x': [1, 2, 3], 'y': [5, 2, 7]}])
        # We can also download an image of the plot by setting the image to the
        format you want. e.g. `image='png'`
        iplot([{'x': [1, 2, 3], 'y': [5, 2, 7]}], image='png')
        ```
        """
        if not ipython:
>           raise ImportError('`iplot` can only run inside an IPython Notebook.')
E           ImportError: `iplot` can only run inside an IPython Notebook.

../../../.miniconda36/envs/_test36/lib/python3.6/site-packages/plotly/offline/offline.py:326: ImportError
________________________________________________________________________________________________________ test_show_calls_prepare_plot ________________________________________________________________________________________________________

    def test_show_calls_prepare_plot():
        patcher = mock.patch.object(OrbitPlotter3D, '_prepare_plot')
        patched = patcher.start()
    
        m = OrbitPlotter3D()
        earth = Orbit.from_body_ephem(Earth)
        m.plot(orbit=earth, label="Object")
>       m.show()

src/poliastro/tests/test_plotting3d.py:96: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.miniconda36/envs/_test36/lib/python3.6/site-packages/poliastro/plotting.py:387: in show
    iplot(self.figure)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

figure_or_data = {'data': [{'type': 'scatter3d', 'x': array([ 3.62760501e+07,  2.71113252e+07,  1.78350502e+07,  8.48457728e+06,
      ...ne': {'xaxis': {'title': 'x (km)'}, 'yaxis': {'title': 'y (km)'}, 'zaxis': {'title': 'z (km)'}, 'aspectmode': 'data'}}}
show_link = True, link_text = 'Export to plot.ly', validate = True, image = None, filename = 'plot_image', image_width = 800, image_height = 600, config = None

    def iplot(figure_or_data, show_link=True, link_text='Export to plot.ly',
              validate=True, image=None, filename='plot_image', image_width=800,
              image_height=600, config=None):
        """
        Draw plotly graphs inside an IPython or Jupyter notebook without
        connecting to an external server.
        To save the chart to Plotly Cloud or Plotly Enterprise, use
        `plotly.plotly.iplot`.
        To embed an image of the chart, use `plotly.image.ishow`.
    
        figure_or_data -- a plotly.graph_objs.Figure or plotly.graph_objs.Data or
                          dict or list that describes a Plotly graph.
                          See https://plot.ly/python/ for examples of
                          graph descriptions.
    
        Keyword arguments:
        show_link (default=True) -- display a link in the bottom-right corner of
                                    of the chart that will export the chart to
                                    Plotly Cloud or Plotly Enterprise
        link_text (default='Export to plot.ly') -- the text of export link
        validate (default=True) -- validate that all of the keys in the figure
                                   are valid? omit if your version of plotly.js
                                   has become outdated with your version of
                                   graph_reference.json or if you need to include
                                   extra, unnecessary keys in your figure.
        image (default=None |'png' |'jpeg' |'svg' |'webp') -- This parameter sets
            the format of the image to be downloaded, if we choose to download an
            image. This parameter has a default value of None indicating that no
            image should be downloaded. Please note: for higher resolution images
            and more export options, consider making requests to our image servers.
            Type: `help(py.image)` for more details.
        filename (default='plot') -- Sets the name of the file your image
            will be saved to. The extension should not be included.
        image_height (default=600) -- Specifies the height of the image in `px`.
        image_width (default=800) -- Specifies the width of the image in `px`.
        config (default=None) -- Plot view options dictionary. Keyword arguments
            `show_link` and `link_text` set the associated options in this
            dictionary if it doesn't contain them already.
    
        Example:
        ```
        from plotly.offline import init_notebook_mode, iplot
        init_notebook_mode()
        iplot([{'x': [1, 2, 3], 'y': [5, 2, 7]}])
        # We can also download an image of the plot by setting the image to the
        format you want. e.g. `image='png'`
        iplot([{'x': [1, 2, 3], 'y': [5, 2, 7]}], image='png')
        ```
        """
        if not ipython:
>           raise ImportError('`iplot` can only run inside an IPython Notebook.')
E           ImportError: `iplot` can only run inside an IPython Notebook.

../../../.miniconda36/envs/_test36/lib/python3.6/site-packages/plotly/offline/offline.py:326: ImportError
============================================================================================ 2 failed, 24 passed, 347 deselected in 40.75 seconds ============================================================================================
```

See for instance https://circleci.com/gh/conda-forge/poliastro-feedstock/62#tests/containers/0. Interestingly, these do not seem to fail in Travis CI nor AppVeyor, and that's why the failures remained silent for so long.

🖥 **Please paste the output of following commands**

`conda info -a`

`python -c "import poliastro.testing; poliastro.testing.test()"`

🎯 **Goal**

We should not have failing tests, especially if we are telling the users to run those tests when reporting issues.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Googling for `"iplot can only run inside an IPython Notebook"` I don't get much information, and also I am _sometimes_ unable to reproduce this failure. WTF?

**Comment by OrbitalMechanic** [comment]
I too encountered two (2) failures testing poliastro as follows (on a Mac Pro running Mac OS X 10.12.6, with the Anaconda distribution Python 3.6):

(prova) Samuels-Mac-Pro:~ user$ conda info -a

     active environment : prova
    active env location : /Users/user/anaconda3/envs/prova
            shell level : 1
       user config file : /Users/user/.condarc
 populated config files : /Users/user/.condarc
          conda version : 4.5.2
    conda-build version : 3.8.0
         python version : 3.6.5.final.0
       base environment : /Users/user/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/user/anaconda3/pkgs
                          /Users/user/.conda/pkgs
       envs directories : /Users/user/anaconda3/envs
                          /Users/user/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.2 requests/2.18.4 CPython/3.6.5 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 503:20
             netrc file : None
           offline mode : False

# conda environments:
#
base                     /Users/user/anaconda3
pagmo                    /Users/user/anaconda3/envs/pagmo
prova                 *  /Users/user/anaconda3/envs/prova

sys.version: 3.6.5 | packaged by conda-forge | (defau...
sys.prefix: /Users/user/anaconda3
sys.executable: /Users/user/anaconda3/bin/python
conda location: /Users/user/anaconda3/lib/python3.6/site-packages/conda
conda-build: /Users/user/anaconda3/bin/conda-build
conda-convert: /Users/user/anaconda3/bin/conda-convert
conda-develop: /Users/user/anaconda3/bin/conda-develop
conda-env: /Users/user/anaconda3/bin/conda-env
conda-index: /Users/user/anaconda3/bin/conda-index
conda-inspect: /Users/user/anaconda3/bin/conda-inspect
conda-metapackage: /Users/user/anaconda3/bin/conda-metapackage
conda-render: /Users/user/anaconda3/bin/conda-render
conda-server: /Users/user/anaconda3/bin/conda-server
conda-skeleton: /Users/user/anaconda3/bin/conda-skeleton
conda-verify: /Users/user/anaconda3/bin/conda-verify
user site dirs: ~/.local/lib/python2.7
                ~/.local/lib/python3.5
                ~/.local/lib/python3.6

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: prova
CONDA_EXE: /Users/user/anaconda3/bin/conda
CONDA_PREFIX: /Users/user/anaconda3/envs/prova
CONDA_PROMPT_MODIFIER: (prova) 
CONDA_PYTHON_EXE: /Users/user/anaconda3/bin/python
CONDA_ROOT: /Users/user/anaconda3
CONDA_SHLVL: 1
DYLD_LIBRARY_PATH: /Applications/Absoft18.0/shlib64:/Applications/Absoft18.0/shlib:
JULIAPATH: /Applications/Julia-0.5.app/Contents/Resources/julia
LD_LIBRARY_PATH: /Users/user/anaconda3/lib:/usr/lib:/usr/local/lib:/usr/local/opt::/Users/user/ODTBX_6_5/GMAT-R2014a-Darwin/bin:/Users/user/cestam/lib
MANPATH: /Users/user/perl5/perlbrew/perls/perl-5.18.4/man:/usr/local/opt/coreutils/libexec/gnuman:/Users/user/Library/Enthought/Canopy_64bit/User/share/man:/usr/share/man:/usr/local/share/man:/opt/subversion/man:/Applications/Absoft18.0/man:/opt/X11/share/man:/Library/Frameworks/Mono.framework/Versions/Current/share/man:/Library/TeX/texbin/man:/sw/share/man:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man
MATLABPATH: /Users/user/ODTBX_6_5/mice/lib
PATH: /Users/user/anaconda3/envs/prova/bin:/Users/user/local/lib/python3.6/site-packages/ester:/Users/user/anaconda3/bin:/Users/user/anaconda3/include:/Users/user/anaconda3/lib:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Applications/Julia-0.5.app/Contents/Resources/julia/bin:/Users/user/gnu:/Users/user/.local/bin/python3.6:/usr/local/atlas/include:/usr/local/atlas/lib:/usr/local/pcre/bin:/Applications/Absoft18.0/bin:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/usr/local/sbin:/Users/user/perl5/perlbrew/bin:/Users/user/perl5/perlbrew/perls/perl-5.18.4/bin:/Users/user/Library/Enthought/Canopy_64bit/User/bin:/Users/user/dislin/bin:/usr/local/texlive/2013/bin:/usr/include:/usr/local/include:/opt/subversion/bin:/Users/user/apache-maven-3.3.9/bin:/Applications/Absoft18.0/bin:/Applications/Absoft18.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin:/Applications/Xamarin
PERLBREW_MANPATH: /Users/user/perl5/perlbrew/perls/perl-5.18.4/man
PERLBREW_PATH: /Users/user/perl5/perlbrew/bin:/Users/user/perl5/perlbrew/perls/perl-5.18.4/bin
PYTHONPATH: /Users/user/anaconda3:/Users/user/local/lib/python3.6/site-packages/ester
REQUESTS_CA_BUNDLE: <not set>
S2PATH: /Users/user/s2plot-3.2.1
S2PLOT_TEXPATH: /Users/user/s2plot-3.2.1/textures
SSL_CERT_FILE: <not set>
ester_path: /Users/user/local/bin
evpath: /Users/user/TWIN/TWIN

License directories:
    /Users/user/.continuum
    /Users/user/Library/Application Support/Anaconda
    /Users/user/anaconda3/licenses
License files (license*.txt):
Package/feature end dates:
(prova) Samuels-Mac-Pro:~ user$ python -c "import poliastro.testing; poliastro.testing.test()"
======================================================================================= test session starts =======================================================================================
platform darwin -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /Users/user, inifile:
plugins: cov-2.5.1
collected 373 items                                                                                                                                                                               

anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_bodies.py ......                                                                                                      [  1%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_coordinates.py ...                                                                                                    [  2%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_hyper.py ...........                                                                                                  [  5%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_iod.py .........                                                                                                      [  7%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_jit.py ...                                                                                                            [  8%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_maneuver.py ......                                                                                                    [ 10%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_patched_conics.py ..                                                                                                  [ 10%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_plotting.py .........                                                                                                 [ 13%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_plotting2d.py ........                                                                                                [ 15%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_plotting3d.py .........                                                                                               [ 17%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_stumpff.py ...                                                                                                        [ 18%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_twobody.py ..                                                                                                         [ 19%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/test_util.py .......                                                                                                       [ 20%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/tests_neos/test_dastcom5.py .........                                                                                      [ 23%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/tests_neos/test_neos_neows.py ......                                                                                       [ 24%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_angles.py ............................................................................................. [ 49%]
..................................................................................................................                                                                          [ 80%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_decorators.py ..                                                                                        [ 80%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_orbit.py ....................                                                                           [ 86%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_perturbations.py ..                                                                                     [ 86%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_propagation.py ..............xx                                                                         [ 91%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_sample.py ......................X                                                                       [ 97%]
anaconda3/envs/prova/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_states.py ..........                                                                                    [100%]

======================================================================== 370 passed, 2 xfailed, 1 xpassed in 43.57 seconds ========================================================================
(prova) Samuels-Mac-Pro:~ user$ 

Please advise.

**Comment by Juanlu001** [comment]
The `2 xfailed` mark means that the tests were expected to fail, so you can forget about those. The `1 xpassed` is a test which was expected to fail, but passed - which for us is still a mistery, but should pose no problems. Your installation is correct and ready :)

**Comment by Juanlu001** [comment]
While trying to fix #397, let's see if we can make sure these errors won't happen again.

**Comment by Juanlu001** [comment]
This is a potential source of noise for people installing the library, so let's try to fix the tests for the next release, or even 0.10.1.

**Comment by Juanlu001** [comment]
As @tomdean1 showed in https://github.com/poliastro/poliastro/issues/411#issuecomment-407179073

> The errors were caused by NOT having Jupyter and IPython.

We are installing all the dev dependencies in the CI, and that's why we were not noticing them. A quick fix is to just skip those tests if Jupyter is not present.

**Comment by Juanlu001** [comment]
Confirmed that `pip install ipython` fixes these issues.
