### ISSUE TITLE
Clarify system requirements to build documentation

### ISSUE THREAD

**Issue by OrbitalMechanic** [poliastro/poliastro#365]
Attempting to build the pdf document for poliastro version 0.90. 

The output I get from executing the command _make latexpdf_ in the docs subdirectory of the distribution

Samuels-Mac-Pro:~ user$ cd poliastro-master
Samuels-Mac-Pro:poliastro-master user$ cd docs
Samuels-Mac-Pro:docs user$ make latexpdf
sphinx-build -b latex -d build/doctrees   source build/latex
Running Sphinx v1.7.4

Extension error:
Could not import extension nbsphinx (exception: No module named 'nbsphinx')
make: *** [latexpdf] Error 2
Samuels-Mac-Pro:docs user$ 

🖥 **Please paste the output of following commands**

`conda info -a`
[conda_info.txt](https://github.com/poliastro/poliastro/files/1969374/conda_info.txt)

`python -c "import poliastro.testing; poliastro.testing.test()"`
[poliastro.testing.txt](https://github.com/poliastro/poliastro/files/1969375/poliastro.testing.txt)

`pip freeze | grep astropy`
[grep_astropy.txt](https://github.com/poliastro/poliastro/files/1969379/grep_astropy.txt)

`pip freeze | grep poliastro`
[grep_poliastro.txt](https://github.com/poliastro/poliastro/files/1969380/grep_poliastro.txt)

Please advise.

**Comment by Juanlu001** [comment]
Hi @OrbitalMechanic and thanks for your renowed interest! It should be better explained in the documentation but to build the docs you need to install all the devekdeoendencies

**Comment by Juanlu001** [comment]
(Sorry, wrong button)

you need to install the development dependencies:

```
pip install poliastro[dev]
```

or

```
pip install ~/poliastro-master/[dev]
```

(Depending on how you installed poliastro originally)

Can you try this to see it that fixed the issue? I see a strange result in the tests so let's see if everything works.

**Comment by Juanlu001** [comment]
@OrbitalMechanic did you succeed in building the docs?

**Comment by OrbitalMechanic** [comment]
I was able to get a document to build using the command /make latex/ as 
opposed to /make latexpdf/. I'm going through the user's guide at 
present. I've attached the resulted PDF to this note.

Hope this helps.

Sam Dupree.

**Comment by Juanlu001** [comment]
I guess `make latexpdf` needs pandoc, which is a bit trickier to install (I normally use conda, which allows `conda install pandoc`). Glad you have the docs working anyway! I enabled PDF builds on Read the Docs which can already be downloaded from here:

http://readthedocs.org/projects/poliastro/downloads/pdf/latest/

Feel ask any questions you might have, I'm leaving this issue open as a reminder to improve the developer documentation.

**Comment by astrojuanlu** [comment]
> Should we add a line regarding the pandoc need?

Good catch @rafaellehmkuhl!

> Once pandoc is installed, we have another error:

Yeah, that's because LaTeX is also needed locally. Take a look at what the CI does:

https://github.com/poliastro/poliastro/blob/fd623c2c2d18c0225031ef0897da6830938bc7be/azure-pipelines.yml#L42-L44

> The docs itself are built on just seconds, but once Sphinx reaches the Markdown notebooks, it takes a long, long time to build (besides the error above). Wouldnt be good to have an option for skipping those notebooks?

Totally. There used to be a trick that @jorgepiloto commented out:

https://github.com/poliastro/poliastro/blob/fd623c2c2d18c0225031ef0897da6830938bc7be/docs/source/conf.py#L143-L151

So, my suggestion is that we replace that with an environment variable `POLIASTRO_SKIP_NOTEBOOKS`. How does that sound?

**Comment by rafaellehmkuhl** [comment]
> > Should we add a line regarding the pandoc need?
> 
> Good catch @rafaellehmkuhl!
> 
> > Once pandoc is installed, we have another error:
> 
> Yeah, that's because LaTeX is also needed locally. Take a look at what the CI does:
> 
> https://github.com/poliastro/poliastro/blob/fd623c2c2d18c0225031ef0897da6830938bc7be/azure-pipelines.yml#L42-L44
> 

Ok , once all of those are installed, we don't have any compiling errors (with just pandoc and the tex packages the errors continue). I will add a line on the contributing section stating that all of those are needed to compile the docs.

> > The docs itself are built on just seconds, but once Sphinx reaches the Markdown notebooks, it takes a long, long time to build (besides the error above). Wouldnt be good to have an option for skipping those notebooks?
> 
> Totally. There used to be a trick that @jorgepiloto commented out:
> 
> https://github.com/poliastro/poliastro/blob/fd623c2c2d18c0225031ef0897da6830938bc7be/docs/source/conf.py#L143-L151
> 
> So, my suggestion is that we replace that with an environment variable `POLIASTRO_SKIP_NOTEBOOKS`. How does that sound?

Sounds good. It would be something like below?

```
 if os.environ.get('READTHEDOCS') or os.environ.get('POLIASTRO_SKIP_NOTEBOOKS'): 
     nbsphinx_execute = 'never' 
 else: 
     nbsphinx_execute = 'always' 
```
If so, the contributing section can also have a line stating this possibility (instructions to add POLIASTRO_SKIP_NOTEBOOKS to the user env vars) if building is taking too long (here it is stuck on the examples at 91% for some good 10 minutes).

**Comment by astrojuanlu** [comment]
> Sounds good. It would be something like below?

Without the `READTHEDOCS` part, we are now running notebooks in RTD as well.

> If so, the contributing section can also have a line stating this possibility (instructions to add POLIASTRO_SKIP_NOTEBOOKS to the user env vars) if building is taking too long (here it is stuck on the examples at 91% for some good 10 minutes).

Hmm interesting, which notebook is it processing? Some of the perturbation ones are quite slow.

**Comment by rafaellehmkuhl** [comment]
> > Sounds good. It would be something like below?
> 
> Without the `READTHEDOCS` part, we are now running notebooks in RTD as well.
> 
> > If so, the contributing section can also have a line stating this possibility (instructions to add POLIASTRO_SKIP_NOTEBOOKS to the user env vars) if building is taking too long (here it is stuck on the examples at 91% for some good 10 minutes).
> 
> Hmm interesting, which notebook is it processing? Some of the perturbation ones are quite slow.

Perfect, I will propose the PR.

About the notebook, I'm almost sure it was the "Using NEOS package".

**Comment by astrojuanlu** [comment]
> About the notebook, I'm almost sure it was the "Using NEOS package".

Oh, right! It needs to download the DASTCOM5 database the first time it's used... :sweat_smile:

**Comment by rafaellehmkuhl** [comment]
Oh, this was probably it. I'm struggling with my internet provider those last days :sweat_smile:
