### ISSUE TITLE
Tests Fail on ubuntu 16.04 pip3 install

### ISSUE THREAD

**Issue by rgreenblatt** [poliastro/poliastro#374]
**Raw Output:**

          python3 -c "import poliastro.testing; poliastro.testing.test()"
=============================================== test session starts ===============================================
platform linux -- Python 3.5.2, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /usr/local/lib/python3.5/dist-packages/poliastro, inifile:
collected 359 items / 2 errors                                                                                    

===================================================== ERRORS ======================================================
_______________________________ ERROR collecting tests/tests_neos/test_dastcom5.py ________________________________
/usr/local/lib/python3.5/dist-packages/poliastro/tests/tests_neos/test_dastcom5.py:7: in <module>
    from poliastro.neos import dastcom5
/usr/local/lib/python3.5/dist-packages/poliastro/neos/__init__.py:13: in <module>
    from poliastro.neos import neows, dastcom5
/usr/local/lib/python3.5/dist-packages/poliastro/neos/neows.py:6: in <module>
    from bs4 import BeautifulSoup
/usr/lib/python3/dist-packages/bs4/__init__.py:30: in <module>
    from .builder import builder_registry, ParserRejectedMarkup
/usr/lib/python3/dist-packages/bs4/builder/__init__.py:314: in <module>
    from . import _html5lib
/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py:70: in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
E   AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
______________________________ ERROR collecting tests/tests_neos/test_neos_neows.py _______________________________
/usr/local/lib/python3.5/dist-packages/poliastro/tests/tests_neos/test_neos_neows.py:8: in <module>
    from poliastro.neos import neows
/usr/local/lib/python3.5/dist-packages/poliastro/neos/__init__.py:13: in <module>
    from poliastro.neos import neows, dastcom5
/usr/local/lib/python3.5/dist-packages/poliastro/neos/neows.py:6: in <module>
    from bs4 import BeautifulSoup
/usr/lib/python3/dist-packages/bs4/__init__.py:30: in <module>
    from .builder import builder_registry, ParserRejectedMarkup
/usr/lib/python3/dist-packages/bs4/builder/__init__.py:314: in <module>
    from . import _html5lib
/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py:70: in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
E   AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
================================================ warnings summary =================================================
None
  could not create cache path /usr/local/lib/python3.5/dist-packages/poliastro/.pytest_cache/v/cache/nodeids
  could not create cache path /usr/local/lib/python3.5/dist-packages/poliastro/.pytest_cache/v/cache/lastfailed

-- Docs: http://doc.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================= 2 warnings, 2 error in 2.39 seconds =======================================

**Install List**

       pip3 list
Package                       Version               
----------------------------- ----------------------
apturl                        0.5.2                 
astropy                       3.0.2                 
attrs                         18.1.0                
beautifulsoup4                4.4.1                 
bleach                        2.1.3                 
blinker                       1.3                   
Brlapi                        0.6.4                 
CALLHORIZONS                  1.0.12                
chardet                       2.3.0                 
checkbox-support              0.22                  
command-not-found             0.3                   
cryptography                  1.2.3                 
cycler                        0.10.0                
decorator                     4.2.1                 
defer                         1.0.6                 
entrypoints                   0.2.3                 
feedparser                    5.1.3                 
guacamole                     0.9.2                 
h5py                          2.7.1                 
html5lib                      1.0.1                 
httplib2                      0.9.1                 
idna                          2.0                   
ipykernel                     4.8.2                 
ipython                       6.2.1                 
ipython-genutils              0.2.0                 
ipywidgets                    7.2.0                 
jedi                          0.11.1                
Jinja2                        2.8                   
jplephem                      2.7                   
jsonschema                    2.6.0                 
jupyter                       1.0.0                 
jupyter-client                5.2.3                 
jupyter-console               5.2.0                 
jupyter-core                  4.4.0                 
kazam                         1.4.5                 
kiwisolver                    1.0.1                 
language-selector             0.1                   
llvmlite                      0.23.0                
louis                         2.6.4                 
lxml                          3.5.0                 
Mako                          1.0.3                 
MarkupSafe                    0.23                  
matplotlib                    2.2.0                 
mistune                       0.8.3                 
more-itertools                4.1.0                 
nbconvert                     5.3.1                 
nbformat                      4.4.0                 
notebook                      5.4.1                 
numba                         0.38.0                
numpy                         1.14.0                
oauthlib                      1.0.3                 
onboard                       1.2.0                 
padme                         1.1.1                 
pandas                        0.22.0                
pandocfilters                 1.4.2                 
parso                         0.1.1                 
pexpect                       4.0.1                 
pickleshare                   0.7.4                 
Pillow                        3.1.2                 
pip                           10.0.1                
plainbox                      0.25                  
plotly                        2.4.1                 
pluggy                        0.6.0                 
poliastro                     0.9.1                 
prompt-toolkit                1.0.15                
ptyprocess                    0.5                   
py                            1.5.3                 
pyasn1                        0.1.9                 
pycups                        1.9.73                
pycurl                        7.43.0                
Pygments                      2.2.0                 
pygobject                     3.20.0                
PyJWT                         1.3.0                 
pyparsing                     2.0.3                 
pytest                        3.5.1                 
python-apt                    1.1.0b1+ubuntu0.16.4.1
python-dateutil               2.6.1                 
python-debian                 0.1.27                
python-systemd                231                   
pytz                          2018.3                
pyxdg                         0.25                  
pyzmq                         17.0.0                
qtconsole                     4.3.1                 
reportlab                     3.3.0                 
requests                      2.9.1                 
scipy                         1.0.0                 
screen-resolution-extra       0.0.0                 
Send2Trash                    1.5.0                 
sessioninstaller              0.0.0                 
setuptools                    20.7.0                
simplegeneric                 0.8.1                 
six                           1.10.0                
ssh-import-id                 5.5                   
system-service                0.3                   
terminado                     0.8.1                 
testpath                      0.3.1                 
tornado                       5.0.2                 
traitlets                     4.3.2                 
ubuntu-drivers-common         0.0.0                 
ufw                           0.35                  
unattended-upgrades           0.1                   
unity-scope-calculator        0.1                   
unity-scope-chromiumbookmarks 0.1                   
unity-scope-colourlovers      0.1                   
unity-scope-devhelp           0.1                   
unity-scope-firefoxbookmarks  0.1                   
unity-scope-gdrive            0.7                   
unity-scope-manpages          0.1                   
unity-scope-openclipart       0.1                   
unity-scope-texdoc            0.1                   
unity-scope-tomboy            0.1                   
unity-scope-virtualbox        0.1                   
unity-scope-yelp              0.1                   
unity-scope-zotero            0.1                   
urllib3                       1.13.1                
usb-creator                   0.3.0                 
wcwidth                       0.1.7                 
webencodings                  0.5.1                 
wheel                         0.29.0                
widgetsnbextension            3.2.0                 
xdiagnose                     3.8.4.1               
xkit                          0.0.0                 
XlsxWriter                    0.7.3

**Comment by Juanlu001** [comment]
Hi @rgreenblatt, thanks for the bug report! It seems that we don't set a minimum version for beautifulsoup4 and that old versions do not work with recent html5lib:

https://bugs.launchpad.net/beautifulsoup/+bug/1603299

Can you help us fixing this issue? Please try upgrading beautifulsoup4 to 4.5.3, see if it works, then if not try upgrading to 4.6.0.

Also, I suspect that you used `sudo pip install poliastro`, is that correct? If that's the case, I encourage you to learn about conda environments or venv, after we fix this problem:

* https://conda.io
* https://docs.python.org/3/library/venv.html

**Comment by Juanlu001** [comment]
Relevant: https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/view/head:/NEWS.txt

**Comment by Juanlu001** [comment]
I just updated the version myself - please try upgrading poliastro (or uninstalling & installing again) and don't hesitate to comment if the problem persists.
