### ISSUE TITLE
exception in "Propagation using Cowell's formulation.ipynb" example

### ISSUE THREAD

**Issue by enritoomey** [poliastro/poliastro#377]
In cell 10 of  docs/source/examples/Propagation using Cowell's formulation.ipynb example, when integrate method of scipy ode module is called,  the follwing exeption ocurs:
  
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-10-b6cb24b30f44> in <module>()
     10 
     11 while rr.successful() and rr.t + dt < t[-1]:
---> 12     rr.integrate(rr.t + dt)
     13     res[ii] = rr.y
     14     ii += 1

~/pyvenvs/poliastro/lib/python3.5/site-packages/scipy/integrate/_ode.py in integrate(self, t, step, relax)
    430             self._y, self.t = mth(self.f, self.jac or (lambda: None),
    431                                   self._y, self.t, t,
--> 432                                   self.f_params, self.jac_params)
    433         except SystemError:
    434             # f2py issue with tuple returns, see ticket 1187.

~/pyvenvs/poliastro/lib/python3.5/site-packages/scipy/integrate/_ode.py in run(self, f, jac, y0, t0, t1, f_params, jac_params)
   1170     def run(self, f, jac, y0, t0, t1, f_params, jac_params):
   1171         x, y, iwork, istate = self.runner(*((f, t0, y0, t1) +
-> 1172                                           tuple(self.call_args) + (f_params,)))
   1173         self.istate = istate
   1174         if istate < 0:

error: failed in processing argument list for call-back fcn.

This is not the only exception I encountered when running the notebook. Also, in cell 13 of same notebook, the following exception occurs.

thrust
0.10

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/pyvenvs/poliastro/lib/python3.5/site-packages/ipywidgets/widgets/interaction.py in update(self, *args)
    249                     value = widget.get_interact_value()
    250                     self.kwargs[widget._kwarg] = value
--> 251                 self.result = self.f(**self.kwargs)
    252                 show_inline_matplotlib_plots()
    253                 if self.auto_display and self.result is not None:

<ipython-input-12-9f1061196c69> in plot_iss(thrust, mass)
     17     r, v = r0, v0
     18     for ii in range(1, len(t)):
---> 19         r, v = cowell(k, r, v, t[ii] - t[ii - 1], ad=ad)
     20         x, y, z = r
     21         vx, vy, vz = v

TypeError: cowell() takes from 2 to 3 positional arguments but 4 positional arguments (and 1 keyword-only argument) were given

<function __main__.plot_iss(thrust=0.1, mass=2000.0)>

I believe both exceptions are not related, but as they belong to the same example, I condense them in the same issue.

`conda info -a`
Not installed with conda, but using python3.5, pip10.0.1, a virtualenv, debian 8. Yes, I know, installation guide says to use conda, but I wanted to avoid installing it.

`python -c "import poliastro.testing; poliastro.testing.test()"`
===================================== test session starts ======================================
platform linux -- Python 3.5.2, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/aocs, inifile:
collected 380 items                                                                            

../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_bodies.py ..... [  1%]
.                                                                                        [  1%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_coordinates.py . [  1%]
..                                                                                       [  2%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_hyper.py ...... [  3%]
.....                                                                                    [  5%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_iod.py ........ [  7%]
.                                                                                        [  7%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_jit.py ...      [  8%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_maneuver.py ... [  9%]
...                                                                                      [ 10%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_patched_conics.py . [ 10%]
...                                                                                      [ 11%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_plotting.py ... [ 11%]
......                                                                                   [ 13%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_plotting2d.py . [ 13%]
.......                                                                                  [ 15%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_plotting3d.py . [ 15%]
........                                                                                 [ 17%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_stumpff.py ...  [ 18%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_twobody.py ..   [ 19%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/test_util.py ....... [ 21%]
                                                                                         [ 21%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/tests_neos/test_dastcom5.py . [ 21%]
........                                                                                 [ 23%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/tests_neos/test_neos_neows.py . [ 23%]
.....                                                                                    [ 25%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/tests_twobody/test_angles.py . [ 25%]
........................................................................................ [ 48%]
........................................................................................ [ 71%]
..............................                                                           [ 79%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/tests_twobody/test_decorators.py . [ 79%]
.                                                                                        [ 80%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/tests_twobody/test_orbit.py . [ 80%]
....................                                                                     [ 85%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/tests_twobody/test_perturbations.py . [ 85%]
...                                                                                      [ 86%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/tests_twobody/test_propagation.py . [ 86%]
............xs...                                                                        [ 91%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/tests_twobody/test_sample.py . [ 91%]
.....................X                                                                   [ 97%]
../../pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/tests_twobody/test_states.py . [ 97%]
.........                                                                                [100%]

======================================= warnings summary =======================================
pyvenvs/poliastro/lib/python3.5/site-packages/poliastro/tests/tests_twobody/test_propagation.py::test_long_propagations_kepler_agrees_mean_motion
  /home/aocs/pyvenvs/poliastro/lib/python3.5/site-packages/astropy/_erfa/core.py:118: ErfaWarning:
  
  ERFA function "taiutc" yielded 1 of "dubious year (Note 4)"
  

-- Docs: http://doc.pytest.org/en/latest/warnings.html
=========== 377 passed, 1 skipped, 1 xfailed, 1 xpassed, 1 warnings in 88.10 seconds ===========

`pip freeze | grep astropy`
astropy==3.0.2
`pip freeze | grep poliastro`
poliastro==0.10.dev0

🎯 **Goal**
I wanted to use poliastro to do some low thrust calculation, and this examples seems the right one.

**Comment by Juanlu001** [comment]
Thanks @enritoomey! Working on it in #378

**Comment by Juanlu001** [comment]
The Continuous Integration didn't show any errors:

https://circleci.com/gh/poliastro/poliastro/3

Will try to reproduce locally.

**Comment by Juanlu001** [comment]
@enritoomey I just checked that the `plot_iss` function is no longer in that notebook, and the same goes to the explicit `while rr.successful() and rr.t + dt < t[-1]:` code. I suspect you're using an old version of the notebook, perhaps the one that was shipped with 0.8.0:

http://docs.poliastro.space/en/v0.8.0/examples/Propagation%20using%20Cowell's%20formulation.html

Can you please try with the most recent one?

http://docs.poliastro.space/en/latest/examples/Propagation%20using%20Cowell's%20formulation.html

**Comment by enritoomey** [comment]
Sorry for the delay, I just check the notebook with lastest version (what is currently in master, last commit being 7f675d76da413618f3bcc25317de750d74ea667e) and it works perfectly. I would say the issue can be close.

**Comment by Juanlu001** [comment]
Thanks a lot @enritoomey! Feel free to ping me if you have more questions :)
