### ISSUE TITLE
AstroPy installed successfully using pip, but tests fail. 

### ISSUE THREAD

**Issue by lghizoni** [poliastro/poliastro#384]
Hello,

I tried installing Poliastro in Ubuntu 16.04. I followed the steps in the website and finally tried the tests, from the following command:

> python -c "import poliastro.testing; poliastro.testing.test()"

Then I get, after a lot of errors, the following: 

======= 3 failed, 30 passed, 1 pytest-warnings, 9 error in 2.99 seconds ========

Can someone please help on this?

Thank you very much in advance.

**Comment by Juanlu001** [comment]
Hi @lghizoni! Thank you very much for your interest in poliastro. I would need you to send some extra information to help you with the problem: in particular the full output of the test failures and the output of `pip freeze | grep astropy` and `pip freeze | grep poliastro`.

Regards,

**Comment by lghizoni** [comment]
Hello,

Thanks a lot for the reply!

Here are the requested info:

$ pip freeze | grep astropy
> astropy==2.0.6

$ pip freeze | grep poliastro
> poliastro==0.6.0

And attached is the output of:

$ python -c "import poliastro.testing; poliastro.testing.test()"

[Poliastro_Test.txt](https://github.com/poliastro/poliastro/files/2089420/Poliastro_Test.txt)

Thanks again :-)

/Leonardo.

**Comment by Juanlu001** [comment]
Hi @lghizoni! You're more than welcome :)

I now see that you are using Python 2. [poliastro 0.5.0 dropped support for Python 2](http://docs.poliastro.space/en/latest/changelog.html#id18), so I guess that old versions of pip do not recognize this issue. It's a known problem, and I'm tracking it in https://github.com/poliastro/poliastro/issues/298.

At the moment, you have three options:

1) If you can create a Python 3 environment, you should be able to use any version of poliastro.
2) If you're stuck with Python 2 and don't mind using old poliastro versions, you can do `pip install "poliastro<0.5"` and it should work (and if something does not work, I'll be glad to help).
3) If you're stuck with Python 2 and need to use recent versions and have some budget, we can discuss by email :wink: 

Looking forward to your response! Also, may I ask what are you interested in using poliastro for? We do have a roadmap but we prioritize tasks depending on user input, so your feedback is very welcome.

**Comment by Juanlu001** [comment]
Closing this issue, as the Python 2 problem is being tracked somewhere else already. Feel free to reach out for any questions!
