### ISSUE TITLE
Sun Incorrectly plotted in plot_solar_system

### ISSUE THREAD

**Issue by shreyasbapat** [poliastro/poliastro#385]
The radius of the plotted sun exceeds the radii of some orbits of inner planets. 
🐞 **Problem**

See this figure:
![screenshot from 2018-06-11 17-23-59](https://user-images.githubusercontent.com/24257914/41230207-8c8137ee-6d9c-11e8-8513-bdba9ed660ab.png)

🖥 **Please paste the output of following commands**

`conda info -a`

`python -c "import poliastro.testing; poliastro.testing.test()"`

`pip freeze | grep astropy`

`pip freeze | grep poliastro`

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Thanks @shreyasbapat! This must be a problem in the method that redraws the attractor, or the minimum radius. Do you want to try fixing it?

**Comment by shreyasbapat** [comment]
Yeah Sure! I will try to fix this.

**Comment by Juanlu001** [comment]
Closed in #387.
