### ISSUE TITLE
Adapt to Plotly 3.0

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#397]
Plotly 3.0 is about to be released and it has a ton of interesting things! :tada: https://medium.com/@plotlygraphs/introducing-plotly-py-3-0-0-7bb1333f69c6

(for the moment, as explained in the installation instructions, only a release candidate is available)

In particular:

* > Just like every other object in Jupyter. plotly.offline.init_notebook_mode and plotly.offline.iplot are no longer necessary.
  - In fact, I just tried and it just works!
* A new `FigureWidget` class has been introduced, which allows for interactivity, animations...
  - Anyhow we should focus on the `Figure` class (we're implicitly using it in the form of a dictionary) because it's easier to share and persist in the notebook.
  - We should probably make the `OrbitPlotter` classes more flexible and don't hardcode a particular type of object, thus allowing the user to create a `Figure` or a `FigureWidget`
* New imperative functions, more similar to how matplotlib works
  - These might make figure updates easier
* Static image export
  - This will require installing node anyway, so for easy, publication-quality static plots we should still offer a matplotlib backend, see #338 

There's a work in progress migration guide:

https://github.com/plotly/plotly.py/blob/ipyplotly_integration/migration-guide.md

This release is going to be huge, so I propose we just add `plotly>=3.0.0` when it's on PyPI and start working from there.

**Comment by Juanlu001** [comment]
As a side comment, I think this will enable a lot of interesting things:

* Animations! @aeronau perhaps you will want to take a look :wink: 
* Better workflow! We will no longer need the `from plotly.offline import init_notebook_mode; init_notebook_mode(connected=True)` part, therefore not making Plotly explicit

(We would have to check whether #281 would be fixed)

Now that the world is moving towards Jupyter Lab, we should make sure that:

* poliastro works nicely for early Jupyter Lab adopters (see #337),
* poliastro keeps working in Jupyter Notebook, which is going to be around for years, and
* poliastro is still useful in non interactive workflows, including static plotting generation

**Comment by shreyasbapat** [comment]
So, my vague question, what do we start with? Should we start moving to Plotly 3.0 Pre releases?

**Comment by Juanlu001** [comment]
I suggest that we start by re-running all the 3D notebooks using Plotly 3.0 RC removing `from plotly.offline import init_notebook_mode; init_notebook_mode(connected=True)` and adding a warning at the top stating that for older versions it was needed, and that 3.0 is not stable yet. We should pay special attention to this: https://github.com/plotly/plotly.py/blob/ipyplotly_integration/migration-guide.md#breaking-changes

**Comment by shreyasbapat** [comment]
Okay!

**Comment by Juanlu001** [comment]
Incrementing the plotly version in setup.py is not necessary at this moment (and I would prefer to wait until a stable version has been released). It's enough that you rerun the notebooks with the latest RC and also that you make sure that the 3D plots show in the documentation:

* http://docs.poliastro.space/en/latest/examples/Going%20to%20Mars%20with%20Python%20using%20poliastro.html
* http://docs.poliastro.space/en/latest/examples/Visualizing%20the%20SpaceX%20Tesla%20Roadster%20trip%20to%20Mars.html
* ...etc

Also, remember to remove the `init_notebook_mode` part and to add a warning.

**Comment by Juanlu001** [comment]
Plotly 3.0 has been just merged to master:

https://github.com/plotly/plotly.py/blob/dbe8ad/plotly/version.py#L1

A public PyPI release is a matter of days.

**Comment by Juanlu001** [comment]
Plotly 3.0 is out:

https://pypi.org/project/plotly/3.0.0/

Time to upgrade!!!!1!

**Comment by shreyasbapat** [comment]
Yeah! But it will break OrbitPlotter2D. We will have to fix that first? Right?

**Comment by Juanlu001** [comment]
If Plotly 3.0 breaks poliastro, we have to fix poliastro first, yes ):

**Comment by shreyasbapat** [comment]
Pull Request Incoming ! (In some time obviously) xD

**Comment by Juanlu001** [comment]
In Jupyter Lab it doesn't:

![screenshot-2018-7-5 jupyterlab](https://user-images.githubusercontent.com/316517/42343909-e4702b66-809a-11e8-892c-21d7da25b68c.png)

On the other hand, I've been playing with `Figure` and `FigureWidget` like this:

```diff
diff --git a/src/poliastro/plotting.py b/src/poliastro/plotting.py
index ff25fea..2188146 100644
--- a/src/poliastro/plotting.py
+++ b/src/poliastro/plotting.py
@@ -244,7 +244,8 @@ class _BaseOrbitPlotter:
 
     @property
     def figure(self):
-        return dict(
+        from plotly.graph_objs import Figure, FigureWidget
+        return Figure(
             data=self._data + [self._attractor_data],
             layout=self._layout,
         )
```

And I suspect that `Figure` is now broken in the classic notebook, and that it only works in Jupyter Lab. Investigating.

**Comment by shreyasbapat** [comment]
Oh! That's fine. So, we may have to instruct the user to use Jupyter Lab for using poliastro. And put up a warning to include that patch of lines for Jupyter Notebook

**Comment by Juanlu001** [comment]
> And I suspect that Figure is now broken in the classic notebook, and that it only works in Jupyter Lab. Investigating.

Not the case, but something is not working with poliastro figures.

**Comment by Juanlu001** [comment]
Never mind, I think I was having some temporary connectivity issues. Everything is working well :+1:
