### ISSUE TITLE
Make propagate fast again

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#408]
(Pun intended)

According to our new shiny benchmarks, we introduced three performance regressions in the default `Orbit.propagate` method, one of them considerably large:

![screenshot from 2018-07-16 09-24-17](https://user-images.githubusercontent.com/316517/42747074-0e18a766-88db-11e8-970b-4c71fd3ccfa0.png)

https://poliastro.github.io/poliastro-benchmarks/#regressions

The list of offending commits is there. The biggest regression comes from the introduction of the new `mean_motion` method by @nikita-astronaut, which couldn't be @jitted back then because we were using `scipy.optimize.newton`. I think we should hardcode a Newton iteration inside the `angles` functions and @jit all the thing, what do you think @nikita-astronaut?

**Comment by nikita-astronaut** [comment]
I agree) considering the fact that Newton method is really simple) Will do it during this week

**Comment by Juanlu001** [comment]
Some work was done in #409, but this gave me some fresh ideas, see #412. I think we can do better in the next release.

**Comment by Juanlu001** [comment]
This was actually fixed for 0.10.0 in #414. Closing!
