### ISSUE TITLE
Test Fails 6 Tests

### ISSUE THREAD

**Issue by tomdean1** [poliastro/poliastro#411]
[poliastro.txt](https://github.com/poliastro/poliastro/files/2204536/poliastro.txt)

🐞 **Problem**

🖥 **Please paste the output of following commands**

`conda info -a`

`python -c "import poliastro.testing; poliastro.testing.test()"`

`pip freeze | grep astropy`

`pip freeze | grep poliastro`

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Hi @tomdean1, thanks for the bug report! Latest version of poliastro is not compatible with Plotly 3.0. We have to release 0.9.2 to reflect this fact.

For the moment, you can wait for poliastro 0.10 (out tomorrow!) or `pip install "plotly<3"`.

**Comment by tomdean1** [comment]
I upgraded to 0.11.dev0, but, still have two errors
> python3 -c "import poliastro; print(poliastro.__version__)"
0.11.dev0
> python3 -c "import poliastro.testing; poliastro.testing.test()" > poliastro.txt
> tail -1 poliastro.txt 
 2 failed, 409 passed, 3 skipped, 5 xfailed, 1 xpassed, 1 warnings in 258.81 seconds 
The failures are import errors
> grep ImportError poliastro.txt | grep local
/usr/local/lib/python3.5/dist-packages/plotly/offline/offline.py:318: ImportError
/usr/local/lib/python3.5/dist-packages/plotly/offline/offline.py:318: ImportError

**Comment by Juanlu001** [comment]
Thanks! Those errors are already known https://github.com/poliastro/poliastro/issues/361 and we're not sure when do they happen, as I can't reproduce them locally. Anyway, these are failures of the tests themselves and not poliastro, so your installation is now correct.

**Comment by tomdean1** [comment]
The sequence of events
1.  python -c "import poliastro.testing; poliastro.testing.test()"
2.  Errors happened
3.  Install Jupyter and IPython
4. python -c "import poliastro.testing; poliastro.testing.test()"
5.  No Errors
The errors were caused by NOT having Jupyter and IPython.

**Comment by Juanlu001** [comment]
> The errors were caused by NOT having Jupyter and IPython.

Oh, that's extremely useful! We'll add this information to the original issue. Thanks for your help!
