### ISSUE TITLE
Perturbations incorrectly placed in documentation

### ISSUE THREAD

**Issue by tomdean1** [poliastro/poliastro#422]
[poliastro_error.txt](https://github.com/poliastro/poliastro/files/2225818/poliastro_error.txt)

🐞 **Problem**

🖥 **Please paste the output of following commands**

`conda info -a`
I do not use conda
`python -c "import poliastro.testing; poliastro.testing.test()"`
Does not show messages
`pip freeze | grep astropy`
astropy==3.0.3

`pip freeze | grep poliastro`
poliastro==0.11.dev0

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
This will be the correct way to import perturbations:
`from poliastro.core.perturbations import J2_perturbation`

**Comment by Juanlu001** [comment]
This is a documentation bug, because I think the User Guide has the old perturbation imports.

Regarding the style thing, it's a warning (not an error) so I would not worry.

**Comment by Juanlu001** [comment]
Thanks @tomdean1 for reporting!

**Comment by Juanlu001** [comment]
I'm labeling this as "help wanted", so pull requests welcome. It's kind of important though, so if nobody does, I'll fix it next week.

**Comment by Juanlu001** [comment]
a) I didn't fix it "the following week" and b) I duplicated this at #436, so I will rename this and close that.

**Comment by Juanlu001** [comment]
Thanks @shreyasbapat!
