### ISSUE TITLE
Automate versioning

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#424]
🐞 **Problem**

Making a release involves lots of steps, some of which [are manual](https://github.com/poliastro/poliastro/wiki/HOWTO-Release). One of these steps is the correct version bumping in all the required places. Some of them could be automatic.

Also, when someone installs poliastro from git, it's not clear which version it's using.

🎯 **Goal**

Make the version bumping, and hence the release process, less error prone, as well as development installations and error reporting.

💡 **Possible solutions**

Use [versioneer](https://github.com/warner/python-versioneer/).

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Notice that development releases work a bit differently. For instance, we wouldn't have a permanent `0.12.dev0` release right after `0.11` anymore, but `0.11+...` (referring to the previous version). This kind of makes sense because automatic systems don't really now what goes next.

**Comment by Juanlu001** [comment]
For using the version in Sphinx, see https://github.com/warner/python-versioneer/issues/185.

**Comment by Juanlu001** [comment]
versioneer does not work with trunk-based development:

https://github.com/warner/python-versioneer/issues/159

so we can explore other options, like [setuptools_scm](https://github.com/pypa/setuptools_scm), but not for this release.

**Comment by Juanlu001** [comment]
@shreyasbapat Maybe! Does it work with trunk-based development?

![Trunk-based development](https://uploads.toptal.io/blog/image/124319/toptal-blog-image-1507018418276-5236f6ebfd31c78b442562d4d202763c.png)

**Comment by shreyasbapat** [comment]
Not sure about that. Will check and let you know. 
If [this](https://github.com/pypa/setuptools_scm) suppports trunk-based development, I can go with that!

**Comment by Juanlu001** [comment]
The problem I have with setuptools_scm is... setuptools. In an ideal world, we would migrate to something like [flit](https://github.com/takluyver/flit) sooner or later (perhaps when pip shows proper PEP 517 support and flit supports `src/` directories, or someone forks it), so I'd prefer not to rely on that. On the other hand, if all the versioning hacks out there depend on setuptools, then there's really no point in trying that now.

**Comment by Juanlu001** [comment]
I don't think there are satisfying tools that support trunk-based development at the moment, so we will have to keep manually bumping the version number. Closing.
