### ISSUE TITLE
poliastro fails 3 self tests after install to a virtualenv

### ISSUE THREAD

**Issue by PhelixPhoenix** [poliastro/poliastro#426]
poliastro fails 3 self tests after install to a virtualenv with all the prerequisites loaded

🐞 **Problem**

🖥 **Please paste the output of following commands**

`conda info -a`
bash: conda: command not found

`python -c "import poliastro.testing; poliastro.testing.test()"`

====================================== test session starts =======================================
platform linux -- Python 3.6.5, pytest-3.6.3, py-1.5.4, pluggy-0.6.0
rootdir: /home/pphoenix, inifile:
collected 393 items / 3 errors                                                                   

============================================= ERRORS =============================================
 ERROR collecting Environments/Astro/lib/python3.6/site-packages/poliastro/tests/test_plotting.py 
ImportError while importing test module '/home/pphoenix/Environments/Astro/lib/python3.6/site-packages/poliastro/tests/test_plotting.py'.                                                           
Hint: make sure your test modules/packages have valid Python names.                               
Traceback:                                                                                        
Environments/Astro/lib/python3.6/site-packages/poliastro/tests/test_plotting.py:5: in <module>    
    import matplotlib.pyplot as plt                                                               
Environments/Astro/lib/python3.6/site-packages/matplotlib/pyplot.py:115: in <module>              
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()                  
Environments/Astro/lib/python3.6/site-packages/matplotlib/backends/__init__.py:62: in pylab_setup 
    [backend_name], 0)                                                                            
Environments/Astro/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py:4: in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.                             
Environments/Astro/lib/python3.6/site-packages/matplotlib/backends/tkagg.py:5: in <module>        
    from six.moves import tkinter as Tk                                                           
Environments/Astro/lib/python3.6/site-packages/six.py:92: in __get__                              
    result = self._resolve()                                                                      
Environments/Astro/lib/python3.6/site-packages/six.py:115: in _resolve                            
    return _import_module(self.mod)                                                               
Environments/Astro/lib/python3.6/site-packages/six.py:82: in _import_module                       
    __import__(name)                                                                              
E   ModuleNotFoundError: No module named 'tkinter'                                                
 ERROR collecting Environments/Astro/lib/python3.6/site-packages/poliastro/tests/test_plotting2d.py 
ImportError while importing test module '/home/pphoenix/Environments/Astro/lib/python3.6/site-packages/poliastro/tests/test_plotting2d.py'.                                                         
Hint: make sure your test modules/packages have valid Python names.                               
Traceback:                                                                                        
Environments/Astro/lib/python3.6/site-packages/poliastro/tests/test_plotting2d.py:10: in <module> 
    from poliastro.plotting import OrbitPlotter2D                                                 
Environments/Astro/lib/python3.6/site-packages/poliastro/plotting.py:12: in <module>              
    import matplotlib.pyplot as plt                                                               
Environments/Astro/lib/python3.6/site-packages/matplotlib/pyplot.py:115: in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
Environments/Astro/lib/python3.6/site-packages/matplotlib/backends/__init__.py:62: in pylab_setup
    [backend_name], 0)
Environments/Astro/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py:4: in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
Environments/Astro/lib/python3.6/site-packages/matplotlib/backends/tkagg.py:5: in <module>
    from six.moves import tkinter as Tk
Environments/Astro/lib/python3.6/site-packages/six.py:92: in __get__
    result = self._resolve()
Environments/Astro/lib/python3.6/site-packages/six.py:115: in _resolve
    return _import_module(self.mod)
Environments/Astro/lib/python3.6/site-packages/six.py:82: in _import_module
    __import__(name)
E   ModuleNotFoundError: No module named 'tkinter'
 ERROR collecting Environments/Astro/lib/python3.6/site-packages/poliastro/tests/test_plotting3d.py 
ImportError while importing test module '/home/pphoenix/Environments/Astro/lib/python3.6/site-packages/poliastro/tests/test_plotting3d.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
Environments/Astro/lib/python3.6/site-packages/poliastro/tests/test_plotting3d.py:10: in <module>
    from poliastro.plotting import OrbitPlotter3D
Environments/Astro/lib/python3.6/site-packages/poliastro/plotting.py:12: in <module>
    import matplotlib.pyplot as plt
Environments/Astro/lib/python3.6/site-packages/matplotlib/pyplot.py:115: in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
Environments/Astro/lib/python3.6/site-packages/matplotlib/backends/__init__.py:62: in pylab_setup
    [backend_name], 0)
Environments/Astro/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py:4: in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
Environments/Astro/lib/python3.6/site-packages/matplotlib/backends/tkagg.py:5: in <module>
    from six.moves import tkinter as Tk
Environments/Astro/lib/python3.6/site-packages/six.py:92: in __get__
    result = self._resolve()
Environments/Astro/lib/python3.6/site-packages/six.py:115: in _resolve
    return _import_module(self.mod)
Environments/Astro/lib/python3.6/site-packages/six.py:82: in _import_module
    __import__(name)
E   ModuleNotFoundError: No module named 'tkinter'
!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================== 3 error in 3.03 seconds =====================================

`pip freeze | grep astropy`

astropy==3.0.3

`pip freeze | grep poliastro`

poliastro==0.10.0

🎯 **Goal**

Reporting self test errors as per the install documentation.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Hey! I guess you fixed the issue by installing tkinter in your operative system :) Thanks for your interest anyway and don't hesitate to open new issues if you find more problems.

**Comment by PhelixPhoenix** [comment]
Yes!

Other errors showed up on the next test for iplot so I’m working through those now.


[cid:image001.png@01D4259E.8E7D8C00]
Stefan McIntyre  Consulting Engineer
www.gci.com/business/nw<http://www.gci.com/business/nw>  |  405.833.1900

**Comment by Juanlu001** [comment]
Perhaps these? https://github.com/poliastro/poliastro/issues/361
