### ISSUE TITLE
Allow the user to define an Orbit in any reference frame

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#434]
🐞 **Problem**

As has been pointed out many times, it's unclear which reference frame is poliastro using for `Orbit` objects, and the answer is that it's implicitly assuming an inertial reference frame centered in the `attractor` (otherwise `propagate` wouldn't work). 

🎯 **Goal**

The use of reference frames in poliastro should be more explicit and configurable. Reference frame transformations are needed all the time, and now poliastro does not make things easy on this front.

💡 **Possible solutions**

See https://github.com/poliastro/poliastro/wiki/Orbits-and-reference-frames for further explanation and ideas.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Perhaps I don't really need to define all the frames before I implement this. It's a boring task that's mentally blocking me from making progress. So I will probably proceed like this:

1. Add the ability to use reference frames labeled as "experimental" in 0.11,
2. Add the rest of the frames and consolidate the API in 0.12

Also notice that I already requested in Astropy to have these kind of frames, see https://github.com/astropy/astropy/issues/5898.

**Comment by Juanlu001** [comment]
On second thought, not adding the frames might be more difficult than adding them.

**Comment by Juanlu001** [comment]
> I tried to implement frames parallel to ICRS centered in other bodies, but I was stopped by #7770.

**Comment by Juanlu001** [comment]
Although we started working on this in #439, the real API for defining an `Orbit` in _any_ frame will have to wait for the next release. At least, the question "which frame does this use" should be settled.

**Comment by hrishikeshgoyal** [comment]
Hi.. I am interested in looking into this.

**Comment by Juanlu001** [comment]
Hi @hrishikeshgoyal, thanks for your interest! All the information is in the wiki and the issue itself. Where do you plan to start?

**Comment by hrishikeshgoyal** [comment]
Hi @Juanlu001, I am new to astrodynamics.. so first exploring some related concepts.. Is there a prescribed book, blog and/or website which can help me in wrap up this?

**Comment by shreyasbapat** [comment]
You can follow a book titled "Orbital Mechanics for Engineering Students"

**Comment by Juanlu001** [comment]
> For example if orbital velocity of a satellite is equal to rotational velocity of the Earth(for simplicity, let attractor is Earth), then in ECEF reference frame orbit will be just a point(as per my current understanding). And there are a plenty of other similar cases.

That's exactly the case of the geostationary orbits you introduced in #524 :wink: 

There is no "orbit" in the sense that, in a non-inertial frame, it would not be a Keplerian orbit (a conic section), but stuff would revolve around the Earth no matter what reference frame we use to look at it.

What we want to achieve is to simplify the use case presented in https://github.com/poliastro/poliastro/issues/429, that is: make it a one-liner to create an `Orbit` object from data (most likely cartesian vectors) that is _not_ in an inertial reference frame, or even a frame centered in the attractor we are looking at (think of an observer pointing a telescope or an antenna to some satellite).

The classical orbit elements are "just" geometric parameters, and therefore they should also be computed in an inertial frame, using proper conversion code.

**Comment by hrishikeshgoyal** [comment]
> What we want to achieve is to simplify the use case presented in #429, that is: make it a one-liner to create an Orbit object from data (most likely cartesian vectors) that is not in an inertial reference frame, or even a frame centered in the attractor we are looking at (think of an observer pointing a telescope or an antenna to some satellite).

The way I can think of right now to solve this is that first transform the given parameters into an inertial reference frame centred at attractor and then create the orbit as usual and also always use that frame to plot the orbit(irrespective of what frame user has used).

**Comment by Juanlu001** [comment]
Aswering to @hrishikeshgoyal comment [here](https://github.com/poliastro/poliastro/pull/439#issuecomment-455647009):

> Does this make sense to attache a new reference frame to `Orbit` in
> addition to the existing `self._frame` that can act as a communicating
> frame?   For example if user needs to create an orbit using
> ephemerides given in some frame(say foo) other than the frame(say bar)
> parallel to ICRS centred at attractor and subsequently needs to call
> propagate. In that case following can be a sequence of steps to
> follow:   
> a. Take user inputs in foo   
> b. Transform inputs given in foo to bar   
> c. Create the orbit in the frame bar.   
> d. Perform all required operations in frame bar (e.g propagate).
> It might also require to transform (i.e. from foo to bar)
> the parameters passed to the operation.   
> e. Transform the output of the operations performed
> in the frame bar to foo.   
> f. Output the results in foo to user.

This would work, but I don't see the need of storing a second frame. I didn't think about this in depth yet, but wouldn't it be easier to retrieve the inertial frame on the fly when it's needed?

**Comment by hrishikeshgoyal** [comment]
hmm.. if I have understood this correctly.. Is that like self._frame is supposed to store the frame specified by the user and we don't need to store inertial frame centred at attractor?

**Comment by Juanlu001** [comment]
I don't see the need of storing two frames, but if you think it's better, then go ahead and let's discuss over the code.

**Comment by Juanlu001** [comment]
Moving this to 0.12, as @hrishikeshgoyal is already tackling it.

**Comment by Juanlu001** [comment]
Closed in #554!
