### ISSUE TITLE
Add DASTCOM5 README.txt to poliastro code

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#443]
Documentation about DASTCOM5 is scarce. At least it would be nice to have the README accessible, without having do download a huge zip.

**Comment by Juanlu001** [comment]
[README.txt](https://github.com/poliastro/poliastro/files/2349343/README.txt)

**Comment by shreyasbapat** [comment]
Where would you like it to be?

**Comment by Juanlu001** [comment]
In 'src/poliastro/neos/`, I would say!

**Comment by shreyasbapat** [comment]
I will change the format to ReStructured Text and create a PR

**Comment by Juanlu001** [comment]
No need to translate I think, I prefer to keep the original version in this
case. Anyway, let's wait for a decision on the astroquery side :)

On 24 Sep 2018 14:10, "Shreyas Bapat" <notifications@github.com> wrote:

I will change the format to ReStructured Text and create a PR

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/poliastro/poliastro/issues/443#issuecomment-423953215>,
or mute the thread

**Comment by Juanlu001** [comment]
Fixed in #466, thanks @shreyasbapat!
