### ISSUE TITLE
Unify plotting tests

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#448]
We now have a testing module for each `OrbitPlotter` class and lots of repeated tests and it's annoying. We should parametrize them somehow (see also #447). This can be done independently of #338.

**Comment by shreyasbapat** [comment]
@Juanlu001  Is this anywhere related to #481 ? Can I take this up?

**Comment by Juanlu001** [comment]
Sure, if #481 becomes a blocker, I'll close it and reopen when I'm ready.

**Comment by shreyasbapat** [comment]
So, we will have just one test script for all the OrbitPlotters or Plotly OrbitPlotters?

**Comment by Juanlu001** [comment]
On second thought, let's leave this one because I will try to do the plotting refactor over the winter holidays, and we might repeat work unnecessarily.
