### ISSUE TITLE
Planetary frames velocity transformations are untested

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#451]
I fixed a bug along the way, but there might be more.

**Comment by shreyasbapat** [comment]
Can you specify which module is?

**Comment by Juanlu001** [comment]
@shreyasbapat it's this one https://github.com/poliastro/poliastro/blob/master/src/poliastro/coordinates.py

**Comment by shreyasbapat** [comment]
Okay! On it!

**Comment by astrojuanlu** [comment]
This is now addressed in https://github.com/poliastro/validation/pull/24! Would be nice to have more unit tests in poliastro, but that's another story.
