### ISSUE TITLE
Test numpy.interp instead of scipy.interpolate.interp1d

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#456]
It's only used here

https://github.com/poliastro/poliastro/blob/d0314cb36f9b5f5ec0a786e4ed3d4f0d9465cd4e/src/poliastro/ephem.py#L2

One reason would be performance https://stackoverflow.com/a/32291305/554319, another would be to minimize the dependence with SciPy.

**Comment by hrishikeshgoyal** [comment]
@Juanlu001  I would like to get started with this as seems like it should not need much poliastro insights.

**Comment by Juanlu001** [comment]
All yours @hrishikeshgoyal! You have to bear in mind that this part of poliastro is probably not very well tested, so apart from the change itself (changing two lines of code) I would expect some sort of test as well :)

**Comment by hrishikeshgoyal** [comment]
Yes, absolutely.

**Comment by hrishikeshgoyal** [comment]
@Juanlu001  As per the `numpy.interp` [doc](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.interp.html), it returns **an array of interpolated values**. 

But we need a **callable function**(needed [here](https://github.com/poliastro/poliastro/blob/ee41c682fdb5ab20aa01c3c42ab946550071b886/src/poliastro/tests/tests_twobody/test_perturbations.py#L352) and next passing that to `cowell()` in line no. 361) which when called with an array of x coordinates, returns y interpolated values.

**Comment by hrishikeshgoyal** [comment]
Additionally, we need cubic interpolation(kind='cubic'), but numpy.interp doesn't seem to support that. 
https://github.com/poliastro/poliastro/blob/ee41c682fdb5ab20aa01c3c42ab946550071b886/src/poliastro/ephem.py#L32

**Comment by Juanlu001** [comment]
`np.intep` won't work, but perhaps `numpy.polynomial.polynomial` will. Perhaps @gorostuck wants to give it a try? :)

**Comment by Juanlu001** [comment]
Damn it, I did not realize `scipy.interpolate.interp1d` gives a cubic **spline**, and NumPy only has polynomials. There's no way to get rid of SciPy here unless we change the package in a more fundamental way, so I'm closing this issue.

**Comment by astrojuanlu** [comment]
Not reopening this yet but... Thinking about ephemeris interpolation again, see https://github.com/poliastro/poliastro/wiki/Orbit-interpolation

**Comment by astrojuanlu** [comment]
Arrived here while browsing old issues. Ended up adding sinc interpolation https://github.com/poliastro/poliastro/pull/882
