### ISSUE TITLE
Allow passing of plotly / iplot parameters into OrbitPlotter3D()

### ISSUE THREAD

**Issue by psychemedia** [poliastro/poliastro#460]
It would be useful to be able to pass `plotly iplot` function parameters when calling `OrbitPlotter3D()`:

```
#/via https://plot.ly/python/offline/

#Help on function iplot in module plotly.offline.offline:

iplot(figure_or_data,
      show_link=True,
      link_text='Export to plot.ly',
      validate=True,
      image=None, 
      filename='plot_image',
      image_width=800,
      image_height=600)
```

This would allow control over things like the display of the link to *plotly* (`show_link`), the image type used when grabbing and downloading a snapshot of the current orientation of a 3D plot (`image`) and the filename it is saved with (`filename`).

At the moment, no parameters are passed into `iplot()`.

From https://github.com/poliastro/poliastro/blob/master/src/poliastro/plotting.py:

```
def show(self, **layout_kwargs):
        """Shows the plot in the Notebook.
        """
        self._prepare_plot(**layout_kwargs)

        iplot(self.figure)
```

**Comment by psychemedia** [comment]
I could have a go... Not sure what the best route is there (I'm an amateur tinkerer rather than a professional developer!)

A clunky way within the `show()` function (so no side effects) would presumably be to pass in `**kwargs` that are valid arguments for `iplot()`? I think `iplot` throws an error if we pass unrecognised arguments to it so we'd need to trap for any that aren't in that set?

Learning something new to me today(!), maybe something along the lines of:

```
import inspect

def show(self, **layout_kwargs):
        """Shows the plot in the Notebook.
        """
        self._prepare_plot(**layout_kwargs)

        #Identify valid arguments for iplot
        _iplot_kwargs = inspect.getfullargspec(iplot).args
        #Limit iplot_kwargs to valid iplot args because unrecognised arguments throw an error
        iplot_kwargs = {k:v for k, v in layout_kwargs.items() if k in _iplot_kwargs}

        #Pass these args on to iplot
        iplot(self.figure, **iplot_kwargs)

**Comment by Juanlu001** [comment]
> I'm an amateur tinkerer rather than a professional developer!

We are all tinkerers here :)

Your second option is feasible. Other ideas that come to mind:

* Make the `_prepare_plot` method public, and use the `**kwargs` of `show` for the `iplot` call
* Make the `layout` property public so the user can do `plotter.layout.update(...)` and use the `**kwargs` of `show` for the `iplot` call
* Configure the `iplot` options when creating the `OrbitPlotter*D` (similar as done with `OrbitPlotter`) and keep the `show` method as it stands

What do you think

**Comment by psychemedia** [comment]
@Juanlu001 Re: options.

I'd considered allowing options in to `OrbitPlotter*D` but it feels to me that that's too early to commit to the `iplot`. It would mean the output parameters are required *before* you build up the plot, rather than just as you are about to plot it, and they are hanging around all the way through the plotting process? 

If `_prepare_plot()` was public then how would it work? Maybe rename it as `style_plot()`, becuase that feels more explicit?

```
def style_plot(self, **layout_kwargs):
        """Style the plot.
        """
        if layout_kwargs:
            self._layout.update(layout_kwargs)

def show(self, **iplot_kwargs):
        """Shows the plot in the Notebook.
              Optionally allows the iplot widget to be customised.
        """
        # If there are no orbits, draw only the attractor
        if not self._data:
            self._redraw_attractor()

        #Plot the figure
        iplot(self.figure, **iplot_kwargs)
#---
...
#and then the user does something like:
frame.style_plot(...) #optionally
frame.show(show_link=False)
...
```

That feels reasonably natural?


How would making the `layout` property public work? What commands would folk be running where? Maybe:

```
frame.layout.update(...)
frame.show(show_link=False)
```

This would require some checking for references to `_layout` elsewhere; for consistency, but then should `_layout` in other classes have to go public too? Maybe this has too many side-effects?

**Comment by Juanlu001** [comment]
Sorry, in my previous message I completely forgot about the very purpose of this issue (I added a clarification there). I agree with your suggestion :+1:

**Comment by Juanlu001** [comment]
I took an alternative route, which is passing a `Figure` or `FigureWidget` to the plotter and let the user customize what they want. Progress in #528.
