### ISSUE TITLE
Propagator kepler crashes when propagating a hyperbolic orbit 0 seconds

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#477]
_Comes from #474, by @TimothySHamilton_

There is an untested code path that would make the `kepler` propagator crash if the eccentricity is greater than 1 and the propagation time is 0:

https://github.com/poliastro/poliastro/blob/1f12764588adee6fb1bf45c625930be3312fa154/src/poliastro/core/propagation.py#L68-L71

This is similar to https://github.com/poliastro/poliastro/issues/328, but on a different level. It should be easy to fix, and requires us to add this code to `propagate`:

```python
if time_of_flight.value == 0:
    return orbit
```

We should strive to make this change for all the methods, as an efficiency measure.

**Comment by aarribas** [comment]
Since it's an easy fix, may I take care of it as an entry point to contribute to the project?

**Comment by Juanlu001** [comment]
Sure, go ahead! If you find any problems, just ask, here or in the chat. I
would expect a test if you are familiar with pytest, but if not we can
decide when you open a pull request.

On 24 Oct 2018 3:58 pm, "Andrés Arribas Flores" <notifications@github.com>
wrote:

Since it's an easy fix, may I take care of it as an entry point to
contribute to the project?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/poliastro/poliastro/issues/477#issuecomment-432668232>,
or mute the thread

**Comment by Juanlu001** [comment]
@aarribas and I forgot to say: thanks so much! :)

**Comment by aarribas** [comment]
I had in mind to include the test(s) too, of course.

**Comment by aarribas** [comment]
I noticed the function documentation comments are not consistent (Kepler function has none) whereas mean_motion has some. The parameters are also inconsistently commented. May I also improve on that.  Incidentally, I had a look at  other .py in /core and noticed that a lot of doc comments where removed when the functions where "jitted". Was this intented? I found them useful.

**Comment by Juanlu001** [comment]
@aarribas definitely - documentation is important to us, and if you noticed these inconsistencies we would be very happy if you fixed them as well (perhaps in separate commits though, so the review is easier). Also, we moved lots of functions to core in a rush, the day of the release, and at 3 AM local time, so I admit we probably missed lots of docstrings in the process.

**Comment by Juanlu001** [comment]
Fixed in #527
