### ISSUE TITLE
OrbitPlotter2D results are different than OrbitPlotter

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#483]
🐞 **Problem**

As per the title:

![screenshot_2018-11-02 talk](https://user-images.githubusercontent.com/316517/47895144-cdcc6880-de77-11e8-8775-e6d296c2b3a9.png)

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>
  
```bash
# Paste your output here:

```
</details>

* `python -c "import poliastro.testing; poliastro.testing.test()"`

<details>

```bash
# Paste your output here:

```
</details>

🎯 **Goal**

To be able to replace the matplotlib backend with the Plotly backend.

💡 **Possible solutions**

See if fixing #480 fixes this.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
I can confirm that it will be fixed on fixing #480 .
Pull Request incoming.
