### ISSUE TITLE
Plotly dark theme

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#490]
See:

https://medium.com/@plotlygraphs/introducing-plotly-py-theming-b644109ac9c7

![Dark theme](https://user-images.githubusercontent.com/316517/48229949-c510f080-e3a9-11e8-9ad3-7bdf33b6160c.png)

Also #389.

**Comment by shreyasbapat** [comment]
I will take this up after #481 is merged :)

**Comment by shreyasbapat** [comment]
Yes. We may want to pass the `dark=True` parameter to OrbitPlotter*D.

**Comment by Juanlu001** [comment]
Thats right @AntoniiaK! Would you like to share that code or even contribute it to poliastro?

**Comment by AntoniiaK** [comment]
I will be glad contribute to your project.

**Comment by Juanlu001** [comment]
@AntoniiaK awesome! Could you please send me an email (my address is in my GitHub profile) or ping me in the poliastro chat (https://riot.im/app/#/room/#poliastro:matrix.org) introducing yourself so I can lend you a hand with the first steps? :rocket:

**Comment by Juanlu001** [comment]
Good catch! Closing
