### ISSUE TITLE
Add multirevolution Lambert example

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#494]
(Follow up from https://github.com/poliastro/poliastro/issues/492#issuecomment-438826436)

I think the multirevolution capabilities of poliastro Lambert solution are not mentioned everywhere. We should add an example of that to the documentation (possibly after checking #348).

**Comment by IngenieroDeAviones** [comment]
I will try to add an example for this in the current pull request for the API Docs Update #491

**Comment by Juanlu001** [comment]
Beautifully crafted example available here https://docs.poliastro.space/en/latest/examples/Multirevolutions%20solution%20in%20Lamberts%20problem.html added in #725!
