### ISSUE TITLE
Use sphinx-gallery for the examples

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#501]
sphinx-gallery has some interesting features:

* It turns scripts into notebooks, reducing the burden in version control and helping maintainability
* It arranges thumbnails nicely
* It has some Binder support

We should look into migrating the current examples to using that.

**Comment by shreyasbapat** [comment]
Does sphinx gallery does not support plotly?
It's not clear in their documentation. 

> Sphinx-Gallery will not manage its dependencies when installing, thus you are required to install them manually. Our minimal dependencies are:
Sphinx
Matplotlib
Pillow

> Sphinx-Gallery has also support for packages like:
Seaborn
Mayavi

**Comment by Juanlu001** [comment]
> Does sphinx-gallery support plotly?

I don't know :)

https://github.com/sphinx-gallery/sphinx-gallery/issues?utf8=%E2%9C%93&q=plotly

If you are interested, maybe you can try.

> If it doesn't, is it like we move some of our examples to sphinx gallery and we don't move the others?

I prefer not to, to be honest. Either we move all of them, we add plotly support to sphinx-gallery, or we stay like this.

**Comment by Juanlu001** [comment]
On behalf of @shreyasbapat: https://github.com/sphinx-gallery/sphinx-gallery/issues/441

**Comment by Juanlu001** [comment]
Another option to consider is jupytext https://towardsdatascience.com/jupytext-1-0-highlights-a49dca9baa7b

cc @jorgepiloto

**Comment by Juanlu001** [comment]
Support for Plotly was added to sphinx-gallery, so this is again open for consideration.

**Comment by astrojuanlu** [comment]
Now nbsphinx will support thumbnails :) https://github.com/spatialaudio/nbsphinx/pull/392

**Comment by jorgepiloto** [comment]
We might consider closing this after #973 was merged :+1:

**Comment by astrojuanlu** [comment]
Yay! Closing!
