### ISSUE TITLE
Consider switching to tox for running the tests

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#509]
I added tox to poliastro a long time ago (https://github.com/poliastro/poliastro/commit/e33186caa19c814d9ce7a68fd0271eb74e083878) despite all the problems when we had Fortran extensions (https://github.com/poliastro/poliastro/issues/12), and then I removed it because we started using conda in our Continuous Integration (https://github.com/poliastro/poliastro/commit/26d6ed01e97e7e88c207cf460539894e3812f49c) but then we removed conda again (https://github.com/poliastro/poliastro/pull/210).

The tests already take some time to run, and there's no easy way to test locally all the Python versions that we support. Also, in theory tox automates some things for you, and [Astropy is considering the switch as well](https://github.com/astropy/astropy/wiki/Minutes-for-Astropy-Meeting-2018#testing). 

Looking at the current state of Linux CI (https://github.com/poliastro/poliastro/blob/0.11.x/.circleci/config.yml), we should consider whether tox makes things simpler or worse, and if the benefit of being able to test locally is worth the change anyway.

**Comment by Juanlu001** [comment]
Apart from running the tests, it can also help to run the quality step, see https://blog.ionelmc.ro/2014/05/25/python-packaging/ for inspiration.

**Comment by shreyasbapat** [comment]
We test poliastro on py35, py36 and py37! And tox will be for non CI purposes right?
So the user would have to have all the three interpreters in their system.

**Comment by Juanlu001** [comment]
We use `tox` from Circle CI for the quality step now, and we could do the same for the Python 3.5, 3.6 and 3.7 tests.

**Comment by Juanlu001** [comment]
Partially addressed in #648. However:

* The Circle CI configuration has to be updated accordingly
* The documentation has to reflect the new commands

**Comment by Juanlu001** [comment]
This is fully implemented now!
