### ISSUE TITLE
Trajectories are not redrawn when the frame is changed

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#518]
🐞 **Problem**

When `OrbitPlotter.plot_trajectory` is used and then the frame is changed, the orbits are redrawn but the trajectories aren't.

Compare:

```python
frame = OrbitPlotter()

frame.plot(churi, label="churi", color="C1")
frame.plot(eros, label='eros', color="C0")
frame.plot_trajectory(rr_earth, label=Earth, color="C2");
```

with

```python
frame = OrbitPlotter()

frame.plot(eros, label='eros', color="C0")
frame.plot(churi, label="churi", color="C1")
frame.plot_trajectory(rr_earth, label=Earth, color="C2")

frame.set_frame(*churi.pqw())
```

| Without `set_frame`                                                                                                      | With `set_frame`                                                                                                      |
|--------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| ![Without set_frame](https://user-images.githubusercontent.com/316517/50514081-3f9de880-0a9c-11e9-80b2-8dd26435ef01.png) | ![With set_frame](https://user-images.githubusercontent.com/316517/50514084-4298d900-0a9c-11e9-8c05-7d5a80b4be04.png) |

💡 **Possible solutions**

Only full orbits are stored in the `OrbitPlotter`, but not trajectories:

https://github.com/poliastro/poliastro/blob/ff437dcdc47b30b953be7362cb5d41066ee873d1/src/poliastro/plotting.py#L124-L146

Therefore, trajectories are lost on redraw:

https://github.com/poliastro/poliastro/blob/ff437dcdc47b30b953be7362cb5d41066ee873d1/src/poliastro/plotting.py#L115-L122

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by shreyasbapat** [comment]
Adding  a trajectory list is enough?

**Comment by Juanlu001** [comment]
Should be!

**Comment by shreyasbapat** [comment]
There might be two solutions to this:
1) Renaming `orbits` list and moving it to plot_trajectory completely
2) Adding an extra Parameter in plot_trajectory which checks if it is being called independently or inside `OrbitPlotter,plot`

What do you suggest?

**Comment by Juanlu001** [comment]
> Adding an extra Parameter in plot_trajectory which checks if it is being called independently or

Don't like it :)

**Comment by Juanlu001** [comment]
I'm in the process of refactoring the whole plotting module, so I will take care of this myself.
