### ISSUE TITLE
Consider replacing NEOWS with astroquery

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#534]
Ref: https://github.com/astropy/astroquery/pull/1325#issuecomment-452765939

Documentation: https://astroquery.readthedocs.io/en/latest/jplsbdb/jplsbdb.html

If all the examples in the [User Guide]() and the NEOS notebook work, with the SBDB interface, that would be great! Otherwise, there's a case for a certain degree of overlap and duplication in astroquery.

**Comment by Juanlu001** [comment]
At first I felt bad about @anhiga work, but then I realized that it predated astroquery implementation by one year. We are pioneers :wink:

**Comment by jorgepiloto** [comment]
Started working on this, hope to be completed at the end of the day :smile:

**Comment by jorgepiloto** [comment]
This is the algorithm I came with:

```python
def from_astroquery(body_name):
    """Returns Orbit instance after query."""
    
    # Request to get body
    body = SBDB.query(body_name)    
    a = body['orbit']['elements']['a'].to(u.km) * u.km # Working 
    ecc = float(body['orbit']['elements']['e']) * u.dimensionless_unscaled # Working
    inc = body['orbit']['elements']['i'].to(u.deg) * u.deg
    raan = body['orbit']['elements']['om'].to(u.deg) * u.deg
    argp = body['orbit']['elements']['w'].to(u.deg) * u.deg
    nu = body['orbit']['elements']['ma'].to(u.deg) * u.deg
    epoch = Time(body['orbit']['epoch'].to(u.d), format='jd')

    return Orbit.from_classical(Sun, a, ecc, inc, raan, argp, nu, epoch=epoch)
```

Those weird transformations are due to transformation from the default class for each classical value (astropy CompositeUnits) to astropy Quantity.

Should this replace the whole `neos.neows` module?

**Comment by Juanlu001** [comment]
Notice that you can use `u.one` instead of `u.dimensionless_unscaled`... It's my child :) https://github.com/astropy/astropy/pull/1980

Those transformations are indeed weird, but nothing too serious. I wonder if `SBDB.query` receives some extra parameters we should allow in `from_astroquery`, but apart from that this looks good.

Also, are you _sure_ that the plane of these orbits is the Earth Equator and not the Ecliptic?

**Comment by shreyasbapat** [comment]
I think it will be better if we name it `from_sbdb` ? (We already have `from_horizons` which is also from astroquery)

**Comment by Juanlu001** [comment]
Good catch @shreyasbapat. Yes, `from_sbdb` is better, to avoid confusion.

**Comment by jorgepiloto** [comment]
I agree with you @shreyasbapat, thank you for the suggestion. 

Since Astroquery makes the request to JPL database, in principle all orbits are given in the plane `heliocentric ecliptic J2000`. 

I also compared `neows` and `astroquery` orbit results and they are the same. However, it is advisable to use the `full_precision=True karg` to achieve these results. Should be enough to add just **kargs in the function, right?

![newplot](https://user-images.githubusercontent.com/28702884/52475378-9a4a5a00-2b9b-11e9-924d-f7183cd5b5fd.png)

**Comment by Juanlu001** [comment]
> Should be enough to add just **kargs in the function, right?

Correct!

**Comment by Juanlu001** [comment]
This has been addressed in #577. To close this issue definitely, I would like to know if there are cases where a SBDB query returns more than one possible orbit (for example Halley's comet) and what does the new `Orbit.from_sbdb` with it.

**Comment by shreyasbapat** [comment]
@Juanlu001 I think it does return more than one orbit.

**Comment by Juanlu001** [comment]
@shreyasbapat proof? :)

**Comment by shreyasbapat** [comment]
```
>>> body1 = SBDB.query("Halley")
>>> body1
OrderedDict([('count', 2), ('signature', OrderedDict([('source', 'NASA/JPL Small-Body Database (SBDB) API'), ('version', '1.1')])), ('moreInfo', 'https://ssd-api.jpl.nasa.gov/doc/sbdb.html'), ('message', 'specified query matched more than one object'), ('code', '300'), ('list', OrderedDict([('pdes', ['2688', '1P']), ('name', ['2688 Halley (1982 HG1)', '1P/Halley'])]))])

```

**Comment by Juanlu001** [comment]
What about the new `Orbit.from_sbdb` method in this particular case then?

**Comment by shreyasbapat** [comment]
It returns a Keyerror.
```
>>> a = Orbit.from_sbdb('Halley')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shreyas/Local Forks/poliastro/src/poliastro/twobody/orbit.py", line 472, in from_sbdb
    a = obj["orbit"]["elements"]["a"].to(u.AU) * u.AU
KeyError: 'orbit'
```

**Comment by shreyasbapat** [comment]
This is because when there are multiple orbits in one search, we will have to do something of this kind. See Cell 5 in http://docs.poliastro.space/en/stable/examples/Using%20NEOS%20package.html

**Comment by Juanlu001** [comment]
> It returns a Keyerror.

That's what I suspected. As you say, we'll have to raise an error.

**Comment by shreyasbapat** [comment]
Should I make a PR?

**Comment by Juanlu001** [comment]
Rather: let's open a new issue, explain what exactly has to be done, and if it's easy enough I'll tag it as "good first issue".

**Comment by shreyasbapat** [comment]
> Rather: let's open a new issue, explain what exactly has to be done, and if it's easy enough I'll tag it as "good first issue".

Being further tracked in #609 . This is good to close.

**Comment by Juanlu001** [comment]
Commented there. I will close this one when we get rid of NEOWS.

**Comment by shreyasbapat** [comment]
I think we have done everything here?

**Comment by Juanlu001** [comment]
Yes! Closing! :tada:
