### ISSUE TITLE
Explore other higher order ODE methods

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#537]
According to DifferentialEquations.jl benchmarks, Verner "most efficient" methods (http://doai.io/10.1007/s11075-009-9290-3) are more efficient than Dormand-Prince 8(5,3) (`dop853`) while also being pure tableau methods, which means that they are easier to implement:

https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl/tree/master/benchmarks/NonStiffODE

* See conversation: https://gitter.im/JuliaDiffEq/Lobby?at=5c39d6cd20b78635b60fb8f0
* More discussion https://docs.juliadiffeq.org/latest/solvers/ode_solve/#Non-Stiff-Problems-1

We should consider adding Verner 7 or Verner 8 to SciPy and switch to that for Cowell's method. Perhaps they give fewer problems that DOP853... (see #455)

**Comment by IngenieroDeAviones** [comment]
I will start working on this tomorrow afternoon. I found a book called `Numerical Analysis` by `Richard L.Burden`. It has the Verner-8 algorithm written down and includes a small pseudo-code for a similar algorithm. In fact, coding the Verner-8 is the proposed exercise 4 of chapter 5.5.

**Comment by Juanlu001** [comment]
Tracking in #541.

**Comment by Juanlu001** [comment]
See also #667

**Comment by Juanlu001** [comment]
Updated some broken links, thanks @NanuSai!

**Comment by astrojuanlu** [comment]
After getting `DOP853` into SciPy, we are now trying to do the same with `Verner87` https://github.com/scipy/scipy/pull/14956

**Comment by astrojuanlu** [comment]
I have tried to make a significant contribution to `scipy.integrate` 3 times: 2013 (rewrite `odeint` in Fortran 95), 2018 (add Dormand-Prince 8(5,3) method we needed in poliastro) and 2021 (add Verner 8(7) method we also needed in poliastro). and the 3 times, someone else has either completely rewritten the underlying base, or sent a competing PR 😅

In any case, I'm happy to report that Verner 8(7) seems to be very very close: https://github.com/scipy/scipy/pull/14956#issuecomment-1052321775

**Comment by astrojuanlu** [comment]
It is unlikely that we work directly on this (although I will lend a hand with the review, and run some informal tests with poliastro). On the other hand, I think it would be better to focus our efforts on #1042. I'm closing this issue, there's nothing special to do here - when `Verner87` comes to SciPy, we can just change it.
