### ISSUE TITLE
Download progress is not shown in DASTCOM5

### ISSUE THREAD

**Issue by shreyasbapat** [poliastro/poliastro#542]
🐞 **Problem**
The download progress is not shown in DASTCOM5 while running `dastcom5.download_dastcom5()` .

Instead, a long whitespace is shown. 
![screenshot from 2019-01-17 22-19-15](https://user-images.githubusercontent.com/24257914/51334538-04447780-1aa6-11e9-91ad-03ea696385f2.png)

This makes the function:
https://github.com/poliastro/poliastro/blob/master/src/poliastro/neos/dastcom5.py#L545-L548

Useless. Also, it is peculiar to see that arguments are not passed to that function. Or atleast I didn't understand how that works. 
https://github.com/poliastro/poliastro/blob/fbb697592df7ba60ad371601b149173b254e398e/src/poliastro/neos/dastcom5.py#L539

from poliastro.neos import dastcom5

dastcom.download_dastcom5()

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>
  
```bash
# Paste your output here:

```
</details>

* `python -c "import poliastro.testing; poliastro.testing.test()"`

<details>

```bash
# Paste your output here:

```
</details>

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by amsuhane** [comment]
I solved the issue into two ways:
* In the first way I have not used any additional library:
![final_self_bar](https://user-images.githubusercontent.com/35529737/52175947-c350a080-27d1-11e9-9a70-6cdde174a27e.png)
* In the second method I have used the tqdm library. The additional benefit in this method is that estimation time and download speed are also shown.
![final_4tqdm](https://user-images.githubusercontent.com/35529737/52175962-ff840100-27d1-11e9-8019-c89924c34118.png)

Which method is preferred?

**Comment by amsuhane** [comment]
I have removed the ``_show_download_progress`` attribute from the dastcom5.py. Instead to show the progress I have used ``DownloadProgressBar`` class. 
Due to this, the test test_dastcom5.py is failing. Should I also remove the ``dastcom5._show_download_progress`` test?

**Comment by shreyasbapat** [comment]
Hi @amsuhane , I will be glad if you can directly contribute it here: https://github.com/shreyasbapat/astroquery/tree/dastcom
Thanks for your help! :)

**Comment by shreyasbapat** [comment]
Being tracked here : https://github.com/shreyasbapat/astroquery/pull/1

**Comment by Juanlu001** [comment]
Not at all, I think it's good enough that we replace it in astroquery.

**Comment by Juanlu001** [comment]
Closing this because we won't fix it in poliastro.
