### ISSUE TITLE
IMPORT ERROR

### ISSUE THREAD

**Issue by davepitch** [poliastro/poliastro#545]
🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>
  
```bash
# Paste your output here:

```
</details>

* `python -c "import poliastro.testing; poliastro.testing.test()"`

<details>

```bash
# Paste your output here:

```
</details>

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by davepitch** [comment]
Hi, bear with me...I'm a newbie.....
I typed:
import matplotlib.pyplot as plt

plt.ion()

from astropy import units as u

from poliastro.bodies import Earth, Mars,Sun
without problems. Then I typed:
from poliastro.twobody import Orbit and got the following:

Traceback (most recent call last):

  File "<ipython-input-7-a9ba3797d19a>", line 1, in <module>
    from poliastro.twobody import Orbit

  File "C:\Users\dapit\Anaconda3\lib\site-packages\poliastro\twobody\__init__.py", line 1, in <module>
    from poliastro.twobody.orbit import Orbit  # flake8: noqa

  File "C:\Users\dapit\Anaconda3\lib\site-packages\poliastro\twobody\orbit.py", line 17, in <module>
    from poliastro.twobody.propagation import propagate, mean_motion

  File "C:\Users\dapit\Anaconda3\lib\site-packages\poliastro\twobody\propagation.py", line 7, in <module>
    from scipy.integrate import solve_ivp

  File "C:\Users\dapit\Anaconda3\lib\site-packages\scipy\integrate\__init__.py", line 55, in <module>
    from .quadrature import *

  File "C:\Users\dapit\Anaconda3\lib\site-packages\scipy\integrate\quadrature.py", line 10, in <module>
    from scipy.special.orthogonal import p_roots

  File "C:\Users\dapit\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 636, in <module>
    from ._ufuncs import *

  File "C:\Users\dapit\Anaconda3\lib\site-packages\scipy\special\_ufuncs.py", line 7, in <module>
    __bootstrap__()

  File "C:\Users\dapit\Anaconda3\lib\site-packages\scipy\special\_ufuncs.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)

  File "C:\Users\dapit\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)

ImportError: DLL load failed: The specified module could not be found.

Is that the correct info that I need or do you need something else?

Dave P

**Comment by Juanlu001** [comment]
> Hi, bear with me...I'm a newbie.....

Of course! :slightly_smiling_face: sorry if I sounded too harsh. I took the libery of editing your comment for formatting.

It seems that you have some sort of installation problem with SciPy: if you try `from scipy.integrate import solve_ivp`, you would see the same error.

Can you paste the output of `conda list` and `conda info --all` so we can know a bit more about your environment?

**Comment by davepitch** [comment]
(base) C:\Users\dapit>conda list
# packages in environment at C:\Users\dapit\Anaconda3:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0
anaconda                  4.3.1               np111py36_0
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.6                    py37_0
anaconda-project          0.8.2                    py37_0
asn1crypto                0.24.0                   py37_0
astroid                   2.1.0                    py37_0
astropy                   1.3                 np111py36_0
astropy                   3.1.1                     <pip>
astroquery                0.3.9                     <pip>
atomicwrites              1.2.1                    py37_0
attrs                     18.2.0           py37h28b3542_0
babel                     2.6.0                    py37_0
backcall                  0.1.0                    py37_0
backports                 1.0                      py37_1
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
beautifulsoup4            4.6.3                    py37_0
bitarray                  0.8.3            py37hfa6e2cd_0
blas                      1.0                         mkl
blaze                     0.10.1                   py36_0
bleach                    3.1.0                    py37_0
bokeh                     0.12.4                   py36_0
boto                      2.49.0                   py37_0
bottleneck                1.2.0               np111py36_0
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2018.03.07                    0
cdflib                    0.3.9                     <pip>
certifi                   2018.11.29               py37_0
cffi                      1.11.5           py37h74b6da3_1
chardet                   3.0.4                    py37_1
chest                     0.2.3                    py37_1
click                     7.0                      py37_0
cloudpickle               0.6.1                    py37_0
clyent                    1.2.2                    py37_1
colorama                  0.4.1                    py37_0
comtypes                  1.1.7                    py37_0
conda                     4.5.12                   py36_0
conda-env                 2.6.0                         1
configobj                 5.0.6                    py37_1
console_shortcut          0.1.1                         3
contextlib2               0.5.5                    py37_0
cryptography              2.4.2            py37h7a1dbc1_0
curl                      7.63.0            h2a8f88b_1000
cycler                    0.10.0                   py37_0
cycler                    0.10.0                    <pip>
cython                    0.29.2           py37ha925a31_0
cytoolz                   0.9.0.1          py37hfa6e2cd_1
dask                      0.13.0                   py36_0
datashape                 0.5.4                    py36_0
decorator                 4.3.0                    py37_0
dill                      0.2.8.2                  py37_0
docutils                  0.14                     py37_0
entrypoints               0.2.3                    py37_2
et_xmlfile                1.0.1                    py37_0
fastcache                 1.0.2            py37hfa6e2cd_2
flask                     1.0.2                    py37_1
flask-cors                3.0.7                    py37_0
freetype                  2.9.1                ha9979f8_1
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.4.0            py37he774522_0
greenlet                  0.4.15           py37hfa6e2cd_0
h5py                      2.6.0               np111py36_2
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.0                    py37_2
html5lib                  1.0.1                     <pip>
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imagesize                 1.1.0                    py37_0
importlib_metadata        0.6                      py37_0
intel-openmp              2019.1                      144
ipykernel                 5.1.0            py37h39e3cac_0
ipython                   7.2.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.4.2                    py37_0
isort                     4.3.4                    py37_0
itsdangerous              1.1.0                    py37_0
jdcal                     1.4                      py37_0
jedi                      0.13.2                   py37_0
jinja2                    2.10                     py37_0
jpeg                      9b                   hb83a4c4_2
jplephem                  2.9                       <pip>
jsonschema                2.6.0                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.4.0                    py37_0
keyring                   17.1.1                   py37_0
kiwisolver                1.0.1                     <pip>
krb5                      1.16.1               hc04afaa_7
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
libcurl                   7.63.0            h2a8f88b_1000
libiconv                  1.15                 h1df5818_7
libpng                    1.6.36               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.0                h7a1dbc1_4
libtiff                   4.0.9                h36446d0_2
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llvmlite                  0.27.0           py37ha925a31_0
locket                    0.2.0                    py37_1
lxml                      4.3.0            py37h1350720_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.0            py37he774522_0
matplotlib                3.0.2                     <pip>
matplotlib                2.0.0               np111py36_0
mccabe                    0.6.1                    py37_1
menuinst                  1.4.14           py37hfa6e2cd_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.1                      144
mkl-service               1.1.2            py37hb782905_5
more-itertools            5.0.0                    py37_0
mpmath                    1.1.0                    py37_0
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
nbconvert                 5.3.1                    py37_0
nbformat                  4.4.0                    py37_0
netCDF4                   1.3.0                     <pip>
networkx                  2.2                      py37_1
nltk                      3.4                      py37_1
nose                      1.3.7                    py37_2
notebook                  5.7.4                    py37_0
numba                     0.42.0                    <pip>
numba                     0.30.1              np111py36_0
numexpr                   2.6.1               np111py36_2
numpy                     1.16.0                    <pip>
numpy                     1.11.3                   py36_0
numpydoc                  0.8.0                    py37_0
odinetcdf                 0.1                       <pip>
odo                       0.5.0                    py36_1
olefile                   0.46                     py37_0
openpyxl                  2.5.12                   py37_0
openssl                   1.1.1a               he774522_0
packaging                 18.0                     py37_0
pandas                    0.19.2              np111py36_1
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.3.1                    py37_0
partd                     0.3.9                    py37_0
path.py                   11.5.0                   py37_0
pathlib2                  2.3.3                    py37_0
patsy                     0.4.1                    py36_0
pep8                      1.7.1                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    5.4.1            py37hdc69c19_0
pip                       18.1                      <pip>
pip                       18.1                     py37_0
plotly                    3.5.0                     <pip>
pluggy                    0.8.1                    py37_0
ply                       3.11                     py37_0
poliastro                 0.11.1                    <pip>
prometheus_client         0.5.0                    py37_0
prompt_toolkit            2.0.7                    py37_0
psutil                    5.4.8            py37he774522_0
py                        1.7.0                    py37_0
pyasn1                    0.4.4            py37h28b3542_0
pycodestyle               2.4.0                    py37_0
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37hfa6e2cd_9
pycurl                    7.43.0.2         py37h7a1dbc1_0
pyflakes                  2.0.0                    py37_0
pygments                  2.3.1                    py37_0
pylint                    2.2.2                    py37_0
pyopenssl                 18.0.0                   py37_0
pyparsing                 2.3.0                    py37_0
pyparsing                 2.3.1                     <pip>
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pysocks                   1.6.8                    py37_0
pytables                  3.2.2               np111py36_4
pytest                    4.1.0                    py37_0
python                    3.7.2                h8c8aaf0_0
python-dateutil           2.7.5                    py37_0
pytz                      2018.7                   py37_0
pywin32                   223              py37hfa6e2cd_1
pywinpty                  0.5.5                 py37_1000
pyyaml                    3.13             py37hfa6e2cd_0
pyzmq                     17.1.2           py37hfa6e2cd_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.5.5                    py37_0
qtconsole                 4.4.3                    py37_0
qtpy                      1.5.2                    py37_0
requests                  2.21.0                   py37_0
retrying                  1.3.3                     <pip>
rope                      0.11.0                   py37_0
ruamel_yaml               0.15.46          py37hfa6e2cd_0
scikit-image              0.12.3              np111py36_1
scikit-learn              0.18.1              np111py36_1
scipy                     0.18.1              np111py36_1
seaborn                   0.7.1                    py36_0
send2trash                1.5.0                    py37_0
setuptools                40.6.3                    <pip>
setuptools                40.6.3                   py37_0
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                    <pip>
six                       1.12.0                   py37_0
snowballstemmer           1.2.1                    py37_0
sockjs-tornado            1.0.6                    py37_0
sphinx                    1.8.2                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                    py37_1
spyder                    3.3.2                    py37_0
spyder-kernels            0.3.0                    py37_0
sqlalchemy                1.2.15           py37he774522_0
sqlite                    3.26.0               he774522_0
statsmodels               0.6.1               np111py36_1
sympy                     1.3                      py37_0
terminado                 0.8.1                    py37_1
testpath                  0.4.2                    py37_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                    py37_0
tornado                   5.1.1            py37hfa6e2cd_0
traitlets                 4.3.2                    py37_0
unicodecsv                0.14.1                   py37_0
UNKNOWN                   0.0.0                     <pip>
urllib3                   1.24.1                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.14.1                   py37_0
wheel                     0.32.3                   py37_0
widgetsnbextension        3.4.2                    py37_0
win_inet_pton             1.0.1                    py37_1
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.10.11          py37hfa6e2cd_2
xlrd                      1.2.0                    py37_0
xlsxwriter                1.1.2                    py37_0
xlwings                   0.15.1                   py37_0
xlwt                      1.3.0                    py37_0
yaml                      0.1.7                hc54c509_2
zeromq                    4.2.5                he025d50_1
zlib                      1.2.11               h62dcd97_3

(base) C:\Users\dapit>

and from conda info:
Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\dapit>conda info

     active environment : None
       user config file : C:\Users\dapit\.condarc
 populated config files : C:\Users\dapit\.condarc
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.2.final.0
       base environment : C:\Users\dapit\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\dapit\Anaconda3\pkgs
                          C:\Users\dapit\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\dapit\Anaconda3\envs
                          C:\Users\dapit\AppData\Local\conda\conda\envs
                          C:\Users\dapit\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.2 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


C:\Users\dapit>

**Comment by Juanlu001** [comment]
@davepitch this is my attempt!

1. Uninstall it using Windows "Add or Remove Programs" or "Uninstall a program"
2. Restart the computer
3. Make sure there is nothing in `C:\Users\dapit\Anaconda3\`, `C:\Users\dapit\.conda\` and `C:\Users\dapit\AppData\Local\conda\`, and otherwise remove those directories
4. Install Anaconda again
5. From now on: don't install packages in the `base` (also known as `root`) environment: always create one environment per project
6. Create a new environment for poliastro using `conda create -n poliastro37 python=3.7`
7. Activate the environment using `activate poliastro37` 
8. Install poliastro as normally (you can do `pip install poliastro` or `conda install poliastro -c conda-forge`)
9. Please come back to confirm that everything worked :)

**Comment by davepitch** [comment]
Juan,
Unfortunately I haven’t had any time to de-install and then re-install Anaconda, due to a business trip. I won’t be able to get back to this until Thursday, could you leave it open until then. Really need to fix it on Thursday though because I really need to use Poliastro for some launch mission analysis that I need to do...

Much thanks for your ongoing help...

Dave P

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Juanlu001** [comment]
Hi @davepitch, I assume you didn't have time to work on this issue anymore so I'm closing. Please feel free to comment further if you still need assistance, or open a new one.
