### ISSUE TITLE
Automate closing of support issues

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#549]
There are some users that ask for support in the issue tracker about installation problems or general usage of the library. That is perfectly fine, but if those issues don't come from a poliastro bug or propose an enhancement, they are handled in a different way: we iterate with the user, and if they don't respond we close it.

This process should be automatic. It would be great to have a bot somewhere.

**Comment by shreyasbapat** [comment]
Precisely this? https://github.com/probot/no-response

**Comment by shreyasbapat** [comment]
I am testing the bot, and would create a PR and ask you to install a GitHub app tomorrow if everything works fine. :)

**Comment by Juanlu001** [comment]
Thanks @shreyasbapat! Yes, something like that. Didn't have time to review the links in depth, but if you find something interesting let me know. I think @IngenieroDeAviones was also giving this a look, coordinate so we don't duplicate efforts :)
