### ISSUE TITLE
Conda install problem

### ISSUE THREAD

**Issue by dragonlost** [poliastro/poliastro#558]
Hello !

I tried to install poliastro on fresh anaconda / anaconda3.
When I run the command:
`conda install poliastro`
After adding conda-forge.

I get the following error message:
```

Collecting package metadata: | WARNING conda.core.index:push_record(193): Skipping conda-forge/noarch::poliastro-0.10.0-py_1 due to InvalidSpec: <4.*
WARNING conda.core.index:push_record(193): Skipping conda-forge/noarch::poliastro-0.11.0-py_0 due to InvalidSpec: <4.*
WARNING conda.core.index:push_record(193): Skipping conda-forge/noarch::poliastro-0.11.1-py_0 due to InvalidSpec: <4.*
done
Solving environment: failed

InvalidVersionSpec: Invalid version '<4.*': invalid operator with '.*'
```

So I go through PIP which has been successful in installing poliastro.

**Comment by Juanlu001** [comment]
Hi @dragonlost, thanks for reporting this issue! I guess you are using the new conda 4.6? I'm not aware of any issues but perhaps our package spec is now wrong, I will check.

**Comment by dragonlost** [comment]
yes i use conda 4.6.2.

Thanks for fix. I will watch tomorrow.

**Comment by dragonlost** [comment]
:( 
I will go through PIP while waiting.

**Comment by Juanlu001** [comment]
Updating to the just-released conda 4.6.3 fixes the problem https://github.com/conda/conda/releases/tag/4.6.3 @dragonlost I just tried on my side, but would you please confirm as well and close the issue if appropriate?

**Comment by dragonlost** [comment]
Ah Super ! I just tested and it works!

Just a warning message:

Collecting package metadata: | WARNING conda.models.version:get_matcher(528): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 4.*, but conda is ignoring the .* and treating it as 4

**Comment by Juanlu001** [comment]
I see! Well, we already fixed the conda package, so I hope this is not a problem in the future (by handling the failure in a less catastrophic way).

Closing!
