### ISSUE TITLE
Implicit assumption about range in `nu_to_E`/`E_to_nu`

### ISSUE THREAD

**Issue by helgee** [poliastro/poliastro#564]
🐞 **Problem**

The code for transformations between eccentric and true anomaly implicitly assumes that
the input anomaly is in the interval `[-pi, pi]`.

🎯 **Goal**

Provide a more robust formulation that also work for `[0.0, 2 * pi]`.

💡 **Possible solutions**

Use the formulation used by [Orekit](https://github.com/CS-SI/Orekit/blob/develop/src/main/java/org/orekit/orbits/KeplerianOrbit.java#L577) which works in both ranges.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by helgee** [comment]
PR incoming...

**Comment by Juanlu001** [comment]
Awesome, thanks a lot Helge! Glad to have you contributing :)
