### ISSUE TITLE
Improve stability of `coe2rv`<->`rv2coe`

### ISSUE THREAD

**Issue by helgee** [poliastro/poliastro#566]
🐞 **Problem**

Because I have been bitten by lacking stability of orbital elements to cartesian vectors conversion
functions in the past, I have started a (mad) little experiment over in Julia land, see [here](https://github.com/JuliaAstro/AstroBase.jl/blob/master/test/orbit_ranges.jl).

I basically construct the valid ranges for the orbital elements for all orbit types (elliptic, hyperbolic, circular, equatorial, circular-equatorial) excluding obvious singularities and check for a certain number of permutations whether the transformation is transitive, i.e. `rv2coe(coe2rv(...))`.

I repeated this test for three different implementations:

- `poliastro`: A Julia implementation of the algorithm currently implemented in poliastro.
- `Orekit`: A Julia implementatopn of the algorithm implemented in Orekit.
- `AstroBase.jl`: A happy mash-up of the two above, i.e. special case handling of poliastro with elliptic/hyperbolic equations adapted from Orekit.

Here are the results (`rejected` means that impossible orbits were discarded):

**Poliastro**

I have not analzyed the results in detail but the current implementation in poliastro struggles across the board (the Julia port might also be buggy, but all three variants pass basic smoke tests).
```
Elliptic Orbits
===============
Testing 262144 combinations with 5 processes.
Passed 163840 (62%), failed 98304 (38%), rejected 0 (0%).
In 27.197244709 seconds.

Hyperbolic Orbits
=================
Testing 262144 combinations with 5 processes.
Passed 73728 (28%), failed 73728 (28%), rejected 114688 (44%).
In 20.730527165 seconds.

Circular Orbits
===============
Testing 4096 combinations with 5 processes.
Passed 39 (1%), failed 4057 (99%), rejected 0 (0%).
In 1.168262474 seconds.

Equatorial Orbits
=================
Testing 4096 combinations with 5 processes.
Passed 2560 (62%), failed 1536 (38%), rejected 0 (0%).
In 0.480839932 seconds.

Circular-Equatorial Orbits
==========================
Testing 64 combinations with 5 processes.
Passed 8 (12%), failed 56 (88%), rejected 0 (0%).
In 0.627632413 seconds.
```

**Orekit**

Orekit gets a perfect score on elliptic/hyperbolical but does 🤷‍♂️ on special cases. This is probably because the user is supposed to use the right *special* orbit class for non-elliptic orbits (a silly concept in my book). 
```
Elliptic Orbits
===============
Testing 262144 combinations with 5 processes.
Passed 262144 (100%), failed 0 (0%), rejected 0 (0%).
In 25.938678205 seconds.

Hyperbolic Orbits
=================
Testing 262144 combinations with 5 processes.
Passed 147456 (56%), failed 0 (0%), rejected 114688 (44%).
In 20.718426606 seconds.

Circular Orbits
===============
Testing 4096 combinations with 5 processes.
Passed 0 (0%), failed 4096 (100%), rejected 0 (0%).
In 1.151732604 seconds.

Equatorial Orbits
=================
Testing 4096 combinations with 5 processes.
Passed 4096 (100%), failed 0 (0%), rejected 0 (0%).
In 0.45797599 seconds.

Circular-Equatorial Orbits
==========================
Testing 64 combinations with 5 processes.
Passed 2 (3%), failed 62 (97%), rejected 0 (0%).
In 0.645712886 seconds.
```

**AstroBase.jl**

And finally the mash-up which takes the best of both worlds and generates a perfect score: https://github.com/JuliaAstro/AstroBase.jl/blob/master/src/TwoBody.jl#L56
```
Elliptic Orbits
===============
Testing 262144 combinations with 5 processes.
Passed 262144 (100%), failed 0 (0%), rejected 0 (0%).
In 27.107912912 seconds.

Hyperbolic Orbits
=================
Testing 262144 combinations with 5 processes.
Passed 147456 (56%), failed 0 (0%), rejected 114688 (44%).
In 21.958699757 seconds.

Circular Orbits
===============
Testing 4096 combinations with 5 processes.
Passed 4096 (100%), failed 0 (0%), rejected 0 (0%).
In 1.278563358 seconds.

Equatorial Orbits
=================
Testing 4096 combinations with 5 processes.
Passed 4096 (100%), failed 0 (0%), rejected 0 (0%).
In 0.560119618 seconds.

Circular-Equatorial Orbits
==========================
Testing 64 combinations with 5 processes.
Passed 64 (100%), failed 0 (0%), rejected 0 (0%).
In 0.726457916 seconds.
```

🎯 **Goal**

- Improve stability of `coe2rv` and by extension `Orbit.from_classical`
- If the user provides a valid orbit the conversions should not fail

💡 **Possible solutions**

- Implement AstroBase.jl algorithm in poliastro

📋  **Steps to solve the problem**

- [ ] Check if test methodology is sound
  - [ ] i.e. are all ranges selected correctly?
- [x] Maybe run the test on a beefier machine with even more samples
- [ ] Implement best algorithm
- [ ] Implement stronger argument checks in e.g. `Orbit.from_classical`
- ...
- [ ] Profit!

**Comment by Juanlu001** [comment]
This is awesome! Great material for https://openastrodynamics.github.io/ :smile: 

I still didn't read your code, but can you comment on the overall strategy you used for improving the scores?

Also, are you by any chance using something like https://pypi.org/project/hypothesis/ for the tests?

**Comment by helgee** [comment]
![grafik](https://user-images.githubusercontent.com/1408922/52351065-40765280-2a2a-11e9-8c78-d1ff0831edc5.png)

**Comment by helgee** [comment]
The new algorithm seems rock-solid 🎉 
```
Elliptic Orbits
===============
Testing 11390625 combinations with 17 processes.
Progress: 100%|█████████████████████████████████████████| Time: 0:26:08
Passed 11390625 (100%), failed 0 (0%), rejected 0 (0%).
In 1572.261626475 seconds.

Hyperbolic Orbits
=================
Testing 11390625 combinations with 17 processes.
Progress: 100%|█████████████████████████████████████████| Time: 0:25:58
Passed 7036875 (62%), failed 0 (0%), rejected 4353750 (38%).
In 1561.246576675 seconds.

Circular Orbits
===============
Testing 50625 combinations with 17 processes.
Passed 50625 (100%), failed 0 (0%), rejected 0 (0%).
In 3.840142336 seconds.

Equatorial Orbits
=================
Testing 50625 combinations with 17 processes.
Passed 50625 (100%), failed 0 (0%), rejected 0 (0%).
In 3.101696227 seconds.

Circular-Equatorial Orbits
==========================
Testing 225 combinations with 17 processes.
Passed 225 (100%), failed 0 (0%), rejected 0 (0%).
In 1.160166671 seconds.
```

**Comment by Juanlu001** [comment]
You mean the new algorithm implemented in #565, or some code you are working on locally?

**Comment by helgee** [comment]
This one: https://github.com/JuliaAstro/AstroBase.jl/blob/master/src/TwoBody.jl#L56

Now I need to port it to Python...

**Comment by jorgepiloto** [comment]
Wow! This is amazing, I never thought about this **massive test**.  If you need any kind of help, I would like to contribute as much as I can. Very interesting issue :+1:
