### ISSUE TITLE
Small error in Orbit docstrings

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#590]
🐞 **Problem**

While working with other issues, I just discovered a small error in docstrings:

https://github.com/poliastro/poliastro/blob/b3d69eca866ce443378bea36ad9c37efcb864256/src/poliastro/twobody/orbit.py#L108-L116

These docstrings are exchanged :sweat_smile: 

💡 **Possible solutions**

Just place them into their corresponding functions. Very simple issue :smile:

**Comment by Juanlu001** [comment]
Ooops, good catch :)

**Comment by Juanlu001** [comment]
Closed in #592.
