### ISSUE TITLE
from_body_ephem should also contain an attribute to enter ephemeris

### ISSUE THREAD

**Issue by Himanshu-Garg** [poliastro/poliastro#606]
**suggestion for a new addition**

I think from_body_ephem should have an option to insert ephemeris
as for some planets like Pluto; default ephemeris don't work and there is no feature to add ephemeris in our present from_body_ephem; which makes it impossible to find its oscillating orbit at the time

**Comment by jorgepiloto** [comment]
Thanks for opening this issue but as said here: https://github.com/poliastro/poliastro/issues/401#issuecomment-404859593

> We won't fix this in poliastro, because it's the user responsability to set a proper ephemeris, but perhaps we can improve the error message.

It may look nice to make `from_body_ephem` function change automatically into available ephemerides, however this way the user is not aware that the software introduced a change in the position and velocity of the body. By forcing the user to input ephemerides manually, he has the full control of such an important parameter.

That is the way I understand the idea behind `raising an error` in the code.

**Comment by Himanshu-Garg** [comment]
Or what we can do is 
If planet(body) is not found in the given ephemeris, it changes the ephemeris and gives a warning that it has been changed, and then itself sets the ephemeris to the original one.
In this way, user will have its data from other ephemeris without changing the ephemeris permanently.

**Comment by Juanlu001** [comment]
> it changes the ephemeris and gives a warning that it has been changed, and then itself sets the ephemeris to the original one.

That complicates the poliastro implementation a lot. If we don't want to change the ephemeris globally, we have to wrap it inside a `with` block. And that also affects other things like coordinate transformations.

I still think failing with a better error message is the best solution to enforce good practices while being helpful to the user.

**Comment by Juanlu001** [comment]
I am closing this as "won't fix".
