### ISSUE TITLE
Time to update this plot in README?

### ISSUE THREAD

**Issue by shreyasbapat** [poliastro/poliastro#610]
🐞 **Problem**

This plot is quite old and the given code does not produce that. We probably need to update it with the latest one!

![Screenshot from 2019-03-18 19-56-22](https://user-images.githubusercontent.com/24257914/54537135-ff257b00-49b7-11e9-9d48-3f5f1c8a7e0b.png)

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>
  
```bash
# Paste your output here:

```
</details>

* `python -c "import poliastro.testing; poliastro.testing.test()"`

<details>

```bash
# Paste your output here:

```
</details>

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
You are totally right. I was hesitant to do the update because the widgets are still a bit tricky to put in the documentation (see https://github.com/jupyter-widgets/ipywidgets/issues/2311...). In fact, I wonder if we could have a `static=True` parameter in `Orbit.plot`...!

**Comment by shreyasbapat** [comment]
> we should have a static=True parameter in Orbit.plot...!

We should definitely have. Another easy issue!

**Comment by azlkiniue** [comment]
Is this the picture you mean?
![image](https://user-images.githubusercontent.com/24465401/57056734-90ce1b00-6cce-11e9-8093-14e44bd17f32.png)

**Comment by Juanlu001** [comment]
Yes.

However, the problem is not just replacing the picture. It is a big issue involving how to properly display Plotly plots on the Read the Docs documentation and also in notebooks.

See the long thread in https://github.com/rtfd/readthedocs.org/issues/4367. This issue is still present in poliastro.

**Comment by shreyasbapat** [comment]
@Juanlu001 I totally agree that this problem must be solved in RTD. But as we did earlier, changing the sphinx theme for our docs seems to fix this issue for us. Do you think we should consider that?

**Comment by Juanlu001** [comment]
I think we shouldn't. Of course it's going to fix the problem for us but we have to be good open source citizens and try to figure out what's going on to advance the ecosystem. It's in our best interest that Plotly works great on HTML and notebooks.

**Comment by Juanlu001** [comment]
Notice that

1) Plotly plots finally works in notebooks!
2) We don't need to use widgets anymore

**Comment by Jaisu-1** [comment]
Hi, I'd like to take this issue up if possible?

**Comment by astrojuanlu** [comment]
Let's do this after #792.

**Comment by astrojuanlu** [comment]
@jorgepiloto has been investigating this. He found that, in the pages outside of the examples, we need to include the Plotly JS:

https://github.com/readthedocs/sphinx_rtd_theme/issues/788#issuecomment-608992554

We might need something like this:

https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file

(notice that [we used to have it](https://github.com/poliastro/poliastro/commit/ae4b105c84c31b80bf73a7ef077c863b5ba9eff4) for other reasons)

**Comment by astrojuanlu** [comment]
I think it's a good moment to update this plot, but I'm going this leave this for someone else. For examples @LuisGMM, do you want to have a look?

**Comment by astrojuanlu** [comment]
I pinky promise we'll do this for the next release.

**Comment by astrojuanlu** [comment]
The joy of closing old issues 👯‍♀️
