### ISSUE TITLE
Allow static plotting in Orbit.plot

### ISSUE THREAD

**Issue by shreyasbapat** [poliastro/poliastro#628]
🐞 **Problem**

Orbit.plot can only produce interactive plotly plots. It would be great to have it produce static plots as well.

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>
  
```bash
# Paste your output here:

```
</details>

* `python -c "import poliastro.testing; poliastro.testing.test()"`

<details>

```bash
# Paste your output here:

```
</details>

🎯 **Goal**

💡 **Possible solutions**

- Orbit.plot(static=True) will be a simple addition

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by vedang08** [comment]
@shreyasbapat  and @Juanlu001, can I work on this?

**Comment by Juanlu001** [comment]
@vedang08 Sure, go ahead!
