### ISSUE TITLE
Investigate accuracy in propagation methods

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#630]
🐞** Problem**

While working on #475, I found the following paper:

* http://derastrodynamics.com/docs/kepler_algorithms_v2.pdf

A total of four examples can be found in this paper. In each of them, different algorithms are tested under Earth orbits, such us LEO or HEO. What surprised me was:

1. These orbits are not so strange in terms of `ecc`. These examples are not dealing with values for the eccentricity of 0.9... or higher.

2. In the paper, solutions for the different methods diverge from each other with orders of 10e3 (check example 3)!!!

I am not sure about the reputation of this paper, so I decided to make a test and parametrize them for all actual propagators. First two passed without problem, however the others failed.

 `Solutions that poliastro showed were those ones marked in red for the last two tests. However mean_motion, kepler and cowell returned same results...`

`Cowell` integrates directly the two body equation, so in principle it should get the best result or very close to the one that the paper states as the `right` one.

What do you think about this? 

🎯 **Goal**

Check who has the most accurate value: poliastro or DerAstrodynamics

💡 **Possible solutions**

1. Test against other available software.
2. Keep working with new integrators, propagators and check when developed.

**Comment by jorgepiloto** [comment]
The test I code is available here, if you want to check:

```python
import pytest
from astropy import units as u
from astropy.tests.helper import assert_quantity_allclose
from numpy.testing import assert_allclose

from poliastro.bodies import Earth
from poliastro.twobody import Orbit
from poliastro.twobody.propagation import cowell, kepler, mean_motion, gauss

@pytest.mark.parametrize("method", [kepler, mean_motion, cowell])
def test_example_1(method):

    # Initial data
    r0 = [2218.922362, -13049.809380, -15.285102] * u.km
    v0 = [3.894738598, 4.630875574, 2.332314347] * u.km / u.s
    tof = 86400 * u.s

    # Expected data
    expected_r = [-27456.2661, -16961.1114, -15098.0763] * u.km
    expected_v = [1.431551, -1.341058, 0.596545] * u.km / u.s

    ss0 = Orbit.from_vectors(Earth, r0, v0)
    ssf = ss0.propagate(tof, method=method)

    assert_quantity_allclose(expected_r, ssf.r, rtol=1.e-3)
    assert_quantity_allclose(expected_v, ssf.v, rtol=1e-3)

@pytest.mark.parametrize("method", [kepler, mean_motion, cowell])
def test_example_2(method):

    # Initial data
    r0 = [-209.011468, -30385.859968, 4.280644] * u.km
    v0 = [2.248716032, 2.177749649, 0.329155365] * u.km / u.s
    tof = 86400 * u.s

    # Expected data
    expected_r = [-16906.0054, 1871.5111, -2495.6927] * u.km
    expected_v = [-4.125426, -3.558097, -0.604363] * u.km / u.s

    ss0 = Orbit.from_vectors(Earth, r0, v0)
    ssf = ss0.propagate(tof, method=method)

    assert_quantity_allclose(expected_r, ssf.r, rtol=1.e-3)
    assert_quantity_allclose(expected_v, ssf.v, rtol=1e-3)


@pytest.mark.parametrize("method", [kepler, mean_motion, cowell])
def test_example_3(method):

    # Initial data
    r0 = [510.306735, 6793.878710, 0.007287] * u.km
    v0 = [-2.949065600, 0.256823630, 7.486987267] * u.km / u.s
    tof = 86400 * u.s

    # Expected data
    expected_r = [216.109788, 6704.762171, 1316.193868] * u.km
    expected_v = [-3.044353, -1.132308, 7.339295] * u.km / u.s

    ss0 = Orbit.from_vectors(Earth, r0, v0)
    ssf = ss0.propagate(tof, method=method)

    assert_quantity_allclose(expected_r, ssf.r, rtol=1.e-3)
    assert_quantity_allclose(expected_v, ssf.v, rtol=1e-3)

@pytest.mark.parametrize("method", [kepler, mean_motion, cowell])
def test_example_4(method):

    # Initial data
    r0 = [6969.687412, 2195.624199, -0.030412] * u.km
    v0 = [-0.695626778, 2.267918155, 6.958092777] * u.km / u.s
    tof = 86400 * u.s

    # Expected data
    expected_r = [5250.523888, 2917.968463, 4151.680633] * u.km
    expected_v = [-4.787513, 0.640780, 5.545121] * u.km / u.s

    ss0 = Orbit.from_vectors(Earth, r0, v0)
    ssf = ss0.propagate(tof, method=method)

    assert_quantity_allclose(expected_r, ssf.r, rtol=1.e-3)
    assert_quantity_allclose(expected_v, ssf.v, rtol=1e-3)
```

**Comment by Juanlu001** [comment]
Great finding @jorgepiloto! I think it would be great to have a structured way of visualizing these differences, like for example the Astropy coordinates benchmark:

http://www.astropy.org/coordinates-benchmark/summary.html

Not sure if this fits in the poliastro test suite itself, but we can build another repository, like the (outdated) performance benchmarks we have here:

https://github.com/poliastro/poliastro-benchmarks

Or the experiments @nikita-astronaut did:

https://github.com/poliastro/kepler-experiments

**Comment by jorgepiloto** [comment]
I saw that the first two tests (the ones `poliastro`is passing) are not taking into account any perturbations. The other are take into account J2, J3, atmospheric drag... That was why not passing the tests, my fault :sweat_smile: 

But it may be really interesting to compare all possible combinations: propagators, with different numerical methods, different perturbations...

I will take a look to previous links :+1:
