### ISSUE TITLE
Consider normalizing user input

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#636]
From #567:

> If we use this opportunity to settle on -pi <= nu < pi (did I understand correctly?) perhaps we should discuss whether we should normalize user data on input and emit a warning.

**Comment by ritzvik** [comment]
@Juanlu001 Should I go for it?

**Comment by Juanlu001** [comment]
@ritiek before you go for it, can you describe your plans here? :)

**Comment by ritzvik** [comment]
I've implemented a function to normalize:
```
import numpy as np
from numpy.testing import assert_allclose
import pytest


def normalize(nu):
    pi2 = 2.0 * np.pi
    if nu < 0:
        new_nu = np.ceil((-nu) / pi2) * pi2 + nu
    else:
        new_nu = nu - np.floor(nu / pi2) * pi2
    if new_nu > np.pi:
        return new_nu - pi2
    else:
        return new_nu


@pytest.mark.parametrize("angle", [1.1, 0, -0.9, 3, 5, 1000.0, -3.1, -6.1, -245.0])
def test_normailization(angle):
    angle_new = normalize(angle)
    assert_allclose(np.sin(angle), np.sin(angle_new), rtol=1e-7)
    assert_allclose(np.cos(angle), np.cos(angle_new), rtol=1e-7)

```
The steps are :
  - Making the angle positive
  - normalize it within [0, 2pi]
  - subtract 2pi from the resultant angle if it is greater than pi

To test:
  - we compare the sin and cos of the original and new angle

**Comment by ritzvik** [comment]
Is the normalization expected to be implemented in `rv_pqw()` in `core/elements.py` if I'm correct?
