### ISSUE TITLE
Add contributing section in docs

### ISSUE THREAD

**Issue by AunSiro** [poliastro/poliastro#638]
The current [documentation in Read the Docs](https://docs.poliastro.space/en/stable/index.html) doesn't contain the information about contributing present in [CONTRIBUTING.rst](https://github.com/poliastro/poliastro/blob/master/CONTRIBUTING.rst)

In order to solve this, knowledge about how to write documentation in Read the Docs is required.

**Comment by michiboo** [comment]
Hi can I take this?

**Comment by Juanlu001** [comment]
@michiboo, this was closed in #640!
