### ISSUE TITLE
Test cases based on Orekit

### ISSUE THREAD

**Issue by GorgiAstro** [poliastro/poliastro#644]
From https://github.com/poliastro/poliastro/wiki/Validation :
Orekit is an open-source space dynamics library written in Java. A Python wrapper is maintained by @petrushy (https://gitlab.orekit.org/orekit-labs/python-wrapper), which allows to include Orekit in the test cases.

🎯 **Goal**

Validate poliastro against Orekit

📋  **Steps**

* Include Orekit as a dependency in [options.extras_require] in `setup.cfg`. Orekit is distributed only via conda, how can we proceed?
* Import Orekit data files, which contain Earth Orientation Parameters, leap seconds history, etc. It is maintained in https://gitlab.orekit.org/orekit/orekit-data. There are several possibilities:
  1) Download it as a zip somewhere in the repo and let this method do the job: https://gitlab.orekit.org/orekit-labs/python-wrapper/blob/master/python_files/pyhelpers.py#L37 
  2) Unzip the current version in a folder somewhere in the repo
  3) Have the Git repository synchronized as a submodule. Probably too much effort for the moment
  4) Do not store the data in the repo, download it when installing poliastro (dev), by including it in `setup.cfg`
  * Common for all four possibilities: where is it best to store the data? In a folder named `data` in the root folder? Or is it poliastro's philosophy not to store any data in the repo? I did not see any SPICE kernel or anything in the repo, just code.
* Write test cases :) Given that Orekit requires to start a JVM, I would rather write the test cases in separate files, what do you think?

**Comment by GorgiAstro** [comment]
WIP :)

**Comment by GorgiAstro** [comment]
The following commit shows an example for Kepler propagation: https://github.com/GorgiAstro/poliastro/commit/512735191f1eba4fcdc1b31056b08eecba76461b

In particular, the `orekit.initVM()` call is necessary to start the JVM prior to any other Orekit imports

**Comment by Juanlu001** [comment]
Thanks a lot for putting together this issue @GorgiAstro! Also, the example with the Python wrappers looks pretty neat.

I think installing Orekit is complex enough that it deserves some care. Definitely it can't be included in `extras_require` because pip won't handle it. Perhaps we can set up a separate repository with recipes to install Orekit, GMAT, SPICE and others, and leave `poliastro/src/tests` for unit tests only? (Just an idea)

**Comment by GorgiAstro** [comment]
You're right, it makes sense to set up a separate repository for testing with external tools. 
How to include the up-to-date version of the main repo in the test repo? Via a subtree?
(Let's open a separate ticket I guess? :smile: )

**Comment by Juanlu001** [comment]
No need to open a separate ticket, we can continue the discussion here :)

Perhaps we don't even need to do such a thing, see for example: http://www.astropy.org/coordinates-benchmark/summary.html (repository: https://github.com/astropy/coordinates-benchmark)

**Comment by GorgiAstro** [comment]
If I understand correctly, the `.travis.yml` file clones the main git and installs the dependencies? 

* How can a normal user (and not Travis CI) install the same environment? By typing manually the same commands?
* Does it support switching branches on the main git? It would be good to be able to test multiple branches of the main git.

**Comment by GorgiAstro** [comment]
I am starting back to work on this. What is the status with the separate repository for tests & benchmarks?

Reading the new issues, there are a few that can be tested with Orekit:

- https://github.com/poliastro/poliastro/pull/719
- NRLMSISE-00 in https://github.com/poliastro/poliastro/issues/702

**Comment by Juanlu001** [comment]
Hi @GorgiAstro, thanks a lot for staying around! :grin: I started drafting some structure in https://github.com/poliastro/validation/ a while ago.

This week we have OSCW (are you around?) so I will focus on fixing some issues in the codebase (outdated dependencies, CI failing etc) and preparing [my workshop](https://indico.oscw.space/event/3/contributions/78/) so I won't be able to pay a lot of attention to this, but my plan is to get back to work after I'm back home again.

**Comment by GorgiAstro** [comment]
Thanks, I took a look at the repo. 

I will create an `orekit` folder, similar to the `vallado` folder. 

Looks like the `tox` setup in the root folder only does code analysis and does not install nor test anything, so can I just add the instructions to install the `conda` environment in the `orekit` folder? If however we want to install the `conda` environment using `tox`, we need something like https://github.com/tox-dev/tox-conda (I haven't tried it though).

**Comment by GorgiAstro** [comment]
In case anyone tries to run the Orekit test cases (still in a private branch), beware that the Python wrapper does not work with doctest at the moment, the test cases will return errors&warnings. This is probably due to JCC, the issue is being investigated by the kind Petrus: https://issues.apache.org/jira/browse/PYLUCENE-51

**Comment by astrojuanlu** [comment]
@jorgepiloto started working on this as part of our NumFOCUS Small Development grant, see latest activity on https://github.com/poliastro/validation/. Thanks @GorgiAstro for pioneering this work! Closing
