### ISSUE TITLE
Behaviour of numpy.linalg.cond

### ISSUE THREAD

**Issue by celinew1221** [poliastro/poliastro#647]
```
@jit(nopython=True, error_model='numpy')
def is_inv(matrix):
    cond_threshold = 1 / np.finfo(np.float64).eps
    cond = np.linalg.cond(matrix)
    return cond < cond_threshold
```
I want to check if a matrix is singular or not because I can't try and catch the singular error in numba. However, np.linalg.cond is now giving my **division by zero** error. I used error_model='numpy', but it still gives me a python semantic error.

**Comment by celinew1221** [comment]
Nvm problem solved, I need to go into targets/linalg/cond_impl to change s[0] / s[-1] division to np.true_divide(s[0], s[-1]) for p=None. Same to the other options too.

**Comment by Juanlu001** [comment]
Hi @celinew1221, how is this related to poliastro?

**Comment by Juanlu001** [comment]
Closing this.

**Comment by celinew1221** [comment]
Sorry that was an accident posting here lol.
