### ISSUE TITLE
Cannot sample orbits around the Moon

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#649]
Code to reproduce:

```
In [1]: from poliastro.bodies import Moon                                                                                               

In [2]: from poliastro.twobody import Orbit                                                                                             

In [3]: from astropy import units as u                                                                                                  

In [4]: o1 = Orbit.circular(Moon, 100 * u.km)                                                                                           

In [5]: o1.sample()                                                                                                                     
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/Development/poliastro/poliastro-library/src/poliastro/frames.py in get_frame(attractor, plane, obstime)
    254     try:
--> 255         frames = _FRAME_MAPPING[attractor]
    256     except KeyError:

KeyError: Moon (☾)

During handling of the above exception, another exception occurred:

NotImplementedError                       Traceback (most recent call last)
<ipython-input-6-5515a447cc0b> in <module>
----> 1 o1.sample()

~/Development/poliastro/poliastro-library/src/poliastro/twobody/orbit.py in sample(self, values, min_anomaly, max_anomaly, method)
   1042 
   1043         time_values = self._generate_time_values(nu_values)
-> 1044         return propagate(self, time.TimeDelta(time_values), method=method)
   1045 
   1046     def _generate_time_values(self, nu_vals):

~/Development/poliastro/poliastro-library/src/poliastro/twobody/propagation.py in propagate(orbit, time_of_flight, method, rtol, **kwargs)
    225     # If the frame supports obstime, set the time values
    226     kwargs = {}
--> 227     if "obstime" in orbit.frame.frame_attributes:
    228         kwargs["obstime"] = orbit.epoch + time_of_flight
    229     else:

~/Development/poliastro/poliastro-library/src/poliastro/twobody/orbit.py in frame(self)
     99         """
    100         if self._frame is None:
--> 101             self._frame = get_frame(self.attractor, self._plane, self.epoch)
    102 
    103         return self._frame

~/Development/poliastro/poliastro-library/src/poliastro/frames.py in get_frame(attractor, plane, obstime)
    256     except KeyError:
    257         raise NotImplementedError(
--> 258             "Frames for orbits around custom bodies are not yet supported"
    259         )
    260 

NotImplementedError: Frames for orbits around custom bodies are not yet supported
```

Perhaps instead of being so strict, we could raise a warning and "just" return the `CartesianCoordinates`. And in that case, perhaps `poliastro.twobody.propagation.propagate` should ignore the frame, and just produce coordinates:

https://github.com/poliastro/poliastro/blob/1d366845e13d7bac59cdd11a3178fe2126d46827/src/poliastro/twobody/propagation.py#L225-L240

**Comment by dragonlost** [comment]
Hello i need your help.
I tried to produce an orbit around the moon but I have the following problem:

Orbit start generate
(<Quantity 1. AU>, <Quantity 0.>, <Quantity 0. deg>, <Quantity 0. deg>, <Quantity 0. deg>, <Quantity 0. deg>)
Propagation :   0%|                                | 0/31535999 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/sdurand/miniconda3/lib/python3.7/site-packages/poliastro/frames.py", line 256, in get_frame
    frames = _FRAME_MAPPING[attractor]
KeyError: Moon (☾)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main_easytraj.py", line 72, in generate_click
    ke.easy_trajectory_run(config_file, sat_name="sat", sat_id="sat_0", origin="DOCKS")
  File "/home/sdurand/git/boulo/DOCKS/Module/Easy-trajectory/kepler_propagator.py", line 116, in easy_trajectory_run
    custom_center_bodie_mu=custom_mu, j2_earth=j2, plot=0)
  File "/home/sdurand/git/boulo/DOCKS/Module/Easy-trajectory/kepler_propagator.py", line 276, in keplerian_orbit
    ss = ss.propagate(time_flight)
  File "/home/sdurand/miniconda3/lib/python3.7/site-packages/poliastro/twobody/orbit.py", line 713, in propagate
    coords = propagate(self, time_of_flight, method=method, rtol=rtol, **kwargs)[0]
  File "/home/sdurand/miniconda3/lib/python3.7/site-packages/poliastro/twobody/propagation.py", line 225, in propagate
    if "obstime" in orbit.frame.frame_attributes:
  File "/home/sdurand/miniconda3/lib/python3.7/site-packages/poliastro/twobody/orbit.py", line 92, in frame
    self._frame = get_frame(self.attractor, self._plane, self.epoch)
  File "/home/sdurand/miniconda3/lib/python3.7/site-packages/poliastro/frames.py", line 259, in get_frame
    "Frames for orbits around custom bodies are not yet supported"
NotImplementedError: Frames for orbits around custom bodies are not yet supported

**Comment by dragonlost** [comment]
I also have this problem when I try to propagate an orbit around a custom object

**Comment by Juanlu001** [comment]
@dragonlost can you please try again after `https://github.com/poliastro/poliastro/archive/master.zip`?

**Comment by Juanlu001** [comment]
(Edit: corrected `pip install` command)

**Comment by dragonlost** [comment]
nice is fixe !

**Comment by Juanlu001** [comment]
We ended up returning a representation in `sample()` for all cases, so this shouldn't be a problem going forward.

**Comment by Juanlu001** [comment]
(See #797)
