### ISSUE TITLE
Evaluate matrix transformation for pqw2ijk

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#668]

**Comment by wselwood** [comment]
When converting orbital elements to vectors at 
https://github.com/poliastro/poliastro/blob/master/src/poliastro/core/elements.py#L145
`poliastro/core/elements.pqw2ijk` is called twice which then performs three rotate operations.

It might be worth investigating creating a single rotation matrix and then applying it to both vectors. 
Found a significant speed improvement with the following change: https://github.com/wselwood/orbcalc/commit/8bbd7e675f9b107ab8d4d6033f54d8d7b3664897#diff-a13637c470ee8875e553be46bad50435

(Though I do not suggest you try and copy the faster rotation matrix method its horrible)

**Comment by wselwood** [comment]
Did a quick test. Some improvement with out using a horrible quick rotation matrix creation.

Master:
wselwood@XXXXXXXXX:/git/poliastro$ python -m timeit "from poliastro.core.elements import coe2rv; coe2rv(132712442099.00002, 6, 0.6, 0.8, 1.4, 6.4, 4)"
10 loops, best of 3: 5.68 usec per loop

Test:
(venv) wselwood@XXXXXXXXX:/git/poliastro$ python -m timeit "from poliastro.core.elements import coe2rv; coe2rv(132712442099.00002, 6, 0.6, 0.8, 1.4, 6.4, 4)"
10 loops, best of 3: 4.67 usec per loop

If you want I can send a pr later.

**Comment by Juanlu001** [comment]
> If you want I can send a pr later.

Sure, that would be great!

**Comment by wselwood** [comment]
https://github.com/poliastro/poliastro/pull/669 should mostly resolve this.

**Comment by Juanlu001** [comment]
Closed in #669.
