### ISSUE TITLE
Provide a way to change orbit attractor

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#676]
See for example https://gist.github.com/Juanlu001/0a730a29c6aadf69638f909b2895a006

**Comment by Juanlu001** [comment]
As I wrote in #679:

> The original intent of the function was to change the attractor for the Galilean moons from the Sun to Jupiter. This makes sense, because the real attractor of these moons is Jupiter. In fact, if one takes the data of .from_horizons and just .propagate, the results are completely wrong, because the propagation happens as if Jupiter does not even exist.

> I think having the possibility to change the attractor of any orbit in this way is quite dangerous. I should have thought about the problem when writing the issue.

However, there is one place where we would benefit from a way to change the attractor:

https://docs.poliastro.space/en/stable/examples/Catch%20that%20asteroid!.html

We changed from an heliocentric orbit to a geocentric orbit **to study the osculating orbit with respect to the Earth**. The important thing to note here is that, while the object of study is within the sphere of influence of the Earth, this makes total sense, and is in fact the basis of the patched conics method.

Therefore, this is a tricky issue because _sometimes_ it makes sense to change the attractor, and sometimes it doesn't. We need to discuss in detail what cases are there before providing an error-prone API.

**Comment by Juanlu001** [comment]
Let's imagine the Sun and any planet, and some body in the Solar System.

* If the body is in a **closed** orbit around the planet, it **always** make sense to have the planet as the attractor.
  - Propagating around the planet ignores the influence of any other body of the Solar System unless explicitly accounted through perturbations, and therefore gives almost perfect results.
  - Propagating around the Sun ignores the influence of the planet and therefore transforms a spiral heliocentric orbit into a elliptic orbit.
* If the body is in an **open** orbit around the planet, it **does** make sense to have the planet as the attractor _up to a certain point_, and it **does** make sense to have the Sun as the attractor.
  - Propagating around the planet is correct until the body escapes the planet sphere of influence, and therefore gives correct results which start degrading from that point.
  - Propagating around the Sun assumes the body already escaped the planet sphere of influence, which gives correct results within the patched conics assumption.
* If the body is in an orbit around the Sun (regardless of its nature), it **almost always** makes sense to have the Sun as the attractor.
  - Propagating around the Sun correctly assumes that the main gravitational influence is the Sun, **but** it ignores any flybys the object might make around nearby planets, and therefore it gives correct results within the patched conics assumption.

**Comment by Juanlu001** [comment]
Almost there in #679. We should simplify the Florence notebook accordingly.

**Comment by Juanlu001** [comment]
@jorgepiloto said offline that precisely the Florence notebook is an example where the asteroid was _outside_ of the sphere of influence of the Earth, therefore our new APIs will fail. Perhaps we would need an extra parameter, `force=False` or `fail_outside_soi=True`, that the user could override if they really wanted to.

**Comment by jorgepiloto** [comment]
Sure! I think the `force=True` key argument is really explicit

**Comment by Juanlu001** [comment]
We fixed this in #729!
