### ISSUE TITLE
tox is not in poliastro/[dev]

### ISSUE THREAD

**Issue by shreyasbapat** [poliastro/poliastro#687]
🐞 **Problem**

The tox should be one of the dependencies in poliastro setup in dev. 

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>
  
```bash
# Paste your output here:

```
</details>

* `python -c "import poliastro.testing; poliastro.testing.test()"`

<details>

```bash
# Paste your output here:

```
</details>

🎯 **Goal**

💡 **Possible solutions**
Add tox in `setup.cfg` under dev.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Good catch @shreyasbapat!

**Comment by Juanlu001** [comment]
I am working in fixing some stuff in tox, so I will close this myself.
