### ISSUE TITLE
small errata in orbit documentation

### ISSUE THREAD

**Issue by WolfsSky** [poliastro/poliastro#689]
I found a small msitake in the orbit documentation at https://docs.poliastro.space/en/stable/api/safe/twobody/orbit.html#poliastro.twobody.orbit.Orbit where

**a**
Semilatus rectum.

**p**
Semimajor axis.

Of course it should be **the other way around**. I see that this mistake has been reported before, but it seems to be still there in the documentation. The code is correct though.

**Comment by Juanlu001** [comment]
Hi @WolfsSky, thanks for reporting! If you look at the `latest` documentation this has already been fixed, so it will become stable next month, with poliastro 0.13 https://docs.poliastro.space/en/latest/api/safe/twobody/orbit.html#poliastro.twobody.orbit.Orbit we probably won't release a 0.12.1, so I'm closing. If you find anything else, please open a new issue!
