### ISSUE TITLE
Question: multiple perturbations in propagation

### ISSUE THREAD

**Issue by WolfsSky** [poliastro/poliastro#690]
Is it possible to add for example both atmopsheric drag and the J2 effect into the perturbations for the orbit propagation? 

Maybe it is documented somewhere, but I can not find it.

**Comment by Juanlu001** [comment]
Hi @WolfsSky, for that you can create a custom perturbation function that adds both effects:

```
def a_d(
    t0, state,
    k, J2, R
    C_D, A, m, H0, rho0
):
    return J2_perturbation(t0, state, k, J2, R) + atmospheric_drag(t0, state, k, R, C_D, A, m, H0, rho0)

```

can you confirm it works?

**Comment by WolfsSky** [comment]
Can confirm that the RAAN and altitude are changing! Thanks a lot.

Would be handy to add this functionality I think. I am fairly new to poliastro and haven't worked a lot with Python lately, so I would not reccommend to let me do it though.

**Comment by WolfsSky** [comment]
I really would like to add it to https://docs.poliastro.space/en/stable/examples/Natural%20and%20artificial%20perturbations.html, but I have no clue how to do this.

**Comment by Juanlu001** [comment]
If you have experience with Jupyter notebooks, it corresponds to this one https://github.com/poliastro/poliastro/blob/master/docs/source/examples/Natural%20and%20artificial%20perturbations.ipynb

**Comment by Juanlu001** [comment]
Addressing this in #691
