### ISSUE TITLE
Issue: Air Drag possibly inconsistent and tolerance problems

### ISSUE THREAD

**Issue by WolfsSky** [poliastro/poliastro#694]
WILL EDIT ISSUE LATER
Comparison of poliastro Cowell, Python sgp4 and TLE from Tiangong 1. 

What can be seen is that for a torelance of 1e-5 the orbit decays, but for 1e-7 the orbit does not. Of course one needs to take into account the less accurate SGP4 than Cowell, however, based on the TLE's Cowell seems to be inaccurate.

Relative Tolerance = 1e-5
![Test1Drag1e5](https://user-images.githubusercontent.com/6907283/59194378-22ac2c00-8b89-11e9-98a9-680d20e7fa0c.png)

Relative Tolerance = 1e-7
![Test1Drag1e7](https://user-images.githubusercontent.com/6907283/59194379-22ac2c00-8b89-11e9-97ea-fa2b44b83e32.png)

🐞 **Problem**

The relative Cowell tolerance has an influence on the outcome of the propagation. SGP4 is known to be inconsistent for long propagation times, however Cowell/Dopri853 should be rather accurate/similar to TLE data.

🖥 **Please paste the output of following commands**

* `conda info -a` (only if you have conda)
* `conda list` (only if you have conda)
* `pip freeze`

<details>
  
```bash
# Paste your output here:

```
</details>

* `python -c "import poliastro.testing; poliastro.testing.test()"`

<details>

```bash
# Paste your output here:

```
</details>

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment]
Hmmm interesting. Please keep us posted when you're done with the analysis, this is important.

**Comment by WolfsSky** [comment]
**Finding 1**
What I find the most peculiar is the too long **Linear decay**, compared to TLE and SGP4. The atmospheric model uses a scale height of 8 km with a rho_0=1.3 kg/m^3. This is true for an atmosphere till 100 km, but above that it is enormous erroneous compared to for example the data found in Space Mission Analysis and Design by Wertz for higher altitudes:
For example, at 300 km the current code will find a density of 6.73e-17 kg/m^3 while Wertz gives an average value of 1.95e-11. poliastro thus computes a factor 1e-6 lower atmospheric drag.

**Finding 2**
There is something going on with the rtol value compared to the stepsizes of the time of flights (tofs). Same propagations with different rtols lead to significant different results, to the point where for rtol=1e-7 no decay happens, where in TLE data the satellite has already re-entered. Reducing the rtol in my situation to 1e-5 lets the satellite re-enter more close to the TLE's. 

It seems a high rtol makes the solution too stiff? Although I would expect the propagator to make smaller steps to account for this. Maybe a minimal step size in the settings lets the propagator use that with the allowed rtol, and thus non-accurate results? (as in rtol is adhered to, but a minimal step size is used for that, which should actually be lower than that minimal stepsize) Not sure how this propagator works exactly.

I think this normally is not an issue, but decaying satellites change their orbit significantly.

Also I had to implement an own termination condition for below 250km attitude, otherwise the propagator gets stuck.

**Comment by Juanlu001** [comment]
Labeling this as a bug, we have to investigate it further.

> Not sure how this propagator works exactly.

The Cowell method is described in many places, for example Vallado "Fundamentals of Astrodynamics and Applications". We use a high order Runge-Kutta method to integrate the equations of motion, specifically Dormand-Prince 8(5,3) (`DOP853`). We did not do a formal validation of our implementation, although you might be interested in trying the new one that will (hopefully) come with SciPy 1.4:

https://github.com/scipy/scipy/pull/10173
https://github.com/poliastro/poliastro/pull/675

> Also I had to implement an own termination condition for below 250km attitude, otherwise the propagator gets stuck.

How did you do it? In theory the new `solve_ivp` function accepts events, so perhaps that would be a nice example of how to use them.

**Comment by WolfsSky** [comment]
**More on finding 1**
I don't think the tolerance is the problem anymore, I just got more similar results with low tolerance because of the wrong atmospheric model. Do not have the Howard Curtis book myself, but it would be inconsistent if they use the normal exponential atmosphere above 100km. 
Now I get under and over estimations of the decay with a rtol of 1e-9, depending on what atmosphere I use (for that matter 1e-7 and 1e-9 almost give the same results, which is more as expected). 

I found this website: http://www.braeunig.us/space/atmmodel.htm, which gives the reference atmospehre up till 1000 km, based on a report by Jacchia (1971). 120km - 1000km tables: http://www.braeunig.us/space/pdf/Atmosphere_120-2K.pdf. Sadly the density is depending on solar maximum and exothermic temperature, but it is anyway more accurate than the exponential atmosphere used in the code.
________________________

> How did you do it?
I got the propagator out of the loop and made my own loop and just checked the altitude to make it break the loop. So no `solve_ivp` was used, still getting the hang of poliastro, thus no advanced things yet.

**Comment by Juanlu001** [comment]
> because of the wrong atmospheric model

Oh, you're right! This atmospheric model that poliastro has is a simple, exponential one. It is more appropriate for "generic" stuff, perhaps for other planets (and especially big ones). I opened a new issue to implement a better model: https://github.com/poliastro/poliastro/issues/702

**Comment by WolfsSky** [comment]
It works for a lot of simulations, for example for steeper re-entries (did my master thesis on that, written in octave though), but this all takes part at about maximum 100 km. But yes, for now the atmospheric drag is off by a lot. Changing it now manually to other values close to the ones in SMAD:
![PredicLine_300TLEs_10days](https://user-images.githubusercontent.com/6907283/59448309-25b35080-8e05-11e9-8820-3d9640d5da1d.png)
(no clue why inclination an eccentricity are so far off, relatively small changes though)

**Comment by Juanlu001** [comment]
@jorgepiloto is adding more atmospheric models in #738.

**Comment by Juanlu001** [comment]
Any chance we could test this again with the models @jorgepiloto added in #738?

**Comment by jorgepiloto** [comment]
The [link]http://www.braeunig.us/space/atmmodel.htm) that @WolfsSky shared is going to be really useful to fully implement pressure and density in `COESA76` up to 1000km. After implementing locally the equation they use to compute previous state variables it seems to work fine. Pull request is coming soon.

On the other hand, they also include the martian atmosphere, really cool :heart_eyes:

**Comment by jorgepiloto** [comment]
Hi @WolfsSky, could you please share any gist or code to reproduce this issue and check if #756 solves it?

**Comment by jorgepiloto** [comment]
Hi @WolfsSky, I am reviewing old issues and was wondering if you still have any piece of code so this issue can be reproduced and checked against the new atmospheric models.

**Comment by astrojuanlu** [comment]
I am sure posting this analysis needed a lot of code: plotting the individual elements, comparing with TLEs... we will be glad to see that code published somewhere (in some personal repository perhaps). In the meanwhile, we added a new atmospheric model and this issue has been inactive for a while, so I will close it. Feel free to comment here or in the chat.
