### ISSUE TITLE
Include more IAU-WGCCRE constants

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#703]
Follow-up from https://github.com/poliastro/poliastro/pull/674#discussion_r290166801

The constants from The IAU Working Group on Cartographic Coordinates and Rotational Elements to Astropy. They contain things like ellipsoidal and mean radiuses, reference meridians, rotational velocities for planets and some minor bodies... The IAU-WGCCRE publishes reports that contain updated values of these constants:

https://astrogeology.usgs.gov/groups/IAU-WGCCRE

We are already using the radiuses of the planets and also the rotational elements, and we could include the ellipsoid parameters as well.

We decided it would be better to have them outside Astropy: https://groups.google.com/d/msg/astropy-dev/Bpmxlfp9z30/S6VVrEBWBQAJ

Related: #109

**Comment by Juanlu001** [comment]
@Sedictious already updated the radii values, and also added some new ones. Next step: reference meridians and rotational velocities.

**Comment by astrojuanlu** [comment]
The radiuses are already in https://github.com/poliastro/poliastro/blob/master/src/poliastro/constants/general.py and we already have the rotational periods in https://github.com/poliastro/poliastro/blob/master/src/poliastro/constants/rotational_elements.py.

Regarding the reference meridians, as it can be seen in https://github.com/poliastro/poliastro/blob/master/src/poliastro/frames/fixed.py and the WGCCRE report itself, some of them are dynamic, so it's not practical to stablish them as constants. Therefore, I'm closing this issue as finished.
