### ISSUE TITLE
Have nice front page

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#712]
Inspired by: https://twitter.com/mrocklin/status/1143276002895966208

![Screenshot_2019-06-25 Twitter Publish](https://user-images.githubusercontent.com/316517/60055778-08bd2e00-96df-11e9-91df-84176f0d38b0.png)

**Comment by Juanlu001** [comment]
Bokeh new front page https://bokeh.org/

**Comment by astrojuanlu** [comment]
Let me expand this issue a little bit:

* https://www.poliastro.space/ and https://poliastro.space/ lead nowhere. Therefore, there's not one "canonical", main website of poliastro
* https://blog.poliastro.space/ has a small banner on top to redirect to https://docs.poliastro.space/en/latest/, but not the other way around. Therefore, unless you know it, the blog is effectively "hidden".
* Because of how I set up GitHub pages, benchmarks are in https://blog.poliastro.space/benchmarks/ :man_facepalming: what does the blog has to do with this? They should be in https://poliastro.space/benchmarks, https://benchmarks.poliastro.space/, or similar

**Comment by Syed-Osama-Hussain** [comment]
@astrojuanlu can you elaborate how the site is hosted? Seems like the sub-domains are confusing. I've had some experience with hosting and web development. Maybe I can help?

**Comment by astrojuanlu** [comment]
At the moment, https://github.com/poliastro/poliastro.github.io/ is deployed in blog.poliastro.space. Therefore, I think we need to:

* Keep poliastro.github.io only for the front page, and deploy it in www.poliastro.space
* Have a separate project for the blog, and deploy it in blog.poliastro.space
* Deploy the benchmarks in benchmarks.poliastro.space

How does this sound?

**Comment by Syed-Osama-Hussain** [comment]
Yes, this sounds nicer and clearer!

**Comment by shreyasbapat** [comment]
> Deploy the benchmarks in benchmarks.poliastro.space

This is independent of the front page. If you make proper DNS Entries for the subdomain, and add a custom domain for the deployment in github pages, shouldn't that work?

**Comment by astrojuanlu** [comment]
> This is independent of the front page. If you make proper DNS Entries for the subdomain, and add a custom domain for the deployment in github pages, shouldn't that work?

Oh wow, maybe you're right... :flushed:  testing it right now!

**Comment by astrojuanlu** [comment]
It works :sob: Thanks @shreyasbapat! One more problem solved!

**Comment by astrojuanlu** [comment]
Missing:

- Switch to `http://www.poliastro.space` and `https://www.poliastro.space`
- Add redirect from `http://poliastro.space` and `https://poliastro.space`
- Redirect old links?

**Comment by astrojuanlu** [comment]
Redirected everything to https://www.poliastro.space, enforced HTTPS, working on having the apex domain (https://poliastro.space) working as well. If you see links to `blog.poliastro.space`, please open issues or fix them directly. Closing!
