### ISSUE TITLE
Add new two-body propagators

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#714]
(Not to be confused with #285)

It's already well known that some of our propagators have issues (see for example #475). Tricky stuff includes:

* Near parabolic orbits
* Very long propagation times
* Very low pericenters
* Others?

It would be nice to have more propagators (and also to benchmark them, see #253).

**Comment by Juanlu001** [comment]
@giordano points us to this interesting method: http://dx.doi.org/10.1007/BF00691917

> Kepler's Equation is solved over the entire range of elliptic motion by a fifth-order refinement of the solution of a cubic equation. This method is not iterative, and requires only four transcendental function evaluations: a square root, a cube root, and two trigonometric functions. The maximum relative error of the algorithm is less than one part in 10^18, exceeding the capability of double-precision computer arithmetic. Roundoff errors in double-precision implementation of the algorithm are addressed, and procedures to avoid them are developed.

Definitely looks very promising! @jorgepiloto is surely looking into it :wink:

**Comment by jorgepiloto** [comment]
I have implemented the previous Kepler equation solver in [this gist](https://gist.github.com/jorgepiloto/8d572ea4bb50c9ffed93c56dfaa81160).

However, when trying to solve for the vectors in #474 it seems to get stucked at the function `nu_to_M`. This may be a clue to what is going one with those vectors :rocket:

**Comment by Juanlu001** [comment]
If it gets stuck, run the code again after exporting `NUMBA_DISABLE_JIT=1`. In my experience, numba sometimes "get stuck" in infinite loops because exceptions are not properly handled.

**Comment by Juanlu001** [comment]
Relevant: https://github.com/poliastro/poliastro/pull/394/

**Comment by jorgepiloto** [comment]
Here are some interesting papers that I have collected during the last months in which different methods for solving Kepler's equation are shown:

* [Robust resolution of Kepler’s equation in all eccentricity regimes](https://link.springer.com/article/10.1007/s10569-013-9476-9)

* [Accurate Kepler equation solver without transcendental function evaluations](https://www.researchgate.net/publication/288133262_Accurate_Kepler_equation_solver_without_transcendental_function_evaluations)

* [A Fast Procedure Solving Gauss' Form of Kepler's Equation](https://www.researchgate.net/publication/226072650_A_Fast_Procedure_Solving_Gauss%27_Form_of_Kepler%27s_Equation)

* [Unified Symbolic Algorithm of Gauss Method for Near-Parabolic Orbits](https://www.researchgate.net/publication/226717033_Unified_Symbolic_Algorithm_of_Gauss_Method_for_Near-Parabolic_Orbits)

* [Kepler Equation solver non iterative](https://link.springer.com/article/10.1007%2FBF00691917)

* [Efficient solution of Kepler's equation via hybrid and digital  approaches](https://www.researchgate.net/publication/304675892_EFFICIENT_SOLUTIONS_OF_KEPLER%27S_EQUATION_VIA_HYBRID_AND_DIGITAL_APPROACHES)

* [Solving Kepler’s equation via Smale’s 𝛼-theory](https://link.springer.com/article/10.1007/s10569-014-9545-8)

**Comment by Juanlu001** [comment]
The first one we already know, look for "Farnocchia" in https://github.com/poliastro/poliastro/blob/ee41c682f/src/poliastro/twobody/angles.py (and https://github.com/poliastro/poliastro/pull/394)

**Comment by Juanlu001** [comment]
Also, when linking papers, if you can try to find for the DOI. It will make it easier to download them later :wink:

**Comment by jorgepiloto** [comment]
The DOIs for the papers were added and their current status updated regarding if totally, partially or not implemented :+1:

**Comment by Juanlu001** [comment]
Awesome!

**Comment by Juanlu001** [comment]
Improving our shiny new propagators is a non-issue (we can do it gradually over time, and also they are very heterogeneous) and you properly noted with `TODO` marks and `NotImplementedError` the parts we could in theory improve, so I'm closing this.
