### ISSUE TITLE
Strange behaviour when plotting some orbits

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#726]
🐞 **Problem**

After working in the example for `Multirevolutions in Lambert's problem` it was found a strange behavior when plotting one of the orbits. The code to reproduce this issue can be found [here](https://gist.github.com/jorgepiloto/76579262d741ce1b4d88d55f6c912d09).

![issue_figure](https://user-images.githubusercontent.com/28702884/61204231-f4bc8900-a6ec-11e9-910f-c2980fa3e0d3.png)

🎯 **Goal**

* Get rid of those straight lines so the orbit plot appears as it should be.

💡 **Possible solutions**

* Check what happens if using the the `plot_trajectory()` method. Does the orbit plot show the same behavior?
* Compare with another propagator. Maybe something wird is going on when propagating this orbit for some points.

**Comment by jorgepiloto** [comment]
As I suspected, if using `from poliastro.plotting.core import OrbitPlotter2D` this behavior is not shown

**Comment by Juanlu001** [comment]
Could you please check again with both `Static` and `2D` to see if it still happens?

**Comment by astrojuanlu** [comment]
This bug is not present in current `master`:

![Figure_1](https://user-images.githubusercontent.com/316517/80285046-80eee880-8722-11ea-8405-7f8343f2e27b.png)

Closing!

**Comment by jorgepiloto** [comment]
You are right @astrojuanlu! When checked locally, everything seem to work properly. However, the latest docs will need to be run again to show this new behavior. Related with checklist from #931
