### ISSUE TITLE
Upload packages for Python 3.5

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#74]

**Comment by newlawrence** [comment]
Please, submit a **conda jplephem** package to your channel and we're done 😊.

**Comment by newlawrence** [comment]
**Python 3.5** with **NumPy 1.9** will work now, [see](https://github.com/poliastro/poliastro/pull/76).

**Comment by Juanlu001** [comment]
This comment https://github.com/conda/conda-build/pull/650#issuecomment-160681665 outlines all the possible cases regarding packages depending on NumPy. jplephem is a pure-python package and so is poliastro, so we shall be very careful of artificially pinning the numpy version - it's mostly harmless, but expensive. I'm still studying this topic.

**Comment by Juanlu001** [comment]
Well, it seems matplotlib is broken for Python 3.5 on Anaconda, so poliastro packages will have to wait a bit. ContinuumIO/anaconda-issues#573

**Comment by Juanlu001** [comment]
I have tried reproducing the problem above in a different Linux box and I can't, so it has to be some specific issue in my home machine. I'll try building Python 3.5 packages today.

**Comment by Juanlu001** [comment]
The packages will be uploaded when making the release, as usual. This is no longer a work in progress and will be closed when poliastro 0.4 is released.

**Comment by Juanlu001** [comment]
Python 3.5 packages were updated at the time of the last release, closing this.
