### ISSUE TITLE
Transonic, Numba, Cython, Pythran

### ISSUE THREAD

**Issue by paugier** [poliastro/poliastro#742]
It is not a feature request!

I'm preparing my participation to EuroScipy 2019 and I read your abstract on "Can we make Python fast without sacrificing readability? numba for Astrodynamics".

During EuroScipy, I'm going to present [Transonic](https://transonic.readthedocs.io), a project strongly related to the subject of your presentation.

Transonic was first developed to use very easily Pythran. Now, we're working on a different goal, namely to be able to use Cython, Pythran or Numba with the same (readable and elegant) code. We should have a serious prototype in September for EuroScipy.

I think Transonic (and Pythran) could be useful for Poliastro. It would be great if you can have a look at these projects before EuroScipy. I hope we will have the opportunity during next EuroScipy to meet and chat about these subjects / projects.

**Comment by Juanlu001** [comment]
Hi @paugier, sorry for the super late reply! I will definitely take a look at Transonic, excited to meet you there :)

**Comment by astrojuanlu** [comment]
Sorry but it's unlikely that this ever happens. I think it's easier for poliastro to just piggyback on numba and leverage numba-specific features without depending on intermediate layers. Also, we are thinking about accelerating some parts of poliastro for GPU computation, and I prefer we take a lower level approach. Thanks anyhow for the suggestion and best luck with Transonic!
