### ISSUE TITLE
When will poliastro ver. 0.13.0 become available from Anaconda?

### ISSUE THREAD

**Issue by OrbitalMechanic** [poliastro/poliastro#749]
When will poliastro ver. 0.13.0 become available from Anaconda? At the time of this note, only ver. 0.12.0 is available.

Lastly, what is the recommended procedure to update poliastro from 0.12.0 to 0.13.0?

**Comment by Juanlu001** [comment]
Hi @OrbitalMechanic! I have to make some tweaks in [the automatic pull request](https://github.com/conda-forge/poliastro-feedstock/pull/29), I hope it's available today. Thanks a lot for the enthusiasm! :smile:

**Comment by Juanlu001** [comment]
poliastro 0.13.0 should be available in conda-forge right now:

https://anaconda.org/conda-forge/poliastro

However, I will likely upload a new build when czml3 is available on conda as well:

https://github.com/conda-forge/staged-recipes/pull/9070

To upgrade poliastro from 0.12.0, assuming you had it in conda, the best way would be:

```
conda update poliastro -c conda-forge
```
