### ISSUE TITLE
nu_to_M different results for same inputs in degree or radians

### ISSUE THREAD

**Issue by WolfsSky** [poliastro/poliastro#751]
The function `nu_to_M` gives different results when inputting *nu* in degrees or radians.
Doesn't say the input can not be degrees.

nuu=150 (in degrees)
ecc=0.08
np.rad2deg(nu_to_M((np.deg2rad(nuu)*u.rad), (ecc)))%360
OUT: 145.16778101222044

(nu_to_M(((nuu*u.deg)), (ecc)))%360
OUT: 150.10969327328553

💡 **Possible solutions**

- add error message
- add check for degrees or radians within function
- add radians requirement in documentation

**Comment by jorgepiloto** [comment]
Hi @WolfsSky,

the `poliastro.angles.nu_to_M` function from the high-level API (the one accepting `astropy.units.Quantity` inputs) works fine. Furthermore, if not passing a `Quantity` instance it raises an error. If you are using the `poliastro.core.angles.nu_to_M` your input should be always in radians.

I wrote a [small gist](https://gist.github.com/jorgepiloto/6383a5b67811befdc64da06aa1b5068d) to show this behaviour.

**Comment by WolfsSky** [comment]
Ah! That makes sense, I did indeed use the core, and not the angles version. Thanks for clarifying :)

**Comment by jorgepiloto** [comment]
Ups, sorry! In fact it is `poliastro.twobody.angles` the one for the high-level API :relaxed:

**Comment by WolfsSky** [comment]
Yes I tried from `poliastro.angles` but it failed then, but thanks!
