### ISSUE TITLE
Ability to pass additional propagation arguments to sample(), such as J2

### ISSUE THREAD

**Issue by mc-allen** [poliastro/poliastro#770]
Currently it doesn't seem like there is a way to call orbit.sample() with J2 propagation. It would be great to extend the sample() API to allow passing arguments that can be forwarded to the propagator functions.

Right now, I am achieving this by monkey patching, which is certainly not ideal.

**Comment by Juanlu001** [comment]
Hi @mc-allen, thanks a lot for your interest in poliastro!

In our last review, we realized that the `Orbit.sample` method was doing too much stuff and in fact we wanted to prevent this sort of catch-all behavior. The way to do what you are thinking involves using a lower level function, `poliastro.twobody.propagation.propagate`, which returns output in the same format as `sample`. Here you can see some examples:

https://docs.poliastro.space/en/stable/examples/Natural%20and%20artificial%20perturbations.html

Please let me know if that fulfills your requirement.

**Comment by astrojuanlu** [comment]
Closing after lack of activity, please feel free to open a new issue or ask this one to be reopened!
