### ISSUE TITLE
propagate Earth orbit to 1 Myr

### ISSUE THREAD

**Issue by Tarlan0001** [poliastro/poliastro#779]
Is it possible to propagate the Earth otbit to 1 Myr to the future using poliastro?

**Comment by jorgepiloto** [comment]
Hi @Tarlan0001 , sorry for this late answer. Before going into code:

> If you want to solve for the position of a Solar System Body at any time you can't just solve for today's position and then apply Kepler's law. This is because you are no longer under the two-body assumption and therefore it is not possible to neglect small body mass against its attractor, in this case the Sun. **You should look to corresponding body ephemerides at desired time.**

Let us get Earth's position at time equals 1e6 years from now:

```python
from astropy import units as u
from astropy.time import Time
from poliastro.bodies import Earth
from poliastro.twobody import Orbit

EPOCH = Time.now() + 1e6 * u.year
ss = Orbit.from_body_ephem(Earth, EPOCH)
```
This raises the following error:

``` python
>>> ValueError: year 1002040 is out of range
```

This is because `astropy` provides the `ephemerides` for `planets` and obviously they are not valid for years higher than the value raised in the error.

**Comment by Tarlan0001** [comment]
Yes, JPL ephemerides are not available for such a long time. What do you think about numerical propagation of the planets and Sun? -------- Original Message --------Subject: Re: [poliastro/poliastro] propagate Earth orbit to 1 Myr (#779)From: Jorge To: poliastro/poliastro CC: Tarlan0001 ,Mention Hi @Tarlan0001 , sorry for this late answer. Before going into code:

If you want to solve for the position of a Solar System Body at any time you can't just solve for today's position and then apply Kepler's law. This is because you are no longer under the two-body assumption and therefore it is not possible to neglect small body mass against its attractor, in this case the Sun. You should look to corresponding body ephemerides at desired time.

Let us get Earth's position at time equals 1e6 years from now:
from astropy import units as u
from astropy.time import Time
from poliastro.bodies import Earth
from poliastro.twobody import Orbit

EPOCH = Time.now() + 1e6 * u.year
ss = Orbit.from_body_ephem(Earth, EPOCH)
This raises the following error:
>>> ValueError: year 1002040 is out of range
This is because astropy provides the ephemerides for planets and obviously they are not valid for years higher than the value raised in the error.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/poliastro/poliastro/issues/779?email_source=notifications\u0026email_token=AECKWNZ5YQJZ7SYTYKQMKELQNG2ZZA5CNFSM4IZEA22KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOGDKA#issuecomment-538730920",
"url": "https://github.com/poliastro/poliastro/issues/779?email_source=notifications\u0026email_token=AECKWNZ5YQJZ7SYTYKQMKELQNG2ZZA5CNFSM4IZEA22KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOGDKA#issuecomment-538730920",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jorgepiloto** [comment]
You mean the following?

```python
ss0 = Orbit.from_body_ephem(Earth, Time.now())
ssf = ss0.propagate(1e6 * u.year)
```

May I ask you why you want to propagate for such a huge amount of time? Just curiosity, feel free to answer or not :smile:

**Comment by Tarlan0001** [comment]
Well, I'm studying the change in Sun-Earth distance with time.
Would it be possible by means of poliastro? Please, show an example.

**Comment by jorgepiloto** [comment]
You can combine both `poliastro` and `astropy` and get the following:


```python
""" Solves for Sun-Earth distance along time. """

import matplotlib.pyplot as plt
from astropy import units as u
from astropy.coordinates import get_body_barycentric
from astropy.time import Time

from poliastro.util import norm, time_range

# Use poliastro to generate time span
time_span = time_range(start=Time.now(), end=(Time.now() + 10 * u.year))

# Solve for Sun and Earth positions
rr_sun = get_body_barycentric("Sun", time=time_span)
rr_earth = get_body_barycentric("Earth", time=time_span)
rr_distance = [norm(rr.xyz) for rr in (rr_sun - rr_earth)]

# Plotting
plt.plot([t.to_datetime() for t in time_span], [r.value for r in rr_distance])
plt.title("Earth-Sun distance as function of time")
plt.xlabel("Time")
plt.ylabel("Distance in AU")
plt.show()
```


![earth_sun](https://user-images.githubusercontent.com/28702884/66268037-3f0b5d00-e839-11e9-9ad8-818d62ccc92c.png)

**Comment by Tarlan0001** [comment]
Does this propagation consider the effect of all planets of the Solar
System?

**Comment by jorgepiloto** [comment]
Check all possible epehemerides data files at [Astropy - Solar System Epehemerides](https://docs.astropy.org/en/stable/coordinates/solarsystem.html). Also, the contruction of the model for the DE430 ones can be checked [here](https://en.wikipedia.org/wiki/Jet_Propulsion_Laboratory_Development_Ephemeris#Construction) :+1:

**Comment by Juanlu001** [comment]
@Tarlan0001 apart from what @jorgepiloto said, poliastro is not an N-body, high-fidelity propagator. Consider using something like https://github.com/hannorein/rebound. I'm closing this issue but feel free to keep the discussion ongoing.
