### ISSUE TITLE
Documentation error: units for rho0 in atmospheric_drag perturbation

### ISSUE THREAD

**Issue by mc-allen** [poliastro/poliastro#780]
🐞 In the atmospheric drag function, the rho0 units are indicated as kg/m^3 (https://github.com/poliastro/poliastro/blob/v0.13.0/src/poliastro/core/perturbations.py#L112).

However, I think that the function actually wants kg/km^3, which is consistent with the example in https://docs.poliastro.space/en/stable/examples/Natural%20and%20artificial%20perturbations.html#Atmospheric-drag

**Comment by Juanlu001** [comment]
Thanks @mc-allen, good catch! @jorgepiloto looks like @mc-allen is correct, can you please confirm? And then we can accept pull requests from new contributors for this issue.

**Comment by Juanlu001** [comment]
Closed in #816
