### ISSUE TITLE
binder link: embedded hyperlinks broken

### ISSUE THREAD

**Issue by mathematicalmichael** [poliastro/poliastro#781]
🐞 **Problem**

Clicking on the binder link in the README leads to a page with broken hyperlinks. Cannot navigate to examples. 

The cached version that shows up during loading does work, though.

**Comment by Juanlu001** [comment]
Hi @mathematicalmichael, thanks for your interest in poliastro! You are right, now the links are not being rendered:

![Screenshot_2019-10-14 index](https://user-images.githubusercontent.com/316517/66723978-b425f600-ee28-11e9-892c-8f41606a3550.png)

I am sure this used to work at some point, we will have to consider some alternatives.

**Comment by shreyasbapat** [comment]
I faced this similar problem! For me, replacing all the spaces in the name with an '_' (Underscore) worked!

**Comment by mathematicalmichael** [comment]
> I faced this similar problem! For me, replacing all the spaces in the name with an '_' (Underscore) worked!

oh yeah, that's definitely it. 
not sure if markup takes escape `\` into account, but this is exactly why I err on the side of caution and never use spaces in filenames.

**Comment by shreyasbapat** [comment]
Minor change required to finally close this!
