### ISSUE TITLE
Time conversion errors in Poliastro (czml) still remains

### ISSUE THREAD

**Issue by OrbitalMechanic** [poliastro/poliastro#784]
I noticed that poliastro was updated to correct time conversion errors in astropy.  I uninstalled and reinstalled poliastro using pip as opposed to conda because conda at present is not working. Poliastro still fails as before. See attached file.

Please advise.

Sam Dupree

[Latest_poliastro_test.txt](https://github.com/poliastro/poliastro/files/3737311/Latest_poliastro_test.txt)

**Comment by Juanlu001** [comment]
Hi Sam! Sorry, I forgot to reply your comment on the other issue - the fix hasn't been released to PyPI yet.

So far our policy has been "close the issues when the fix lands in `master`" (the GitHub workflow encourages that) but I see how this can be confusing. I'll keep this one open until we make a release with the fixes, which should happen within a few weeks. In fact, today I want to make some fixes in czml3 too.

**Comment by OrbitalMechanic** [comment]
Juan,

Thanks for the explanation. I'll be on the lookout when the fixes become 
available. :-)

With these fixes, will one still need to rename setup.cfg to run python 
-c "import poliastro.testing; poliastro.testing.test()"?

Sam Dupree

**Comment by Juanlu001** [comment]
Hi @OrbitalMechanic! Status update: we plan to release poliastro 0.13.1 this month including a fix to this particular problem (poliastro 0.14.0 will come next January with lots of changes). I'll ping you here when it's ready.

**Comment by Juanlu001** [comment]
Hi @OrbitalMechanic! We released with 0.13.1 with this fix. Could you please upgrade and confirm that it works? Thanks!

**Comment by OrbitalMechanic** [comment]
Almost there. I just got around to updating to version 0.13.1. The errors I'm now seeing are as follows.

users-MacBook-Pro:~ user$ python -c "import poliastro.testing; poliastro.testing.test()"
============================================================= test session starts =============================================================
platform darwin -- Python 3.7.3, pytest-5.1.2, py-1.8.0, pluggy-0.12.0
rootdir: /Users/user/anaconda3, inifile: setup.cfg
plugins: openfiles-0.3.2, arraydiff-0.3, timeout-1.3.3, doctestplus-0.3.0, remotedata-0.3.1
collected 850 items / 2 errors / 848 selected                                                                                                                                   

==================================================================================== ERRORS =====================================================================================
_________________________________________ ERROR collecting lib/python3.7/site-packages/poliastro/tests/tests_plotting/test_porkchop.py __________________________________________
'mpl_image_compare' not found in `markers` configuration option
__________________________________________ ERROR collecting lib/python3.7/site-packages/poliastro/tests/tests_plotting/test_static.py ___________________________________________
'mpl_image_compare' not found in `markers` configuration option
=============================================================================== warnings summary ================================================================================
anaconda3/lib/python3.7/site-packages/parso/python/tree.py:46
  /Users/user/anaconda3/lib/python3.7/site-packages/parso/python/tree.py:46: DeprecationWarning:
  
  Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/widget.py:280
  /Users/user/anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/widget.py:280: DeprecationWarning:
  
  Widget registration using a string name has been deprecated. Widget registration now uses a plain `@register` decorator.

anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/widget_upload.py:45
  /Users/user/anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/widget_upload.py:45: DeprecationWarning:
  
  Traits should be given as instances, not types (for example, `Int()`, not `Int`). Passing types is deprecated in traitlets 4.1.

anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/widget_upload.py:46
  /Users/user/anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/widget_upload.py:46: DeprecationWarning:
  
  Traits should be given as instances, not types (for example, `Int()`, not `Int`). Passing types is deprecated in traitlets 4.1.

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================= 4 warnings, 2 error in 50.29s =========================================================================
users-MacBook-Pro:~ user$ 

Please advise.

**Comment by Juanlu001** [comment]
Thanks for reporting back @OrbitalMechanic! I think we are back to [the same issue you had with statsmodels `setup.cfg`](https://github.com/poliastro/poliastro/issues/750). I did a bit of research and luckily statsmodels 0.11 stopped shipping its own `setup.cfg`:

https://github.com/statsmodels/statsmodels/pull/6117

While 0.11 makes its way to the default Anaconda packages, please remove `/Users/user/anaconda3/setup.cfg` and try again running poliastro tests.

**Comment by Juanlu001** [comment]
In fact, we can fix this problem by shipping our own `setup.cfg` to the right location! I will open a new issue for it.

Let's close this one if the time conversion errors in CZML were fixed.

**Comment by astrojuanlu** [comment]
We fixed the original issue, and also stopped shipping our tests. Therefore, I'm closing this.
