### ISSUE TITLE
Only NumPy 1.10 used in tests

### ISSUE THREAD

**Issue by newlawrence** [poliastro/poliastro#79]
@Juanlu001 glad to see you managed to unpin the **NumPy** version from the package, but there's still the problem I mentioned you before.

Specifying the **NumPy** version on the tests scripts is irrelevant since it'll be always updated to the latest version as **jplephem** is installed, as you can see in the logs ([Anaconda - see line 448](https://anaconda.org/poliastro/poliastro/builds/7/1), [Travis - see line 209](https://travis-ci.org/poliastro/poliastro/jobs/95123104) and [Appveyor - see line 147](https://ci.appveyor.com/project/poliastro/poliastro/branch/master/job/rlp3syt1ak8ryv3v)).

**Comment by Juanlu001** [comment]
Oh well, that's embarrasing :) You are totally right. Further comments in your PR.
