### ISSUE TITLE
Reconsider having reference elements for planets

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#790]
💡 **Feature request**

To have representative/reference/mean orbital parameters for major bodies.

🎯 **Goal**

The issue of having mean elements for planets instead of relying on the ephemerides has appeared many times in the past.

One of such times was [this pull request by @AunSiro](https://github.com/poliastro/poliastro/pull/153). Even though it made the computation of the radius of the Sphere of Influence trivial, I was not convinced:

> I'm not sure if the semimajor axis and the eccentricity belong here. While properties like the mass and the planet mean radius are clearly property of the planets themselves, the parameters of the orbit are a consequence of that body being in orbit around a certain attractor. For instance, you can retrieve the osculating orbit using ephem.planet_ephem, as described here http://poliastro.readthedocs.io/en/latest/user_guide.html#where-are-the-planets-computing-ephemerides. One could argue that having the mean properties of the orbit attached to the bodies might be practical, but still I'm not convinced from a code point of view.

This appeared again [some months after that](https://github.com/poliastro/poliastro/issues/150#issuecomment-326518564) and I said:

> I still maintain that we should not add orbital parameters to bodies.

As a result, this is the approach we are following for the SOI radius:

https://github.com/poliastro/poliastro/blob/68dc1de3170dc7e28ecbc2c11d65182427a9c7ff/src/poliastro/threebody/soi.py#L56-L64

One could argue that, after all, this is equivalent to hardcoding some parameters! But instead of having a representative value, we are using the instantaneous one at J2000.

And finally, in https://github.com/poliastro/poliastro/pull/774 we came back to the same problem: we need to know the mean motion of the planets around the Sun to model the Sun-synchronous condition.

JPL provides [lower accuracy formulas for planetary positions](https://ssd.jpl.nasa.gov/?planet_pos) and a nice justification:

> Lower accuracy formulae for planetary positions have a number of important applications when one doesn't need the full accuracy of an integrated ephemeris. They are often used in observation scheduling, telescope pointing, and prediction of certain phenomena as well as in the planning and design of spacecraft missions.

Therefore, I think the time has come to include them in poliastro.

**Comment by helgee** [comment]
For reference: https://github.com/JuliaAstro/AstroBase.jl/tree/master/src/ephemerides

**Comment by Juanlu001** [comment]
Notice that having the orbital elements is clearly not enough, even if we assume that they refer to the `.parent`. For example, it's not obvious whether they should refer to the Ecliptic plane or the Earth Equator plane.

**Comment by Juanlu001** [comment]
These are my notes: https://github.com/poliastro/poliastro/wiki/Body-orbits

**Comment by Juanlu001** [comment]
Or, instead of introducing a new frameless orbit as suggested in #659, I can use an existing object: a `ClassicalState`!

https://github.com/poliastro/poliastro/blob/0c9c545770c1451fcec1bb223dd90eb7b6ceba21/src/poliastro/twobody/_states.py#L58-L70

It doesn't have quick ways of computing other elements (bad) but it can't be propagated (good) and it already exists (great!)

**Comment by Juanlu001** [comment]
Not so fast: this is still not enough, since I don't have an explicit reference frame.

Definitely orbits without frames should not exist, but orbits with no `propagate` method should.

**Comment by Juanlu001** [comment]
...although it is by no means mandatory to provide the functionality we want. We will still need to restrict what the user can do with a `body.orbit`, but that's decoupled from having it.

**Comment by Juanlu001** [comment]
Also, even if we decide to put mean orbits in the bodies, we still want to know the position of the body within this mean orbit at a particular time. In the case of the [approximate elements given by JPL](https://ssd.jpl.nasa.gov/txt/aprx_pos_planets.pdf), this is given by the Mean Longitude (notice its rate of variation):

![Screenshot_2019-12-21 aprx_pos_planets pdf](https://user-images.githubusercontent.com/316517/71309558-87cebd00-2409-11ea-8647-06e25b827a8d.png)

**Comment by Juanlu001** [comment]
Two options:

* Have a `BodyMeanOrbit` with custom `propagate` and `sample` methods based on the elements above.
* Have a `Body.get_mean_orbit(epoch=J2000)`

**Comment by Juanlu001** [comment]
Choosing the second one because it's the simplest.

**Comment by Juanlu001** [comment]
Didn't like the approach in #825, going back to the option of adding a `ClassicalState` after merging #827.

**Comment by astrojuanlu** [comment]
Adding a `Body.mean_elements=ClassicalState(..., plane=Planes.EARTH_ECLIPTIC)` introduces a circular dependency that I find difficult to remove...

**Comment by astrojuanlu** [comment]
In the end, using PLAN94 from `astropy._erfa`.
