### ISSUE TITLE
Different namespace for Earth-specific functionality

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#791]
💡 **Feature request**

Add a new module `poliastro.earth` or `poliastro.twobody.earth` for Earth-specific functionality, possibly including an `EarthOrbit` object.

🎯 **Goal**

We traditionally wanted poliastro to be as generic as possible and don't include any Earth-specific functionality. As stated in the README:

https://github.com/poliastro/poliastro/blob/5d710592f33a41065eb22f26aa2ede0b77e1fa0a/README.rst#L222-L223

However, we already added at least two: [export to CZML/Cesium](https://github.com/poliastro/poliastro/pulls?q=is%3Apr+author%3Asedictious+is%3Aclosed) (mostly for the Earth until we figure out a way to represent the other planets), and [Earth atmospheric models](https://github.com/poliastro/poliastro/pull/738). In fact, we proposed and accepted a Google Summer of Code project titled ["Improving poliastro Earth capabilities"](https://summerofcode.withgoogle.com/projects/#6467241724346368)!

Advantages of making poliastro more useful for Earthlings :alien::

* Some algorithms are better documented for the Earth, making them easier to implement (and later some of them could be generalized)
* Most commercial applications are Earth-bound, so adding some functionality could make poliastro more attractive for these users (for example, being able to propagate TLEs with SGP4!)

Even if we decided not to add more functionality, we should probably find a better place for the code we already merged, and we will expand it anyway.

**Comment by noc0lour** [comment]
Given poliastro is in a unique position to give non-aerospace people an easy entry into calculating propagation in Python this would come in handy for a lot of applications. Addition of Earth-specifics shouldn't come at cost of losing functionality for other planets though.

**Comment by shreyasbapat** [comment]
What functionalities will be in Earth Namespace? 
A rough list? So that I don't miss them.

**Comment by astrojuanlu** [comment]
Let's tackle this after https://github.com/poliastro/poliastro/issues/445 is solved, see https://github.com/poliastro/poliastro/projects/3.

**Comment by astrojuanlu** [comment]
Quick proposal (before I start writing a page in the wiki, which might have to wait a few months still):

```python
from poliastro.earth import EarthOrbit  # Separate child class of Orbit with extra methods
from poliastro.earth.atmosphere import COESA76
from poliastro.earth.gravity import EGM84  # Does not exist... yet

EarthOrbit.heliosynchronous(...)  # Already present in Orbit
EarthOrbit.from_tle(...)  # Everybody wants this!
```

More ideas? cc @jorgepiloto

**Comment by priyanshurohilla** [comment]
> Quick proposal (before I start writing a page in the wiki, which might have to wait a few months still):
> 
> ```python
> from poliastro.earth import EarthOrbit  # Separate child class of Orbit with extra methods
> from poliastro.earth.atmosphere import COESA76
> from poliastro.earth.gravity import EGM84  # Does not exist... yet
> 
> EarthOrbit.heliosynchronous(...)  # Already present in Orbit
> EarthOrbit.from_tle(...)  # Everybody wants this!
> ```
> 
> More ideas? cc @jorgepiloto

Here are some ideas which i propose 
``` 
from poliastro.plotting import GroundtrackPoltter # seperate module in plotiing 
from poliastro.earth import EarthOrbit
from poliastro.earth import LaunchWindows # implementation Of launch windows in poliastro.earth
EarthOrbit.stationkeeping(...)
LaunchWindows.Orbit(...)
```
We can also add functionalities for mission analysis and the thing which i am most excited about is if we can add Rendezvous capabilities too. I would love to work on it

**Comment by astrojuanlu** [comment]
Good proposals @priyanshurohilla, we have some of them as issues (#21 for example) and some others we don't. Having launch windows would be great indeed!

**Comment by priyanshurohilla** [comment]
Yes @astrojuanlu. I have many things in my mind and would love to discuss each and everything in the Roadmap 😊

**Comment by antoinetavant** [comment]
Other Earth related aspects :
* geomagnetic field (the IGRF propose a python implementation [here](https://www.ngdc.noaa.gov/IAGA/vmod/igrf.html) and by several packages as [igrf12](https://github.com/space-physics/igrf12) (that wraps the fortran code) and [pyIGRF](https://pypi.org/project/pyIGRF/) that uses numpy (it may be the best solution)
* Specific Reference Frames such as:
   - local East North Up ( [ENU](https://en.wikipedia.org/wiki/Axes_conventions#World_reference_frames:_ENU_and_NED)  that can be named "topocentric North" (at least[ here](https://sourceforge.isae.fr/svn/dcas-soft-espace/support/softs/CelestLab/trunk/help/en_US/scilab_en_US_help/Local%20frames.html)

**Comment by astrojuanlu** [comment]
@Meuge started addressing this in gh-970, more progress soon!

**Comment by astrojuanlu** [comment]
As a summary of our recent advances: we are experimenting with a new `poliastro.earth` module, adding a class `EarthSatellite` that composes an `Orbit` and a new object `Spacecraft`. This class has one convenience method now, `propagate`, that takes the configuration of the perturbation directly, like this:

```python
from astropy import units as u

from poliastro.examples import iss  # Orbit
from poliastro.earth.atmosphere import COESA76  # Moved!
from poliastro.earth.enums import EarthGravity  # New!
from poliastro.spacecraft import Spacecraft  # New!

sat = EarthSatellite(iss, Spacecraft(A=10 * u.m ** 2, C_D=2.2 * u.one, m=420e3 * u.kg))
sat.propagate(100 * u.min, gravity=EarthGravity.J2, atmosphere=COESA76())
```

The idea is that this `Spacecraft` can have properties like geometry, mass, and who knows? Propulsion, attitude...

This is highly experimental and we are not 100 % settled yet, so all feedback is more than welcome.

In the meantime, I am closing this issue.
