### ISSUE TITLE
Cannot set ISS attractor to Earth

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#798]
```python
In [20]: epoch = Time("2019-11-10 12:00:00")                                                                                            

In [21]: iss = Orbit.from_horizons("International Space Station", epoch=epoch, id_type="majorbody"); iss                                
Out[21]: 1 x 1 AU x 19.1 deg (HCRS) orbit around Sun (☉) at epoch 2019-11-10 12:01:09.183 (TDB)

In [22]: iss.change_attractor(Earth)                                                                                                    
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-3297d9422d44> in <module>
----> 1 iss.change_attractor(Earth)

~/Development/poliastro/poliastro/src/poliastro/twobody/orbit.py in change_attractor(self, new_attractor, force)
    488         if distance > r_soi and not force:
    489             raise ValueError(
--> 490                 "Orbit is out of new attractor's SOI. If required, use 'force=True'."
    491             )
    492         elif self.ecc < 1.0 and not force:

ValueError: Orbit is out of new attractor's SOI. If required, use 'force=True'.
```

Strange!

**Comment by Juanlu001** [comment]
Using `force=True` worked, by the way:

```python
In [8]: iss_e = iss.change_attractor(Earth, force=True); iss_e                                                                          
/home/juanlu/Development/poliastro/poliastro/src/poliastro/twobody/orbit.py:489: PatchedConicsWarning: Leaving the SOI of the current attractor
  warn("Leaving the SOI of the current attractor", PatchedConicsWarning)
Out[8]: 2842 x 5259 km x 53.1 deg (GCRS) orbit around Earth (♁) at epoch 2019-11-10 12:01:09.183 (TDB)
```

Note however that the eccentricity is quite high:

```
In [9]: iss_e.ecc                                                                                                                       
Out[9]: <Quantity 0.2983701>
```

**Comment by Juanlu001** [comment]
There are two problems here: some faulty logic in the Sphere of Influence check, and some numerical issue with the frame transformation. @jorgepiloto any idea about the former? I can check the latter.

**Comment by Juanlu001** [comment]
Part of the problem has been solved in #800.

**Comment by astrojuanlu** [comment]
This is still a problem, as far as I see it.

```
>>> iss = Orbit.from_horizons("International Space Station", Sun, epoch=epoch, id_type="majorbody"); iss
1 x 1 AU x 19.1 deg (HCRS) orbit around Sun (☉) at epoch 2019-11-10 12:01:09.183 (TDB)
>>> iss.change_attractor(Earth)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/.pyenv/versions/poliastro38/lib/python3.8/site-packages/poliastro/twobody/orbit.py", line 498, in change_attractor
    raise ValueError(
ValueError: Orbit is out of new attractor's SOI. If required, use 'force=True'.
```

**Comment by iamabhishek0** [comment]
@astrojuanlu I think this is caused because in line https://github.com/poliastro/poliastro/blob/master/src/poliastro/twobody/orbit.py#L490
because self.r is in HCRS frame while get_body_barycentric returns cartesian coordinates in ICRS frame. Can you suggest how to bring both coordinates in the same frame?

**Comment by astrojuanlu** [comment]
@iamabhishek0 😱 good catch!! That's exactly the problem! Let me think this weekend

**Comment by astrojuanlu** [comment]
I think the best thing would be to explicitly convert the `CartesianRepresentation` coming from `get_body_barycentric` to ICRS, `transform_to` the frame of the `Orbit`, and then use that to make the subtraction.

To whoever wants to fix this bug, my recommendation is:

1. Write a test that tries `iss.change_attractor(iss.attractor)`
2. Watch it fail
3. Fix the code
4. Commit
5. Push and open a pull request :)

**Comment by priyanshurohilla** [comment]
I am working on it.

**Comment by iamabhishek0** [comment]
@priyanshurohilla If you don't mind I have already made some progress on this one, please let me work on this. As you are already  working on #868

**Comment by astrojuanlu** [comment]
@priyanshurohilla There is no need to announce you are working on a particular issue. On one hand, we see a pattern of people making the announcement and then never sending a pull request, which gives a bad impression (I have been guilty of this in other projects, and it still is not a nice thing to do). On the other hand, it gives the impression that others should refrain to work on the issue, which is wrong.

And finally, as @iamabhishek0 correctly points out, he did the investigation, probably already has some progress, and you announced you were working in other issue.

This is not a competition folks. Thanks for your enthusiasm!

**Comment by priyanshurohilla** [comment]
@astrojuanlu you said in the comments that whosoever wants to work on it. Thats why i mentioned it. If @iamabhishek0 wants to work on it i dont have any problem regarding that. All yours @iamabhishek0

**Comment by astrojuanlu** [comment]
This logic:

https://github.com/poliastro/poliastro/blob/f4547d2b1b89eba41a9ee29b3fe35d9ba393c64c/src/poliastro/twobody/orbit.py#L502-L503

covers this case:

https://github.com/poliastro/poliastro/blob/f4547d2b1b89eba41a9ee29b3fe35d9ba393c64c/tests/tests_twobody/test_orbit.py#L1061-L1067

Therefore, we can't just remove it, because it's legitimate. However, there should be a way to detect when an object is, in fact, orbiting a closer body.

_Originally posted by @astrojuanlu in https://github.com/poliastro/poliastro/pull/894_

**Comment by priyanshurohilla** [comment]
> This logic:
> 
> https://github.com/poliastro/poliastro/blob/f4547d2b1b89eba41a9ee29b3fe35d9ba393c64c/src/poliastro/twobody/orbit.py#L502-L503
> 
> covers this case:
> 
> https://github.com/poliastro/poliastro/blob/f4547d2b1b89eba41a9ee29b3fe35d9ba393c64c/tests/tests_twobody/test_orbit.py#L1061-L1067
> 
> Therefore, we can't just remove it, because it's legitimate. However, there should be a way to detect when an object is, in fact, orbiting a closer body.
> 
> _Originally posted by @astrojuanlu in #894_

We can detect it by looking into the values of Periapsis and Apoapsis and make a parameter which can be used to check those values and hence determine if it is orbiting a closer body.

**Comment by jorgepiloto** [comment]
I just saw this issue is in the 0.15 milestone so got interested on solving this. After reading previous comments, just found that @iamabhishek0 found the solution. However, I also saw the following line

https://github.com/poliastro/poliastro/blob/bf9cfa6b9485d54fd4dec98ebf53ce9cdccbf906/src/poliastro/twobody/orbit.py#L511-L516

applies a conversion to current orbit's position vector in corresponding frame. Shouldn't both `self.r` and `new_attractor_r` be in the same frame? I will check in the next hours and paste some results under this lines. By the way, are you @iamabhishek0 still working on this?

**Comment by astrojuanlu** [comment]
`Orbit.from_horizons` no longer exists. This is what happens now:

```
In [11]: iss = Ephem.from_horizons(
    ...:     "International Space Station", epochs=Time.now(), attractor=Earth
    ...: )
    ...: iss
Out[11]: Ephemerides at 1 epochs from 2022-01-16 10:40:40.301272 (UTC) to 2022-01-16 10:40:40.301272 (UTC)

In [12]: Orbit.from_ephem(Earth, iss, iss._epochs[0])
Out[12]: 6789 x 6803 km x 51.7 deg (GCRS) orbit around Earth (♁) at epoch 2022-01-16 10:40:40.301272 (UTC)
```

Which looks perfect to me! So I'm closing.
