### ISSUE TITLE
Fixed planetary frame transformation error

### ISSUE THREAD

**Issue by noc0lour** [poliastro/poliastro#801]
When creating a coordinate in a planetary fixed frame a transformation is not possible due to 
an error in `frames/fixed.py`

🐞 **Problem**

```
testloc = frames.fixed.MarsFixed(10 * u.deg, 20 * u.deg, distance=bodies.Mars.R, obstime=start_time)
testloc.transform_to(frames.ICRS)
```

```
~/git/misc/poliastro/src/poliastro/frames/fixed.py in to_equatorial(fixed_coo, equatorial_frame)
     73         assert fixed_coo.body == equatorial_frame.body
     74 
---> 75         r = fixed_coo.data.xyz
     76         v = fixed_coo.data.differentials["s"].d_xyz
     77 

AttributeError: 'SphericalRepresentation' object has no attribute 'xyz'
```

💡 **Possible solutions**

Converting to CartesianRepresentation and filling in the CartesianDifferentials. Possibly similar to how it is handled for `EarthLocation` in `earth.py` in astropy.

**Comment by noc0lour** [comment]
For my current use case actually I only would need a transformation to `MarsICRS` which is even simpler, but in the end it's the same machinery for both.

**Comment by Juanlu001** [comment]
Thanks @noc0lour! `to_equatorial` should probably convert to `CartesianRepresentation` before trying to get `.xyz`. Do you want to try if that fixes the problem?
