### ISSUE TITLE
wheel files for 64-bit Windows

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [poliastro/poliastro#812]
I'm not sure if this is the right place to report this, but I'm unable to find wheel files for 64-bit Windows.  I'm specifically looking for wheels for Python 3.6 and Python 3.7.

**Comment by Juanlu001** [comment]
Hi @Phillip-M-Feldman! poliastro is a pure Python package and therefore has universal wheels. Did you have any trouble installing it?

**Comment by Phillip-M-Feldman** [comment]
My main difficulty is that I haven't been able to find any wheel file.

**Comment by Juanlu001** [comment]
Here you can find the wheel of the latest release: https://pypi.org/project/poliastro/#files (`poliastro-0.13.0-py3-none-any.whl`)

**Comment by Phillip-M-Feldman** [comment]
Thanks very much!

**Comment by Juanlu001** [comment]
You're welcome! Closing :muscle:
