### ISSUE TITLE
czmlExtractor: allow passing custom arguments to propagate

### ISSUE THREAD

**Issue by noc0lour** [poliastro/poliastro#814]
Currently the propagator call in CZML limits use to only Keplerian orbits without artificial perturbations. For propagation of orbits with e.g. J2 perturbation it would be necessary to pass custom arguments

🎯 **Goal**

Create CZML packets out of different trajectory data.
I could think of a utility function which converts Coordinate data to CZML packets without doing the propagation itself since Coordinates have a obstime property attached anyhow.

**Comment by Juanlu001** [comment]
Perhaps we should have a similar API than the `OrbitPlotter`s: `plot(orbit)` and then the Keplerian orbit is plotted, and `plot_trajectory(...)` and then the users chooses how to propagate.

**Comment by noc0lour** [comment]
Sounds like a good idea. More or less a simple function which converts a coordinate time series to a CZML packet.

**Comment by Syed-Osama-Hussain** [comment]
So basically we need to construct a packet by it's positional attributes with respect to time?

**Comment by astrojuanlu** [comment]
@Syed-Osama-Hussain The `CZMLExtractor` class has an `add_orbit` method. Let's have an `add_trajectory` that takes a `CartesianRepresentation`, similar to `plot` vs `plot_trajectory` in the plotters.

**Comment by Syed-Osama-Hussain** [comment]
Okay @astrojuanlu . Do we have to provide ground tracking and all the other optional parameters as in add_orbit?

**Comment by astrojuanlu** [comment]
Let's start with `if groundtrack_show: raise NotImplementedError` to simplify.

**Comment by Syed-Osama-Hussain** [comment]
Okay.

**Comment by astrojuanlu** [comment]
The `add_trajectory` method addressed this issue: now users can propagate it "outside" of the `CZMLExtractor`. It would be nice to have an `add_ephem` too, but I'll let others open an issue for that if they really want it. Closing!
