### ISSUE TITLE
Unify propagate and Orbit.propagate API

### ISSUE THREAD

**Issue by noc0lour** [poliastro/poliastro#815]
Currently to get intermediate sampling positions & the orbit at the end of simulation `propagate()` is essentially called twice and the whole propagation is performed twice. 

```
            results = propagate(
                sc.orbit,
                sampling_times,
                method=cowell,
                ad=J2_perturbation,
                J2=bodies.Earth.J2,
                R=bodies.Earth.R.to(u.km).value,
                rtol=1e-13,
            )
            sc.orbit = sc.orbit.propagate(
                sc.orbit.epoch + ticks * self._sampling,
                method=cowell,
                ad=J2_perturbation,
                J2=bodies.Earth.J2,
                R=bodies.Earth.R.to(u.km).value,
            )
```

💡 **Feature request**

Having either the `propagate()` function from `twobody` optionally return the new propagated orbit.
Or the `Orbit.propagate()` function to return a time-series of coordinates + a new orbit upon input of a time-series.

🎯 **Goal**

Speeding up simulations 2x by only `propagate()`ing once since orbit.propagate() calls propagate() internally.

**Comment by priyanshurohilla** [comment]
i want to work on it.

**Comment by astrojuanlu** [comment]
First things first: sorry @noc0lour for the looooooong delay, I know we talked in the chat but it doesn't usually take me that much time to respond to an issue in poliastro. I'm in a better position now :)

Simpler case:

```python
In [8]: times = time_range(Time("2020-04-04 12:00:00", scale="tt"), periods=3, end=Time("2020-04-04 14:00:00", scale="tt"))                                                                                                                   

In [9]: times                                                                                                                                                                                                                                 
Out[9]: 
<Time object: scale='tt' format='iso' value=['2020-04-04 12:00:00.000' '2020-04-04 13:00:00.000'
 '2020-04-04 14:00:00.000']>

In [10]: propagate(iss, times)  # Representation in all times, no Orbit                                                                                                                                                                                                              
Out[10]: 
<CartesianRepresentation (x, y, z) in km
    [( 5128.4602846 ,  3729.87885198, -2425.77381503),
     (  237.13966575, -4293.07533267,  5234.77691922),
     (-5384.63450019,  1436.20865414, -3861.90127496)]
 (has differentials w.r.t.: 's')>

In [11]: iss.propagate(times[-1])  # Orbit in chosen time, no intermediate positions                                                                                                                                                                                                           
Out[11]: 6772 x 6790 km x 51.6 deg (GCRS) orbit around Earth (♁) at epoch 2020-04-04 13:58:50.816 (UTC)
```

My first thought: isn't is simpler to use `Orbit.from_coords(..., results[-1], ...)`? But then this happened:

```
In [13]: results = propagate(iss, times)                                                                                                                                                                                                     

In [14]: final_iss = Orbit.from_coords(iss.attractor, results[-1], iss.plane)                                                                                                                                                                 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-85836c6f6c86> in <module>
----> 1 final_iss = Orbit.from_coords(iss.attractor, results[-1], iss.plane)

~/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/poliastro/twobody/orbit.py in from_coords(cls, attractor, coord, plane)
    285 
    286         """
--> 287         if "s" not in coord.cartesian.differentials:
    288             raise ValueError(
    289                 "Coordinate instance doesn't have a differential with respect to time"

AttributeError: 'CartesianRepresentation' object has no attribute 'cartesian'
```

Which makes me realize that `Orbit.from_coords` does too many things. It should receive either the `BaseCoordinateFrame` and use that information to set the plane, or a `BaseRepresentation` + `plane`.

@noc0lour with a proper functioning `Orbit.from_coords`, would this be a solution for you?

**Comment by priyanshurohilla** [comment]
Well I didn't give thissss much of a thought! Now as @astrojuanlu has stormed his brain on it. I'll do it too and try to get the solution for it. But I would be needing some guidance :)

**Comment by astrojuanlu** [comment]
`Orbit.from_coords` is fine like that, having a `BaseCoordinateFrame` + `plane` allows poliastro to convert the input coordinates to a known frame.

The natural option now, instead of propagating twice, would be doing something like this:

```python
In [12]: final_iss = Orbit.from_vectors( 
    ...:   iss.attractor, 
    ...:   results[-1].xyz, 
    ...:   results[-1].differentials["s"].d_xyz, 
    ...:   epoch=times[-1], 
    ...:   plane=iss.plane 
    ...: )
```

which recovers exactly what you want.

I am -1 on changing `Orbit.propagate`, as it breaks a lot of interactive workflows and chaining operations, and -1 on changing `poliastro.twobody.propagation.propagate` as well, as it introduces a circular dependency with the former.

Do you have any other ideas on how the code above could be made even simpler?

**Comment by priyanshurohilla** [comment]
@astrojuanlu the steps you are suggesting would require manipulation from the user end, Like the user have to think of writing that code to access it 2x faster, but it would be better if we can fix this on our end, So that the user can be at ease. What do you think @astrojuanlu ?🤔

**Comment by priyanshurohilla** [comment]
What i propose is we can change the function of `orbit.propgate()` to take one more parameter something like `cartessian` and if the user provide it as `True` then we can return the `cartesian` otherwise we can have our normal working of function. Would this method also affect other files?@astrojaunlu like what happened by changing the return value of the function?🤔

**Comment by astrojuanlu** [comment]
I am generally not in favor of changing the type of the return value depending on a function parameter. Yes, we do it in some parts of the code (like `maneuvers.py`), but I'd say it's a bad practice. I've seen it in SciPy too - don't like it :sweat:

**Comment by astrojuanlu** [comment]
I think the solution we gave in https://github.com/poliastro/poliastro/issues/815#issuecomment-609469484 is good enough - poliastro shouldn't necessarily commit to cover every possible use case with a single function. With the same number of lines of code we avoided the performance penalty, so I am closing this. Feel free to add more information of you still want this to be considered.

**Comment by noc0lour** [comment]
I think the solution is appropriate, maybe it would be good to include this in the documentation for future users.
