### ISSUE TITLE
CZMLExtractor: Provide a 'czml3.Document' directly

### ISSUE THREAD

**Issue by kerel-fs** [poliastro/poliastro#818]
Currently the CZMLExtractor provides a list of packets as output (with the first packet being a `czml3.Preamble`), which has to be wrapped by `Document(extractor.packets)` to be able to view the resulting document with the `czml3.CZMLWidget`.

💡 **Feature request**

Provide a way to get a `czml3.Document` directly from the `CZMLExtractor`. Implementation idea:
Add the method `getDocument()`  (I don't like this name!) to `CZMLExtractor`.

🎯 **Goal**
- Improve interoperability of the poliastro CZMLExtractor with the CZMLWidget

**Related issues**
- this isssue is based on https://github.com/poliastro/czml3/issues/45#issuecomment-561667027

**Comment by Juanlu001** [comment]
Excellent idea! I propose `get_document()`. Pull requests welcome :) Let's leave this one for first contributors.

**Comment by asalia-1** [comment]
Hi, I would like to take up this issue

**Comment by Juanlu001** [comment]
Hi @asalia-1, all yours!

**Comment by asalia-1** [comment]
Hello @Juanlu001 , 
Sorry for getting to this issue late. From the description of this issue, I am deducing that the solution is to write a method that simply passes the **self.packets** list to **Document()** as in **docx.Document(self.packets)** and then returns the Document object. 
However, on reading the documentation for docx.Document(), I am not sure if I can pass a list as a valid argument to Document(). 

I also noticed a **Document class** from **czml3.core**. Am I supposed to use that instead?
I wanted to check with you before submitting the pull request for this issue. 
Thanks for the help!

**Comment by Juanlu001** [comment]
Hi @asalia-1, no worries! Rather than `docx.Document`, as you already noticed we want to use `czml3.core.Document`. Let us know if you have more questions.

**Comment by asalia-1** [comment]
Thanks @Juanlu001 !

**Comment by Syed-Osama-Hussain** [comment]
Hello. How can I run the tests on test_czml.py locally?

**Comment by astrojuanlu** [comment]
Hello @Syed-Osama-Hussain! You need to use `pytest` for that, `pytest -k czml` should work (provided you have `czml` installed). If you have questions, please direct them to our [poliastro-newbies](https://riot.im/app/#/room/#poliastro-newbies:matrix.org) chat.

**Comment by astrojuanlu** [comment]
Fixed in #886. @kerel-fs let us know if you try it out in the development version :) For the moment, I'm closing this feature request.
