### ISSUE TITLE
No check against plotting orbits in different planes?

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#824]
🐞 **Problem**

I suspect that we are not doing any transformation when plotting orbits in different planes.

💡 **Possible solutions**

First, check that this is the case.

If it is, we should implement `change_plane` if appropriate (see for example [this implementation](https://docs.poliastro.space/en/latest/examples/Analyzing%20the%20Parker%20Solar%20Probe%20flybys.html)) and use it in plotting.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by priyanshurohilla** [comment]
i want to work on this issue.

**Comment by Juanlu001** [comment]
This can be a bit involved and it depends on a refactoring I'm doing, so I prefer to assign it to myself :)

**Comment by astrojuanlu** [comment]
No, there's no check, and wrong results are plotted.

![Screenshot_2020-03-21 Untitled - Jupyter Notebook](https://user-images.githubusercontent.com/316517/77236339-ec8ee480-6bbd-11ea-9eed-8629e3328486.png)
