### ISSUE TITLE
Typo in equinoctial elements documentation

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#829]
https://github.com/poliastro/poliastro/blob/d8ff14980ff2b2bd6790aa6eb709a521f2a52daa/src/poliastro/core/elements.py#L390-L391

**Comment by asalia-1** [comment]
Hello Juan, I am Abdallah Salia, I am new to the poliastro community and I would like to resolve this issue

**Comment by Juanlu001** [comment]
Thanks @asalia-1 for this first contribution! Please don't hesitate to join our chat and ask around if you want to keep working in the project :tada:
