### ISSUE TITLE
Can't update poliastro from 0.12 to 0.13.1 with anaconda

### ISSUE THREAD

**Issue by WolfsSky** [poliastro/poliastro#839]
Hi!

I have been excited to use the new propagators within poliastro, however I can't get anaconda to update poliastro to 0.13.1. 
`conda install poliastro==0.13.1` 
gives 
`PackagesNotFoundError: The following packages are not available from current channels:`
` - poliastro==0.13.1`

Same happens for 0.13.

Is it not yet released as a stable version? or am I doing something wrong?

**Comment by Juanlu001** [comment]
Hi @WolfsSky! Yes, the conda-forge upgrade is broken :frowning_face: https://github.com/conda-forge/poliastro-feedstock/pull/31 and there were some tests failing https://github.com/conda-forge/poliastro-feedstock/issues/30. I don't use conda anymore so I would like someone else to take a look and try to understand what's going on.

**Comment by WolfsSky** [comment]
Ah ok, thanks for the info. I am not very proficient with Conda, I just use it as an easy way to have everything bundled. Is using `pip` as an alternative ok, or would that also fail?

**Comment by Juanlu001** [comment]
Using pip is perfectly OK!

**Comment by NanuSai** [comment]
> Hi!
> 
> I have been excited to use the new propagators within poliastro, however I can't get anaconda to update poliastro to 0.13.1.
> `conda install poliastro==0.13.1`
> gives
> `PackagesNotFoundError: The following packages are not available from current channels:`
> ` - poliastro==0.13.1`
> 
> Same happens for 0.13.
> 
> Is it not yet released as a stable version? or am I doing something wrong?

I'm not much of a pro but I've installed it inside my conda environment and things seems to be running smoothly.
```
$ conda list poliastro
# packages in environment at /home/psykik/anaconda3/envs/tf_gpu:
#
# Name                    Version                   Build  Channel
poliastro                 0.13.0                     py_0    conda-forge
```
Maybe try conda remove and then install as per the README.md?

**Comment by NanuSai** [comment]
> Hi!
> 
> I have been excited to use the new propagators within poliastro, however I can't get anaconda to update poliastro to 0.13.1.
> `conda install poliastro==0.13.1`
> gives
> `PackagesNotFoundError: The following packages are not available from current channels:`
> ` - poliastro==0.13.1`
> 
> Same happens for 0.13.
> 
> Is it not yet released as a stable version? or am I doing something wrong?

Hey WolfsSky,
I tried creating a new environment with poliastro ver 0.12. Here's what I found

- Using `conda install poliastro==0.13.0` , successfully updates to poliastro from 0.12
- Using `pip install poliastro==0.13.1` installs your desired version exclusively to that conda environment(which is the basic purpose of conda env anyway). 
- Using pip method, also enlists it in `conda list`.
- Updating to 0.13.1 using conda fails as you've mentioned

Hope it's helpful! :)

**Comment by Juanlu001** [comment]
In a few minutes, `conda install poliastro=0.13.1 -c conda-forge` will be available, as I finally fixed the package. I would still love to have someone else volunteer on this :) Thanks for your patience!
