### ISSUE TITLE
Cut off Windows CI

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#84]
The Windows builds take forever to run in AppVeyor. While the slowest build on Anaconda Server can be around 3 minutes (https://anaconda.org/poliastro/poliastro/builds) and 4 minutes in Travis CI https://travis-ci.org/poliastro/poliastro/builds/95558901, AppVeyor builds can take as long as 7 minutes and they run *sequentially* https://travis-ci.org/poliastro/poliastro/builds/95558901. Therefore, at the current pace one has to wait between 30 and 40 minutes for Windows builds to finish. This is unacceptable.

Based on the survey that Thomas Robitaille run earlier this year (http://astrofrog.github.io/blog/2015/05/09/2015-survey-results/):

![Versions](http://astrofrog.github.io/images/survey_plots/os_vs_python.svg)

it looks like Windows users are usually the most up to date. The Windows users I care about are using Anaconda or similar.

I suggest removing these builds:

* Python 3.3: nobody uses it.
* Python 3.5/NumPy 1.9: if you are using the latest Python you probably aren't stuck with NumPy 1.9.
* Python 3.4/NumPy 1.10: if you are using the latest NumPy you probably can upgrade your Python version too.

With this we would save between 15 and 20 minutes, which is *a lot*. What do you think @newlawrence @AunSiro? @proinsias I don't know what OS are you using, what are your thoughts on this?

**Comment by Juanlu001** [comment]
The other option is to disable it completely except for release branches, and put there last minute fixes.

**Comment by newlawrence** [comment]
It's a matter of project workflow philosophy. It will be ideal to be sure that every single change in the code doesn't break it on every single combination of the dependencies and posible contexts. But, if the tests take longer each time... can we still considering it agile development?

I think your last suggestion is right. If the tests take so long, then just lets use them as a way to keep final releases bugs free. The package has the advantage to be, in principle, platform agnostic so if there's no issues in one of the platforms it shouldn't be in the rest.

**Comment by Juanlu001** [comment]
I disabled Windows builds for pull requests and the `master` branch, at least for the moment. Feel free to go on with the discussion - if AppVeyor ever switches to parallel builds I might consider activating them again.

**Comment by proinsias** [comment]
@Juanlu001 – apologies for the delay in replying. I mostly use OS X now, so this change wouldn't affect me. Thanks for checking with me!
