### ISSUE TITLE
Duplicated sphinx extension

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#850]
:beetle: About the issue

In the `docs/source/conf.py` there exists a duplicated extension: `sphinx.ext.mathjax`.

:bulb: Solution

Simply remove one of the two lines; we are importing twice the extension... This can be an easy issue for new GSOC aspirants to know how to proceed and the issue/pull-request workflow :rocket:

**Comment by iamabhishek0** [comment]
I am working on this
