### ISSUE TITLE
Review astropy.units performance tips

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#856]
See https://astropy.readthedocs.io/en/latest/units/index.html#performance-tips

* Use of composite units and `<<` to avoid copies
* Replace `q.to(unit).value` by `q.to_value(unit)`, see http://docs.astropy.org/en/stable/units/quantity.html#converting-to-different-units

**Comment by NanuSai** [comment]
Hey @Juanlu001, our codebase has multiple cases of directly multiplying **units**
I propose we put it as an open PR( people can work independently on this and reference this issue in their PR) in that way the issue will be solved much quicker. 😁

But it's your call

**Comment by priyanshurohilla** [comment]
> Hey @Juanlu001, our codebase has multiple cases of directly multiplying **units**
> I propose we put it as an open PR( people can work independently on this and reference this issue in their PR) in that way the issue will be solved much quicker. 
> 
> But it's your call

I agree with @NanuSai  ... It would be better if it's an open PR..

**Comment by astrojuanlu** [comment]
Changing the units should be done everywhere in the code, but @NanuSai went ahead in one function (#857) and it was slower in his computer. So this should be handled with care.

Unfortunately, [our benchmarks](https://github.com/poliastro/benchmarks) are abandoned and we don't run them anymore... So we have limited tools to know the performance impact of this.

**Comment by NanuSai** [comment]
@priyanshurohilla or anyone in that matter, Why not try in your computer the changes I made as suggested in #857 ? Maybe it's an intrinsic problem of my computer.Let's get that cleared, then we can get to the root of it.

**Comment by astrojuanlu** [comment]
Good idea!

**Comment by iamabhishek0** [comment]
@astrojuanlu I would like to help!

**Comment by astrojuanlu** [comment]
@iamabhishek0 great! Then please follow @NanuSai advice and try the changes in #857 locally, to see if you also observe the slowdown (please post the details there)

**Comment by iamabhishek0** [comment]
Sure :)

**Comment by astrojuanlu** [comment]
This issue is more difficult than it seems for several reasons:

* Any change in how we use units affects performance (that's why we want to do it, right?) but *sometimes surprising results appear*, as we saw in #857. Therefore, given that our benchmarks at https://github.com/poliastro/benchmarks were last run a long time ago, we *at least* need some microbenchmarking, as @NanuSai and @iamabhishek0 did in #857.
* This is tightly coupled with the idea of *not* using units in core (fast, unsafe) functions: https://github.com/poliastro/poliastro/issues/707

**Comment by astrojuanlu** [comment]
Successful application of this in #857

**Comment by astrojuanlu** [comment]
Another cheap improvement:

```
$ grep -E 'to\(u.(.*)\).value' src/ -r | wc -l
158
```

Replace those by `q.to_value(unit)`, see above.

**Comment by astrojuanlu** [comment]
We have been slowly replacing the units as per the tips above. Closing this issue.
