### ISSUE TITLE
poliastro does not work on Binder

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#859]
🐞 **Problem**

At the moment poliastro can't be deployed on Binder.

To reproduce, [try it](https://mybinder.org/v2/gh/poliastro/poliastro/master?filepath=index.ipynb).

💡 **Possible solutions**

It has been suggested that there's a problem in our Dockerfile. We should either:

* Fix it
* Find an alternative method that works

I was never fond of Docker for library code, so if we can do without it, :+1: 

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by iamabhishek0** [comment]
@astrojuanlu I have fixed the [Dockerfile](https://github.com/iamabhishek0/poliastro/blob/dockerfile_update/Dockerfile), I suggest having a requirements.txt. If ever there's a need for a Dockerfile it can be used, I have tested it on Binder.

**Comment by astrojuanlu** [comment]
Sorry @iamabhishek0, too late - I removed it. Too much complexity for what should be a simple problem. Now we are using a `requirements.txt`, as advised :)
