### ISSUE TITLE
Stop shipping tests in wheels

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#863]
Well, I don't think it can be easily done for a file that is out of the `src` tree. This is probably a symptom that we shouldn't be shipping our tests, even though other packages in the scientific Python ecosystem do it.

Out of curiosity, I checked SciPy wheels and, even though they have `include tox.ini pytest.ini` in their `MANIFEST.in`, their pytest configuration doesn't make it to the wheels.

It's OK that we managed to include `setup.cfg` in our source distribution, but perhaps we should think about removing the tests from the wheels.

_Originally posted by @astrojuanlu in https://github.com/poliastro/poliastro/issues/832#issuecomment-590885043_

**Comment by astrojuanlu** [comment]
Apart from not doing it anymore, we should update the documentation and stop telling people to do `python -c "import poliastro.testing; poliastro.testing.test()"`, and give an alternative method instead.

**Comment by jains8844** [comment]
I tried this [https://github.com/jains8844/poliastro/commit/2486dd4c5c009bd17709fe947ed927f120e7ead0](https://github.com/jains8844/poliastro/commit/2486dd4c5c009bd17709fe947ed927f120e7ead0) and built the wheel and source distribution with ``` flit build ```
The resulting package did not contain tests. Is this what is required ?

**Comment by astrojuanlu** [comment]
Kind of, but I think it's easier to just move all the `tests` directory to the top of the repository and remove `testing.py`. I'll take care of this one.

**Comment by jains8844** [comment]
Sure 👍
