### ISSUE TITLE
Restore coverage reporting

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#880]
After #846, we stopped reporting coverage to Codecov. Instead, we see this kind of messages:

https://dev.azure.com/poliastro/poliastro/_build/results?buildId=41&view=logs&j=0d2e6dee-4abd-58ce-47f1-cbb7d58969b6&t=64ccd6c1-282f-5a50-12e1-cb249088790a&l=11

> ##[warning]No test result files matching **/test-*.xml were found.

**Comment by jains8844** [comment]
For the coverage test, we need to pass the codecov token as an environment variable named ```CODECOV_TOKEN``` to the pipeline. See this https://github.com/OpenAstronomy/azure-pipelines-templates/blob/master/run-tox-env.yml#L155.

The warning ``` ##[warning]No test result files matching **/test-*.xml were found.``` is generated by this line in my opinion https://github.com/OpenAstronomy/azure-pipelines-templates/blob/master/run-tox-env.yml#L41

**Comment by astrojuanlu** [comment]
Thanks @jains8844! I added a `CODECOV_TOKEN` secret to the repository, however "Secrets are not passed to workflows that are triggered by a pull request from a fork" https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#using-encrypted-secrets-in-a-workflow

So I will add it to the configuration and let's see how it goes.

**Comment by astrojuanlu** [comment]
Closed in #884
