### ISSUE TITLE
Error in porkchop docstrings

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#892]
🐞 **Problem**

While working with `poliastro.plotting.porkchop` I noticed that the docstring
regarding the output values for the `porkchop` function is not updated. There
are two missing values: `dv_launch` and `dv_arrival`. Both should be included.

💡 **Possible solutions**

* Add corresponding function docstrings.

📋  **Steps to solve the problem**

 * Add, commit, run tests and push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by iamabhishek0** [comment]
@jorgepiloto I would like to fix it. Will make a PR soon.

**Comment by jorgepiloto** [comment]
Thank you @iamabhishek0! :rocket:

**Comment by iamabhishek0** [comment]
@priyanshurohilla I was working on it :)

**Comment by jorgepiloto** [comment]
@iamabhishek0 There is no problem usually if two users working on the same issue. We do normally merge the first PR to success all reviews and code tests :rocket:

**Comment by iamabhishek0** [comment]
@jorgepiloto Sure, will keep that in mind.

**Comment by astrojuanlu** [comment]
Closed in #893.
