### ISSUE TITLE
Test 3D maneuvers

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#905]
@jorgepiloto I notice we didn't add any new tests to this pull request. Can you please find an example of a Hohmann transfer that could not be done before it, that now works?

_Originally posted by @astrojuanlu in https://github.com/poliastro/poliastro/pull/599#issuecomment-513470149_

**Comment by jorgepiloto** [comment]
Sorry for this late answer, 

I found a paper that holds different examples on Lambert's algorithms, there is the [link](https://www.amostech.com/TechnicalPapers/2011/Poster/DER.pdf). We might make use of those ECI vectors to solve for this problem.

**Comment by Syed-Osama-Hussain** [comment]
So the ECI position vectors would have to normalized?

**Comment by jorgepiloto** [comment]
Hi @Syed-Osama-Hussain, let me develop this a little:

Many books explain orbital maneuvers from a 2D perspective. They are always referred to the PQW plane, which remember is the plane defined by the orbit itself. Therefore, if you want to apply a maneuver you must first convert your state vector into the pqw one, apply the whatever maneuver and finally re-convert to original state vector in 3D case.

The idea on how to test this was to make use of other available open-source tools such us GMAT, which by making use of scripts can be used as "test-generator", let us say. In fact, there exists a repository called [validation](https://github.com/poliastro/validation) which is supposed to be used to achieve this kind of "third party" testing.

Therefore, the thing is as follows:
 * On a GMAT script, under the assumption of the two-body problem, create a simple orbit.
 * Apply after a certain amount of time a maneuver.
 * Check tof, and final state vector.
 * Use exactly same initial data, apply the same maneuver and finally check if both GMAT and poliastro outpus are the same.

**Comment by Syed-Osama-Hussain** [comment]
Thanks for the detail! I'll follow these steps and notify when done.

**Comment by astrojuanlu** [comment]
Let's follow the conversation in https://github.com/poliastro/validation/issues/10!
