### ISSUE TITLE
Move maneuver computation to core

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#906]
Right now there is quite some logic in the `poliastro.maneuvers` module that could probably be moved to `poliastro.core.maneuvers`.

**Comment by Syed-Osama-Hussain** [comment]
@astrojuanlu , any pointers to understand canonical units and to apply them?

**Comment by priyanshurohilla** [comment]
> Right now there is quite some logic in the `poliastro.maneuvers` module that could probably be moved to `poliastro.core.maneuvers`.

@astrojuanlu We currently don't have any module called `poliastro.core.maneuvers'. Do you want me to make one or what shpuld be done. Can you please elaborate a bit

**Comment by astrojuanlu** [comment]
Before tackling this, it would be better to add some extra tests for "3D maneuvers" https://github.com/poliastro/poliastro/issues/905

**Comment by jorgepiloto** [comment]
After https://github.com/poliastro/validation/pull/20 has been merged, poliastro's 3D impulsive maneuvers are now validated against Orekit. Hence, this issue is no longer blocked.

I saw you append this issue to the `Use of canonical units` project board, @astrojuanlu. May people still address this?

**Comment by astrojuanlu** [comment]
True @jorgepiloto ! Despite having this in the board, the issue is no longer blocked.

**Comment by xlxs4** [comment]
Would you guys think this could be a ![](https://img.shields.io/github/labels/poliastro/poliastro/good%20first%20issue)? If so, any pointers?

**Comment by Yash-10** [comment]
I think the functions having numerically intensive calculations (for eg: in `hohmann`, `bielliptic`, `lambert`, and `correct_pericenter`) can be better implemented in the core module and also potentially `@njit`-ing those to speed up the calculations. 

Once we do that, the corresponding high-level API can be configured to use the core implementations.

Please correct me if I am wrong in interpreting anywhere.

Thanks!!

**Comment by astrojuanlu** [comment]
@xlxs4 Hmmm not sure, it might be a bit delicate to get right. I prefer to have more experienced contributors tackle this.

@Yash-10 your assessment is correct!

**Comment by astrojuanlu** [comment]
Closed in #1136!
