### ISSUE TITLE
OrbitPlotter error in the new version

### ISSUE THREAD

**Issue by Tarlan0001** [poliastro/poliastro#914]
I used the following code before to draw the plots and it worked very well. 
```
from astropy import units as u
from poliastro.plotting import OrbitPlotter
from poliastro.twobody import Orbit
from poliastro.core.elements import coe2rv
from poliastro.bodies import Earth
import matplotlib.pyplot as plt
import math

Req = Earth.R.to(u.km).value
Earth_k = Earth.k

def keplerian2cartesian_alt(kepler):

    a=(kepler[0]+kepler[1]+Req*2)*1000/2  # m
    e=(kepler[0]-kepler[1])/(kepler[0]+kepler[1]+Req*2)
    p = a * (1 - e ** 2)

    return coe2rv(Earth_k, p, e, kepler[2], kepler[3], kepler[4], kepler[5])

op = OrbitPlotter()

r0, v0= keplerian2cartesian_alt([8000, 600, 64.3*math.pi/180,  0, 310*math.pi/180,0])
r1, v1= keplerian2cartesian_alt([40000, 3000, 64.3*math.pi/180,  0, 270*math.pi/180,math.pi])

o0=Orbit.from_vectors(Earth, r0*u.km/1000, v0*u.km/u.s/1000)
o1=Orbit.from_vectors(Earth, r1*u.km/1000, v1*u.km/u.s/1000)

op.plot(o0, label="Initial orbit")
op.plot(o1, label="Transfer orbit")
plt.show()
```

After the recent package update I get the following error:
```
Traceback (most recent call last):
  File "...\test.py", line 2, in <module>
    from poliastro.plotting import OrbitPlotter
ImportError: cannot import name 'OrbitPlotter' from 'poliastro.plotting' (...\miniconda3\lib\site-packages\poliastro\plotting\__init__.py)
```

Can you please help to adjust this code to the new package version?

**Comment by jains8844** [comment]
@Tarlan0001 Replacing ```OrbitPlotter``` with ```StaticOrbitPlotter``` would work.

**Comment by astrojuanlu** [comment]
as @jains8844 said, you have to do `from poliastro.plotting.static import StaticOrbitPlotter as OrbitPlotter` and everything will stay the same. Sorry for not putting a deprecation warning! :innocent: Please let us know if this works.

**Comment by Tarlan0001** [comment]
Works, thanks!

**Comment by Tarlan0001** [comment]
> as @jains8844 said, you have to do `from poliastro.plotting.static import StaticOrbitPlotter as OrbitPlotter` and everything will stay the same. Sorry for not putting a deprecation warning! 😇 Please let us know if this works.

What about 3D plots?

**Comment by astrojuanlu** [comment]
@Tarlan0001 does `from poliastro.plotting import OrbitPlotter3D` work for you?

**Comment by Tarlan0001** [comment]
Is something wrong here? Sorry, i didn't find an explanation in the documentation.

```
from astropy import units as u
from poliastro.plotting import OrbitPlotter3D
from poliastro.twobody import Orbit
from poliastro.core.elements import coe2rv
from poliastro.bodies import Earth
import math


Req = Earth.R.to(u.km).value
Earth_k = Earth.k

def keplerian2cartesian(kepler):

    a=(kepler[0]+kepler[1]+Req*2)*1000/2  # m
    e=(kepler[0]-kepler[1])/(kepler[0]+kepler[1]+Req*2)
    p = a * (1 - e ** 2)

    return coe2rv(Earth_k, p, e, kepler[2], kepler[3], kepler[4], kepler[5])


op = OrbitPlotter3D()

r0, v0= keplerian2cartesian([8000,  600, 64.3*math.pi/180, 0, 300*math.pi/180,0])
r1, v1= keplerian2cartesian([39754, 600, 64.3*math.pi/180, 0, 270*math.pi/180,0])
r2, v2= keplerian2cartesian([2000,  800, 80*math.pi/180,   0, 300*math.pi/180,math.pi])

o0=Orbit.from_vectors(Earth, r0*u.km/1000, v0*u.km/u.s/1000)
o1=Orbit.from_vectors(Earth, r1*u.km/1000, v1*u.km/u.s/1000)
o2=Orbit.from_vectors(Earth, r2*u.km/1000, v2*u.km/u.s/1000)

op.plot(o0)
op.plot(o1)
op.plot(o2)

plt.show()

```

**Comment by Tarlan0001** [comment]
@astrojuanlu Indeed, there is no working example for OrbitPlotter3D for a custom orbit...

**Comment by astrojuanlu** [comment]
@Tarlan0001 please try these :) https://docs.poliastro.space/en/stable/examples/Plotting in 3D.html

**Comment by astrojuanlu** [comment]
Your code above won't work, because `plt.show()` is for matplotlib, but `OrbitPlotter3D` is based on Plotly

**Comment by Tarlan0001** [comment]
Thank you. Using Plotly, even for the examples in the link, the plot isn't opened automatically. I set up the pio.renderers.default = "browser". I can't see the plot.

Can you, please, share a working example for my code?

**Comment by astrojuanlu** [comment]
Your code works for me:

![Screenshot_2020-05-17 Untitled - Jupyter Notebook](https://user-images.githubusercontent.com/316517/82150032-ed5b9400-9857-11ea-9dc7-eb098870efab.png)

Perhaps you have some outdated versions of notebook, ipywidgets or plotly. Please try upgrading your dependencies, displaying a simple Plotly plot (without poliastro) and then running your code again.

**Comment by Tarlan0001** [comment]
Dear @astrojuanlu ,

Plotly works well, checked this code:
```
fig = dict({
    "data": [{"type": "bar",
              "x": [1, 2, 3],
              "y": [1, 3, 2]}],
    "layout": {"title": {"text": "A Figure Specified By Python Dictionary"}}
})
import plotly.io as pio
pio.show(fig)
```

But my code above doesn't show the plot. I've even reinstalled Python, tried to run the code from cmd, from Pyzo. **No errors are shown**, but it doesn't work as expected.

What would you suggest?

**Comment by astrojuanlu** [comment]
I didn't expect the basic Plotly plot to work from cmd or Pyzo to be honest, I though this would only work on Jupyter notebook. Can you share a screenshot with a jupyter notebook containing these two cells?

Cell 1:

```python
fig = dict({
    "data": [{"type": "bar",
              "x": [1, 2, 3],
              "y": [1, 3, 2]}],
    "layout": {"title": {"text": "A Figure Specified By Python Dictionary"}}
})
import plotly.io as pio
pio.show(fig)
```

Cell 2:

```python
from poliastro import iss
from poliastro.plotting import OrbitPlotter3D
plotter = OrbitPlotter3D()
plotter.plot(iss)
```

And also please share the versions of all the dependencies installed in your environment (for example using `pip freeze`).

**Comment by astrojuanlu** [comment]
Closing this issue as inactive, feel free to open new ones!
