### ISSUE TITLE
Return time information from `Orbit.sample()`

### ISSUE THREAD

**Issue by priyanshurohilla** [poliastro/poliastro#923]
The sample method currently only returns a set of `CartesianRepresentation`, which has no associated frame and therefore no `obstime` attribute.

💡 **Feature request**

Provide a feature which can return a `GCRS` vector array in `sample()` function

**Comment by priyanshurohilla** [comment]
While working on it I realized that the codebase has significatly changed from the previous version and will require some changes in the codebase. While trying to add this feature I realized some points which I need to discuss with you@astrojuanlu-

-  In `__init__()` function there is no `def frame()` which does not help in getting `frame_attributes` . While going through the codebase I realized there is a function called `def get_frame()` which has a similar functionality but does not allow `frame_attributes`

-  While trying to add this feature i realized that now  `__init__()`function does not take `plane` as a parameter ,which is posing a problem for the 'obstime' in `sample()` to work properly. Also i `def plane()` now returns `self.state_plane` so i think maybe it is also creating some problems in evolving with `obstime` of which i am not sure of.

Please guide me @astrojuanlu

**Comment by priyanshurohilla** [comment]
Any updates on this @astrojuanlu ?

**Comment by astrojuanlu** [comment]
Took me a while to respond to this one...

Maybe `sample` should return an `Ephemeris` instead of a `CartesianRepresentation`, so it has time information attached.

**Comment by astrojuanlu** [comment]
gh-1521 addresses this by _not_ changing the `Orbit.sample` return value, and instead introducing a `Orbit.to_ephem` method that returns an `Ephem` object, containing both coordinates and epochs, as it should. We went full circle from returning a `BaseCoordinateFrame` to them returning an `Ephem`, but ours is a bit easier to understand I hope.

**Comment by astrojuanlu** [comment]
Closed in gh-1521.
