### ISSUE TITLE
RFC: atmospheric_drag API change

### ISSUE THREAD

**Issue by wumpus** [poliastro/poliastro#935]
At the moment we have 2 functions for atmospheric_drag: `atmospheric_drag()`, which uses a naive exponential atmosphere, and `atmospheric_drag_model()`, which uses more sophisticated models from `poliastro.atmosphere`.

I'd like to rename `atmospheric_drag` to `atmospheric_drag_exponential` so that users are less likely to think that this routine is a good default.

While I'm in there, these routines take a separate `A` (area) and `m` (mass) parameters. The literature uses `A/m`. I'd like to change the calling signature to take A_over_m instead of two separate arguments.

cc @iamabhishek0

**Comment by wumpus** [comment]
While I'm here I should note that it's very confusing that the user calls atmospheric_drag() with kw arguments but the function doesn't have any kw arguments. I know python 3.6+ preserves the order of kwargs but it sure seems fragile. @astrojuanlu

**Comment by astrojuanlu** [comment]
The first idea is totally reasonable to me, let's follow up in #936 now that @priyanshurohilla started the PR.

Regarding your second comment, I don't quite see what are you referring to - could you write an example?

**Comment by wumpus** [comment]
For the second think about

```
    rr, _ = cowell(
        Earth.k,
        orbit.r,
        orbit.v,
        [tof] * u.s,
        ad=atmospheric_drag_exponential,
        R=R,
        C_D=C_D,
        A_over_m=A_over_m,
        H0=H0,
	rho0=rho0,
    )
```

What is the function signature of `atmospheric_drag_exponential`? It's

```
def atmospheric_drag_exponential(t0, state, k, R, C_D, A_over_m, H0, rho0):
```

and it's called as

```
    ax, ay, az = ad(t0, u_, k, **ad_kwargs)
```

... so in short, it's turning kwargs into named args. And it depends on the order of the kwargs being correct. Python programmers aren't really used to having to pay attention to the order of kwargs when calling functions like `cowell()`.

**Comment by wumpus** [comment]
We either need to document this everywhere and still expect user confusion, or, change all of the ad() functions to have kwargs instead of args.

**Comment by astrojuanlu** [comment]
Very true, now I see the issue. What about

```
def atmospheric_drag_exponential(t0, state, k, *, R, C_D, A_over_m, H0, rho0):
```

and in general have every perturbation function use `*` for everything after `(t0, state, k)`. (Notice that [this won't be respected in numba though](https://github.com/numba/numba/issues/5655)).

**Comment by astrojuanlu** [comment]
Hi @wumpus! What do you think of [this solution](https://github.com/poliastro/poliastro/issues/935#issuecomment-621669780)?

**Comment by wumpus** [comment]
I don't see how that addresses the problem that the named parameters to `propagate()` currently have to be in a particular order. Doesn't seem like I'm successfully communicating the problem!

**Comment by wumpus** [comment]
I can put in a PR with a failing test, if that will help.

**Comment by astrojuanlu** [comment]
Hi @wumpus, sorry it took so much to answer, the end of the pandemic was a bit stressful. Yes, having a PR with a failing test would be perfect, thanks!

**Comment by wumpus** [comment]
The last part of this bug is obsolete, #1052 will fix it.

**Comment by astrojuanlu** [comment]
I had forgotten about this, thanks for following up @wumpus! I do think that the new API is simpler and better, and besides it makes maintenance easier.
