### ISSUE TITLE
Code dropped in refactor: M_to_mu

### ISSUE THREAD

**Issue by wumpus** [poliastro/poliastro#937]
in commit

```
commit 52ef39b063db0e0107e8f06af7a52f54dfd4fe0d                                                                                                                
Author: Juan Luis Cano Rodríguez <hello@juanlu.space>                                                                                                          
Date:   Sat Apr 18 19:37:32 2020 +0200

    Move propagator-specific functions to module
```

The code for `M_to_nu` was fully deleted. Similar routines `E_to_mu` and `F_to_mu` were kept.

I noticed because https://github.com/FedericoStra/tletools/ uses this `M_to_nu` code.

**Comment by astrojuanlu** [comment]
Thanks for the shout out! Yes, they were thrown away for a good reason. There's a long stream of thought in https://github.com/poliastro/poliastro/pull/908, and [this comment](https://github.com/poliastro/poliastro/pull/908#issuecomment-615889854) is of particular importance.

In short: `M_to_nu` and `nu_to_M` give the impression that they are valid with all eccentricity regimes, but this is fraught with problems:

* It's not even clear what the mean anomaly means for non elliptic orbits. Different authors consider different definitions, and some of them even avoid the topic completely.
* The near-parabolic region is numerically unstable and there are many different methods to bridge the gap in a smooth way. We implemented the one proposed by Farnocchia, but I am sure there are others. (Most authors don't care about this thin region though, which is a shame. We can talk another day about how everybody seems eager to share their algorithms but not the code for their numerical validations...)

I'll leave a comment in https://github.com/FedericoStra/tletools/issues/5, however this is a non-issue in poliastro, so I am closing it.

On the topic of smooth transitions and deprecation warnings... We are not very consistent with it - sometimes we do deprecation warnings, sometimes we don't. I acknowledge it, but with poliastro still undergoing heavy API refactorings from time to time (yeah, even after 7 years of being born), it is a lot of effort to do this right. And even so, many people will not care about deprecation warnings, and [others will just take your bugs as features](https://xkcd.com/1172/). Therefore, I will make a bigger effort to maintain backwards compatibility when we reach 1.0 (hopefully 2021, although it's a bit of a moving target).
