### ISSUE TITLE
Interface infelicity: third_body()

### ISSUE THREAD

**Issue by wumpus** [poliastro/poliastro#938]
`poliastro.core.perturbations` has a method `third_body` that has a kw argument named `third_body`.

Think for a moment what that means when you try to wrap the function:
```
from poliastro.core.perturbations import third_body
def wrapper(**kwargs):
   foo = third_body(..., third_body)
```

**Comment by jorgepiloto** [comment]
Wow! Good catch @wumpus :rocket: 

What about `perturbation_body` as function parameter? :thinking:

**Comment by wumpus** [comment]
That's a great name.

**Comment by astrojuanlu** [comment]
"infelicity" made me chuckle :) Agreed with @jorgepiloto suggestion

**Comment by priyanshurohilla** [comment]
I have fixed this issue. Just waiting for my previous PR #940 to merge and then i'll open a PR for this:)

**Comment by priyanshurohilla** [comment]
@astrojuanlu  This can be closed now:)
