### ISSUE TITLE
tox_reformat was not done for recent merge

### ISSUE THREAD

**Issue by priyanshurohilla** [poliastro/poliastro#946]
🐞 **Problem**
In the recent merge #945 . The `tox -e reformat` wasn't done. Hence after updating my local repo with `poliastro/master` when i ran `tox -e check` , it produced a reformat error. 

💡 **Possible solutions**
 Just run `tox -e reformat` and open a pull request

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by astrojuanlu** [comment]
I confirm this is the case: https://dev.azure.com/poliastro/poliastro/_build/results?buildId=290&view=results

**Comment by astrojuanlu** [comment]
Closed in #947.
