### ISSUE TITLE
Review condescending language in docs

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#949]
* "just"
* "simply"
* "obviously"
* "of course"
* "easy"

Inspired by https://twitter.com/AdamChainz/status/1256202405311655938

**Comment by priyanshurohilla** [comment]
Well its interesting to see this , that the documentation with these words leave a impact on the readers... I went through the docs and we don't have obviously or of course, but yeah some changes needs to be done! Do you want me to do it ?

**Comment by jorgepiloto** [comment]
The `Contribute` section within documentation might be an example of this, in particular de [Code writing](https://docs.poliastro.space/en/latest/contributing.html#code-writing) subsection. Many lines start with `If`, leading to a tedious reading while first person sentences can be found in some paragraphs.

**Comment by astrojuanlu** [comment]
I hope we can participate on Google Season of Docs some day, so a technical writer reviews all of this :)

**Comment by astrojuanlu** [comment]
> The Contribute section within documentation might be an example of this, in particular de Code writing subsection. Many lines start with If, leading to a tedious reading while first person sentences can be found in some paragraphs.

Addressing this in #1321, finally!

**Comment by astrojuanlu** [comment]
I did review this very quickly (doing a `Ctrl+F` with my editor) and didn't find anything obvious. Documentation improvements are always welcome, but we don't need to keep this issue open.
