### ISSUE TITLE
Publish packages from CI

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#950]
See https://openastronomy-azure-pipelines.readthedocs.io/en/latest/publish.html#usage-and-options.

**Comment by priyanshurohilla** [comment]
For this do you want me to add just the template or the template along with the tests on the generated packages?

**Comment by astrojuanlu** [comment]
Not sure if we want to do this through Azure Pipelines (the CI we are using now for everything else) or setup GitHub actions. Whoever wants to do the research and cast some light on the matter is more than welcome to do so :)

**Comment by astrojuanlu** [comment]
Prospective contributors: as we are already using OpenAstronomy template for Azure Pipelines, I think it would be simpler to leverage that. I prefer to (1) use only one Continuous Integration system and (2) not be coupled with GitHub, in case it becomes evil some day :wink:

**Comment by epassaro** [comment]
hi @astrojuanlu I have some experience with Azure Pipelines, but this seems oddly specific to OpenAstronomy. I can try if you want.

**Comment by astrojuanlu** [comment]
Hi @epassaro, thanks for your interest! If you want to take a look at the template, that would be super helpful :+1: Let me know if I can lend a hand with anything!

**Comment by epassaro** [comment]
sorry for the delay @astrojuanlu I have a question: do you want to use the OA template in the current `azure-pipelines.yml` file, right?

Also, I'm on Telegram and Discord with the same username (I don't use Discord so much but I've joined the PyEs Hacktoberfest event).

**Comment by astrojuanlu** [comment]
Yes, we are already using the template so I'd like to continue using it, for simplicity.

I don't see you on Discord, feel free to ping me there :)

**Comment by epassaro** [comment]
It's required to set an endpoint for PyPI following these short steps: https://openastronomy-azure-pipelines.readthedocs.io/en/latest/publish.html#configuring-the-pypi-service-connection

**Comment by epassaro** [comment]
Any news about this? @astrojuanlu

**Comment by astrojuanlu** [comment]
Hi @epassaro , sorry for the delay! I just created a connection with the instructions you linked (thanks!) with the name `pypi_upload`. For the moment, it's using the test PyPI, so we can see how it works.
