### ISSUE TITLE
Exclude docs from source distributions?

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#951]
Notebooks are quite heavy.

**Comment by jorgepiloto** [comment]
Before #978 was merged, notebooks directory where `14MB` but now, after moving to Jupytext they have reduced half that size, around `7.4MB`. Are we still interested in excluding docs from source?

**Comment by astrojuanlu** [comment]
Yeah, even `7.4 MB` is quite a lot. The only consumer of those source distributions is `pip`, I bet the rest of the users check out the documentation or the repository.

**Comment by jorgepiloto** [comment]
Sorry, I took into account some cache files since the actual disk usage of `docs/source` seems to be around `4.3MB`. However, I agree with you about excluding this from source :+1:

**Comment by astrojuanlu** [comment]
Closed in #988
