### ISSUE TITLE
Replace all Riot/Matrix links with chat.poliastro.space

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#960]
[Cool idea coming from the GNU Radio folks](https://www.gnuradio.org/blog/2020-04-27-moving-to-the-matrix/)

**Comment by astrojuanlu** [comment]
My domain provider won't allow me to input `https://chat.openastronomy.org/#/room/#poliastro:matrix.org` as the redirection URL, but they will look into it soon.

**Comment by astrojuanlu** [comment]
Oops, this URL does not exist anymore, it's `https://openastronomy.riot.im/#/room/#poliastro:matrix.org`. We have to fix the README as well.

**Comment by astrojuanlu** [comment]
My provider is working on a fix :heart_eyes:

**Comment by astrojuanlu** [comment]
It's working :tada:

**Comment by Rocknpools** [comment]
I'm not sure i understand so just to be clear, this is just about replacing all the "https://riot.im/app/#/room/#poliastro:matrix.org" with "https://chat.poliastro.space"?

Or given the recent transition from riot to element should i replace with "https://openastronomy.element.io/#/room/#poliastro:matrix.org" ?

**Comment by astrojuanlu** [comment]
@Rocknpools as a matter of fact, users can join the poliastro chat from both `https://riot.im/app/#/room/#poliastro:matrix.org` and `https://openastronomy.element.io/#/room/#poliastro:matrix.org` (formerly `https://openastronomy.riot.im/#/room/#poliastro:matrix.org`), being Matrix a decentralized system :)

Therefore, to (1) minimize confusion, (2) give a shorter URL that can be shared everywhere and (3) allow ourselves to migrate the "main" or "primary" matrix server in the future, we should replace all these URLs in our docs and README:

- https://openastronomy.riot.im/#/room/#poliastro:matrix.org
- https://openastronomy.element.io/#/room/#poliastro:matrix.org (probably not used anywhere)
- https://riot.im/app/#/room/#poliastro:matrix.org

by https://chat.poliastro.space.

**Comment by Rocknpools** [comment]
> by https://chat.poliastro.space.

Ok! this is what i got at first but then i tried to click on https://chat.poliastro.space and it doesn't work. Is it my problem or something is not right?

**Comment by astrojuanlu** [comment]
Hmmm weird! The redirection does seem to work for me. What happens in your case? Does it give an error, hang, just shows a blank page?

**Comment by Rocknpools** [comment]
I get connection Timeout. Not only on my laptop(in my home network) but also on my phone using my data plan.
Anyway i can open a pull request with all the links replaced with https://chat.poliastro.space/ but i think it's better to investigate this before merging

**Comment by astrojuanlu** [comment]
You're right, I'm getting problems now as well. Let me investigate, thanks for bringing this up!

**Comment by astrojuanlu** [comment]
Oh, I see what's happening - it's http://chat.poliastro.space (no HTTPS!), which then 301 redirects to the appropriate place. I will edit my comment above.
