### ISSUE TITLE
twobody.propagation.cowell issue with cross track constant accelerations

### ISSUE THREAD

**Issue by DaveTheDepraved** [poliastro/poliastro#964]
Hi Everyone,

I'm trying to use Cowell's method to propagate a low-thrust inclination change maneuver.  Basically all I did was modify the constant_accel_factory closure in the exemplar code to produce a unit vector in the direction of the angular momentum vector, cross track, direction instead of the along-track direction shown in the example.  Even with large timescales and very small step size, or even unrealistically large constant accels, it doesn't appear to change the propagated trajectory much at all.  

I'm having a bit of trouble with debugging this, and/or finding a workaround.  Very happy with suggestions on either count.  

Plots to follow.  Uploaded the code in a txt file, sorry was having formatting issues for inline. 

Thanks
-Dave

what it should look like
![image](https://user-images.githubusercontent.com/65629616/82382903-0bf19480-99ea-11ea-9c0b-bf4b0102e7c5.png)

what it actually looks like
![image](https://user-images.githubusercontent.com/65629616/82382971-2f1c4400-99ea-11ea-98e3-78b912d93349.png)

[Low Thrust Cowell - upload.txt](https://github.com/poliastro/poliastro/files/4653487/Low.Thrust.Cowell.-.upload.txt)

**Comment by astrojuanlu** [comment]
Hi @DaveTheDepraved, thanks for your interest in poliastro! One question: how do you know the expected shape of the orbit? Do you have some other code you're comparing against?

Also, pasting your code here for easier reference:

```python
# -*- coding: utf-8 -*-
"""
Created on Tue May 19 15:58:08 2020

@author: Owner
"""


import numpy as np
from astropy import units as u
from astropy import time

from astropy.visualization import quantity_support
quantity_support()
#THe above two lines allows one to simply put plot elements through matplotlib.pyplot

from poliastro.bodies import Earth
from poliastro.twobody import Orbit
from poliastro.twobody.propagation import propagate
from poliastro.examples import iss

from poliastro.twobody.propagation import cowell
from poliastro.twobody.propagation import mikkola
from poliastro.twobody.propagation import markley
from poliastro.twobody.propagation import kepler
from poliastro.twobody.propagation import markley
from poliastro.twobody.propagation import danby

from poliastro.plotting import OrbitPlotter3D
from poliastro.util import norm

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

import plotly.io as pio
pio.renderers.default = "notebook_connected"

#Orbit definition
alt_apoapsis = 500.0 *u.km #[km]
r_apoapsis = alt_apoapsis + ((Earth.R_mean.value)/1000.0)*u.km
e = u.quantity.Quantity(0.0) 
r_periapsis = r_apoapsis*((1-e)/(1+e))
a = 0.5*(r_apoapsis + r_periapsis)
i = 0.0*u.deg # [deg]
raan = 0.0*u.deg #[deg]
argp = 0.0*u.deg #[deg]
mean_anomaly = 0.0*u.deg

print(a)

orbit_object = Orbit.from_classical(Earth,a.to(u.m),e,i,raan,argp,mean_anomaly)

accel = 2e-5 #[km/s^2]


h_tol = 0.001

def constant_accel_factory(accel):
    def constant_accel(t0, state, k):
        v = state[3:]   # velocity vector (cartesian)
        r = state[0:3]  # position vector (cartesian)
        h = (-1.0)*np.array([((v[1]*r[2])-(v[2]*r[1])), -((v[0]*r[2])-(v[2]*r[0])), ((v[0]*r[1])-(v[1]*r[0]))])
        #[] orbital angular momentum vector (h = r cross mutliplied with v)
        #   NOTE: This could be done easier with np.cross
        
        norm_h = (h[0]**2 + h[1]**2 + h[2]**2)**.5
        h_unit = h / norm_h
        #[] Unit vector of the angular momentum  Note that this is also exactly orthogonal to the orbital plane

        norm_v = (v[0]**2 + v[1]**2 + v[2]**2)**.5
        v_unit = v / norm_v
        #[] Unit vector of the velocity vector. 

        return accel * h_unit
    
    return constant_accel

times = np.linspace(0, 500 * orbit_object.period, 5000)


positions = propagate(
    orbit_object,
    time.TimeDelta(times),
    method=cowell,
    rtol=1e-11,
    ad=constant_accel_factory(accel),
)


fig = plt.figure()
ax = fig.add_subplot(111,projection='3d')
# ax.scatter(np.array(positions.get_xyz()[0,:]),np.array(positions.get_xyz()[1,:]),np.array(positions.get_xyz()[2,:]),zdir='z')
ax.plot(np.array(positions.get_xyz()[0,:]),np.array(positions.get_xyz()[1,:]),np.array(positions.get_xyz()[2,:]),zdir='z')
ax.azim = 45
ax.elev = 45

# ax.axis('equal')
plt.xlabel('x')
plt.ylabel('y')
# plt.zlabel('z')
```

**Comment by DaveTheDepraved** [comment]
Hi Juan,

I really like Poliastro so far!  And to be honest I'm not sure that's how the inclination change trajectory is supposed to look.  I've been using a few papers and my old Astro textbook for reference, but there's not much in the way of propagated trajectory plots in anything I've been reading for low thrust inclination change.  

However, looking through the 'positions' vector generated by the propagate method, it doesn't look like there is much of any change to inclination.   Not sure about the shape of the propagated track, but constant cross track acceleration should yield at least some inclination change, especially when I crank the acceleration way up.  

I suspect I'm doing something wrong here still.

Thanks!
-Dave

here's one of the references I've been using if it's relevant.
https://ntrl.ntis.gov/NTRL/dashboard/searchResults/titleDetail/ADA384536.xhtml

**Comment by astrojuanlu** [comment]
J. E. Pollard, my old friend :) I devoted my Master thesis to perturbations and this is one of the references I used. You can read it here:

https://github.com/astrojuanlu/pfc-uc3m/

(Python 3.6 and poliastro 0.6, time flies!)

In fact, we already have the simultaneous change in eccentricity and inclination proposed by Pollard implemented in poliastro:

https://github.com/poliastro/poliastro/blob/master/src/poliastro/twobody/thrust/change_inc_ecc.py

I suspect that the reason you don't see a change in inclination is that, if you always apply acceleration in the cross-track direction *without changing the sign*, the net contribution is zero. I would try switching signs at the line of nodes.

**Comment by astrojuanlu** [comment]
By the way, thanks to you I discovered that these thrust guidance laws do not appear in the documentation #966 so thanks a lot! :grin:

**Comment by DaveTheDepraved** [comment]
Hi Juan,

You're right about the guidance law, man I feel a bit dim!  Thanks very much for the catch.

Cheers,
-Dave

**Comment by astrojuanlu** [comment]
Haha no worries! There's not much information online about perturbations and low thrust, or people to ask. Feel free to join our chat and to open further issues! 🚀
