### ISSUE TITLE
Autogenerate docs

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#967]
It has happened a few times in the recent past that we discovered functions or even entire modules that were undocumented (see #966 for the last instance of this). Even after the rewrite that @jorgepiloto did, I think we should switch to something more automatic, for example:

- https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#sphinx-autogen-generate-autodoc-stub-pages
- https://github.com/readthedocs/sphinx-autoapi
- ?

This probably involves a lot of work, and perhaps a redesign.

**Comment by jorgepiloto** [comment]
I have checked for `sphinx-autoapi` and it is awesome! With this tool properly configured, we might even get rid of the whole `docs/source/api/*.rst` files. It simplifies API documentation process a lot, moving all the workload to each class, function or module docstring.

**Comment by danlub** [comment]
`sphinx-autoapi` works very well! I truly recommend it

**Comment by jorgepiloto** [comment]
Finally closing this! :rocket:
