### ISSUE TITLE
Create mailing list

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#97]
And link to it in README.

**Comment by Juanlu001** [comment]
An alternative to Google Groups exists, and it is called https://groups.io/ :smile:

**Comment by tritium21** [comment]
You could probably lobby to get on scipy's mailman installation...

**Comment by Juanlu001** [comment]
Do you think @tritium21? This is still a small project so I would be a bit embarrased to ask for a mailing list in https://mail.scipy.org/mailman/listinfo, but the big advantage is that I would not have to manage it. I'll think about it this week, thanks for the suggestion!

**Comment by Juanlu001** [comment]
In the end I decided to create it on groups.io. Less burden for me, and I want to support the only real alternative to Google Groups that I know of. Feel free to subscribe :)

https://groups.io/g/poliastro-dev/members
