### ISSUE TITLE
Evaluate MyST (reST-like Markdown flavor) for docs 

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#977]
https://twitter.com/choldgraf/status/1272633413132943360

https://myst-parser.readthedocs.io/en/latest/index.html

I've been observing the development of MyST over the past few months and I think it's very promising. A real alternative to ditch reST (a markdown language used *only* in the Python community) while keep most of its interesting features _and_ fixing some of most obvious reST shortcomings.

I posed a question to Chris about docstrings and the NumPy standard, but in any case I think this is worth trying.

**Comment by astrojuanlu** [comment]
Relevant issues:

- https://github.com/executablebooks/MyST-Parser/issues/164
- https://github.com/executablebooks/MyST-Parser/issues/163

**Comment by jorgepiloto** [comment]
People from [executablebooks](https://github.com/executablebooks) also offer converter from `*.rst` file into `*.md` ones in their project [rst2myst](https://github.com/executablebooks/rst2myst/blob/master/rst_to_md.sh). Might be interesting!

**Comment by astrojuanlu** [comment]
Worth checking too https://github.com/executablebooks/MyST-Parser/pull/156

**Comment by astrojuanlu** [comment]
Closed in #1073 🎉
