### ISSUE TITLE
3d body perturbation defined from orbit

### ISSUE THREAD

**Issue by niels56** [poliastro/poliastro#982]
I am trying to simulate the perturbation of the orbit of a satellite orbiting around an object I defined that has a diameter of 780m that is being orbited by another object with a diameter of 160m.

In the 3d perturbation example the data for the propagation of the third_body is done using an interpolation from ephemeris as such:

body_r =build_ephem_interpolant(....
rr = propagate(initial, tofs, method=cowell, rtol=1e-6,ad=third_body,k_third=k_moon,third_body=body_r

Is it possible to have the body_r from Orbit values such as: Orbit.from_vectors(...?

The type of body_r is scipy.interpolate.interp1d. It is described as ''a callable object returning the position of the pertubation body that causes the perturbation''. Is there another way to input the bodies position coordinates without ephemeris?

Thanks in advance, Niels

**Comment by astrojuanlu** [comment]
Hi @niels56, thanks for your interest in poliastro and sorry for the slight delay!

This one is a very good question. The underlying code expects a function that can be called at arbitrary points in time, so providing a callable is a good solution.

If you already have an `Orbit`, I suppose you could do something like this:

```python
def perturbation_body(t):
    r, v = Orbit.propagate(t * u.s).rv()
    return np.concatenate([r.to_value(u.km), v.to_value(u.km / u.s)])
```

I didn't test this code, but the only tricky thing I anticipate matching the `epoch` of the `Orbit` with the starting point of the propagation.

Please let us know if this suits your needs.

**Comment by astrojuanlu** [comment]
(Edit: clarified instance of `Orbit` vs actual class)

**Comment by niels56** [comment]
Dear Juan! Thank you very much for your quick response.

I tried to implement your suggestion in the code that I will share with you here:

Determining the main body:
`density = 1700 # kg/m`
`diameter_didymos = 780 # m`
`didymos_mass = (4/3)*math.pi*((diameter_didymos/2)**3)*density`
`didymos_volume = (4/3)*math.pi*((diameter_didymos/2)**3)`
`a = ((4/3)*math.pi*((diameter_didymos/2)**3))**(1./3.0)`
`G = 6.67408*10**(-20) #km3/kg s2`
`m = didymos_mass`
`k = G*m*u.km**3/u.s**2`
`name = "Dydimos"`
`didy = Body(None,k, name)`

Determining orbit of the satellite:
`r = [4.0,0.0,0.0] * u.km`
`v = [0.0,7.270456978812678e-05,4.19761216313734e-05]* u.km /u.s`
`ss = Orbit.from_vectors(didy, r, v)`

Detemining the 3r body and its orbit:
`diameter_didymoon = 160 # m`
`didymoon_mass = (4/3)*math.pi*((diameter_didymoon/2)**3)*density`
`didymoon_volume = (4/3)*math.pi*((diameter_didymoon/2)**3)`
`G = 6.67408*10**(-20) #km3/kg s2`
`mm = didymoon_mass`
`k_moon = G*mm#*u.km**3/u.s**2`
`name_moon = "didymoon"`
`didymoon = Body(None,k_moon, name_moon)`
`moon_r = [1.18,0.0,0.0]*u.km`
`moon_v = [0.0,0.00015456828072977154,0.0]* u.km /u.s`
`rm = Orbit.from_vectors(didy, moon_r, moon_v)`

The function you proposed adding to bypass the ephemeris:
`t = 5184000`
`def perturbation_body(t):`
    `r, v = rm.propagate(t * u.s).rv()`
    `return np.concatenate([r.to_value(u.km),v.to_value(u.km / u.s)])`
`moon_per = perturbation_body(t)`

3rd Body perturbation function: 
`tofs = TimeDelta(np.linspace(0,60 * u.day, num=1000))`
`rr = propagate(
    ss,
    tofs,
    method=cowell,
    ad=third_body,
    k_third=k_moon,
    third_body=moon_per,
)`

Nevertheless I get the following error message:
`TypeError: 'numpy.ndarray' object is not callable`

I understood from the start that whatever that object that I tried to define was going to be a Type error. Therefore I tried to put the same type of object as when the ephemeris is called which is a scipy.interpolate.interp1d. I tried to make the perturbation_body function as follow:

`def perturbation_body(t):`
    `r, v = rm.propagate(t * u.s).rv()`
    `return interpolate.interp1d(r.to_value(u.km),v.to_value(u.km / u.s)`

But then I get this error message:

`Traceback (most recent call last):
  File "moon_body.py", line 103, in <module>
    third_body=moon_per,
  File "/home/niels/.local/lib/python3.6/site-packages/poliastro/twobody/propagation.py", line 468, in propagate
    orbit.attractor.k, orbit.r, orbit.v, time_of_flight.to(u.s), rtol=rtol, **kwargs
  File "/home/niels/.local/lib/python3.6/site-packages/poliastro/twobody/propagation.py", line 105, in cowell
    dense_output=True,
  File "/home/niels/.local/lib/python3.6/site-packages/scipy/integrate/_ivp/ivp.py", line 543, in solve_ivp
    solver = method(fun, t0, y0, tf, vectorized=vectorized, **options)
  File "/home/niels/.local/lib/python3.6/site-packages/poliastro/integrators.py", line 375, in __init__
    self.f = self.fun(self.t, self.y)
  File "/home/niels/.local/lib/python3.6/site-packages/scipy/integrate/_ivp/base.py", line 139, in fun
    return self.fun_single(t, y)
  File "/home/niels/.local/lib/python3.6/site-packages/scipy/integrate/_ivp/base.py", line 21, in fun_wrapped
    return np.asarray(fun(t, y), dtype=dtype)
  File "/home/niels/.local/lib/python3.6/site-packages/poliastro/core/propagation.py", line 37, in func_twobody
    ax, ay, az = ad(t0, u_, k, **ad_kwargs)
  File "/home/niels/.local/lib/python3.6/site-packages/poliastro/core/perturbations.py", line 183, in third_body
    return k_third * delta_r / norm(delta_r) ** 3 - k_third * body_r / norm(body_r) ** 3
  File "/home/niels/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/niels/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/niels/.local/lib/python3.6/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'dot' of type float64`

`File "../.local/lib/python3.6/site-packages/poliastro/core/util.py", line 118:
def norm(vec):
    <source elided>
    vec = 1.0 * vec  # Cast to float
    return np.sqrt(vec.dot(vec))
    ^`

`[1] During: typing of get attribute at /home/niels/.local/lib/python3.6/site-packages/poliastro/core/util.py (118)`

`File "../.local/lib/python3.6/site-packages/poliastro/core/util.py", line 118:
def norm(vec):
    <source elided>
    vec = 1.0 * vec  # Cast to float
    return np.sqrt(vec.dot(vec))
    ^`

`This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.`

I have the feeling that there is an issue with the fact that the values from the r and v components are float64. But I would not know for sure. Again thanks for your time. If you would have any suggestions for solving this issue I would really appreciate. Cheers, Niels.

**Comment by niels56** [comment]
Dear Juan! Thank you very much for your quick response.

I tried to implement your suggestion in the code that I will share with you here:

Determining the main body:
`density = 1700 # kg/m`
`diameter_didymos = 780 # m`
`didymos_mass = (4/3)*math.pi*((diameter_didymos/2)**3)*density`
`didymos_volume = (4/3)*math.pi*((diameter_didymos/2)**3)`
`a = ((4/3)*math.pi*((diameter_didymos/2)**3))**(1./3.0)`
`G = 6.67408*10**(-20) #km3/kg s2`
`m = didymos_mass`
`k = G*m*u.km**3/u.s**2`
`name = "Dydimos"`
`didy = Body(None,k, name)`

Determining orbit of the satellite:
`r = [4.0,0.0,0.0] * u.km`
`v = [0.0,7.270456978812678e-05,4.19761216313734e-05]* u.km /u.s`
`ss = Orbit.from_vectors(didy, r, v)`

Detemining the 3r body and its orbit:
`diameter_didymoon = 160 # m`
`didymoon_mass = (4/3)*math.pi*((diameter_didymoon/2)**3)*density`
`didymoon_volume = (4/3)*math.pi*((diameter_didymoon/2)**3)`
`G = 6.67408*10**(-20) #km3/kg s2`
`mm = didymoon_mass`
`k_moon = G*mm#*u.km**3/u.s**2`
`name_moon = "didymoon"`
`didymoon = Body(None,k_moon, name_moon)`
`moon_r = [1.18,0.0,0.0]*u.km`
`moon_v = [0.0,0.00015456828072977154,0.0]* u.km /u.s`
`rm = Orbit.from_vectors(didy, moon_r, moon_v)`

The function you proposed adding to bypass the ephemeris:
`t = 5184000`
`def perturbation_body(t):`
    `r, v = rm.propagate(t * u.s).rv()`
    `return np.concatenate([r.to_value(u.km),v.to_value(u.km / u.s)])`
`moon_per = perturbation_body(t)`

3rd Body perturbation function: 
`tofs = TimeDelta(np.linspace(0,60 * u.day, num=1000))`
`rr = propagate(
    ss,
    tofs,
    method=cowell,
    ad=third_body,
    k_third=k_moon,
    third_body=moon_per,
)`

Nevertheless I get the following error message:
`TypeError: 'numpy.ndarray' object is not callable`

I understood from the start that whatever that object that I tried to define was going to be a Type error. Therefore I tried to put the same type of object as when the ephemeris is called which is a scipy.interpolate.interp1d. I tried to make the perturbation_body function as follow:

`def perturbation_body(t):`
    `r, v = rm.propagate(t * u.s).rv()`
    `return interpolate.interp1d(r.to_value(u.km),v.to_value(u.km / u.s)`

But then I get this error message:

`Traceback (most recent call last):
  File "moon_body.py", line 103, in <module>
    third_body=moon_per,
  File "/home/niels/.local/lib/python3.6/site-packages/poliastro/twobody/propagation.py", line 468, in propagate
    orbit.attractor.k, orbit.r, orbit.v, time_of_flight.to(u.s), rtol=rtol, **kwargs
  File "/home/niels/.local/lib/python3.6/site-packages/poliastro/twobody/propagation.py", line 105, in cowell
    dense_output=True,
  File "/home/niels/.local/lib/python3.6/site-packages/scipy/integrate/_ivp/ivp.py", line 543, in solve_ivp
    solver = method(fun, t0, y0, tf, vectorized=vectorized, **options)
  File "/home/niels/.local/lib/python3.6/site-packages/poliastro/integrators.py", line 375, in __init__
    self.f = self.fun(self.t, self.y)
  File "/home/niels/.local/lib/python3.6/site-packages/scipy/integrate/_ivp/base.py", line 139, in fun
    return self.fun_single(t, y)
  File "/home/niels/.local/lib/python3.6/site-packages/scipy/integrate/_ivp/base.py", line 21, in fun_wrapped
    return np.asarray(fun(t, y), dtype=dtype)
  File "/home/niels/.local/lib/python3.6/site-packages/poliastro/core/propagation.py", line 37, in func_twobody
    ax, ay, az = ad(t0, u_, k, **ad_kwargs)
  File "/home/niels/.local/lib/python3.6/site-packages/poliastro/core/perturbations.py", line 183, in third_body
    return k_third * delta_r / norm(delta_r) ** 3 - k_third * body_r / norm(body_r) ** 3
  File "/home/niels/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/niels/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/niels/.local/lib/python3.6/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'dot' of type float64`

`File "../.local/lib/python3.6/site-packages/poliastro/core/util.py", line 118:
def norm(vec):
    <source elided>
    vec = 1.0 * vec  # Cast to float
    return np.sqrt(vec.dot(vec))
    ^`

`[1] During: typing of get attribute at /home/niels/.local/lib/python3.6/site-packages/poliastro/core/util.py (118)`

`File "../.local/lib/python3.6/site-packages/poliastro/core/util.py", line 118:
def norm(vec):
    <source elided>
    vec = 1.0 * vec  # Cast to float
    return np.sqrt(vec.dot(vec))
    ^`

`This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.`

I have the feeling that there is an issue with the fact that the values from the r and v components are float64. But I would not know for sure. Again thanks for your time. If you would have any suggestions for solving this issue I would really appreciate. Cheers, Niels.

**Comment by astrojuanlu** [comment]
I edited your comment for formatting (use triple backquotes for long blobs of formatted text :rocket:). Let me see if I can fix the issue!

**Comment by astrojuanlu** [comment]
Hi @niels56, sorry for the long delay - getting back to this as part of the SciPy 2020 sprints. I'll try to rerun your code and see what's happening.

**Comment by astrojuanlu** [comment]
It turns out that I was wrong, but fortunately the needed change is not that difficult.

The actual code for the propagation is:

```python
tofs = TimeDelta(np.linspace(0,60 * u.day, num=1000))
rr = propagate(
    ss,
    tofs,
    method=cowell,
    ad=third_body,
    k_third=k_moon,
    perturbation_body=perturbation_body,  # not third_body= and not =moon_per!
)
```

The relevant part of the `TypeError` traceback is:

```
~/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/poliastro/core/propagation/__init__.py in func_twobody(t0, u_, k, ad, ad_kwargs)
     48 
     49     """
---> 50     ax, ay, az = ad(t0, u_, k, **ad_kwargs)
     51 
     52     x, y, z, vx, vy, vz = u_

~/.pyenv/versions/3.8.0/envs/poliastro38/lib/python3.8/site-packages/poliastro/core/perturbations.py in third_body(t0, state, k, k_third, perturbation_body)
    227     """
    228 
--> 229     body_r = perturbation_body(t0)
    230     delta_r = body_r - state[:3]
    231     return k_third * delta_r / norm(delta_r) ** 3 - k_third * body_r / norm(body_r) ** 3

TypeError: 'numpy.ndarray' object is not callable
```

which shows that `poliastro.core.perturbations.third_body` was actually expecting that to be a function, not a precomputed array.

Also, with only this change I was still getting a `ValueError: operands could not be broadcast together with shapes (6,) (3,)`. This was my fault: the `perturbation_body` function must return only the position, not the velocity!

```python
def perturbation_body(t):
    r, v = rm.propagate(t * u.s).rv()
    return r.to_value(u.km)
```

After that, `rr` ends up being something like this:

```
In [37]: rr                                                                                                                                                                                                                                   
Out[37]: 
<CartesianRepresentation (x, y, z) in km
    [( 4.        ,  0.        ,  0.        ),
     ( 3.97363282,  0.37602952,  0.21738167),
     ( 3.89587533,  0.74481823,  0.43213509),
     ( 3.77016524,  1.10033612,  0.64166989),
     ( 3.60078139,  1.43856764,  0.84342794),
     ( 3.39155367,  1.75742482,  1.03489752),
...
```

which I hope is more similar to what you need.

Let me know if I can help in anything else.

**Comment by astrojuanlu** [comment]
Closing this support issue, let me know if we can help in any other way!
