### ISSUE TITLE
Add fancy links in docs

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#986]
Idea taken from SfePy new website:

![Screenshot_2020-06-30 SfePy Simple Finite Elements in Python — SfePy version 2020 2 documentation](https://user-images.githubusercontent.com/316517/86114760-47907b80-bacb-11ea-9199-218f0a523249.png)

**Comment by ibLeDy** [comment]
Hi, i would love to work on this issue.

**Comment by astrojuanlu** [comment]
Hola @ibLeDy, welcome to poliastro! Feel free to send a pull request, and if you have questions please join our chat http://chat.poliastro.space and maybe see you on Sunday? ;)

**Comment by ibLeDy** [comment]
Thanks! The only questions i have atm are about the formatting and info which will be added, like:
- Section title (`Connections` in the screenshot)
- Links which will be included
- If linking to a document that doesn't exist, it will need to be created (not sure if i would be the one to do it as i'm not really familiar with the codebase, although the ones that appear on the screenshot are doable)

Also i think this question is more suitable to in-issue discussion, but if i have general questions i will definetely ask them on your chat! (Unless you guys consider all questions more suitable/convenient to be asked in the chat)

**Comment by astrojuanlu** [comment]
Fair enough, excellent questions:

- Let's put "Links" instead
- Let's have
  - Blog https://blog.poliastro.space/
  - Source code https://github.com/poliastro/poliastro/
  - Issue tracker https://github.com/poliastro/poliastro/issues/
  - Mailing list https://groups.io/g/poliastro-dev/
  - Chat http://chat.poliastro.space
  - Citation https://doi.org/10.5281/zenodo.593610

**Comment by ibLeDy** [comment]
Alright, seems like i'm almost ready to sumbit the PR.

I tried including the "Links" section as another toctree in `index.rst`, the urls were working but could'n find a way of displaying the icons, so i followed what SfePy did to achieve it:

- Added a [`html_context` dictionary](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_context) to `conf.py`, which holds the text (including the icon) and url for each item, as well as the caption of the section.
- Created a template file which extends the default theme layout. The file (`layout.html`) is located inside a new folder called `_templates`.

I used the following icons, as they seemed appropiate (i need confirmation that they are indeed appropiate):

![2020-10-01_20-04-13](https://user-images.githubusercontent.com/45886240/94846578-a72b5980-0421-11eb-8256-30225980a5cc.png)

I would like confirmation that they are indeed appropiate (if they're not, please choose from [the available ones](https://fontawesome.com/v4.7.0/icons/)), and i would be ready to sumbit the PR

**Comment by astrojuanlu** [comment]
Great job! Sure thing, go ahead @ibLeDy :muscle:
