### ISSUE TITLE
Units error in COESA amtospheric models

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/poliastro#992]
🐞 **Problem**

I just noticed that the universal gas constant defined in both `coesa62.py` and `coesa76.py` hold wrong units: they make use of `u.J / u.kg / u.K` while proper units should be `u.J / u.kmol / u.K`. **Though defined with wrong units, no errors were raised since code does not make use of those variables.** 

https://github.com/poliastro/poliastro/blob/817fac96365e3848348052d159f6258e502357b1/src/poliastro/earth/atmosphere/coesa62.py#L76
https://github.com/poliastro/poliastro/blob/817fac96365e3848348052d159f6258e502357b1/src/poliastro/earth/atmosphere/coesa76.py#L55

When the universal gas constant is divided by the mean molecular weight of the gas (with `u.kg / u.kmol`), the specific gas constant is obtained with units `u.J / u.kg / u.K`. 

💡 **Possible solutions**

Either delete de variables or correct their units will solve for this problem.

**Comment by rafaellehmkuhl** [comment]
I will send a PR for this one.
